; title: Axel F
; author: Harold Faltermeyer
; instrument: Piano
; Converted by Serenade Music Converter

SendInput {Numpad6}
Sleep, 508
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 381
SendInput {Numpad9}
SendInput {Numpad6}
Sleep, 254
SendInput {Numpad6}
Sleep, 127
SendInput {Numpad2}
Sleep, 254
SendInput {Numpad6}
Sleep, 254
SendInput {Numpad5}
Sleep, 254
SendInput {Numpad6}
Sleep, 508
SendInput {Numpad0}
SendInput {Numpad3}
Sleep, 381
SendInput {Numpad9}
SendInput {Numpad6}
Sleep, 254
SendInput {Numpad6}
Sleep, 127
SendInput {Numpad4}
Sleep, 254
SendInput {Numpad3}
Sleep, 254
SendInput {Numpad1}
Sleep, 254
SendInput {Numpad6}
Sleep, 254
SendInput {Numpad0}
SendInput {Numpad3}
Sleep, 254
SendInput {Numpad6}
Sleep, 254
SendInput {Numpad9}
SendInput {Numpad6}
Sleep, 127
SendInput {Numpad5}
Sleep, 254
SendInput {Numpad5}
Sleep, 127
SendInput {Numpad3}
Sleep, 254
SendInput {Numpad7}
Sleep, 254
SendInput {Numpad6}
Sleep, 2288
SendInput {Numpad6}
Sleep, 508
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 381
SendInput {Numpad9}
SendInput {Numpad6}
Sleep, 254
SendInput {Numpad6}
Sleep, 127
SendInput {Numpad2}
Sleep, 254
SendInput {Numpad6}
Sleep, 254
SendInput {Numpad5}
Sleep, 254
SendInput {Numpad6}
Sleep, 508
SendInput {Numpad0}
SendInput {Numpad3}
Sleep, 381
SendInput {Numpad9}
SendInput {Numpad6}
Sleep, 254
SendInput {Numpad6}
Sleep, 127
SendInput {Numpad4}
Sleep, 254
SendInput {Numpad3}
Sleep, 254
SendInput {Numpad1}
Sleep, 254
SendInput {Numpad6}
Sleep, 254
SendInput {Numpad0}
SendInput {Numpad3}
Sleep, 254
SendInput {Numpad6}
Sleep, 254
SendInput {Numpad9}
SendInput {Numpad6}
Sleep, 127
SendInput {Numpad5}
Sleep, 254
SendInput {Numpad5}
Sleep, 127
SendInput {Numpad3}
Sleep, 254
SendInput {Numpad7}
Sleep, 254
SendInput {Numpad6}
Sleep, 2288
SendInput {Numpad9}
SendInput {Numpad6}
Sleep, 508
SendInput {Numpad0}
SendInput {Numpad6}
Sleep, 381
SendInput {Numpad9}
SendInput {Numpad5}
Sleep, 254
SendInput {Numpad0}
SendInput {Numpad5}
Sleep, 127
SendInput {Numpad3}
Sleep, 254
SendInput {Numpad3}
Sleep, 254
SendInput {Numpad9}
SendInput {Numpad5}
Sleep, 254
SendInput {Numpad6}
Sleep, 508
SendInput {Numpad0}
SendInput {Numpad6}
Sleep, 636
SendInput {Numpad9}
SendInput {Numpad3}
Sleep, 127
SendInput {Numpad3}
Sleep, 254
SendInput {Numpad5}
Sleep, 254
SendInput {Numpad6}
Sleep, 254
SendInput {Numpad4}
Sleep, 508
SendInput {Numpad0}
SendInput {Numpad4}
Sleep, 381
SendInput {Numpad9}
SendInput {Numpad5}
Sleep, 254
SendInput {Numpad0}
SendInput {Numpad5}
Sleep, 127
SendInput {Numpad3}
Sleep, 254
SendInput {Numpad5}
Sleep, 254
SendInput {Numpad6}
Sleep, 254
SendInput {Numpad6}
Sleep, 1144
SendInput {Numpad5}
Sleep, 127
SendInput {Numpad3}
Sleep, 254
SendInput {Numpad2}
Sleep, 254
SendInput {Numpad1}
Sleep, 254
SendInput {Numpad9}
SendInput {Numpad6}
Sleep, 508
SendInput {Numpad0}
SendInput {Numpad6}
Sleep, 381
SendInput {Numpad9}
SendInput {Numpad5}
Sleep, 254
SendInput {Numpad0}
SendInput {Numpad5}
Sleep, 127
SendInput {Numpad3}
Sleep, 254
SendInput {Numpad3}
Sleep, 254
SendInput {Numpad9}
SendInput {Numpad5}
Sleep, 254
SendInput {Numpad6}
Sleep, 508
SendInput {Numpad0}
SendInput {Numpad6}
Sleep, 636
SendInput {Numpad9}
SendInput {Numpad3}
Sleep, 127
SendInput {Numpad3}
Sleep, 254
SendInput {Numpad5}
Sleep, 254
SendInput {Numpad6}
Sleep, 254
SendInput {Numpad4}
Sleep, 508
SendInput {Numpad0}
SendInput {Numpad4}
Sleep, 381
SendInput {Numpad9}
SendInput {Numpad5}
Sleep, 254
SendInput {Numpad0}
SendInput {Numpad5}
Sleep, 127
SendInput {Numpad3}
Sleep, 254
SendInput {Numpad5}
Sleep, 254
SendInput {Numpad6}
Sleep, 254
SendInput {Numpad6}
Sleep, 1144
SendInput {Numpad5}
Sleep, 127
SendInput {Numpad3}
Sleep, 254
SendInput {Numpad2}
Sleep, 254
SendInput {Numpad1}
Sleep, 254
SendInput {Numpad6}
Sleep, 508
SendInput {Numpad0}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 381
SendInput {Numpad9}
SendInput {Numpad5}
SendInput {Numpad6}
Sleep, 254
SendInput {Numpad5}
SendInput {Numpad6}
Sleep, 127
SendInput {Numpad3}
SendInput {Numpad2}
Sleep, 254
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 254
SendInput {Numpad5}
Sleep, 254
SendInput {Numpad6}
Sleep, 508
SendInput {Numpad0}
SendInput {Numpad6}
SendInput {Numpad3}
Sleep, 381
SendInput {Numpad9}
SendInput {Numpad6}
Sleep, 254
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 127
SendInput {Numpad3}
SendInput {Numpad4}
Sleep, 254
SendInput {Numpad5}
SendInput {Numpad3}
Sleep, 254
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 254
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 254
SendInput {Numpad0}
SendInput {Numpad3}
Sleep, 254
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 254
SendInput {Numpad9}
SendInput {Numpad6}
Sleep, 127
SendInput {Numpad5}
Sleep, 254
SendInput {Numpad5}
Sleep, 127
SendInput {Numpad3}
Sleep, 254
SendInput {Numpad5}
SendInput {Numpad7}
Sleep, 254
SendInput {Numpad6}
Sleep, 254
SendInput {Numpad6}
Sleep, 1144
SendInput {Numpad5}
Sleep, 127
SendInput {Numpad3}
Sleep, 254
SendInput {Numpad2}
Sleep, 254
SendInput {Numpad1}
Sleep, 254
SendInput {Numpad6}
Sleep, 508
SendInput {Numpad0}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 381
SendInput {Numpad9}
SendInput {Numpad5}
SendInput {Numpad6}
Sleep, 254
SendInput {Numpad5}
SendInput {Numpad6}
Sleep, 127
SendInput {Numpad3}
SendInput {Numpad2}
Sleep, 254
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 254
SendInput {Numpad5}
Sleep, 254
SendInput {Numpad6}
Sleep, 508
SendInput {Numpad0}
SendInput {Numpad6}
SendInput {Numpad3}
Sleep, 381
SendInput {Numpad9}
SendInput {Numpad6}
Sleep, 254
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 127
SendInput {Numpad3}
SendInput {Numpad4}
Sleep, 254
SendInput {Numpad5}
SendInput {Numpad3}
Sleep, 254
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 254
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 254
SendInput {Numpad0}
SendInput {Numpad3}
Sleep, 254
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 254
SendInput {Numpad9}
SendInput {Numpad6}
Sleep, 127
SendInput {Numpad5}
Sleep, 254
SendInput {Numpad5}
Sleep, 127
SendInput {Numpad3}
Sleep, 254
SendInput {Numpad5}
SendInput {Numpad7}
Sleep, 254
SendInput {Numpad6}
Sleep, 254
SendInput {Numpad6}
Sleep, 1144
SendInput {Numpad5}
Sleep, 127
SendInput {Numpad3}
Sleep, 254
SendInput {Numpad2}
Sleep, 254
SendInput {Numpad1}
Sleep, 254
SendInput {Numpad9}
SendInput {Numpad6}
Sleep, 254
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad6}
SendInput {F1}
SendInput {Numpad3}
Sleep, 254
SendInput {Numpad9}
SendInput {Numpad6}
SendInput {F1}
SendInput {Numpad3}
Sleep, 254
SendInput {Numpad0}
SendInput {Numpad6}
SendInput {F1}
SendInput {Numpad3}
Sleep, 127
SendInput {Numpad5}
SendInput {Numpad7}
SendInput {Numpad2}
Sleep, 254
SendInput {Numpad9}
SendInput {Numpad5}
SendInput {Numpad7}
SendInput {Numpad2}
Sleep, 127
SendInput {Numpad3}
Sleep, 127
SendInput {Numpad7}
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 127
SendInput {Numpad3}
SendInput {Numpad6}
SendInput {Numpad2}
SendInput {F3}
Sleep, 254
SendInput {Numpad0}
SendInput {Numpad5}
SendInput {Numpad6}
SendInput {Numpad2}
SendInput {F3}
Sleep, 254
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad6}
Sleep, 254
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad6}
SendInput {F1}
SendInput {Numpad3}
Sleep, 254
SendInput {Numpad9}
SendInput {Numpad6}
SendInput {F1}
SendInput {Numpad3}
Sleep, 254
SendInput {Numpad0}
SendInput {Numpad6}
SendInput {F1}
SendInput {Numpad3}
Sleep, 127
SendInput {Numpad7}
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 254
SendInput {Numpad3}
SendInput {Numpad7}
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 127
SendInput {Numpad3}
SendInput {Numpad6}
SendInput {Numpad2}
SendInput {F3}
Sleep, 254
SendInput {Numpad5}
SendInput {Numpad6}
SendInput {F1}
SendInput {Numpad3}
Sleep, 254
SendInput {Numpad6}
Sleep, 254
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad4}
Sleep, 254
SendInput {Numpad0}
SendInput {Numpad4}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 254
SendInput {Numpad4}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 254
SendInput {Numpad4}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 127
SendInput {Numpad5}
Sleep, 127
SendInput {Numpad4}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 127
SendInput {Numpad5}
SendInput {Numpad7}
SendInput {Numpad2}
Sleep, 127
SendInput {Numpad3}
Sleep, 127
SendInput {Numpad5}
SendInput {Numpad7}
SendInput {Numpad2}
Sleep, 127
SendInput {Numpad5}
Sleep, 127
SendInput {Numpad5}
SendInput {Numpad7}
SendInput {Numpad2}
Sleep, 127
SendInput {Numpad6}
Sleep, 127
SendInput {Numpad5}
SendInput {Numpad7}
SendInput {Numpad2}
Sleep, 127
SendInput {Numpad5}
SendInput {Numpad6}
SendInput {Numpad7}
SendInput {Numpad2}
Sleep, 254
SendInput {Numpad0}
SendInput {Numpad6}
SendInput {F1}
SendInput {Numpad3}
Sleep, 254
SendInput {Numpad6}
SendInput {F1}
SendInput {Numpad3}
Sleep, 254
SendInput {Numpad6}
SendInput {F1}
SendInput {Numpad3}
Sleep, 254
SendInput {Numpad9}
SendInput {Numpad5}
SendInput {Numpad7}
SendInput {Numpad2}
Sleep, 127
SendInput {Numpad5}
SendInput {Numpad6}
SendInput {F1}
SendInput {Numpad3}
Sleep, 127
SendInput {Numpad3}
Sleep, 127
SendInput {Numpad6}
SendInput {F1}
SendInput {Numpad3}
Sleep, 127
SendInput {Numpad2}
Sleep, 254
SendInput {Numpad1}
Sleep, 254
SendInput {Numpad9}
SendInput {Numpad6}
Sleep, 254
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad6}
SendInput {F1}
SendInput {Numpad3}
Sleep, 254
SendInput {Numpad9}
SendInput {Numpad6}
SendInput {F1}
SendInput {Numpad3}
Sleep, 254
SendInput {Numpad0}
SendInput {Numpad6}
SendInput {F1}
SendInput {Numpad3}
Sleep, 127
SendInput {Numpad5}
SendInput {Numpad7}
SendInput {Numpad2}
Sleep, 254
SendInput {Numpad9}
SendInput {Numpad5}
SendInput {Numpad7}
SendInput {Numpad2}
Sleep, 127
SendInput {Numpad3}
Sleep, 127
SendInput {Numpad7}
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 127
SendInput {Numpad3}
SendInput {Numpad6}
SendInput {Numpad2}
SendInput {F3}
Sleep, 254
SendInput {Numpad0}
SendInput {Numpad5}
SendInput {Numpad6}
SendInput {Numpad2}
SendInput {F3}
Sleep, 254
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad6}
Sleep, 254
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad6}
SendInput {F1}
SendInput {Numpad3}
Sleep, 254
SendInput {Numpad9}
SendInput {Numpad6}
SendInput {F1}
SendInput {Numpad3}
Sleep, 254
SendInput {Numpad0}
SendInput {Numpad6}
SendInput {F1}
SendInput {Numpad3}
Sleep, 127
SendInput {Numpad7}
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 254
SendInput {Numpad3}
SendInput {Numpad7}
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 127
SendInput {Numpad3}
SendInput {Numpad6}
SendInput {Numpad2}
SendInput {F3}
Sleep, 254
SendInput {Numpad5}
SendInput {Numpad6}
SendInput {F1}
SendInput {Numpad3}
Sleep, 254
SendInput {Numpad6}
Sleep, 254
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad4}
Sleep, 254
SendInput {Numpad0}
SendInput {Numpad4}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 254
SendInput {Numpad4}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 254
SendInput {Numpad4}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 127
SendInput {Numpad5}
Sleep, 127
SendInput {Numpad4}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 127
SendInput {Numpad5}
SendInput {Numpad7}
SendInput {Numpad2}
Sleep, 127
SendInput {Numpad3}
Sleep, 127
SendInput {Numpad5}
SendInput {Numpad7}
SendInput {Numpad2}
Sleep, 127
SendInput {Numpad5}
Sleep, 127
SendInput {Numpad5}
SendInput {Numpad7}
SendInput {Numpad2}
Sleep, 127
SendInput {Numpad6}
Sleep, 127
SendInput {Numpad5}
SendInput {Numpad7}
SendInput {Numpad2}
Sleep, 127
SendInput {Numpad5}
SendInput {Numpad6}
SendInput {Numpad7}
SendInput {Numpad2}
Sleep, 254
SendInput {Numpad0}
SendInput {Numpad6}
SendInput {F1}
SendInput {Numpad3}
Sleep, 254
SendInput {Numpad6}
SendInput {F1}
SendInput {Numpad3}
Sleep, 254
SendInput {Numpad6}
SendInput {F1}
SendInput {Numpad3}
Sleep, 254
SendInput {Numpad9}
SendInput {Numpad5}
SendInput {Numpad7}
SendInput {Numpad2}
Sleep, 127
SendInput {Numpad5}
SendInput {Numpad6}
SendInput {F1}
SendInput {Numpad3}
Sleep, 127
SendInput {Numpad3}
Sleep, 127
SendInput {Numpad6}
SendInput {F1}
SendInput {Numpad3}
Sleep, 127
SendInput {Numpad2}
Sleep, 254
SendInput {Numpad1}
Sleep, 254
SendInput {Numpad6}
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 508
SendInput {Numpad6}
Sleep, 381
SendInput {Numpad9}
SendInput {Numpad5}
Sleep, 254
SendInput {Numpad0}
SendInput {Numpad5}
Sleep, 127
SendInput {Numpad3}
Sleep, 254
SendInput {Numpad3}
Sleep, 254
SendInput {Numpad9}
SendInput {Numpad5}
Sleep, 254
SendInput {Numpad6}
Sleep, 508
SendInput {Numpad0}
SendInput {Numpad6}
Sleep, 381
SendInput {Numpad9}
SendInput {Numpad5}
Sleep, 254
SendInput {Numpad0}
SendInput {Numpad5}
Sleep, 127
SendInput {Numpad3}
Sleep, 254
SendInput {Numpad3}
Sleep, 254
SendInput {Numpad9}
SendInput {Numpad5}
Sleep, 254
SendInput {Numpad6}
Sleep, 2034
SendInput {Numpad6}
Sleep, 508
SendInput {Numpad0}
SendInput {Numpad6}
Sleep, 381
SendInput {Numpad9}
SendInput {Numpad5}
Sleep, 254
SendInput {Numpad0}
SendInput {Numpad5}
Sleep, 127
SendInput {Numpad3}
Sleep, 254
SendInput {Numpad3}
Sleep, 254
SendInput {Numpad9}
SendInput {Numpad5}
Sleep, 254
SendInput {Numpad6}
Sleep, 508
SendInput {Numpad0}
SendInput {Numpad6}
Sleep, 636
SendInput {Numpad9}
SendInput {Numpad3}
Sleep, 127
SendInput {Numpad3}
Sleep, 254
SendInput {Numpad5}
Sleep, 254
SendInput {Numpad6}
Sleep, 254
SendInput {Numpad4}
Sleep, 508
SendInput {Numpad0}
SendInput {Numpad4}
Sleep, 381
SendInput {Numpad9}
SendInput {Numpad5}
Sleep, 254
SendInput {Numpad0}
SendInput {Numpad5}
Sleep, 127
SendInput {Numpad3}
Sleep, 254
SendInput {Numpad5}
Sleep, 254
SendInput {Numpad6}
Sleep, 254
SendInput {Numpad6}
Sleep, 1144
SendInput {Numpad5}
Sleep, 127
SendInput {Numpad3}
Sleep, 254
SendInput {Numpad2}
Sleep, 254
SendInput {Numpad1}
Sleep, 254
SendInput {Numpad9}
SendInput {Numpad6}
Sleep, 508
SendInput {Numpad0}
SendInput {Numpad6}
Sleep, 254
Sleep, 127
SendInput {Numpad5}
Sleep, 254
SendInput {Numpad5}
Sleep, 127
SendInput {Numpad3}
Sleep, 254
SendInput {Numpad3}
Sleep, 254
SendInput {Numpad9}
SendInput {Numpad5}
Sleep, 254
SendInput {Numpad6}
Sleep, 508
SendInput {Numpad0}
SendInput {Numpad6}
Sleep, 254
Sleep, 381
SendInput {Numpad9}
SendInput {Numpad3}
Sleep, 127
SendInput {Numpad3}
Sleep, 254
SendInput {Numpad5}
Sleep, 254
SendInput {Numpad6}
Sleep, 254
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 508
SendInput {Numpad9}
SendInput {Numpad4}
Sleep, 381
SendInput {Numpad9}
SendInput {Numpad5}
Sleep, 254
SendInput {Numpad0}
SendInput {Numpad5}
Sleep, 127
SendInput {Numpad3}
Sleep, 254
SendInput {Numpad5}
Sleep, 254
SendInput {Numpad6}
Sleep, 254
SendInput {Numpad6}
Sleep, 1144
SendInput {Numpad5}
Sleep, 127
SendInput {Numpad3}
Sleep, 254
SendInput {Numpad2}
Sleep, 254
SendInput {Numpad1}
Sleep, 254
SendInput {Numpad6}
Sleep, 508
SendInput {Numpad0}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 381
SendInput {Numpad9}
SendInput {Numpad5}
SendInput {Numpad6}
Sleep, 254
SendInput {Numpad5}
SendInput {Numpad6}
Sleep, 127
SendInput {Numpad3}
SendInput {Numpad2}
Sleep, 254
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 254
SendInput {Numpad5}
Sleep, 254
SendInput {Numpad6}
Sleep, 508
SendInput {Numpad0}
SendInput {Numpad6}
SendInput {Numpad3}
Sleep, 381
SendInput {Numpad9}
SendInput {Numpad6}
Sleep, 254
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 127
SendInput {Numpad3}
SendInput {Numpad4}
Sleep, 254
SendInput {Numpad5}
SendInput {Numpad3}
Sleep, 254
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 254
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 254
SendInput {Numpad0}
SendInput {Numpad3}
Sleep, 254
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 254
SendInput {Numpad9}
SendInput {Numpad6}
Sleep, 127
SendInput {Numpad5}
Sleep, 254
SendInput {Numpad5}
Sleep, 127
SendInput {Numpad3}
Sleep, 254
SendInput {Numpad5}
SendInput {Numpad7}
Sleep, 254
SendInput {Numpad6}
Sleep, 254
SendInput {Numpad6}
Sleep, 1144
SendInput {Numpad5}
Sleep, 127
SendInput {Numpad3}
Sleep, 254
SendInput {Numpad2}
Sleep, 254
SendInput {Numpad1}
Sleep, 254
SendInput {Numpad6}
Sleep, 508
SendInput {Numpad0}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 381
SendInput {Numpad9}
SendInput {Numpad5}
SendInput {Numpad6}
Sleep, 254
SendInput {Numpad5}
SendInput {Numpad6}
Sleep, 127
SendInput {Numpad3}
SendInput {Numpad2}
Sleep, 254
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 254
SendInput {Numpad5}
Sleep, 254
SendInput {Numpad6}
Sleep, 508
SendInput {Numpad0}
SendInput {Numpad6}
SendInput {Numpad3}
Sleep, 381
SendInput {Numpad9}
SendInput {Numpad6}
Sleep, 254
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 127
SendInput {Numpad3}
SendInput {Numpad4}
Sleep, 254
SendInput {Numpad5}
SendInput {Numpad3}
Sleep, 254
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 254
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 254
SendInput {Numpad0}
SendInput {Numpad3}
Sleep, 254
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 254
SendInput {Numpad9}
SendInput {Numpad6}
Sleep, 127
SendInput {Numpad5}
Sleep, 254
SendInput {Numpad5}
Sleep, 127
SendInput {Numpad3}
Sleep, 254
SendInput {Numpad5}
SendInput {Numpad7}
Sleep, 254
SendInput {Numpad6}
Sleep, 254
SendInput {Numpad6}
Sleep, 1144
SendInput {Numpad9}
SendInput {Numpad6}
Sleep, 127
SendInput {Numpad6}
Sleep, 254
SendInput {Numpad6}
Sleep, 254
SendInput {Numpad7}
Sleep, 254
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 381
SendInput {Numpad9}
SendInput {Numpad5}
Sleep, 127
SendInput {Numpad1}
Sleep, 254
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 127
SendInput {F5}
Sleep, 254
SendInput {F5}
Sleep, 127
SendInput {Numpad5}
Sleep, 254
SendInput {F5}
SendInput {Numpad1}
Sleep, 254
SendInput {Numpad9}
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 254
SendInput {Numpad0}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 381
SendInput {Numpad9}
SendInput {Numpad5}
Sleep, 127
SendInput {Numpad6}
Sleep, 254
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 508
SendInput {Numpad9}
SendInput {Numpad5}
Sleep, 254
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 127
SendInput {Numpad1}
Sleep, 127
SendInput {Numpad5}
Sleep, 254
SendInput {F5}
SendInput {Numpad1}
Sleep, 381
SendInput {Numpad9}
SendInput {Numpad5}
Sleep, 127
SendInput {F5}
Sleep, 254
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 127
SendInput {F5}
Sleep, 254
SendInput {F5}
Sleep, 127
SendInput {F5}
SendInput {Numpad5}
Sleep, 254
SendInput {F5}
SendInput {Numpad1}
Sleep, 254
SendInput {Numpad9}
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 254
SendInput {Numpad0}
SendInput {Numpad5}
SendInput {Numpad1}
Sleep, 381
SendInput {Numpad9}
SendInput {Numpad5}
Sleep, 127
SendInput {Numpad5}
Sleep, 254
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 381
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad4}
Sleep, 127
SendInput {Numpad5}
Sleep, 254
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 254
SendInput {Numpad9}
SendInput {Numpad5}
Sleep, 254
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 381
SendInput {Numpad9}
SendInput {Numpad5}
Sleep, 127
SendInput {Numpad1}
Sleep, 254
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 127
SendInput {F5}
Sleep, 254
SendInput {F5}
Sleep, 127
SendInput {Numpad5}
Sleep, 254
SendInput {F5}
SendInput {Numpad1}
Sleep, 254
SendInput {Numpad9}
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 254
SendInput {Numpad0}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 381
SendInput {Numpad9}
SendInput {Numpad5}
Sleep, 127
SendInput {Numpad6}
Sleep, 254
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 508
SendInput {Numpad9}
SendInput {Numpad5}
Sleep, 254
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 127
SendInput {Numpad1}
Sleep, 127
SendInput {Numpad5}
Sleep, 254
SendInput {F5}
SendInput {Numpad1}
Sleep, 381
SendInput {Numpad9}
SendInput {Numpad5}
Sleep, 127
SendInput {F5}
Sleep, 254
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 127
SendInput {F5}
Sleep, 254
SendInput {F5}
Sleep, 127
SendInput {F5}
SendInput {Numpad5}
Sleep, 254
SendInput {F5}
SendInput {Numpad1}
Sleep, 254
SendInput {Numpad9}
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 254
SendInput {Numpad0}
SendInput {Numpad5}
SendInput {Numpad1}
Sleep, 381
SendInput {Numpad9}
SendInput {Numpad5}
Sleep, 127
SendInput {Numpad5}
Sleep, 254
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 381
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad4}
Sleep, 127
SendInput {Numpad5}
Sleep, 254
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 254
SendInput {Numpad9}
SendInput {Numpad5}
Sleep, 254
SendInput {Numpad0}
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 127
SendInput {Numpad3}
Sleep, 127
SendInput {Numpad2}
Sleep, 127
SendInput {Numpad1}
Sleep, 127
SendInput {Numpad1}
Sleep, 127
SendInput {Numpad2}
Sleep, 254
SendInput {F5}
SendInput {Numpad3}
Sleep, 127
SendInput {Numpad5}
Sleep, 127
SendInput {F5}
Sleep, 127
SendInput {Numpad5}
SendInput {Numpad3}
Sleep, 254
SendInput {F5}
SendInput {Numpad2}
Sleep, 254
SendInput {Numpad1}
Sleep, 254
SendInput {Numpad6}
SendInput {Numpad5}
Sleep, 127
SendInput {Numpad3}
Sleep, 127
SendInput {Numpad2}
Sleep, 127
SendInput {Numpad1}
Sleep, 127
SendInput {Numpad6}
Sleep, 127
SendInput {Numpad2}
Sleep, 254
SendInput {Numpad3}
Sleep, 127
SendInput {Numpad5}
Sleep, 254
SendInput {Numpad3}
Sleep, 254
SendInput {Numpad2}
Sleep, 254
SendInput {Numpad1}
Sleep, 254
SendInput {F5}
SendInput {Numpad5}
Sleep, 127
SendInput {Numpad4}
Sleep, 127
SendInput {Numpad2}
Sleep, 127
SendInput {Numpad1}
Sleep, 127
SendInput {F5}
Sleep, 127
SendInput {Numpad2}
Sleep, 254
SendInput {F5}
SendInput {Numpad4}
Sleep, 127
SendInput {Numpad5}
Sleep, 127
SendInput {F5}
Sleep, 127
SendInput {F5}
SendInput {Numpad4}
Sleep, 254
SendInput {F5}
SendInput {Numpad2}
Sleep, 254
SendInput {Numpad1}
Sleep, 254
SendInput {Numpad5}
Sleep, 127
SendInput {Numpad4}
Sleep, 127
SendInput {Numpad2}
Sleep, 127
SendInput {Numpad1}
Sleep, 127
SendInput {Numpad5}
Sleep, 127
SendInput {Numpad2}
Sleep, 254
SendInput {Numpad4}
Sleep, 127
SendInput {Numpad5}
Sleep, 127
SendInput {Numpad4}
Sleep, 127
SendInput {Numpad5}
SendInput {Numpad4}
Sleep, 254
SendInput {Numpad6}
SendInput {Numpad2}
Sleep, 254
SendInput {Numpad5}
SendInput {Numpad1}
Sleep, 254
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 127
SendInput {Numpad3}
Sleep, 127
SendInput {Numpad2}
Sleep, 127
SendInput {Numpad1}
Sleep, 127
SendInput {Numpad1}
Sleep, 127
SendInput {Numpad2}
Sleep, 254
SendInput {F5}
SendInput {Numpad3}
Sleep, 127
SendInput {Numpad5}
Sleep, 127
SendInput {F5}
Sleep, 127
SendInput {Numpad5}
SendInput {Numpad3}
Sleep, 254
SendInput {F5}
SendInput {Numpad2}
Sleep, 254
SendInput {Numpad1}
Sleep, 254
SendInput {Numpad6}
SendInput {Numpad5}
Sleep, 127
SendInput {Numpad3}
Sleep, 127
SendInput {Numpad2}
Sleep, 127
SendInput {Numpad1}
Sleep, 127
SendInput {Numpad6}
Sleep, 127
SendInput {Numpad2}
Sleep, 254
SendInput {Numpad3}
Sleep, 127
SendInput {Numpad5}
Sleep, 254
SendInput {Numpad3}
Sleep, 254
SendInput {Numpad2}
Sleep, 254
SendInput {Numpad1}
Sleep, 254
SendInput {F5}
SendInput {Numpad5}
Sleep, 127
SendInput {Numpad4}
Sleep, 127
SendInput {Numpad2}
Sleep, 127
SendInput {Numpad1}
Sleep, 127
SendInput {F5}
Sleep, 127
SendInput {Numpad2}
Sleep, 254
SendInput {F5}
SendInput {Numpad4}
Sleep, 127
SendInput {Numpad5}
Sleep, 127
SendInput {F5}
Sleep, 127
SendInput {F5}
SendInput {Numpad4}
Sleep, 254
SendInput {F5}
SendInput {Numpad2}
Sleep, 254
SendInput {Numpad1}
Sleep, 254
SendInput {Numpad5}
Sleep, 127
SendInput {Numpad4}
Sleep, 127
SendInput {Numpad2}
Sleep, 127
SendInput {Numpad1}
Sleep, 127
SendInput {Numpad5}
Sleep, 127
SendInput {Numpad2}
Sleep, 254
SendInput {Numpad4}
Sleep, 127
SendInput {Numpad5}
Sleep, 127
SendInput {Numpad4}
Sleep, 127
SendInput {Numpad5}
SendInput {Numpad4}
Sleep, 254
SendInput {Numpad6}
SendInput {Numpad2}
Sleep, 254
SendInput {Numpad5}
SendInput {Numpad1}
Sleep, 254
SendInput {F5}
SendInput {Numpad5}
Sleep, 127
SendInput {Numpad4}
Sleep, 127
SendInput {Numpad2}
Sleep, 127
SendInput {Numpad1}
Sleep, 127
SendInput {F5}
Sleep, 127
SendInput {Numpad2}
Sleep, 254
SendInput {F5}
SendInput {Numpad4}
Sleep, 127
SendInput {Numpad5}
Sleep, 127
SendInput {F5}
Sleep, 127
SendInput {F5}
SendInput {Numpad4}
Sleep, 254
SendInput {F5}
SendInput {Numpad2}
Sleep, 254
SendInput {Numpad1}
Sleep, 254
SendInput {Numpad5}
Sleep, 127
SendInput {Numpad4}
Sleep, 127
SendInput {Numpad2}
Sleep, 127
SendInput {Numpad1}
Sleep, 127
SendInput {Numpad5}
Sleep, 127
SendInput {Numpad2}
Sleep, 254
SendInput {Numpad4}
Sleep, 127
SendInput {Numpad5}
Sleep, 254
SendInput {Numpad4}
Sleep, 254
SendInput {Numpad2}
Sleep, 127
SendInput {Numpad5}
Sleep, 127
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 254
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad6}
Sleep, 254
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad6}
SendInput {F1}
SendInput {Numpad3}
Sleep, 254
SendInput {Numpad9}
SendInput {Numpad6}
SendInput {F1}
SendInput {Numpad3}
Sleep, 254
SendInput {Numpad0}
SendInput {Numpad6}
SendInput {F1}
SendInput {Numpad3}
Sleep, 127
SendInput {Numpad5}
SendInput {Numpad7}
SendInput {Numpad2}
Sleep, 254
SendInput {Numpad9}
SendInput {Numpad5}
SendInput {Numpad7}
SendInput {Numpad2}
Sleep, 127
SendInput {Numpad3}
Sleep, 127
SendInput {Numpad7}
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 127
SendInput {Numpad3}
SendInput {Numpad6}
SendInput {Numpad2}
SendInput {F3}
Sleep, 254
SendInput {Numpad0}
SendInput {Numpad5}
SendInput {Numpad6}
SendInput {Numpad2}
SendInput {F3}
Sleep, 254
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad6}
Sleep, 254
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad6}
SendInput {F1}
SendInput {Numpad3}
Sleep, 254
SendInput {Numpad9}
SendInput {Numpad6}
SendInput {F1}
SendInput {Numpad3}
Sleep, 254
SendInput {Numpad0}
SendInput {Numpad6}
SendInput {F1}
SendInput {Numpad3}
Sleep, 127
SendInput {Numpad7}
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 254
SendInput {Numpad3}
SendInput {Numpad7}
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 127
SendInput {Numpad3}
SendInput {Numpad6}
SendInput {Numpad2}
SendInput {F3}
Sleep, 254
SendInput {Numpad5}
SendInput {Numpad6}
SendInput {F1}
SendInput {Numpad3}
Sleep, 254
SendInput {Numpad6}
Sleep, 254
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad4}
Sleep, 254
SendInput {Numpad0}
SendInput {Numpad4}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 254
SendInput {Numpad4}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 254
SendInput {Numpad4}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 127
SendInput {Numpad5}
Sleep, 127
SendInput {Numpad4}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 127
SendInput {Numpad5}
SendInput {Numpad7}
SendInput {Numpad2}
Sleep, 127
SendInput {Numpad3}
Sleep, 127
SendInput {Numpad5}
SendInput {Numpad7}
SendInput {Numpad2}
Sleep, 127
SendInput {Numpad5}
Sleep, 127
SendInput {Numpad5}
SendInput {Numpad7}
SendInput {Numpad2}
Sleep, 127
SendInput {Numpad6}
Sleep, 127
SendInput {Numpad5}
SendInput {Numpad7}
SendInput {Numpad2}
Sleep, 127
SendInput {Numpad5}
SendInput {Numpad6}
SendInput {Numpad7}
SendInput {Numpad2}
Sleep, 254
SendInput {Numpad0}
SendInput {Numpad6}
SendInput {F1}
SendInput {Numpad3}
Sleep, 254
SendInput {Numpad6}
SendInput {F1}
SendInput {Numpad3}
Sleep, 254
SendInput {Numpad6}
SendInput {F1}
SendInput {Numpad3}
Sleep, 254
SendInput {Numpad9}
SendInput {Numpad5}
SendInput {Numpad7}
SendInput {Numpad2}
Sleep, 127
SendInput {Numpad5}
SendInput {Numpad6}
SendInput {F1}
SendInput {Numpad3}
Sleep, 127
SendInput {Numpad3}
Sleep, 127
SendInput {Numpad6}
SendInput {F1}
SendInput {Numpad3}
Sleep, 127
SendInput {Numpad2}
Sleep, 254
SendInput {Numpad1}
Sleep, 254
SendInput {Numpad9}
SendInput {Numpad6}
Sleep, 254
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad6}
SendInput {F1}
SendInput {Numpad3}
Sleep, 254
SendInput {Numpad9}
SendInput {Numpad6}
SendInput {F1}
SendInput {Numpad3}
Sleep, 254
SendInput {Numpad0}
SendInput {Numpad6}
SendInput {F1}
SendInput {Numpad3}
Sleep, 127
SendInput {Numpad5}
SendInput {Numpad7}
SendInput {Numpad2}
Sleep, 254
SendInput {Numpad9}
SendInput {Numpad5}
SendInput {Numpad7}
SendInput {Numpad2}
Sleep, 127
SendInput {Numpad3}
Sleep, 127
SendInput {Numpad7}
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 127
SendInput {Numpad3}
SendInput {Numpad6}
SendInput {Numpad2}
SendInput {F3}
Sleep, 254
SendInput {Numpad0}
SendInput {Numpad5}
SendInput {Numpad6}
SendInput {Numpad2}
SendInput {F3}
Sleep, 254
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad6}
Sleep, 254
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad6}
SendInput {F1}
SendInput {Numpad3}
Sleep, 254
SendInput {Numpad9}
SendInput {Numpad6}
SendInput {F1}
SendInput {Numpad3}
Sleep, 254
SendInput {Numpad0}
SendInput {Numpad6}
SendInput {F1}
SendInput {Numpad3}
Sleep, 127
SendInput {Numpad7}
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 254
SendInput {Numpad3}
SendInput {Numpad7}
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 127
SendInput {Numpad3}
SendInput {Numpad6}
SendInput {Numpad2}
SendInput {F3}
Sleep, 254
SendInput {Numpad5}
SendInput {Numpad6}
SendInput {F1}
SendInput {Numpad3}
Sleep, 254
SendInput {Numpad6}
Sleep, 254
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad4}
Sleep, 254
SendInput {Numpad0}
SendInput {Numpad4}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 254
SendInput {Numpad4}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 254
SendInput {Numpad4}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 127
SendInput {Numpad5}
Sleep, 127
SendInput {Numpad4}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 127
SendInput {Numpad5}
SendInput {Numpad7}
SendInput {Numpad2}
Sleep, 127
SendInput {Numpad3}
Sleep, 127
SendInput {Numpad5}
SendInput {Numpad7}
SendInput {Numpad2}
Sleep, 127
SendInput {Numpad5}
Sleep, 127
SendInput {Numpad5}
SendInput {Numpad7}
SendInput {Numpad2}
Sleep, 127
SendInput {Numpad6}
Sleep, 127
SendInput {Numpad5}
SendInput {Numpad7}
SendInput {Numpad2}
Sleep, 127
SendInput {Numpad5}
SendInput {Numpad6}
SendInput {Numpad7}
SendInput {Numpad2}
Sleep, 254
SendInput {Numpad0}
SendInput {Numpad6}
SendInput {F1}
SendInput {Numpad3}
Sleep, 254
SendInput {Numpad6}
SendInput {F1}
SendInput {Numpad3}
Sleep, 254
SendInput {Numpad6}
SendInput {F1}
SendInput {Numpad3}
Sleep, 254
SendInput {Numpad9}
SendInput {Numpad5}
SendInput {Numpad7}
SendInput {Numpad2}
Sleep, 127
SendInput {Numpad5}
SendInput {Numpad6}
SendInput {F1}
SendInput {Numpad3}
Sleep, 127
SendInput {Numpad3}
Sleep, 127
SendInput {Numpad6}
SendInput {F1}
SendInput {Numpad3}
Sleep, 127
SendInput {Numpad2}
Sleep, 254
SendInput {Numpad1}
Sleep, 254
SendInput {Numpad9}
SendInput {Numpad4}
Sleep, 254
SendInput {Numpad0}
SendInput {Numpad4}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 254
SendInput {Numpad4}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 254
SendInput {Numpad4}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 127
SendInput {Numpad5}
Sleep, 127
SendInput {Numpad4}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 127
SendInput {Numpad5}
SendInput {Numpad7}
SendInput {Numpad2}
Sleep, 127
SendInput {Numpad3}
Sleep, 127
SendInput {Numpad5}
SendInput {Numpad7}
SendInput {Numpad2}
Sleep, 127
SendInput {Numpad5}
Sleep, 127
SendInput {Numpad5}
SendInput {Numpad7}
SendInput {Numpad2}
Sleep, 127
SendInput {Numpad6}
Sleep, 127
SendInput {Numpad5}
SendInput {Numpad7}
SendInput {Numpad2}
Sleep, 127
SendInput {Numpad5}
SendInput {Numpad6}
SendInput {Numpad7}
SendInput {Numpad2}
Sleep, 254
SendInput {Numpad0}
SendInput {Numpad6}
SendInput {F1}
SendInput {Numpad3}
Sleep, 254
SendInput {Numpad6}
SendInput {F1}
SendInput {Numpad3}
Sleep, 254
SendInput {Numpad6}
SendInput {F1}
SendInput {Numpad3}
Sleep, 254
SendInput {Numpad9}
SendInput {Numpad5}
SendInput {Numpad7}
SendInput {Numpad2}
Sleep, 127
SendInput {Numpad5}
SendInput {Numpad6}
SendInput {F1}
SendInput {Numpad3}
Sleep, 127
SendInput {Numpad3}
Sleep, 127
SendInput {Numpad6}
SendInput {F1}
SendInput {Numpad3}
Sleep, 127
SendInput {Numpad2}
Sleep, 254
SendInput {Numpad1}
Sleep, 254
SendInput {Numpad6}
Sleep, 508
SendInput {Numpad0}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 381
SendInput {Numpad9}
SendInput {Numpad5}
SendInput {Numpad6}
Sleep, 254
SendInput {Numpad5}
SendInput {Numpad6}
Sleep, 127
SendInput {Numpad3}
SendInput {Numpad2}
Sleep, 254
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 254
SendInput {Numpad5}
Sleep, 254
SendInput {Numpad6}
Sleep, 508
SendInput {Numpad0}
SendInput {Numpad6}
SendInput {Numpad3}
Sleep, 381
SendInput {Numpad9}
SendInput {Numpad6}
Sleep, 254
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 127
SendInput {Numpad3}
SendInput {Numpad4}
Sleep, 254
SendInput {Numpad5}
SendInput {Numpad3}
Sleep, 254
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 254
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 254
SendInput {Numpad0}
SendInput {Numpad3}
Sleep, 254
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 254
SendInput {Numpad9}
SendInput {Numpad6}
Sleep, 127
SendInput {Numpad5}
Sleep, 254
SendInput {Numpad5}
Sleep, 127
SendInput {Numpad3}
Sleep, 254
SendInput {Numpad5}
SendInput {Numpad7}
Sleep, 254
SendInput {Numpad6}
Sleep, 254
SendInput {Numpad6}
Sleep, 1144
SendInput {Numpad5}
Sleep, 127
SendInput {Numpad3}
Sleep, 254
SendInput {Numpad2}
Sleep, 254
SendInput {Numpad1}
Sleep, 254
SendInput {Numpad6}
Sleep, 508
SendInput {Numpad0}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 381
SendInput {Numpad9}
SendInput {Numpad5}
SendInput {Numpad6}
Sleep, 254
SendInput {Numpad5}
SendInput {Numpad6}
Sleep, 127
SendInput {Numpad3}
SendInput {Numpad2}
Sleep, 254
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 254
SendInput {Numpad5}
Sleep, 254
SendInput {Numpad6}
Sleep, 508
SendInput {Numpad0}
SendInput {Numpad6}
SendInput {Numpad3}
Sleep, 381
SendInput {Numpad9}
SendInput {Numpad6}
Sleep, 254
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 127
SendInput {Numpad3}
SendInput {Numpad4}
Sleep, 254
SendInput {Numpad5}
SendInput {Numpad3}
Sleep, 254
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 254
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 254
SendInput {Numpad0}
SendInput {Numpad3}
Sleep, 254
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 254
SendInput {Numpad9}
SendInput {Numpad6}
Sleep, 127
SendInput {Numpad5}
Sleep, 254
SendInput {Numpad5}
Sleep, 127
SendInput {Numpad3}
Sleep, 254
SendInput {Numpad5}
SendInput {Numpad7}
Sleep, 254
SendInput {Numpad6}
Sleep, 254
SendInput {Numpad6}
Sleep, 1144
SendInput {Numpad5}
Sleep, 127
SendInput {Numpad3}
Sleep, 254
SendInput {Numpad2}
Sleep, 254
SendInput {Numpad1}
Sleep, 1000
