; title: Baby Shark
; author: Pinkfong
; instrument: Piano
; Converted by Serenade Music Converter

SendInput {Numpad9}
SendInput {Numpad7}
Sleep, 1034
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 1034
SendInput {Numpad9}
SendInput {Numpad7}
Sleep, 1034
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 1034
SendInput {Numpad9}
SendInput {Numpad7}
Sleep, 517
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 517
SendInput {Numpad9}
SendInput {Numpad7}
Sleep, 517
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 517
SendInput {Numpad3}
SendInput {Numpad7}
Sleep, 259
SendInput {Numpad0}
SendInput {Numpad2}
SendInput {Numpad1}
Sleep, 259
SendInput {Numpad9}
SendInput {Numpad3}
SendInput {Numpad7}
Sleep, 259
SendInput {Numpad0}
SendInput {Numpad4}
SendInput {Numpad1}
Sleep, 259
SendInput {Numpad9}
SendInput {Numpad3}
SendInput {Numpad7}
Sleep, 259
SendInput {Numpad0}
SendInput {Numpad2}
SendInput {Numpad1}
Sleep, 259
SendInput {Numpad9}
SendInput {Numpad7}
Sleep, 259
SendInput {Numpad0}
SendInput {Numpad2}
SendInput {Numpad1}
Sleep, 259
SendInput {Numpad9}
SendInput {Numpad3}
SendInput {F4}
SendInput {Numpad7}
Sleep, 259
SendInput {Numpad0}
SendInput {Numpad2}
Sleep, 259
SendInput {Numpad3}
Sleep, 259
SendInput {Numpad4}
Sleep, 259
SendInput {Numpad3}
Sleep, 259
SendInput {Numpad2}
Sleep, 259
SendInput {Numpad9}
SendInput {Numpad3}
SendInput {Numpad7}
Sleep, 259
SendInput {Numpad0}
SendInput {Numpad2}
Sleep, 259
SendInput {Numpad6}
SendInput {F1}
SendInput {Numpad3}
Sleep, 259
SendInput {Numpad2}
Sleep, 259
SendInput {Numpad6}
SendInput {Numpad3}
Sleep, 259
SendInput {Numpad4}
Sleep, 259
SendInput {Numpad6}
SendInput {Numpad3}
Sleep, 259
SendInput {Numpad2}
Sleep, 259
SendInput {Numpad9}
SendInput {Numpad6}
SendInput {Numpad7}
Sleep, 259
SendInput {Numpad0}
SendInput {Numpad2}
Sleep, 259
SendInput {Numpad9}
SendInput {F1}
SendInput {F4}
SendInput {Numpad7}
SendInput {Numpad3}
Sleep, 259
SendInput {Numpad0}
SendInput {Numpad2}
Sleep, 259
SendInput {F1}
SendInput {Numpad3}
Sleep, 259
SendInput {Numpad4}
Sleep, 259
SendInput {F1}
SendInput {Numpad3}
Sleep, 259
SendInput {Numpad2}
Sleep, 259
SendInput {F1}
Sleep, 259
SendInput {Numpad3}
Sleep, 259
SendInput {Numpad9}
SendInput {Numpad7}
SendInput {F2}
SendInput {F3}
Sleep, 1034
SendInput {Numpad7}
Sleep, 517
SendInput {Numpad0}
SendInput {F1}
Sleep, 517
SendInput {Numpad3}
SendInput {F4}
SendInput {Numpad7}
Sleep, 259
SendInput {Numpad3}
Sleep, 259
SendInput {Numpad3}
Sleep, 259
SendInput {Numpad3}
Sleep, 129
SendInput {F4}
SendInput {Numpad7}
SendInput {Numpad3}
Sleep, 129
SendInput {Numpad3}
Sleep, 129
SendInput {Numpad3}
Sleep, 129
SendInput {Numpad3}
Sleep, 259
SendInput {Numpad9}
SendInput {Numpad3}
SendInput {Numpad7}
Sleep, 259
SendInput {Numpad0}
SendInput {F1}
Sleep, 259
SendInput {Numpad6}
SendInput {F1}
SendInput {Numpad3}
Sleep, 259
SendInput {Numpad3}
Sleep, 259
SendInput {Numpad6}
SendInput {Numpad3}
Sleep, 259
SendInput {Numpad3}
Sleep, 129
SendInput {Numpad6}
SendInput {F1}
SendInput {Numpad3}
Sleep, 129
SendInput {Numpad6}
Sleep, 129
SendInput {Numpad3}
Sleep, 129
SendInput {Numpad3}
Sleep, 259
SendInput {Numpad9}
SendInput {Numpad6}
SendInput {Numpad7}
Sleep, 259
SendInput {Numpad0}
SendInput {F1}
Sleep, 259
SendInput {F1}
SendInput {F4}
SendInput {Numpad7}
SendInput {Numpad3}
Sleep, 259
SendInput {Numpad3}
Sleep, 259
SendInput {F1}
SendInput {Numpad3}
Sleep, 259
SendInput {Numpad3}
Sleep, 129
SendInput {F4}
SendInput {Numpad7}
SendInput {Numpad3}
Sleep, 129
SendInput {F1}
Sleep, 129
SendInput {Numpad3}
Sleep, 129
SendInput {Numpad3}
Sleep, 259
SendInput {F1}
SendInput {Numpad3}
Sleep, 259
SendInput {Numpad3}
Sleep, 259
SendInput {Numpad7}
SendInput {F3}
SendInput {F2}
Sleep, 517
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad7}
Sleep, 517
SendInput {Numpad0}
SendInput {Numpad7}
Sleep, 517
SendInput {Numpad0}
SendInput {Numpad7}
SendInput {F1}
Sleep, 517
SendInput {Numpad3}
SendInput {F4}
SendInput {Numpad7}
Sleep, 259
SendInput {Numpad3}
Sleep, 259
SendInput {Numpad3}
Sleep, 259
SendInput {Numpad3}
Sleep, 129
SendInput {F4}
SendInput {Numpad7}
SendInput {Numpad3}
Sleep, 129
SendInput {Numpad3}
Sleep, 129
SendInput {Numpad3}
Sleep, 129
SendInput {Numpad3}
Sleep, 259
SendInput {Numpad9}
SendInput {Numpad3}
SendInput {Numpad7}
Sleep, 259
SendInput {Numpad0}
SendInput {F1}
Sleep, 259
SendInput {Numpad6}
SendInput {F1}
SendInput {Numpad3}
Sleep, 259
SendInput {Numpad3}
Sleep, 259
SendInput {Numpad6}
SendInput {Numpad3}
Sleep, 259
SendInput {Numpad3}
Sleep, 129
SendInput {Numpad6}
SendInput {F1}
SendInput {Numpad3}
Sleep, 129
SendInput {Numpad6}
Sleep, 129
SendInput {Numpad3}
Sleep, 129
SendInput {Numpad3}
Sleep, 259
SendInput {Numpad9}
SendInput {Numpad6}
SendInput {Numpad7}
Sleep, 259
SendInput {Numpad0}
SendInput {F1}
Sleep, 259
SendInput {F1}
SendInput {F4}
SendInput {Numpad7}
SendInput {Numpad3}
Sleep, 259
SendInput {Numpad3}
Sleep, 259
SendInput {F1}
SendInput {Numpad3}
Sleep, 259
SendInput {Numpad3}
Sleep, 129
SendInput {F4}
SendInput {Numpad7}
SendInput {Numpad3}
Sleep, 129
SendInput {F1}
Sleep, 129
SendInput {Numpad3}
Sleep, 129
SendInput {Numpad3}
Sleep, 259
SendInput {F1}
SendInput {Numpad3}
Sleep, 259
SendInput {Numpad3}
Sleep, 259
SendInput {Numpad7}
SendInput {F3}
SendInput {F2}
Sleep, 1034
SendInput {Numpad9}
SendInput {Numpad7}
Sleep, 517
SendInput {Numpad0}
SendInput {F1}
Sleep, 517
SendInput {Numpad3}
SendInput {F4}
SendInput {Numpad7}
Sleep, 259
SendInput {Numpad3}
Sleep, 259
SendInput {Numpad3}
Sleep, 259
SendInput {Numpad3}
Sleep, 129
SendInput {F4}
SendInput {Numpad7}
SendInput {Numpad3}
Sleep, 129
SendInput {Numpad3}
Sleep, 129
SendInput {Numpad3}
Sleep, 129
SendInput {Numpad3}
Sleep, 259
SendInput {Numpad9}
SendInput {Numpad3}
SendInput {Numpad7}
Sleep, 259
SendInput {Numpad0}
SendInput {F1}
Sleep, 259
SendInput {Numpad6}
SendInput {F1}
SendInput {Numpad3}
Sleep, 259
SendInput {Numpad3}
Sleep, 259
SendInput {Numpad6}
SendInput {Numpad3}
Sleep, 259
SendInput {Numpad3}
Sleep, 129
SendInput {Numpad6}
SendInput {F1}
SendInput {Numpad3}
Sleep, 129
SendInput {Numpad6}
Sleep, 129
SendInput {Numpad3}
Sleep, 129
SendInput {Numpad3}
Sleep, 259
SendInput {Numpad9}
SendInput {Numpad6}
SendInput {Numpad7}
Sleep, 259
SendInput {Numpad0}
SendInput {F1}
Sleep, 259
SendInput {F1}
SendInput {F4}
SendInput {Numpad7}
SendInput {Numpad3}
Sleep, 259
SendInput {Numpad3}
Sleep, 259
SendInput {F1}
SendInput {Numpad3}
Sleep, 259
SendInput {Numpad3}
Sleep, 129
SendInput {F4}
SendInput {Numpad7}
SendInput {Numpad3}
Sleep, 129
SendInput {F1}
Sleep, 129
SendInput {Numpad3}
Sleep, 129
SendInput {Numpad3}
Sleep, 259
SendInput {F1}
SendInput {Numpad3}
Sleep, 259
SendInput {Numpad3}
Sleep, 259
SendInput {Numpad7}
SendInput {F3}
SendInput {F2}
Sleep, 517
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad7}
Sleep, 517
SendInput {Numpad0}
SendInput {Numpad7}
Sleep, 517
SendInput {Numpad0}
SendInput {Numpad7}
SendInput {F1}
Sleep, 517
SendInput {Numpad3}
SendInput {F4}
SendInput {Numpad7}
Sleep, 259
SendInput {Numpad3}
Sleep, 259
SendInput {Numpad3}
Sleep, 259
SendInput {Numpad3}
Sleep, 129
SendInput {F4}
SendInput {Numpad7}
SendInput {Numpad3}
Sleep, 129
SendInput {Numpad3}
Sleep, 129
SendInput {Numpad3}
Sleep, 129
SendInput {Numpad3}
Sleep, 259
SendInput {Numpad9}
SendInput {Numpad3}
SendInput {Numpad7}
Sleep, 259
SendInput {Numpad0}
SendInput {F1}
Sleep, 259
SendInput {Numpad6}
SendInput {F1}
SendInput {Numpad3}
Sleep, 259
SendInput {Numpad3}
Sleep, 259
SendInput {Numpad6}
SendInput {Numpad3}
Sleep, 259
SendInput {Numpad3}
Sleep, 129
SendInput {Numpad6}
SendInput {F1}
SendInput {Numpad3}
Sleep, 129
SendInput {Numpad6}
Sleep, 129
SendInput {Numpad3}
Sleep, 129
SendInput {Numpad3}
Sleep, 259
SendInput {Numpad9}
SendInput {Numpad6}
SendInput {Numpad7}
Sleep, 259
SendInput {Numpad0}
SendInput {F1}
Sleep, 259
SendInput {F1}
SendInput {F4}
SendInput {Numpad7}
SendInput {Numpad3}
Sleep, 259
SendInput {Numpad3}
Sleep, 259
SendInput {F1}
SendInput {Numpad3}
Sleep, 259
SendInput {Numpad3}
Sleep, 129
SendInput {F4}
SendInput {Numpad7}
SendInput {Numpad3}
Sleep, 129
SendInput {F1}
Sleep, 129
SendInput {Numpad3}
Sleep, 129
SendInput {Numpad3}
Sleep, 259
SendInput {F1}
SendInput {Numpad3}
Sleep, 259
SendInput {Numpad3}
Sleep, 259
SendInput {Numpad7}
SendInput {F3}
SendInput {F2}
Sleep, 1034
SendInput {Numpad9}
SendInput {Numpad7}
Sleep, 517
SendInput {Numpad0}
SendInput {F1}
Sleep, 517
SendInput {Numpad4}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 259
SendInput {Numpad4}
Sleep, 259
SendInput {Numpad4}
Sleep, 259
SendInput {Numpad4}
Sleep, 129
SendInput {Numpad6}
SendInput {Numpad1}
SendInput {Numpad4}
Sleep, 129
SendInput {Numpad4}
Sleep, 129
SendInput {Numpad4}
Sleep, 129
SendInput {Numpad4}
Sleep, 259
SendInput {Numpad4}
SendInput {Numpad1}
Sleep, 259
SendInput {Numpad2}
Sleep, 259
SendInput {F5}
SendInput {Numpad2}
SendInput {Numpad4}
Sleep, 259
SendInput {Numpad4}
Sleep, 259
SendInput {F5}
SendInput {Numpad4}
Sleep, 259
SendInput {Numpad4}
Sleep, 129
SendInput {F5}
SendInput {Numpad2}
SendInput {Numpad4}
Sleep, 129
SendInput {F5}
Sleep, 129
SendInput {Numpad4}
Sleep, 129
SendInput {Numpad4}
Sleep, 259
SendInput {F5}
SendInput {Numpad1}
Sleep, 259
SendInput {Numpad2}
Sleep, 259
SendInput {Numpad2}
SendInput {Numpad6}
SendInput {Numpad1}
SendInput {Numpad4}
Sleep, 259
SendInput {Numpad4}
Sleep, 259
SendInput {Numpad2}
SendInput {Numpad4}
Sleep, 259
SendInput {Numpad4}
Sleep, 129
SendInput {Numpad6}
SendInput {Numpad1}
SendInput {Numpad4}
Sleep, 129
SendInput {Numpad2}
Sleep, 129
SendInput {Numpad4}
Sleep, 129
SendInput {Numpad4}
Sleep, 259
SendInput {Numpad2}
SendInput {Numpad4}
Sleep, 259
SendInput {Numpad4}
Sleep, 259
SendInput {Numpad1}
SendInput {Numpad5}
SendInput {Numpad3}
Sleep, 388
SendInput {Numpad5}
SendInput {Numpad1}
SendInput {Numpad3}
Sleep, 129
SendInput {Numpad1}
Sleep, 259
SendInput {Numpad5}
SendInput {Numpad1}
SendInput {Numpad3}
Sleep, 259
SendInput {Numpad9}
SendInput {Numpad1}
Sleep, 259
SendInput {Numpad0}
SendInput {Numpad5}
SendInput {Numpad1}
SendInput {Numpad3}
Sleep, 259
SendInput {Numpad9}
SendInput {Numpad1}
SendInput {Numpad5}
SendInput {Numpad3}
Sleep, 517
SendInput {Numpad0}
SendInput {Numpad5}
SendInput {Numpad1}
SendInput {Numpad3}
Sleep, 259
SendInput {Numpad5}
SendInput {Numpad1}
SendInput {Numpad3}
Sleep, 259
SendInput {Numpad5}
SendInput {Numpad1}
SendInput {Numpad3}
Sleep, 517
SendInput {Numpad1}
Sleep, 517
SendInput {Numpad2}
Sleep, 517
SendInput {Numpad4}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 259
SendInput {Numpad4}
Sleep, 259
SendInput {Numpad4}
Sleep, 259
SendInput {Numpad4}
Sleep, 129
SendInput {Numpad6}
SendInput {Numpad1}
SendInput {Numpad4}
Sleep, 129
SendInput {Numpad4}
Sleep, 129
SendInput {Numpad4}
Sleep, 129
SendInput {Numpad4}
Sleep, 259
SendInput {Numpad4}
SendInput {Numpad1}
Sleep, 259
SendInput {Numpad2}
Sleep, 259
SendInput {F5}
SendInput {Numpad2}
SendInput {Numpad4}
Sleep, 259
SendInput {Numpad4}
Sleep, 259
SendInput {F5}
SendInput {Numpad4}
Sleep, 259
SendInput {Numpad4}
Sleep, 129
SendInput {F5}
SendInput {Numpad2}
SendInput {Numpad4}
Sleep, 129
SendInput {F5}
Sleep, 129
SendInput {Numpad4}
Sleep, 129
SendInput {Numpad4}
Sleep, 259
SendInput {F5}
SendInput {Numpad1}
Sleep, 259
SendInput {Numpad2}
Sleep, 259
SendInput {Numpad2}
SendInput {Numpad6}
SendInput {Numpad1}
SendInput {Numpad4}
Sleep, 259
SendInput {Numpad4}
Sleep, 259
SendInput {Numpad2}
SendInput {Numpad4}
Sleep, 259
SendInput {Numpad4}
Sleep, 129
SendInput {Numpad6}
SendInput {Numpad1}
SendInput {Numpad4}
Sleep, 129
SendInput {Numpad2}
Sleep, 129
SendInput {Numpad4}
Sleep, 129
SendInput {Numpad4}
Sleep, 259
SendInput {Numpad2}
SendInput {Numpad4}
Sleep, 259
SendInput {Numpad4}
Sleep, 259
SendInput {Numpad1}
SendInput {Numpad5}
SendInput {Numpad3}
Sleep, 517
SendInput {Numpad9}
SendInput {Numpad1}
Sleep, 517
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 517
SendInput {Numpad1}
SendInput {Numpad2}
Sleep, 517
SendInput {Numpad4}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 259
SendInput {Numpad4}
Sleep, 259
SendInput {Numpad4}
Sleep, 259
SendInput {Numpad4}
Sleep, 129
SendInput {Numpad6}
SendInput {Numpad1}
SendInput {Numpad4}
Sleep, 129
SendInput {Numpad4}
Sleep, 129
SendInput {Numpad4}
Sleep, 129
SendInput {Numpad4}
Sleep, 259
SendInput {Numpad4}
SendInput {Numpad1}
Sleep, 259
SendInput {Numpad2}
Sleep, 259
SendInput {F5}
SendInput {Numpad2}
SendInput {Numpad4}
Sleep, 259
SendInput {Numpad4}
Sleep, 259
SendInput {F5}
SendInput {Numpad4}
Sleep, 259
SendInput {Numpad4}
Sleep, 129
SendInput {F5}
SendInput {Numpad2}
SendInput {Numpad4}
Sleep, 129
SendInput {F5}
Sleep, 129
SendInput {Numpad4}
Sleep, 129
SendInput {Numpad4}
Sleep, 259
SendInput {F5}
SendInput {Numpad1}
Sleep, 259
SendInput {Numpad2}
Sleep, 259
SendInput {Numpad2}
SendInput {Numpad6}
SendInput {Numpad1}
SendInput {Numpad4}
Sleep, 259
SendInput {Numpad4}
Sleep, 259
SendInput {Numpad2}
SendInput {Numpad4}
Sleep, 259
SendInput {Numpad4}
Sleep, 129
SendInput {Numpad5}
SendInput {Numpad1}
SendInput {Numpad4}
Sleep, 129
SendInput {Numpad1}
SendInput {Numpad4}
SendInput {Numpad5}
Sleep, 129
SendInput {Numpad4}
Sleep, 129
SendInput {Numpad4}
Sleep, 259
SendInput {Numpad1}
SendInput {Numpad5}
SendInput {Numpad4}
Sleep, 259
SendInput {Numpad4}
Sleep, 259
SendInput {Numpad4}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 259
SendInput {Numpad1}
Sleep, 129
SendInput {Numpad2}
Sleep, 259
SendInput {Numpad1}
Sleep, 129
SendInput {Numpad2}
Sleep, 259
SendInput {Numpad9}
SendInput {Numpad4}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 1000
