; title: Behind Blue Eyes
; author: The Who
; instrument: Piano
; Converted by Serenade Music Converter

SendInput {Numpad0}
SendInput {Numpad6}
SendInput {Numpad2}
SendInput {Numpad3}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad3}
Sleep, 300
SendInput {Numpad6}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad2}
Sleep, 600
SendInput {Numpad3}
Sleep, 300
SendInput {Numpad2}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad6}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad6}
Sleep, 300
SendInput {Numpad3}
Sleep, 300
SendInput {Numpad2}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad6}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad3}
Sleep, 300
SendInput {Numpad2}
Sleep, 300
SendInput {Numpad3}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad6}
Sleep, 300
SendInput {Numpad3}
Sleep, 300
SendInput {Numpad6}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad2}
Sleep, 300
SendInput {Numpad3}
Sleep, 300
SendInput {Numpad2}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad6}
Sleep, 300
SendInput {Numpad3}
Sleep, 300
SendInput {Numpad6}
Sleep, 300
SendInput {Numpad3}
Sleep, 300
SendInput {Numpad6}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad2}
Sleep, 300
SendInput {Numpad6}
Sleep, 300
SendInput {Numpad3}
Sleep, 300
SendInput {Numpad2}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad6}
Sleep, 300
SendInput {Numpad3}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad6}
SendInput {Numpad1}
SendInput {Numpad3}
Sleep, 300
SendInput {Numpad3}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad1}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad6}
SendInput {Numpad3}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad3}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad1}
SendInput {Numpad2}
Sleep, 300
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 300
SendInput {Numpad1}
SendInput {Numpad3}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad1}
SendInput {Numpad5}
SendInput {Numpad3}
Sleep, 300
SendInput {Numpad5}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad3}
Sleep, 300
SendInput {Numpad1}
Sleep, 300
SendInput {Numpad5}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad3}
Sleep, 300
SendInput {Numpad1}
SendInput {Numpad3}
Sleep, 300
SendInput {Numpad3}
Sleep, 300
SendInput {Numpad5}
SendInput {Numpad7}
SendInput {Numpad2}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad2}
Sleep, 300
SendInput {Numpad5}
Sleep, 300
SendInput {Numpad7}
Sleep, 300
SendInput {Numpad5}
SendInput {Numpad7}
Sleep, 300
SendInput {Numpad2}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad7}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad2}
Sleep, 300
SendInput {Numpad5}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad5}
Sleep, 300
SendInput {Numpad2}
Sleep, 300
SendInput {Numpad7}
Sleep, 300
SendInput {Numpad5}
SendInput {Numpad7}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad2}
SendInput {Numpad3}
Sleep, 300
SendInput {Numpad5}
SendInput {Numpad3}
Sleep, 300
SendInput {Numpad4}
SendInput {Numpad5}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad1}
Sleep, 300
SendInput {Numpad5}
Sleep, 300
SendInput {Numpad6}
Sleep, 300
SendInput {Numpad5}
SendInput {Numpad6}
Sleep, 300
SendInput {Numpad4}
Sleep, 300
SendInput {Numpad1}
Sleep, 300
SendInput {Numpad2}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad4}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 300
SendInput {Numpad5}
Sleep, 300
SendInput {Numpad6}
Sleep, 300
SendInput {Numpad5}
Sleep, 300
SendInput {Numpad4}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 300
SendInput {Numpad2}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad2}
SendInput {F3}
SendInput {Numpad6}
SendInput {Numpad3}
Sleep, 300
SendInput {Numpad6}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad3}
Sleep, 300
SendInput {Numpad6}
SendInput {Numpad2}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad3}
Sleep, 300
SendInput {Numpad2}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad6}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad2}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad1}
Sleep, 300
SendInput {Numpad6}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad3}
Sleep, 300
SendInput {Numpad6}
Sleep, 300
SendInput {Numpad3}
Sleep, 300
SendInput {Numpad2}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad6}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad2}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad6}
SendInput {Numpad1}
SendInput {Numpad3}
Sleep, 300
SendInput {Numpad3}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad1}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad6}
SendInput {Numpad3}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad3}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad1}
SendInput {Numpad2}
Sleep, 300
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 300
SendInput {Numpad1}
SendInput {Numpad3}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad1}
SendInput {Numpad5}
SendInput {Numpad3}
Sleep, 300
SendInput {Numpad5}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad3}
Sleep, 300
SendInput {Numpad1}
Sleep, 300
SendInput {Numpad5}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad3}
Sleep, 300
SendInput {Numpad1}
SendInput {Numpad3}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad3}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad5}
SendInput {Numpad7}
SendInput {Numpad2}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad2}
Sleep, 300
SendInput {Numpad5}
Sleep, 300
SendInput {Numpad7}
Sleep, 300
SendInput {Numpad5}
SendInput {Numpad7}
Sleep, 300
SendInput {Numpad2}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad7}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad2}
Sleep, 300
SendInput {Numpad5}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad5}
Sleep, 300
SendInput {Numpad2}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad7}
SendInput {Numpad3}
Sleep, 300
SendInput {Numpad5}
SendInput {Numpad2}
SendInput {Numpad3}
Sleep, 300
SendInput {Numpad2}
SendInput {Numpad3}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad5}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad4}
SendInput {Numpad5}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad1}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad5}
SendInput {Numpad1}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad6}
Sleep, 300
SendInput {Numpad5}
SendInput {Numpad6}
Sleep, 300
SendInput {Numpad4}
Sleep, 300
SendInput {Numpad1}
Sleep, 300
SendInput {Numpad2}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad4}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 300
SendInput {Numpad5}
Sleep, 300
SendInput {Numpad5}
Sleep, 300
SendInput {Numpad5}
SendInput {Numpad6}
Sleep, 300
SendInput {Numpad4}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 300
SendInput {Numpad2}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad2}
SendInput {F3}
SendInput {Numpad6}
SendInput {Numpad3}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad6}
SendInput {Numpad3}
Sleep, 300
SendInput {Numpad3}
SendInput {Numpad2}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad6}
Sleep, 300
SendInput {Numpad3}
Sleep, 300
SendInput {Numpad2}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad6}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad2}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad2}
Sleep, 300
SendInput {Numpad6}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad2}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad6}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad2}
SendInput {Numpad3}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad1}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad5}
Sleep, 300
Sleep, 300
SendInput {Numpad4}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 600
SendInput {Numpad6}
SendInput {Numpad1}
SendInput {Numpad4}
Sleep, 600
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad1}
Sleep, 600
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad1}
SendInput {Numpad4}
Sleep, 300
SendInput {Numpad7}
Sleep, 150
SendInput {Numpad6}
Sleep, 150
SendInput {Numpad5}
SendInput {Numpad7}
SendInput {Numpad2}
Sleep, 600
SendInput {Numpad9}
SendInput {Numpad7}
SendInput {Numpad2}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad6}
Sleep, 300
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 600
SendInput {Numpad9}
SendInput {Numpad7}
SendInput {Numpad2}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad6}
Sleep, 300
SendInput {Numpad1}
SendInput {Numpad5}
SendInput {Numpad3}
Sleep, 600
SendInput {Numpad3}
SendInput {Numpad5}
SendInput {Numpad1}
Sleep, 1200
SendInput {Numpad9}
SendInput {Numpad1}
SendInput {Numpad5}
SendInput {Numpad3}
Sleep, 600
SendInput {Numpad9}
SendInput {Numpad3}
Sleep, 600
SendInput {Numpad0}
SendInput {Numpad5}
SendInput {Numpad1}
Sleep, 600
SendInput {Numpad0}
SendInput {Numpad1}
SendInput {Numpad3}
Sleep, 600
SendInput {Numpad3}
SendInput {Numpad5}
SendInput {Numpad1}
Sleep, 600
SendInput {Numpad4}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 600
SendInput {Numpad9}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 600
SendInput {Numpad0}
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 600
SendInput {Numpad9}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 600
SendInput {Numpad5}
SendInput {Numpad7}
SendInput {Numpad2}
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad2}
Sleep, 1050
SendInput {Numpad9}
SendInput {Numpad2}
Sleep, 600
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad6}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad6}
SendInput {F1}
SendInput {Numpad3}
Sleep, 600
SendInput {Numpad9}
SendInput {F1}
SendInput {Numpad3}
Sleep, 300
SendInput {F1}
SendInput {Numpad3}
Sleep, 300
Sleep, 600
SendInput {Numpad9}
SendInput {Numpad3}
Sleep, 600
Sleep, 600
SendInput {Numpad0}
SendInput {Numpad3}
SendInput {Numpad6}
SendInput {F1}
Sleep, 600
SendInput {Numpad0}
SendInput {Numpad6}
SendInput {Numpad3}
Sleep, 600
SendInput {Numpad5}
SendInput {Numpad6}
SendInput {F1}
Sleep, 600
SendInput {Numpad3}
SendInput {Numpad5}
SendInput {Numpad7}
SendInput {Numpad6}
Sleep, 600
SendInput {Numpad9}
SendInput {Numpad7}
SendInput {Numpad3}
Sleep, 600
SendInput {Numpad0}
SendInput {Numpad3}
SendInput {Numpad5}
Sleep, 600
SendInput {Numpad9}
SendInput {Numpad5}
SendInput {Numpad7}
SendInput {Numpad3}
Sleep, 600
SendInput {Numpad9}
SendInput {Numpad3}
Sleep, 600
SendInput {Numpad0}
SendInput {Numpad7}
SendInput {Numpad3}
Sleep, 600
SendInput {Numpad0}
SendInput {Numpad6}
Sleep, 600
SendInput {Numpad3}
SendInput {Numpad5}
Sleep, 300
SendInput {Numpad3}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad4}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad2}
Sleep, 300
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 300
SendInput {Numpad2}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad4}
Sleep, 600
SendInput {Numpad0}
SendInput {Numpad1}
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 600
SendInput {Numpad9}
SendInput {Numpad4}
Sleep, 600
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad6}
Sleep, 300
SendInput {Numpad1}
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 600
SendInput {Numpad0}
SendInput {Numpad4}
SendInput {Numpad6}
SendInput {Numpad2}
Sleep, 300
SendInput {Numpad2}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad5}
SendInput {Numpad7}
SendInput {Numpad2}
Sleep, 300
SendInput {Numpad2}
SendInput {Numpad5}
SendInput {Numpad7}
Sleep, 900
SendInput {Numpad9}
SendInput {Numpad5}
Sleep, 600
SendInput {Numpad0}
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 600
SendInput {Numpad9}
SendInput {Numpad5}
Sleep, 600
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad2}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad7}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad5}
SendInput {Numpad2}
SendInput {Numpad1}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad7}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad5}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad5}
Sleep, 300
SendInput {Numpad2}
SendInput {F3}
SendInput {Numpad6}
SendInput {Numpad3}
Sleep, 600
SendInput {Numpad3}
SendInput {F3}
Sleep, 600
SendInput {Numpad0}
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 600
SendInput {Numpad9}
SendInput {Numpad2}
SendInput {Numpad3}
SendInput {F3}
Sleep, 300
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad2}
SendInput {F3}
Sleep, 600
SendInput {Numpad9}
SendInput {Numpad3}
SendInput {F3}
SendInput {Numpad6}
Sleep, 600
SendInput {Numpad9}
SendInput {Numpad2}
Sleep, 600
SendInput {Numpad0}
SendInput {Numpad2}
SendInput {Numpad3}
SendInput {F3}
SendInput {Numpad6}
Sleep, 300
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad2}
Sleep, 600
SendInput {Numpad0}
SendInput {Numpad3}
SendInput {F3}
SendInput {Numpad6}
Sleep, 600
SendInput {Numpad9}
SendInput {Numpad2}
Sleep, 600
SendInput {Numpad0}
SendInput {Numpad2}
SendInput {Numpad3}
SendInput {F3}
SendInput {Numpad6}
Sleep, 300
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad2}
Sleep, 600
SendInput {Numpad0}
SendInput {Numpad3}
SendInput {F3}
SendInput {Numpad6}
Sleep, 600
SendInput {Numpad9}
SendInput {Numpad2}
Sleep, 600
SendInput {Numpad0}
SendInput {Numpad2}
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 600
SendInput {Numpad0}
SendInput {Numpad6}
SendInput {Numpad1}
SendInput {Numpad3}
Sleep, 300
SendInput {Numpad3}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad1}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad6}
SendInput {Numpad3}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad3}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad1}
SendInput {Numpad2}
Sleep, 300
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 300
SendInput {Numpad1}
SendInput {Numpad3}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad1}
SendInput {Numpad5}
SendInput {Numpad3}
Sleep, 300
SendInput {Numpad5}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad3}
Sleep, 300
SendInput {Numpad1}
Sleep, 300
SendInput {Numpad5}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad3}
Sleep, 300
SendInput {Numpad1}
SendInput {Numpad3}
Sleep, 300
SendInput {Numpad3}
Sleep, 300
SendInput {Numpad5}
SendInput {Numpad7}
SendInput {Numpad2}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad2}
Sleep, 300
SendInput {Numpad5}
Sleep, 300
SendInput {Numpad7}
Sleep, 300
SendInput {Numpad5}
SendInput {Numpad7}
Sleep, 300
SendInput {Numpad2}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad7}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad2}
Sleep, 300
SendInput {Numpad5}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad5}
Sleep, 300
SendInput {Numpad2}
Sleep, 300
SendInput {Numpad7}
Sleep, 300
SendInput {Numpad5}
SendInput {Numpad7}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad2}
SendInput {Numpad3}
Sleep, 300
SendInput {Numpad5}
SendInput {Numpad3}
Sleep, 300
SendInput {Numpad4}
SendInput {Numpad5}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad1}
Sleep, 300
SendInput {Numpad5}
Sleep, 300
SendInput {Numpad6}
Sleep, 300
SendInput {Numpad5}
SendInput {Numpad6}
Sleep, 300
SendInput {Numpad4}
Sleep, 300
SendInput {Numpad1}
Sleep, 300
SendInput {Numpad2}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad4}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 300
SendInput {Numpad5}
Sleep, 300
SendInput {Numpad6}
Sleep, 300
SendInput {Numpad5}
Sleep, 300
SendInput {Numpad4}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 300
SendInput {Numpad2}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad2}
SendInput {F3}
SendInput {Numpad6}
SendInput {Numpad3}
Sleep, 300
SendInput {Numpad6}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad3}
Sleep, 300
SendInput {Numpad6}
SendInput {Numpad2}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad3}
Sleep, 300
SendInput {Numpad2}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad6}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad2}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad1}
Sleep, 300
SendInput {Numpad6}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad3}
Sleep, 300
SendInput {Numpad6}
Sleep, 300
SendInput {Numpad3}
Sleep, 300
SendInput {Numpad2}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad6}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad2}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad6}
SendInput {Numpad1}
SendInput {Numpad3}
Sleep, 300
SendInput {Numpad3}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad1}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad6}
SendInput {Numpad3}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad3}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad1}
SendInput {Numpad2}
Sleep, 300
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 300
SendInput {Numpad1}
SendInput {Numpad3}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad1}
SendInput {Numpad5}
SendInput {Numpad3}
Sleep, 300
SendInput {Numpad5}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad3}
Sleep, 300
SendInput {Numpad1}
Sleep, 300
SendInput {Numpad5}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad3}
Sleep, 300
SendInput {Numpad1}
SendInput {Numpad3}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad3}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad5}
SendInput {Numpad7}
SendInput {Numpad2}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad2}
Sleep, 300
SendInput {Numpad5}
Sleep, 300
SendInput {Numpad7}
Sleep, 300
SendInput {Numpad5}
SendInput {Numpad7}
Sleep, 300
SendInput {Numpad2}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad7}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad2}
Sleep, 300
SendInput {Numpad5}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad5}
Sleep, 300
SendInput {Numpad2}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad7}
SendInput {Numpad3}
Sleep, 300
SendInput {Numpad5}
SendInput {Numpad2}
SendInput {Numpad3}
Sleep, 300
SendInput {Numpad2}
SendInput {Numpad3}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad5}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad4}
SendInput {Numpad5}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad1}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad5}
SendInput {Numpad1}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad6}
Sleep, 300
SendInput {Numpad5}
SendInput {Numpad6}
Sleep, 300
SendInput {Numpad4}
Sleep, 300
SendInput {Numpad1}
Sleep, 300
SendInput {Numpad2}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad4}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 300
SendInput {Numpad5}
Sleep, 300
SendInput {Numpad5}
Sleep, 300
SendInput {Numpad5}
SendInput {Numpad6}
Sleep, 300
SendInput {Numpad4}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 300
SendInput {Numpad2}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad2}
SendInput {F3}
SendInput {Numpad6}
SendInput {Numpad3}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad6}
SendInput {Numpad3}
Sleep, 300
SendInput {Numpad3}
SendInput {Numpad2}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad6}
Sleep, 300
SendInput {Numpad3}
Sleep, 300
SendInput {Numpad2}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad6}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad2}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad2}
Sleep, 300
SendInput {Numpad6}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad2}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad6}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad2}
SendInput {Numpad3}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad1}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad5}
Sleep, 300
Sleep, 300
SendInput {Numpad4}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 600
SendInput {Numpad6}
SendInput {Numpad1}
SendInput {Numpad4}
Sleep, 600
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad1}
Sleep, 600
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad1}
SendInput {Numpad4}
Sleep, 300
SendInput {Numpad7}
Sleep, 150
SendInput {Numpad6}
Sleep, 150
SendInput {Numpad5}
SendInput {Numpad7}
SendInput {Numpad2}
Sleep, 600
SendInput {Numpad9}
SendInput {Numpad7}
SendInput {Numpad2}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad6}
Sleep, 300
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 600
SendInput {Numpad9}
SendInput {Numpad7}
SendInput {Numpad2}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad6}
Sleep, 300
SendInput {Numpad1}
SendInput {Numpad5}
SendInput {Numpad3}
Sleep, 600
SendInput {Numpad3}
SendInput {Numpad5}
SendInput {Numpad1}
Sleep, 1200
SendInput {Numpad9}
SendInput {Numpad1}
SendInput {Numpad5}
SendInput {Numpad3}
Sleep, 600
SendInput {Numpad9}
SendInput {Numpad3}
Sleep, 600
SendInput {Numpad0}
SendInput {Numpad5}
SendInput {Numpad1}
Sleep, 600
SendInput {Numpad0}
SendInput {Numpad1}
SendInput {Numpad3}
Sleep, 600
SendInput {Numpad3}
SendInput {Numpad5}
SendInput {Numpad1}
Sleep, 600
SendInput {Numpad4}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 600
SendInput {Numpad9}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 600
SendInput {Numpad0}
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 600
SendInput {Numpad9}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 600
SendInput {Numpad5}
SendInput {Numpad7}
SendInput {Numpad2}
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad2}
Sleep, 1050
SendInput {Numpad9}
SendInput {Numpad2}
Sleep, 600
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad6}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad6}
SendInput {F1}
SendInput {Numpad3}
Sleep, 600
SendInput {Numpad9}
SendInput {F1}
SendInput {Numpad3}
Sleep, 300
SendInput {F1}
SendInput {Numpad3}
Sleep, 300
Sleep, 600
SendInput {Numpad9}
SendInput {Numpad3}
Sleep, 600
Sleep, 600
SendInput {Numpad0}
SendInput {Numpad3}
SendInput {Numpad6}
SendInput {F1}
Sleep, 600
SendInput {Numpad0}
SendInput {Numpad6}
SendInput {Numpad3}
Sleep, 600
SendInput {Numpad5}
SendInput {Numpad6}
SendInput {F1}
Sleep, 600
SendInput {Numpad3}
SendInput {Numpad5}
SendInput {Numpad7}
SendInput {Numpad6}
Sleep, 600
SendInput {Numpad9}
SendInput {Numpad7}
SendInput {Numpad3}
Sleep, 600
SendInput {Numpad0}
SendInput {Numpad3}
SendInput {Numpad5}
Sleep, 600
SendInput {Numpad9}
SendInput {Numpad5}
SendInput {Numpad7}
SendInput {Numpad3}
Sleep, 600
SendInput {Numpad9}
SendInput {Numpad3}
Sleep, 600
SendInput {Numpad0}
SendInput {Numpad7}
SendInput {Numpad3}
Sleep, 600
SendInput {Numpad0}
SendInput {Numpad6}
Sleep, 600
SendInput {Numpad3}
SendInput {Numpad5}
Sleep, 300
SendInput {Numpad3}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad4}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad2}
Sleep, 300
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 300
SendInput {Numpad2}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad4}
Sleep, 600
SendInput {Numpad0}
SendInput {Numpad1}
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 600
SendInput {Numpad9}
SendInput {Numpad4}
Sleep, 600
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad6}
Sleep, 300
SendInput {Numpad1}
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 600
SendInput {Numpad0}
SendInput {Numpad4}
SendInput {Numpad6}
SendInput {Numpad2}
Sleep, 300
SendInput {Numpad2}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad5}
SendInput {Numpad7}
SendInput {Numpad2}
Sleep, 300
SendInput {Numpad2}
SendInput {Numpad5}
SendInput {Numpad7}
Sleep, 900
SendInput {Numpad9}
SendInput {Numpad5}
Sleep, 600
SendInput {Numpad0}
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 600
SendInput {Numpad9}
SendInput {Numpad5}
Sleep, 600
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad2}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad7}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad5}
SendInput {Numpad2}
SendInput {Numpad1}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad7}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad5}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad5}
Sleep, 300
SendInput {Numpad2}
SendInput {F3}
SendInput {Numpad6}
SendInput {Numpad3}
Sleep, 600
SendInput {Numpad3}
SendInput {F3}
Sleep, 600
SendInput {Numpad0}
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 600
SendInput {Numpad9}
SendInput {Numpad2}
SendInput {Numpad3}
SendInput {F3}
Sleep, 300
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad2}
SendInput {F3}
Sleep, 600
SendInput {Numpad9}
SendInput {Numpad3}
SendInput {F3}
SendInput {Numpad6}
Sleep, 600
SendInput {Numpad9}
SendInput {Numpad2}
Sleep, 600
SendInput {Numpad0}
SendInput {Numpad2}
SendInput {Numpad3}
SendInput {F3}
SendInput {Numpad6}
Sleep, 300
Sleep, 300
SendInput {Numpad3}
SendInput {Numpad6}
SendInput {F1}
Sleep, 600
SendInput {Numpad3}
SendInput {Numpad6}
SendInput {F1}
Sleep, 300
Sleep, 300
SendInput {Numpad3}
SendInput {Numpad6}
SendInput {F1}
Sleep, 600
SendInput {Numpad3}
SendInput {Numpad6}
SendInput {F1}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad3}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad3}
SendInput {Numpad5}
SendInput {Numpad7}
Sleep, 600
SendInput {Numpad3}
SendInput {Numpad5}
SendInput {Numpad7}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad2}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad2}
SendInput {F3}
SendInput {Numpad6}
Sleep, 600
SendInput {Numpad2}
SendInput {F3}
SendInput {Numpad6}
Sleep, 300
Sleep, 300
SendInput {Numpad3}
SendInput {Numpad6}
SendInput {F1}
Sleep, 600
SendInput {Numpad3}
SendInput {Numpad6}
SendInput {F1}
Sleep, 300
Sleep, 300
SendInput {Numpad3}
SendInput {Numpad6}
SendInput {F1}
Sleep, 600
SendInput {Numpad3}
SendInput {Numpad6}
SendInput {F1}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad3}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad3}
SendInput {Numpad5}
SendInput {Numpad7}
Sleep, 600
SendInput {Numpad3}
SendInput {Numpad5}
SendInput {Numpad7}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad2}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad2}
SendInput {F3}
SendInput {Numpad6}
Sleep, 600
SendInput {Numpad2}
SendInput {F3}
SendInput {Numpad6}
Sleep, 300
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad6}
SendInput {F1}
SendInput {Numpad3}
Sleep, 300
Sleep, 600
SendInput {F1}
Sleep, 300
SendInput {Numpad3}
SendInput {Numpad6}
SendInput {F1}
Sleep, 300
SendInput {Numpad3}
Sleep, 600
SendInput {Numpad3}
SendInput {Numpad5}
SendInput {Numpad7}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad3}
SendInput {Numpad5}
SendInput {Numpad7}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad3}
Sleep, 600
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad2}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad2}
SendInput {F3}
SendInput {Numpad6}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad3}
Sleep, 300
SendInput {Numpad2}
Sleep, 300
SendInput {Numpad3}
SendInput {Numpad6}
SendInput {F1}
Sleep, 300
SendInput {Numpad6}
SendInput {F1}
SendInput {Numpad3}
Sleep, 900
SendInput {F1}
Sleep, 300
SendInput {Numpad3}
SendInput {Numpad6}
SendInput {F1}
Sleep, 300
SendInput {Numpad3}
Sleep, 600
SendInput {Numpad3}
SendInput {Numpad5}
SendInput {Numpad7}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad3}
SendInput {Numpad5}
SendInput {Numpad7}
Sleep, 600
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad3}
Sleep, 300
SendInput {Numpad1}
SendInput {Numpad3}
Sleep, 300
SendInput {Numpad1}
SendInput {Numpad5}
SendInput {Numpad3}
Sleep, 300
SendInput {Numpad2}
Sleep, 300
SendInput {Numpad1}
Sleep, 300
SendInput {Numpad5}
SendInput {Numpad7}
SendInput {Numpad2}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad5}
SendInput {Numpad7}
SendInput {Numpad2}
Sleep, 900
Sleep, 300
SendInput {Numpad5}
SendInput {Numpad7}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad7}
SendInput {Numpad2}
Sleep, 600
SendInput {Numpad3}
SendInput {Numpad5}
SendInput {Numpad7}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad3}
SendInput {Numpad5}
SendInput {Numpad7}
Sleep, 900
SendInput {Numpad2}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad2}
SendInput {F3}
SendInput {Numpad6}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad2}
Sleep, 300
SendInput {Numpad2}
Sleep, 300
SendInput {Numpad5}
SendInput {Numpad7}
SendInput {Numpad2}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad5}
SendInput {Numpad7}
SendInput {Numpad2}
Sleep, 600
SendInput {Numpad7}
Sleep, 300
Sleep, 300
SendInput {Numpad5}
SendInput {Numpad7}
Sleep, 300
SendInput {Numpad7}
Sleep, 600
SendInput {Numpad0}
SendInput {Numpad3}
SendInput {Numpad2}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad3}
SendInput {Numpad5}
SendInput {Numpad7}
Sleep, 900
SendInput {Numpad0}
SendInput {Numpad2}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad2}
SendInput {F3}
SendInput {Numpad6}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad2}
Sleep, 600
SendInput {Numpad9}
SendInput {Numpad7}
Sleep, 300
SendInput {F1}
SendInput {Numpad3}
SendInput {Numpad6}
SendInput {Numpad7}
Sleep, 300
SendInput {Numpad6}
Sleep, 600
Sleep, 300
SendInput {F1}
SendInput {Numpad3}
Sleep, 600
SendInput {F1}
SendInput {Numpad3}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad3}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad3}
SendInput {Numpad5}
SendInput {Numpad7}
Sleep, 600
SendInput {Numpad3}
SendInput {Numpad5}
SendInput {Numpad7}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad2}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad2}
SendInput {F3}
SendInput {Numpad6}
Sleep, 600
SendInput {Numpad2}
SendInput {F3}
SendInput {Numpad6}
Sleep, 300
Sleep, 300
SendInput {Numpad3}
SendInput {Numpad6}
SendInput {F1}
Sleep, 600
SendInput {Numpad3}
SendInput {Numpad6}
SendInput {F1}
Sleep, 300
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad6}
SendInput {F1}
SendInput {Numpad3}
Sleep, 300
SendInput {Numpad3}
Sleep, 600
SendInput {Numpad3}
SendInput {Numpad5}
SendInput {Numpad7}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad3}
SendInput {Numpad5}
SendInput {Numpad7}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad3}
Sleep, 600
SendInput {Numpad2}
SendInput {F3}
SendInput {Numpad6}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad2}
SendInput {F3}
SendInput {Numpad6}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad2}
Sleep, 300
SendInput {Numpad2}
Sleep, 300
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 300
SendInput {Numpad6}
SendInput {F1}
SendInput {Numpad3}
Sleep, 300
SendInput {F1}
Sleep, 600
Sleep, 300
SendInput {Numpad3}
SendInput {Numpad6}
SendInput {F1}
Sleep, 600
SendInput {Numpad3}
Sleep, 300
SendInput {Numpad3}
SendInput {Numpad5}
SendInput {Numpad7}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad3}
SendInput {Numpad5}
SendInput {Numpad7}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad3}
Sleep, 600
SendInput {Numpad1}
SendInput {Numpad3}
Sleep, 300
SendInput {Numpad1}
SendInput {Numpad3}
SendInput {Numpad5}
SendInput {Numpad2}
Sleep, 600
SendInput {Numpad3}
SendInput {Numpad5}
SendInput {Numpad1}
Sleep, 300
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad2}
SendInput {Numpad5}
SendInput {Numpad7}
Sleep, 900
SendInput {Numpad7}
Sleep, 300
SendInput {Numpad5}
SendInput {Numpad7}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad5}
SendInput {Numpad7}
SendInput {Numpad2}
Sleep, 600
SendInput {Numpad3}
SendInput {Numpad5}
SendInput {Numpad7}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad3}
SendInput {Numpad5}
SendInput {Numpad7}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad3}
Sleep, 300
SendInput {Numpad5}
SendInput {Numpad7}
SendInput {Numpad3}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad2}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad2}
SendInput {F3}
SendInput {Numpad6}
Sleep, 600
SendInput {Numpad0}
SendInput {Numpad2}
Sleep, 300
SendInput {Numpad2}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad2}
SendInput {Numpad5}
SendInput {Numpad7}
Sleep, 600
SendInput {Numpad2}
SendInput {Numpad5}
SendInput {Numpad7}
Sleep, 300
Sleep, 300
SendInput {Numpad5}
SendInput {Numpad7}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad7}
SendInput {Numpad2}
Sleep, 600
SendInput {Numpad3}
SendInput {Numpad5}
SendInput {Numpad7}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad3}
SendInput {Numpad5}
SendInput {Numpad7}
Sleep, 600
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad5}
SendInput {Numpad7}
SendInput {Numpad3}
Sleep, 300
SendInput {Numpad2}
SendInput {Numpad3}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad2}
SendInput {F3}
SendInput {Numpad6}
Sleep, 600
SendInput {Numpad0}
SendInput {Numpad2}
Sleep, 300
SendInput {Numpad9}
SendInput {F1}
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad6}
SendInput {F1}
SendInput {Numpad3}
Sleep, 900
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad3}
SendInput {Numpad6}
SendInput {F1}
Sleep, 600
SendInput {Numpad3}
SendInput {Numpad6}
SendInput {F1}
Sleep, 300
Sleep, 300
SendInput {Numpad3}
SendInput {Numpad6}
SendInput {F1}
Sleep, 600
SendInput {Numpad3}
SendInput {Numpad6}
SendInput {F1}
Sleep, 300
Sleep, 300
SendInput {Numpad3}
SendInput {Numpad6}
SendInput {F1}
Sleep, 600
SendInput {Numpad3}
SendInput {Numpad6}
SendInput {F1}
Sleep, 600
SendInput {Numpad0}
SendInput {Numpad6}
SendInput {Numpad1}
SendInput {Numpad3}
Sleep, 300
SendInput {Numpad3}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad6}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad1}
SendInput {Numpad3}
Sleep, 600
SendInput {Numpad6}
SendInput {Numpad2}
Sleep, 300
SendInput {Numpad3}
SendInput {Numpad1}
Sleep, 300
SendInput {Numpad5}
SendInput {Numpad1}
SendInput {Numpad3}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad1}
SendInput {Numpad5}
SendInput {Numpad3}
Sleep, 300
SendInput {Numpad5}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 300
SendInput {Numpad3}
Sleep, 600
SendInput {Numpad0}
SendInput {Numpad1}
SendInput {Numpad3}
Sleep, 300
SendInput {Numpad5}
SendInput {Numpad3}
Sleep, 300
SendInput {Numpad3}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad5}
SendInput {Numpad7}
SendInput {Numpad2}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad2}
Sleep, 300
SendInput {Numpad5}
Sleep, 300
SendInput {Numpad7}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad2}
SendInput {Numpad5}
SendInput {Numpad7}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad5}
Sleep, 300
SendInput {Numpad2}
Sleep, 300
Sleep, 300
Sleep, 300
SendInput {Numpad2}
Sleep, 300
SendInput {Numpad5}
Sleep, 300
SendInput {Numpad7}
Sleep, 600
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad5}
SendInput {Numpad2}
Sleep, 300
SendInput {Numpad2}
SendInput {Numpad5}
SendInput {Numpad7}
SendInput {Numpad3}
Sleep, 300
SendInput {Numpad3}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad4}
SendInput {Numpad5}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad1}
Sleep, 300
SendInput {Numpad5}
Sleep, 300
SendInput {Numpad6}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad1}
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad6}
Sleep, 300
SendInput {Numpad5}
Sleep, 300
SendInput {Numpad1}
Sleep, 300
Sleep, 300
SendInput {Numpad1}
Sleep, 300
SendInput {Numpad5}
Sleep, 300
SendInput {Numpad6}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad6}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad4}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 300
SendInput {Numpad2}
SendInput {F3}
SendInput {Numpad6}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad2}
SendInput {F3}
SendInput {Numpad6}
Sleep, 600
SendInput {Numpad0}
SendInput {Numpad3}
Sleep, 300
SendInput {F3}
SendInput {Numpad6}
SendInput {Numpad2}
