; title: Billie Jean
; author: Michael Jackson
; instrument: Piano
; Converted by Serenade Music Converter

SendInput {Numpad6}
SendInput {Numpad1}
SendInput {Numpad3}
Sleep, 833
SendInput {Numpad6}
SendInput {Numpad2}
SendInput {F3}
SendInput {Numpad7}
Sleep, 1389
SendInput {Numpad6}
SendInput {Numpad3}
SendInput {Numpad5}
SendInput {Numpad1}
Sleep, 833
SendInput {Numpad6}
SendInput {Numpad2}
SendInput {F3}
SendInput {Numpad7}
Sleep, 1389
SendInput {Numpad6}
SendInput {Numpad1}
SendInput {Numpad3}
Sleep, 833
SendInput {Numpad6}
SendInput {Numpad2}
SendInput {F3}
SendInput {Numpad7}
Sleep, 1389
SendInput {Numpad6}
SendInput {Numpad3}
SendInput {Numpad5}
SendInput {Numpad1}
Sleep, 833
SendInput {Numpad6}
SendInput {Numpad2}
SendInput {F3}
SendInput {Numpad7}
Sleep, 1389
SendInput {Numpad6}
SendInput {Numpad1}
SendInput {Numpad3}
Sleep, 556
SendInput {Numpad0}
SendInput {Numpad3}
Sleep, 278
SendInput {Numpad9}
SendInput {Numpad6}
SendInput {Numpad2}
SendInput {F3}
SendInput {Numpad7}
Sleep, 278
SendInput {Numpad0}
SendInput {Numpad3}
Sleep, 278
SendInput {Numpad2}
Sleep, 278
SendInput {Numpad1}
Sleep, 278
SendInput {Numpad2}
Sleep, 278
SendInput {Numpad9}
SendInput {Numpad6}
SendInput {Numpad3}
SendInput {Numpad1}
Sleep, 278
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 278
SendInput {Numpad3}
Sleep, 278
SendInput {Numpad9}
SendInput {Numpad6}
SendInput {Numpad2}
SendInput {F3}
SendInput {Numpad7}
Sleep, 139
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 139
SendInput {Numpad2}
Sleep, 278
SendInput {Numpad1}
Sleep, 278
SendInput {Numpad3}
Sleep, 556
SendInput {Numpad9}
SendInput {Numpad6}
SendInput {Numpad1}
SendInput {Numpad3}
Sleep, 278
SendInput {Numpad0}
SendInput {Numpad3}
Sleep, 278
SendInput {Numpad3}
Sleep, 278
SendInput {Numpad9}
SendInput {Numpad6}
SendInput {Numpad2}
SendInput {F3}
SendInput {Numpad7}
Sleep, 278
SendInput {Numpad0}
SendInput {Numpad3}
Sleep, 278
SendInput {Numpad2}
Sleep, 278
SendInput {Numpad1}
Sleep, 278
SendInput {Numpad2}
Sleep, 278
SendInput {Numpad9}
SendInput {Numpad6}
SendInput {Numpad3}
SendInput {Numpad1}
Sleep, 278
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 278
SendInput {Numpad3}
Sleep, 278
SendInput {Numpad9}
SendInput {Numpad6}
SendInput {Numpad2}
SendInput {F3}
SendInput {Numpad7}
Sleep, 556
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 278
SendInput {Numpad9}
SendInput {Numpad7}
Sleep, 556
SendInput {Numpad2}
SendInput {Numpad1}
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 833
SendInput {Numpad9}
SendInput {Numpad2}
SendInput {Numpad6}
Sleep, 833
SendInput {Numpad0}
SendInput {Numpad6}
Sleep, 139
SendInput {Numpad7}
Sleep, 139
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 278
SendInput {Numpad9}
SendInput {Numpad2}
SendInput {Numpad1}
Sleep, 556
SendInput {Numpad0}
SendInput {Numpad6}
Sleep, 139
SendInput {Numpad7}
Sleep, 139
SendInput {Numpad2}
SendInput {Numpad6}
SendInput {Numpad4}
Sleep, 833
SendInput {Numpad6}
Sleep, 139
SendInput {Numpad7}
Sleep, 139
SendInput {Numpad6}
Sleep, 278
SendInput {Numpad6}
SendInput {Numpad1}
SendInput {Numpad3}
Sleep, 833
SendInput {Numpad6}
SendInput {Numpad2}
SendInput {F3}
SendInput {Numpad7}
Sleep, 1389
SendInput {Numpad6}
SendInput {Numpad3}
SendInput {Numpad5}
SendInput {Numpad1}
Sleep, 278
SendInput {Numpad6}
Sleep, 278
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 278
SendInput {Numpad9}
SendInput {Numpad6}
SendInput {Numpad2}
SendInput {F3}
SendInput {Numpad7}
Sleep, 556
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 278
SendInput {Numpad9}
SendInput {Numpad7}
Sleep, 556
SendInput {Numpad2}
SendInput {Numpad1}
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 833
SendInput {Numpad9}
SendInput {Numpad2}
SendInput {Numpad6}
Sleep, 833
SendInput {Numpad0}
SendInput {Numpad6}
Sleep, 139
SendInput {Numpad7}
Sleep, 139
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 278
SendInput {Numpad9}
SendInput {Numpad2}
SendInput {Numpad1}
Sleep, 556
SendInput {Numpad0}
SendInput {Numpad6}
Sleep, 139
SendInput {Numpad7}
Sleep, 139
SendInput {Numpad2}
SendInput {Numpad6}
SendInput {Numpad4}
Sleep, 833
SendInput {Numpad6}
Sleep, 139
SendInput {Numpad7}
Sleep, 139
SendInput {Numpad6}
Sleep, 278
SendInput {Numpad6}
SendInput {Numpad1}
SendInput {Numpad3}
Sleep, 833
SendInput {Numpad6}
SendInput {Numpad2}
SendInput {F3}
SendInput {Numpad7}
Sleep, 1389
SendInput {Numpad6}
SendInput {Numpad3}
SendInput {Numpad5}
SendInput {Numpad1}
Sleep, 833
SendInput {Numpad6}
SendInput {Numpad2}
SendInput {F3}
SendInput {Numpad7}
Sleep, 1389
SendInput {Numpad6}
SendInput {Numpad1}
SendInput {Numpad3}
Sleep, 278
SendInput {Numpad0}
SendInput {Numpad3}
Sleep, 278
SendInput {Numpad3}
Sleep, 278
SendInput {Numpad9}
SendInput {Numpad6}
SendInput {Numpad2}
SendInput {F3}
SendInput {Numpad7}
Sleep, 278
SendInput {Numpad0}
SendInput {Numpad3}
Sleep, 278
SendInput {Numpad2}
Sleep, 278
SendInput {Numpad1}
Sleep, 278
SendInput {Numpad2}
Sleep, 278
SendInput {Numpad9}
SendInput {Numpad6}
SendInput {Numpad3}
SendInput {Numpad1}
Sleep, 278
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 278
SendInput {Numpad3}
Sleep, 278
SendInput {Numpad9}
SendInput {Numpad6}
SendInput {Numpad2}
SendInput {F3}
SendInput {Numpad7}
Sleep, 139
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 139
SendInput {Numpad2}
Sleep, 278
SendInput {Numpad1}
Sleep, 278
SendInput {Numpad3}
Sleep, 556
SendInput {Numpad9}
SendInput {Numpad6}
SendInput {Numpad1}
SendInput {Numpad3}
Sleep, 278
SendInput {Numpad0}
SendInput {Numpad3}
Sleep, 278
SendInput {Numpad3}
Sleep, 278
SendInput {Numpad9}
SendInput {Numpad6}
SendInput {Numpad2}
SendInput {F3}
SendInput {Numpad7}
Sleep, 278
SendInput {Numpad0}
SendInput {Numpad3}
Sleep, 278
SendInput {Numpad2}
Sleep, 278
SendInput {Numpad1}
Sleep, 278
SendInput {Numpad2}
Sleep, 278
SendInput {Numpad9}
SendInput {Numpad6}
SendInput {Numpad3}
SendInput {Numpad1}
Sleep, 278
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 278
SendInput {Numpad3}
Sleep, 278
SendInput {Numpad9}
SendInput {Numpad6}
SendInput {Numpad2}
SendInput {F3}
SendInput {Numpad7}
Sleep, 278
SendInput {Numpad0}
SendInput {Numpad2}
Sleep, 278
SendInput {Numpad1}
Sleep, 278
SendInput {Numpad9}
SendInput {Numpad7}
Sleep, 556
SendInput {Numpad2}
SendInput {Numpad1}
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 833
SendInput {Numpad9}
SendInput {Numpad2}
SendInput {Numpad6}
Sleep, 833
SendInput {Numpad0}
SendInput {Numpad6}
Sleep, 139
SendInput {Numpad7}
Sleep, 139
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 278
SendInput {Numpad9}
SendInput {Numpad2}
SendInput {Numpad1}
Sleep, 556
SendInput {Numpad0}
SendInput {Numpad6}
Sleep, 139
SendInput {Numpad7}
Sleep, 139
SendInput {Numpad2}
SendInput {Numpad6}
SendInput {Numpad4}
Sleep, 833
SendInput {Numpad6}
Sleep, 139
SendInput {Numpad7}
Sleep, 139
SendInput {Numpad6}
Sleep, 278
SendInput {Numpad6}
SendInput {Numpad1}
SendInput {Numpad3}
Sleep, 833
SendInput {Numpad6}
SendInput {Numpad2}
SendInput {F3}
SendInput {Numpad7}
Sleep, 1389
SendInput {Numpad6}
SendInput {Numpad3}
SendInput {Numpad5}
SendInput {Numpad1}
Sleep, 833
SendInput {Numpad6}
SendInput {Numpad2}
SendInput {F3}
SendInput {Numpad7}
Sleep, 1389
SendInput {Numpad4}
SendInput {Numpad1}
SendInput {Numpad6}
Sleep, 278
SendInput {Numpad0}
SendInput {Numpad5}
Sleep, 278
SendInput {Numpad6}
Sleep, 278
SendInput {Numpad5}
Sleep, 278
SendInput {Numpad6}
Sleep, 278
Sleep, 556
SendInput {Numpad6}
Sleep, 278
SendInput {Numpad6}
SendInput {Numpad1}
SendInput {Numpad3}
Sleep, 278
SendInput {Numpad6}
Sleep, 139
SendInput {Numpad6}
Sleep, 139
SendInput {Numpad6}
Sleep, 278
SendInput {Numpad5}
Sleep, 278
SendInput {Numpad6}
Sleep, 556
SendInput {Numpad3}
Sleep, 278
SendInput {Numpad6}
Sleep, 278
SendInput {Numpad9}
SendInput {Numpad4}
SendInput {Numpad1}
SendInput {Numpad6}
SendInput {Numpad5}
Sleep, 139
SendInput {Numpad0}
SendInput {Numpad6}
Sleep, 139
SendInput {Numpad6}
Sleep, 278
SendInput {Numpad6}
Sleep, 278
SendInput {Numpad5}
Sleep, 278
SendInput {Numpad6}
Sleep, 278
SendInput {Numpad7}
Sleep, 556
SendInput {Numpad1}
SendInput {Numpad6}
Sleep, 278
SendInput {Numpad9}
SendInput {Numpad6}
SendInput {Numpad1}
SendInput {Numpad3}
Sleep, 833
SendInput {Numpad9}
SendInput {Numpad6}
Sleep, 278
SendInput {Numpad6}
Sleep, 556
SendInput {Numpad6}
Sleep, 278
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad5}
Sleep, 278
SendInput {Numpad9}
SendInput {Numpad4}
SendInput {Numpad1}
SendInput {Numpad6}
Sleep, 278
SendInput {Numpad0}
SendInput {Numpad5}
Sleep, 278
SendInput {Numpad6}
Sleep, 278
SendInput {Numpad5}
Sleep, 278
SendInput {Numpad6}
Sleep, 278
SendInput {Numpad6}
Sleep, 556
SendInput {Numpad6}
Sleep, 278
SendInput {Numpad6}
SendInput {Numpad1}
SendInput {Numpad3}
Sleep, 278
SendInput {Numpad6}
Sleep, 139
SendInput {Numpad6}
Sleep, 139
SendInput {Numpad6}
Sleep, 278
SendInput {Numpad5}
Sleep, 278
SendInput {Numpad6}
Sleep, 556
SendInput {Numpad3}
Sleep, 278
SendInput {Numpad6}
Sleep, 278
SendInput {Numpad9}
SendInput {Numpad4}
SendInput {Numpad1}
SendInput {Numpad6}
Sleep, 278
SendInput {Numpad0}
SendInput {Numpad4}
Sleep, 139
SendInput {Numpad4}
Sleep, 139
SendInput {Numpad4}
Sleep, 278
SendInput {Numpad5}
Sleep, 278
SendInput {Numpad6}
Sleep, 833
SendInput {Numpad6}
Sleep, 139
SendInput {Numpad6}
Sleep, 139
SendInput {Numpad3}
SendInput {Numpad2}
SendInput {F4}
SendInput {Numpad7}
Sleep, 278
SendInput {Numpad3}
SendInput {F4}
Sleep, 139
SendInput {Numpad3}
SendInput {F4}
Sleep, 417
SendInput {Numpad6}
Sleep, 278
SendInput {Numpad7}
Sleep, 556
SendInput {Numpad6}
Sleep, 139
SendInput {Numpad7}
Sleep, 139
SendInput {Numpad6}
Sleep, 278
SendInput {Numpad6}
SendInput {Numpad1}
SendInput {Numpad3}
Sleep, 556
SendInput {Numpad1}
SendInput {Numpad6}
Sleep, 278
SendInput {Numpad9}
SendInput {Numpad6}
SendInput {Numpad2}
SendInput {F3}
SendInput {Numpad7}
Sleep, 278
SendInput {Numpad0}
SendInput {Numpad5}
Sleep, 278
SendInput {Numpad3}
Sleep, 278
SendInput {Numpad3}
Sleep, 556
SendInput {Numpad6}
SendInput {Numpad3}
SendInput {Numpad1}
Sleep, 278
SendInput {Numpad1}
SendInput {Numpad6}
Sleep, 556
SendInput {Numpad9}
SendInput {Numpad6}
SendInput {Numpad2}
SendInput {F3}
SendInput {Numpad7}
Sleep, 556
SendInput {Numpad0}
SendInput {Numpad3}
Sleep, 833
SendInput {Numpad9}
SendInput {Numpad6}
SendInput {Numpad1}
SendInput {Numpad3}
Sleep, 278
SendInput {Numpad0}
SendInput {Numpad1}
SendInput {Numpad6}
Sleep, 278
SendInput {Numpad1}
SendInput {Numpad6}
Sleep, 278
SendInput {Numpad9}
SendInput {Numpad6}
SendInput {Numpad2}
SendInput {F3}
SendInput {Numpad7}
Sleep, 278
SendInput {Numpad0}
SendInput {Numpad5}
Sleep, 278
SendInput {Numpad3}
Sleep, 278
SendInput {Numpad3}
Sleep, 556
SendInput {Numpad6}
SendInput {Numpad3}
SendInput {Numpad5}
SendInput {Numpad1}
Sleep, 278
Sleep, 556
SendInput {Numpad9}
SendInput {Numpad6}
SendInput {Numpad2}
SendInput {F3}
SendInput {Numpad7}
Sleep, 556
Sleep, 278
SendInput {Numpad0}
SendInput {Numpad7}
Sleep, 556
SendInput {Numpad2}
SendInput {Numpad1}
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 833
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad2}
SendInput {Numpad6}
Sleep, 556
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 556
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 278
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad2}
SendInput {Numpad1}
Sleep, 278
Sleep, 278
Sleep, 278
SendInput {Numpad2}
SendInput {Numpad6}
Sleep, 278
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad6}
Sleep, 278
SendInput {Numpad4}
Sleep, 556
SendInput {Numpad1}
SendInput {Numpad3}
Sleep, 278
SendInput {Numpad9}
SendInput {Numpad6}
SendInput {Numpad1}
SendInput {Numpad3}
Sleep, 833
SendInput {Numpad6}
SendInput {Numpad2}
SendInput {F3}
SendInput {Numpad7}
Sleep, 1389
SendInput {Numpad0}
SendInput {Numpad6}
SendInput {Numpad3}
SendInput {Numpad5}
SendInput {Numpad1}
Sleep, 278
SendInput {Numpad6}
Sleep, 278
Sleep, 278
SendInput {Numpad9}
SendInput {Numpad6}
SendInput {Numpad2}
SendInput {F3}
SendInput {Numpad7}
Sleep, 556
Sleep, 278
SendInput {Numpad0}
SendInput {Numpad7}
Sleep, 556
SendInput {Numpad2}
SendInput {Numpad1}
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 833
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad2}
SendInput {Numpad6}
Sleep, 556
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 556
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 278
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad2}
SendInput {Numpad1}
Sleep, 278
Sleep, 278
Sleep, 278
SendInput {Numpad2}
SendInput {Numpad6}
Sleep, 278
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad6}
Sleep, 278
SendInput {Numpad4}
Sleep, 556
SendInput {Numpad1}
SendInput {Numpad3}
Sleep, 278
SendInput {Numpad9}
SendInput {Numpad6}
SendInput {Numpad1}
SendInput {Numpad3}
Sleep, 833
SendInput {Numpad6}
SendInput {Numpad2}
SendInput {F3}
SendInput {Numpad7}
Sleep, 1389
SendInput {Numpad0}
SendInput {Numpad6}
SendInput {Numpad3}
SendInput {Numpad5}
SendInput {Numpad1}
Sleep, 833
SendInput {Numpad9}
SendInput {Numpad6}
SendInput {Numpad2}
SendInput {F3}
SendInput {Numpad7}
Sleep, 1389
SendInput {Numpad6}
SendInput {Numpad1}
SendInput {Numpad3}
Sleep, 556
SendInput {Numpad0}
SendInput {Numpad3}
Sleep, 278
SendInput {Numpad9}
SendInput {Numpad6}
SendInput {Numpad2}
SendInput {F3}
SendInput {Numpad7}
Sleep, 278
SendInput {Numpad0}
SendInput {Numpad3}
Sleep, 278
SendInput {Numpad2}
Sleep, 278
SendInput {Numpad1}
Sleep, 278
SendInput {Numpad2}
Sleep, 278
SendInput {Numpad9}
SendInput {Numpad6}
SendInput {Numpad3}
SendInput {Numpad1}
Sleep, 278
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 278
SendInput {Numpad3}
Sleep, 278
SendInput {Numpad9}
SendInput {Numpad6}
SendInput {Numpad2}
SendInput {F3}
SendInput {Numpad7}
Sleep, 139
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 139
SendInput {Numpad2}
Sleep, 278
SendInput {Numpad1}
Sleep, 278
SendInput {Numpad3}
Sleep, 556
SendInput {Numpad9}
SendInput {Numpad6}
SendInput {Numpad1}
SendInput {Numpad3}
Sleep, 278
SendInput {Numpad0}
SendInput {Numpad3}
Sleep, 278
SendInput {Numpad3}
Sleep, 278
SendInput {Numpad9}
SendInput {Numpad6}
SendInput {Numpad2}
SendInput {F3}
SendInput {Numpad7}
Sleep, 278
SendInput {Numpad0}
SendInput {Numpad3}
Sleep, 278
SendInput {Numpad2}
Sleep, 278
SendInput {Numpad1}
Sleep, 278
SendInput {Numpad2}
Sleep, 278
SendInput {Numpad9}
SendInput {Numpad6}
SendInput {Numpad3}
SendInput {Numpad1}
Sleep, 278
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 278
SendInput {Numpad3}
Sleep, 278
SendInput {Numpad9}
SendInput {Numpad6}
SendInput {Numpad2}
SendInput {F3}
SendInput {Numpad7}
Sleep, 556
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 278
SendInput {Numpad9}
SendInput {Numpad7}
Sleep, 556
SendInput {Numpad2}
SendInput {Numpad1}
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 833
SendInput {Numpad9}
SendInput {Numpad2}
SendInput {Numpad6}
Sleep, 833
SendInput {Numpad0}
SendInput {Numpad6}
Sleep, 139
SendInput {Numpad7}
Sleep, 139
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 278
SendInput {Numpad9}
SendInput {Numpad2}
SendInput {Numpad1}
Sleep, 556
SendInput {Numpad0}
SendInput {Numpad6}
Sleep, 139
SendInput {Numpad7}
Sleep, 139
SendInput {Numpad2}
SendInput {Numpad6}
SendInput {Numpad4}
Sleep, 833
SendInput {Numpad6}
Sleep, 139
SendInput {Numpad7}
Sleep, 139
SendInput {Numpad6}
Sleep, 278
SendInput {Numpad6}
SendInput {Numpad1}
SendInput {Numpad3}
Sleep, 833
SendInput {Numpad6}
SendInput {Numpad2}
SendInput {F3}
SendInput {Numpad7}
Sleep, 1389
SendInput {Numpad6}
SendInput {Numpad3}
SendInput {Numpad5}
SendInput {Numpad1}
Sleep, 278
SendInput {Numpad6}
Sleep, 278
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 278
SendInput {Numpad9}
SendInput {Numpad6}
SendInput {Numpad2}
SendInput {F3}
SendInput {Numpad7}
Sleep, 556
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 278
SendInput {Numpad9}
SendInput {Numpad7}
Sleep, 556
SendInput {Numpad2}
SendInput {Numpad1}
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 833
SendInput {Numpad9}
SendInput {Numpad2}
SendInput {Numpad6}
Sleep, 833
SendInput {Numpad0}
SendInput {Numpad6}
Sleep, 139
SendInput {Numpad7}
Sleep, 139
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 278
SendInput {Numpad9}
SendInput {Numpad2}
SendInput {Numpad1}
Sleep, 556
SendInput {Numpad0}
SendInput {Numpad6}
Sleep, 139
SendInput {Numpad7}
Sleep, 139
SendInput {Numpad2}
SendInput {Numpad6}
SendInput {Numpad4}
Sleep, 833
SendInput {Numpad6}
Sleep, 139
SendInput {Numpad7}
Sleep, 139
SendInput {Numpad6}
Sleep, 278
SendInput {Numpad6}
SendInput {Numpad1}
SendInput {Numpad3}
Sleep, 833
SendInput {Numpad6}
SendInput {Numpad2}
SendInput {F3}
SendInput {Numpad7}
Sleep, 1389
SendInput {Numpad6}
SendInput {Numpad3}
SendInput {Numpad5}
SendInput {Numpad1}
Sleep, 833
SendInput {Numpad6}
SendInput {Numpad2}
SendInput {F3}
SendInput {Numpad7}
Sleep, 1389
SendInput {Numpad6}
SendInput {Numpad1}
SendInput {Numpad3}
Sleep, 278
SendInput {Numpad0}
SendInput {Numpad3}
Sleep, 278
SendInput {Numpad3}
Sleep, 278
SendInput {Numpad9}
SendInput {Numpad6}
SendInput {Numpad2}
SendInput {F3}
SendInput {Numpad7}
Sleep, 278
SendInput {Numpad0}
SendInput {Numpad3}
Sleep, 278
SendInput {Numpad2}
Sleep, 278
SendInput {Numpad1}
Sleep, 278
SendInput {Numpad2}
Sleep, 278
SendInput {Numpad9}
SendInput {Numpad6}
SendInput {Numpad3}
SendInput {Numpad1}
Sleep, 278
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 278
SendInput {Numpad3}
Sleep, 278
SendInput {Numpad9}
SendInput {Numpad6}
SendInput {Numpad2}
SendInput {F3}
SendInput {Numpad7}
Sleep, 139
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 139
SendInput {Numpad2}
Sleep, 278
SendInput {Numpad1}
Sleep, 278
SendInput {Numpad3}
Sleep, 556
SendInput {Numpad9}
SendInput {Numpad6}
SendInput {Numpad1}
SendInput {Numpad3}
Sleep, 278
SendInput {Numpad0}
SendInput {Numpad3}
Sleep, 278
SendInput {Numpad3}
Sleep, 278
SendInput {Numpad9}
SendInput {Numpad6}
SendInput {Numpad2}
SendInput {F3}
SendInput {Numpad7}
Sleep, 278
SendInput {Numpad0}
SendInput {Numpad3}
Sleep, 278
SendInput {Numpad2}
Sleep, 278
SendInput {Numpad1}
Sleep, 278
SendInput {Numpad2}
Sleep, 278
SendInput {Numpad9}
SendInput {Numpad6}
SendInput {Numpad3}
SendInput {Numpad1}
Sleep, 278
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 278
SendInput {Numpad3}
Sleep, 278
SendInput {Numpad9}
SendInput {Numpad6}
SendInput {Numpad2}
SendInput {F3}
SendInput {Numpad7}
Sleep, 278
SendInput {Numpad0}
SendInput {Numpad2}
Sleep, 278
SendInput {Numpad1}
Sleep, 278
SendInput {Numpad9}
SendInput {Numpad7}
Sleep, 556
SendInput {Numpad2}
SendInput {Numpad1}
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 833
SendInput {Numpad9}
SendInput {Numpad2}
SendInput {Numpad6}
Sleep, 833
SendInput {Numpad0}
SendInput {Numpad6}
Sleep, 139
SendInput {Numpad7}
Sleep, 139
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 278
SendInput {Numpad9}
SendInput {Numpad2}
SendInput {Numpad1}
Sleep, 556
SendInput {Numpad0}
SendInput {Numpad6}
Sleep, 139
SendInput {Numpad7}
Sleep, 139
SendInput {Numpad2}
SendInput {Numpad6}
SendInput {Numpad4}
Sleep, 833
SendInput {Numpad6}
Sleep, 139
SendInput {Numpad7}
Sleep, 139
SendInput {Numpad6}
Sleep, 278
SendInput {Numpad6}
SendInput {Numpad1}
SendInput {Numpad3}
Sleep, 833
SendInput {Numpad6}
SendInput {Numpad2}
SendInput {F3}
SendInput {Numpad7}
Sleep, 1389
SendInput {Numpad6}
SendInput {Numpad3}
SendInput {Numpad5}
SendInput {Numpad1}
Sleep, 833
SendInput {Numpad6}
SendInput {Numpad2}
SendInput {F3}
SendInput {Numpad7}
Sleep, 1389
SendInput {Numpad4}
SendInput {Numpad1}
SendInput {Numpad6}
Sleep, 278
SendInput {Numpad0}
SendInput {Numpad5}
Sleep, 278
SendInput {Numpad6}
Sleep, 278
SendInput {Numpad5}
Sleep, 278
SendInput {Numpad6}
Sleep, 278
Sleep, 556
SendInput {Numpad6}
Sleep, 278
SendInput {Numpad6}
SendInput {Numpad1}
SendInput {Numpad3}
Sleep, 278
SendInput {Numpad6}
Sleep, 139
SendInput {Numpad6}
Sleep, 139
SendInput {Numpad6}
Sleep, 278
SendInput {Numpad5}
Sleep, 278
SendInput {Numpad6}
Sleep, 556
SendInput {Numpad3}
Sleep, 278
SendInput {Numpad6}
Sleep, 278
SendInput {Numpad9}
SendInput {Numpad4}
SendInput {Numpad1}
SendInput {Numpad6}
SendInput {Numpad5}
Sleep, 139
SendInput {Numpad0}
SendInput {Numpad6}
Sleep, 139
SendInput {Numpad6}
Sleep, 278
SendInput {Numpad6}
Sleep, 278
SendInput {Numpad5}
Sleep, 278
SendInput {Numpad6}
Sleep, 278
SendInput {Numpad7}
Sleep, 556
SendInput {Numpad1}
SendInput {Numpad6}
Sleep, 278
SendInput {Numpad9}
SendInput {Numpad6}
SendInput {Numpad1}
SendInput {Numpad3}
Sleep, 833
SendInput {Numpad9}
SendInput {Numpad6}
Sleep, 278
SendInput {Numpad6}
Sleep, 556
SendInput {Numpad6}
Sleep, 278
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad5}
Sleep, 278
SendInput {Numpad9}
SendInput {Numpad4}
SendInput {Numpad1}
SendInput {Numpad6}
Sleep, 278
SendInput {Numpad0}
SendInput {Numpad5}
Sleep, 278
SendInput {Numpad6}
Sleep, 278
SendInput {Numpad5}
Sleep, 278
SendInput {Numpad6}
Sleep, 278
SendInput {Numpad6}
Sleep, 556
SendInput {Numpad6}
Sleep, 278
SendInput {Numpad6}
SendInput {Numpad1}
SendInput {Numpad3}
Sleep, 278
SendInput {Numpad6}
Sleep, 139
SendInput {Numpad6}
Sleep, 139
SendInput {Numpad6}
Sleep, 278
SendInput {Numpad5}
Sleep, 278
SendInput {Numpad6}
Sleep, 556
SendInput {Numpad3}
Sleep, 278
SendInput {Numpad6}
Sleep, 278
SendInput {Numpad9}
SendInput {Numpad4}
SendInput {Numpad1}
SendInput {Numpad6}
Sleep, 278
SendInput {Numpad0}
SendInput {Numpad4}
Sleep, 139
SendInput {Numpad4}
Sleep, 139
SendInput {Numpad4}
Sleep, 278
SendInput {Numpad5}
Sleep, 278
SendInput {Numpad6}
Sleep, 833
SendInput {Numpad6}
Sleep, 139
SendInput {Numpad6}
Sleep, 139
SendInput {Numpad3}
SendInput {Numpad2}
SendInput {F4}
SendInput {Numpad7}
Sleep, 278
SendInput {Numpad3}
SendInput {F4}
Sleep, 139
SendInput {Numpad3}
SendInput {F4}
Sleep, 417
SendInput {Numpad6}
Sleep, 278
SendInput {Numpad7}
Sleep, 556
SendInput {Numpad6}
Sleep, 139
SendInput {Numpad7}
Sleep, 139
SendInput {Numpad6}
Sleep, 278
SendInput {Numpad6}
SendInput {Numpad1}
SendInput {Numpad3}
Sleep, 556
SendInput {Numpad1}
SendInput {Numpad6}
Sleep, 278
SendInput {Numpad9}
SendInput {Numpad6}
SendInput {Numpad2}
SendInput {F3}
SendInput {Numpad7}
Sleep, 278
SendInput {Numpad0}
SendInput {Numpad5}
Sleep, 278
SendInput {Numpad3}
Sleep, 278
SendInput {Numpad3}
Sleep, 556
SendInput {Numpad6}
SendInput {Numpad3}
SendInput {Numpad1}
Sleep, 278
SendInput {Numpad1}
SendInput {Numpad6}
Sleep, 556
SendInput {Numpad9}
SendInput {Numpad6}
SendInput {Numpad2}
SendInput {F3}
SendInput {Numpad7}
Sleep, 556
SendInput {Numpad0}
SendInput {Numpad3}
Sleep, 833
SendInput {Numpad9}
SendInput {Numpad6}
SendInput {Numpad1}
SendInput {Numpad3}
Sleep, 278
SendInput {Numpad0}
SendInput {Numpad1}
SendInput {Numpad6}
Sleep, 278
SendInput {Numpad1}
SendInput {Numpad6}
Sleep, 278
SendInput {Numpad9}
SendInput {Numpad6}
SendInput {Numpad2}
SendInput {F3}
SendInput {Numpad7}
Sleep, 278
SendInput {Numpad0}
SendInput {Numpad5}
Sleep, 278
SendInput {Numpad3}
Sleep, 278
SendInput {Numpad3}
Sleep, 556
SendInput {Numpad6}
SendInput {Numpad3}
SendInput {Numpad5}
SendInput {Numpad1}
Sleep, 278
Sleep, 556
SendInput {Numpad9}
SendInput {Numpad6}
SendInput {Numpad2}
SendInput {F3}
SendInput {Numpad7}
Sleep, 556
Sleep, 278
SendInput {Numpad0}
SendInput {Numpad7}
Sleep, 556
SendInput {Numpad2}
SendInput {Numpad1}
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 833
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad2}
SendInput {Numpad6}
Sleep, 556
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 556
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 278
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad2}
SendInput {Numpad1}
Sleep, 278
Sleep, 278
Sleep, 278
SendInput {Numpad2}
SendInput {Numpad6}
Sleep, 278
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad6}
Sleep, 278
SendInput {Numpad4}
Sleep, 556
SendInput {Numpad1}
SendInput {Numpad3}
Sleep, 278
SendInput {Numpad9}
SendInput {Numpad6}
SendInput {Numpad1}
SendInput {Numpad3}
Sleep, 833
SendInput {Numpad6}
SendInput {Numpad2}
SendInput {F3}
SendInput {Numpad7}
Sleep, 1389
SendInput {Numpad0}
SendInput {Numpad6}
SendInput {Numpad3}
SendInput {Numpad5}
SendInput {Numpad1}
Sleep, 278
SendInput {Numpad6}
Sleep, 278
Sleep, 278
SendInput {Numpad9}
SendInput {Numpad6}
SendInput {Numpad2}
SendInput {F3}
SendInput {Numpad7}
Sleep, 556
Sleep, 278
SendInput {Numpad0}
SendInput {Numpad7}
Sleep, 556
SendInput {Numpad2}
SendInput {Numpad1}
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 833
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad2}
SendInput {Numpad6}
Sleep, 556
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 556
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 278
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad2}
SendInput {Numpad1}
Sleep, 278
Sleep, 278
Sleep, 278
SendInput {Numpad2}
SendInput {Numpad6}
Sleep, 278
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad6}
Sleep, 278
SendInput {Numpad4}
Sleep, 556
SendInput {Numpad1}
SendInput {Numpad3}
Sleep, 278
SendInput {Numpad9}
SendInput {Numpad6}
SendInput {Numpad1}
SendInput {Numpad3}
Sleep, 833
SendInput {Numpad6}
SendInput {Numpad2}
SendInput {F3}
SendInput {Numpad7}
Sleep, 1389
SendInput {Numpad0}
SendInput {Numpad6}
SendInput {Numpad3}
SendInput {Numpad5}
SendInput {Numpad1}
Sleep, 833
SendInput {Numpad9}
SendInput {Numpad6}
SendInput {Numpad2}
SendInput {F3}
SendInput {Numpad7}
Sleep, 1389
SendInput {Numpad0}
SendInput {Numpad2}
SendInput {Numpad1}
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 833
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad2}
SendInput {Numpad6}
Sleep, 556
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 556
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 278
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad2}
SendInput {Numpad1}
Sleep, 278
Sleep, 278
Sleep, 278
SendInput {Numpad2}
SendInput {Numpad6}
Sleep, 278
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad6}
Sleep, 278
SendInput {Numpad4}
Sleep, 556
SendInput {Numpad1}
SendInput {Numpad3}
Sleep, 278
SendInput {Numpad9}
SendInput {Numpad6}
SendInput {Numpad1}
SendInput {Numpad3}
Sleep, 833
SendInput {Numpad6}
SendInput {Numpad2}
SendInput {F3}
SendInput {Numpad7}
Sleep, 1389
SendInput {Numpad0}
SendInput {Numpad6}
SendInput {Numpad3}
SendInput {Numpad5}
SendInput {Numpad1}
Sleep, 833
SendInput {Numpad9}
SendInput {Numpad6}
SendInput {Numpad2}
SendInput {F3}
SendInput {Numpad7}
Sleep, 1389
SendInput {Numpad6}
SendInput {Numpad1}
SendInput {Numpad3}
Sleep, 833
SendInput {Numpad6}
SendInput {Numpad2}
SendInput {F3}
SendInput {Numpad7}
Sleep, 1389
SendInput {Numpad6}
SendInput {Numpad3}
SendInput {Numpad5}
SendInput {Numpad1}
Sleep, 833
SendInput {Numpad6}
SendInput {Numpad2}
SendInput {F3}
SendInput {Numpad7}
Sleep, 1389
SendInput {Numpad9}
SendInput {Numpad6}
Sleep, 1000
