; title: Don't Stop Believin'
; author: Journey
; instrument: Piano
; Converted by Serenade Music Converter v1.1.1

SendInput {Numpad0}
Sleep, 60
SendInput {Numpad5}
SendInput {Numpad2}
Sleep, 201
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad5}
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad5}
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad6}
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad7}
SendInput {Numpad5}
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad2}
Sleep, 201
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad2}
Sleep, 201
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad6}
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad6}
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad3}
SendInput {Numpad2}
Sleep, 261
SendInput {F3}
SendInput {Numpad6}
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad3}
SendInput {Numpad2}
Sleep, 201
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad2}
Sleep, 201
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad5}
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad5}
SendInput {Numpad2}
Sleep, 261
SendInput {F3}
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad5}
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad1}
SendInput {Numpad2}
Sleep, 201
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad1}
Sleep, 201
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad1}
Sleep, 261
SendInput {Numpad3}
SendInput {Numpad1}
Sleep, 261
SendInput {Numpad1}
Sleep, 261
SendInput {Numpad3}
SendInput {Numpad1}
Sleep, 261
SendInput {F3}
SendInput {Numpad1}
Sleep, 261
SendInput {Numpad5}
SendInput {Numpad3}
SendInput {Numpad1}
Sleep, 261
SendInput {Numpad2}
Sleep, 201
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad5}
SendInput {Numpad2}
Sleep, 201
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad5}
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad5}
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad6}
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad7}
SendInput {Numpad5}
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad2}
Sleep, 201
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad2}
Sleep, 201
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad6}
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad6}
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad3}
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad5}
SendInput {Numpad6}
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad7}
SendInput {Numpad2}
Sleep, 201
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad2}
Sleep, 201
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad2}
Sleep, 261
SendInput {F3}
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad2}
Sleep, 261
SendInput {F3}
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad6}
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad7}
SendInput {F3}
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad1}
SendInput {Numpad2}
Sleep, 201
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad1}
Sleep, 201
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad1}
Sleep, 261
SendInput {Numpad3}
SendInput {Numpad1}
Sleep, 261
SendInput {Numpad1}
Sleep, 261
SendInput {Numpad3}
SendInput {Numpad1}
Sleep, 261
SendInput {F3}
SendInput {Numpad1}
Sleep, 261
SendInput {Numpad5}
SendInput {Numpad3}
SendInput {Numpad1}
Sleep, 261
SendInput {Numpad1}
Sleep, 261
SendInput {Numpad2}
SendInput {Numpad5}
SendInput {Numpad7}
Sleep, 261
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad5}
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad5}
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad6}
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad7}
Sleep, 261
SendInput {Numpad5}
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad2}
SendInput {F3}
SendInput {Numpad6}
Sleep, 261
SendInput {Numpad6}
SendInput {Numpad2}
Sleep, 522
SendInput {Numpad7}
SendInput {Numpad2}
Sleep, 462
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad3}
Sleep, 261
SendInput {F3}
Sleep, 462
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad2}
SendInput {Numpad3}
SendInput {Numpad5}
SendInput {Numpad7}
Sleep, 261
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad5}
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad3}
Sleep, 130
SendInput {Numpad5}
Sleep, 130
SendInput {Numpad5}
SendInput {F3}
Sleep, 201
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad5}
Sleep, 201
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad5}
SendInput {Numpad1}
Sleep, 261
SendInput {Numpad1}
SendInput {Numpad3}
SendInput {Numpad5}
SendInput {Numpad2}
Sleep, 462
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad2}
Sleep, 201
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad7}
SendInput {Numpad3}
Sleep, 522
SendInput {Numpad6}
SendInput {F3}
SendInput {Numpad3}
Sleep, 201
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad5}
Sleep, 462
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad2}
SendInput {Numpad5}
SendInput {Numpad7}
Sleep, 261
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad5}
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad5}
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad2}
SendInput {Numpad6}
Sleep, 261
SendInput {Numpad7}
Sleep, 261
SendInput {Numpad5}
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad2}
SendInput {F3}
SendInput {Numpad6}
Sleep, 261
SendInput {Numpad6}
SendInput {Numpad2}
Sleep, 522
SendInput {Numpad7}
SendInput {Numpad2}
Sleep, 522
SendInput {Numpad6}
SendInput {Numpad3}
SendInput {Numpad2}
Sleep, 201
SendInput {Numpad9}
Sleep, 60
SendInput {F3}
Sleep, 201
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad5}
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad2}
SendInput {F3}
SendInput {Numpad6}
SendInput {Numpad7}
Sleep, 261
SendInput {Numpad2}
Sleep, 261
SendInput {F3}
Sleep, 261
SendInput {Numpad7}
SendInput {Numpad2}
Sleep, 261
SendInput {F3}
Sleep, 261
SendInput {Numpad6}
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad5}
SendInput {Numpad7}
Sleep, 201
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad1}
Sleep, 201
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad1}
SendInput {Numpad3}
SendInput {Numpad5}
Sleep, 261
SendInput {Numpad1}
Sleep, 261
SendInput {Numpad3}
SendInput {Numpad1}
Sleep, 261
SendInput {Numpad1}
Sleep, 261
SendInput {Numpad3}
SendInput {Numpad1}
Sleep, 261
SendInput {F3}
SendInput {Numpad1}
Sleep, 261
SendInput {Numpad5}
SendInput {Numpad3}
SendInput {Numpad1}
Sleep, 261
SendInput {Numpad1}
Sleep, 261
SendInput {Numpad2}
SendInput {Numpad5}
SendInput {Numpad7}
Sleep, 261
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad5}
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad5}
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad6}
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad7}
Sleep, 261
SendInput {Numpad5}
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad2}
SendInput {F3}
SendInput {Numpad6}
Sleep, 261
SendInput {Numpad6}
SendInput {Numpad2}
Sleep, 522
SendInput {Numpad7}
SendInput {Numpad2}
Sleep, 462
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad3}
Sleep, 261
SendInput {F3}
Sleep, 462
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad2}
SendInput {Numpad3}
SendInput {Numpad5}
SendInput {Numpad7}
Sleep, 261
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad5}
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad3}
Sleep, 130
SendInput {Numpad5}
Sleep, 130
SendInput {Numpad5}
SendInput {F3}
Sleep, 201
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad5}
Sleep, 201
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad5}
SendInput {Numpad1}
Sleep, 261
SendInput {Numpad1}
SendInput {Numpad3}
SendInput {Numpad5}
SendInput {Numpad2}
Sleep, 462
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad2}
Sleep, 201
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad7}
SendInput {Numpad3}
Sleep, 522
SendInput {Numpad6}
SendInput {F3}
SendInput {Numpad3}
Sleep, 201
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad5}
Sleep, 462
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad2}
SendInput {Numpad5}
SendInput {Numpad7}
Sleep, 261
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad5}
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad5}
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad2}
SendInput {Numpad6}
Sleep, 261
SendInput {Numpad7}
Sleep, 261
SendInput {Numpad5}
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad2}
SendInput {F3}
SendInput {Numpad6}
Sleep, 261
SendInput {Numpad6}
SendInput {Numpad2}
Sleep, 522
SendInput {Numpad7}
SendInput {Numpad2}
Sleep, 522
SendInput {Numpad6}
SendInput {Numpad3}
SendInput {Numpad2}
Sleep, 201
SendInput {Numpad9}
Sleep, 60
SendInput {F3}
Sleep, 201
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad5}
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad2}
SendInput {F3}
SendInput {Numpad6}
SendInput {Numpad7}
Sleep, 261
SendInput {Numpad2}
Sleep, 261
SendInput {F3}
Sleep, 261
SendInput {Numpad7}
SendInput {Numpad2}
Sleep, 261
SendInput {F3}
Sleep, 261
SendInput {Numpad6}
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad5}
SendInput {Numpad7}
Sleep, 201
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad1}
Sleep, 201
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad1}
SendInput {Numpad3}
SendInput {Numpad5}
Sleep, 261
SendInput {Numpad1}
Sleep, 261
SendInput {Numpad3}
SendInput {Numpad1}
Sleep, 261
SendInput {Numpad1}
Sleep, 261
SendInput {Numpad3}
SendInput {Numpad1}
Sleep, 261
SendInput {F3}
SendInput {Numpad1}
Sleep, 261
SendInput {Numpad5}
SendInput {Numpad3}
SendInput {Numpad1}
Sleep, 261
SendInput {Numpad1}
Sleep, 261
SendInput {Numpad2}
SendInput {Numpad5}
SendInput {Numpad7}
Sleep, 261
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad5}
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad5}
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad6}
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad7}
SendInput {Numpad5}
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad2}
Sleep, 201
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad2}
Sleep, 201
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad6}
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad6}
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad3}
SendInput {Numpad2}
Sleep, 261
SendInput {F3}
SendInput {Numpad6}
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad3}
SendInput {Numpad2}
Sleep, 201
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad2}
Sleep, 201
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad5}
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad5}
SendInput {Numpad2}
Sleep, 261
SendInput {F3}
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad5}
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad1}
SendInput {Numpad2}
Sleep, 201
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad1}
Sleep, 201
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad1}
Sleep, 261
SendInput {Numpad3}
SendInput {Numpad1}
Sleep, 261
SendInput {Numpad1}
Sleep, 261
SendInput {Numpad3}
SendInput {Numpad1}
Sleep, 261
SendInput {F3}
SendInput {Numpad1}
Sleep, 261
SendInput {Numpad5}
SendInput {Numpad3}
SendInput {Numpad1}
Sleep, 261
SendInput {Numpad5}
SendInput {Numpad2}
Sleep, 201
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad2}
Sleep, 201
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad5}
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad5}
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad6}
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad7}
SendInput {Numpad5}
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad2}
Sleep, 201
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad2}
Sleep, 201
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad6}
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad6}
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad3}
SendInput {Numpad2}
Sleep, 261
SendInput {F3}
SendInput {Numpad6}
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad3}
SendInput {Numpad2}
Sleep, 201
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad2}
Sleep, 201
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad5}
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad5}
SendInput {Numpad2}
Sleep, 261
SendInput {F3}
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad5}
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad1}
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad1}
SendInput {Numpad3}
SendInput {Numpad5}
Sleep, 261
SendInput {Numpad1}
Sleep, 261
SendInput {Numpad3}
SendInput {Numpad1}
Sleep, 261
SendInput {Numpad1}
Sleep, 261
SendInput {Numpad3}
SendInput {Numpad1}
Sleep, 522
SendInput {Numpad2}
SendInput {Numpad5}
SendInput {Numpad7}
Sleep, 261
SendInput {Numpad5}
SendInput {Numpad2}
SendInput {Numpad7}
Sleep, 261
SendInput {Numpad2}
SendInput {Numpad5}
SendInput {Numpad7}
Sleep, 261
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad5}
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad7}
Sleep, 261
SendInput {Numpad6}
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad7}
Sleep, 261
SendInput {Numpad5}
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad2}
SendInput {F3}
SendInput {Numpad6}
Sleep, 261
SendInput {Numpad6}
SendInput {Numpad2}
Sleep, 522
SendInput {Numpad7}
SendInput {Numpad2}
Sleep, 462
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad3}
Sleep, 261
SendInput {F3}
Sleep, 462
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad2}
SendInput {Numpad3}
SendInput {Numpad5}
SendInput {Numpad7}
Sleep, 261
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad5}
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad3}
Sleep, 261
SendInput {Numpad5}
Sleep, 130
SendInput {Numpad5}
Sleep, 130
SendInput {Numpad5}
SendInput {F3}
SendInput {Numpad2}
Sleep, 201
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad5}
Sleep, 201
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad5}
SendInput {Numpad1}
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad1}
SendInput {Numpad3}
SendInput {Numpad5}
SendInput {Numpad2}
Sleep, 462
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad2}
Sleep, 201
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad7}
SendInput {Numpad3}
Sleep, 522
SendInput {Numpad6}
SendInput {F3}
SendInput {Numpad3}
Sleep, 201
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad5}
Sleep, 462
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad2}
SendInput {Numpad5}
SendInput {Numpad7}
Sleep, 261
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad7}
Sleep, 261
SendInput {Numpad6}
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad7}
Sleep, 261
SendInput {Numpad6}
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad6}
SendInput {Numpad7}
Sleep, 261
SendInput {Numpad5}
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad2}
SendInput {F3}
SendInput {Numpad6}
Sleep, 522
SendInput {Numpad6}
Sleep, 261
SendInput {Numpad7}
SendInput {Numpad2}
Sleep, 462
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad3}
Sleep, 27
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad6}
Sleep, 114
SendInput {Numpad9}
Sleep, 60
SendInput {F3}
Sleep, 114
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad5}
Sleep, 348
SendInput {Numpad2}
SendInput {F3}
SendInput {Numpad6}
SendInput {Numpad7}
Sleep, 261
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad7}
SendInput {Numpad3}
Sleep, 261
SendInput {Numpad6}
SendInput {Numpad7}
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad7}
SendInput {F3}
Sleep, 261
SendInput {Numpad7}
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad7}
SendInput {Numpad3}
Sleep, 261
SendInput {Numpad6}
SendInput {Numpad7}
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad1}
SendInput {Numpad3}
SendInput {Numpad5}
Sleep, 261
SendInput {Numpad1}
Sleep, 261
SendInput {Numpad7}
SendInput {Numpad1}
SendInput {Numpad3}
Sleep, 261
SendInput {Numpad7}
SendInput {Numpad1}
Sleep, 130
SendInput {Numpad6}
Sleep, 130
SendInput {Numpad5}
SendInput {Numpad1}
Sleep, 201
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad1}
Sleep, 261
SendInput {Numpad1}
Sleep, 261
SendInput {Numpad1}
Sleep, 201
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad2}
SendInput {F3}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 201
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad1}
Sleep, 261
SendInput {Numpad1}
Sleep, 201
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad1}
SendInput {Numpad3}
SendInput {Numpad5}
Sleep, 201
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad1}
Sleep, 261
SendInput {Numpad1}
Sleep, 261
SendInput {Numpad1}
Sleep, 261
SendInput {Numpad1}
Sleep, 201
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad2}
SendInput {F3}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 201
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad1}
Sleep, 261
SendInput {Numpad1}
Sleep, 201
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad2}
SendInput {Numpad5}
SendInput {Numpad7}
SendInput {Numpad1}
Sleep, 201
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad7}
Sleep, 261
SendInput {Numpad6}
Sleep, 261
SendInput {Numpad5}
Sleep, 261
SendInput {Numpad2}
Sleep, 201
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad2}
SendInput {F3}
SendInput {Numpad6}
SendInput {Numpad5}
Sleep, 201
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad5}
SendInput {Numpad6}
SendInput {F3}
Sleep, 201
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad2}
SendInput {Numpad5}
SendInput {Numpad7}
SendInput {Numpad6}
Sleep, 201
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad5}
SendInput {Numpad7}
Sleep, 201
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad5}
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad5}
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad5}
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad5}
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad2}
SendInput {F3}
SendInput {Numpad6}
SendInput {Numpad5}
Sleep, 201
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad5}
Sleep, 141
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad1}
SendInput {F3}
Sleep, 201
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad2}
SendInput {Numpad5}
SendInput {Numpad7}
Sleep, 201
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad5}
Sleep, 261
SendInput {Numpad5}
Sleep, 201
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad6}
SendInput {F3}
Sleep, 201
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad5}
Sleep, 201
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad2}
SendInput {F3}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 201
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad1}
Sleep, 261
SendInput {Numpad1}
Sleep, 201
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad1}
SendInput {Numpad3}
SendInput {Numpad5}
Sleep, 201
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad1}
Sleep, 261
SendInput {Numpad1}
Sleep, 261
SendInput {Numpad1}
Sleep, 261
SendInput {Numpad1}
Sleep, 201
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad2}
SendInput {F3}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 201
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad1}
Sleep, 261
SendInput {Numpad1}
Sleep, 201
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad2}
SendInput {Numpad5}
SendInput {Numpad7}
SendInput {Numpad1}
Sleep, 201
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad7}
Sleep, 201
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad6}
Sleep, 261
SendInput {Numpad5}
Sleep, 261
SendInput {Numpad6}
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad2}
SendInput {F3}
SendInput {Numpad6}
SendInput {Numpad5}
Sleep, 201
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad5}
Sleep, 201
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad7}
SendInput {Numpad5}
Sleep, 261
SendInput {Numpad2}
SendInput {Numpad5}
SendInput {Numpad7}
Sleep, 201
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad5}
Sleep, 261
SendInput {Numpad5}
Sleep, 261
SendInput {Numpad5}
Sleep, 261
SendInput {Numpad5}
Sleep, 201
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad2}
SendInput {F3}
SendInput {Numpad6}
SendInput {Numpad5}
Sleep, 261
SendInput {Numpad5}
SendInput {Numpad2}
SendInput {Numpad6}
Sleep, 261
SendInput {F3}
SendInput {Numpad2}
SendInput {Numpad6}
Sleep, 261
SendInput {Numpad2}
SendInput {Numpad5}
SendInput {Numpad7}
Sleep, 201
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad5}
Sleep, 261
SendInput {Numpad5}
Sleep, 261
SendInput {F3}
Sleep, 261
SendInput {Numpad5}
Sleep, 201
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad2}
SendInput {F3}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 201
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad1}
Sleep, 261
SendInput {Numpad1}
Sleep, 201
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad1}
SendInput {Numpad3}
SendInput {Numpad5}
Sleep, 201
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad1}
Sleep, 261
SendInput {Numpad1}
Sleep, 261
SendInput {Numpad1}
Sleep, 261
SendInput {Numpad1}
Sleep, 201
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad2}
SendInput {F3}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 201
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad1}
Sleep, 261
SendInput {Numpad1}
Sleep, 201
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad2}
SendInput {Numpad5}
SendInput {Numpad7}
SendInput {Numpad1}
Sleep, 201
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad7}
Sleep, 261
SendInput {Numpad6}
Sleep, 261
SendInput {Numpad5}
Sleep, 261
SendInput {Numpad2}
Sleep, 201
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad2}
SendInput {F3}
SendInput {Numpad6}
SendInput {Numpad5}
Sleep, 201
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad5}
SendInput {Numpad6}
SendInput {F3}
Sleep, 201
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad2}
SendInput {Numpad5}
SendInput {Numpad7}
SendInput {Numpad6}
Sleep, 201
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad5}
SendInput {Numpad7}
Sleep, 201
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad5}
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad5}
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad5}
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad5}
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad2}
SendInput {F3}
SendInput {Numpad6}
SendInput {Numpad5}
Sleep, 201
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad5}
Sleep, 141
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad1}
SendInput {F3}
Sleep, 201
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad2}
SendInput {Numpad5}
SendInput {Numpad7}
Sleep, 201
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad5}
Sleep, 261
SendInput {Numpad5}
Sleep, 201
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad6}
SendInput {F3}
Sleep, 201
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad5}
Sleep, 201
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad2}
SendInput {F3}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 201
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad1}
Sleep, 261
SendInput {Numpad1}
Sleep, 201
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad1}
SendInput {Numpad3}
SendInput {Numpad5}
Sleep, 201
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad1}
Sleep, 261
SendInput {Numpad1}
Sleep, 261
SendInput {Numpad1}
Sleep, 261
SendInput {Numpad1}
Sleep, 201
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad2}
SendInput {F3}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 201
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad1}
Sleep, 261
SendInput {Numpad1}
Sleep, 201
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad2}
SendInput {Numpad5}
SendInput {Numpad7}
SendInput {Numpad1}
Sleep, 201
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad7}
Sleep, 201
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad6}
Sleep, 261
SendInput {Numpad5}
Sleep, 201
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad2}
Sleep, 201
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad2}
SendInput {F3}
SendInput {Numpad6}
Sleep, 783
SendInput {Numpad2}
SendInput {Numpad5}
SendInput {Numpad7}
Sleep, 1304
SendInput {Numpad2}
SendInput {F3}
SendInput {Numpad6}
Sleep, 522
SendInput {Numpad2}
SendInput {Numpad5}
SendInput {Numpad7}
Sleep, 261
SendInput {Numpad1}
SendInput {Numpad3}
SendInput {Numpad5}
Sleep, 1304
SendInput {Numpad2}
SendInput {Numpad5}
SendInput {Numpad7}
Sleep, 201
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad5}
Sleep, 201
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad5}
SendInput {Numpad2}
Sleep, 201
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad5}
Sleep, 261
SendInput {Numpad5}
Sleep, 261
SendInput {Numpad6}
Sleep, 261
SendInput {Numpad7}
Sleep, 201
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad2}
SendInput {Numpad6}
Sleep, 201
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad2}
Sleep, 201
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad3}
Sleep, 261
SendInput {F3}
Sleep, 261
SendInput {Numpad3}
Sleep, 261
SendInput {Numpad3}
SendInput {Numpad7}
Sleep, 201
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad3}
Sleep, 261
SendInput {Numpad3}
Sleep, 261
SendInput {Numpad3}
Sleep, 201
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad3}
Sleep, 261
SendInput {F3}
Sleep, 261
SendInput {Numpad5}
Sleep, 261
SendInput {Numpad1}
Sleep, 261
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 201
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad1}
Sleep, 261
SendInput {Numpad1}
Sleep, 261
SendInput {Numpad1}
Sleep, 201
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad1}
Sleep, 201
SendInput {Numpad9}
Sleep, 60
SendInput {F3}
SendInput {Numpad7}
Sleep, 261
SendInput {Numpad5}
SendInput {Numpad6}
Sleep, 261
SendInput {Numpad5}
Sleep, 201
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad2}
SendInput {Numpad5}
SendInput {Numpad7}
Sleep, 201
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad5}
Sleep, 201
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad7}
SendInput {Numpad5}
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad6}
SendInput {Numpad5}
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad7}
SendInput {Numpad5}
Sleep, 261
SendInput {Numpad6}
Sleep, 201
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad7}
Sleep, 201
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad5}
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad2}
SendInput {F3}
SendInput {Numpad6}
Sleep, 261
SendInput {Numpad6}
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad7}
SendInput {Numpad2}
Sleep, 201
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad3}
Sleep, 261
SendInput {F3}
Sleep, 261
SendInput {Numpad3}
Sleep, 201
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad2}
SendInput {Numpad3}
SendInput {Numpad5}
SendInput {Numpad7}
Sleep, 261
SendInput {Numpad3}
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad3}
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad3}
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad5}
SendInput {Numpad3}
Sleep, 130
SendInput {Numpad5}
Sleep, 130
SendInput {Numpad5}
SendInput {F3}
Sleep, 201
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad5}
Sleep, 201
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad5}
SendInput {Numpad1}
Sleep, 261
SendInput {Numpad1}
SendInput {Numpad3}
SendInput {Numpad5}
SendInput {Numpad2}
Sleep, 201
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad1}
Sleep, 141
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad2}
SendInput {Numpad1}
Sleep, 201
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad7}
SendInput {Numpad1}
SendInput {Numpad3}
Sleep, 201
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad1}
Sleep, 201
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad6}
SendInput {F3}
SendInput {Numpad3}
Sleep, 201
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad5}
Sleep, 261
SendInput {Numpad5}
Sleep, 201
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad2}
SendInput {Numpad5}
SendInput {Numpad7}
Sleep, 201
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad5}
Sleep, 201
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad7}
SendInput {Numpad5}
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad6}
SendInput {Numpad5}
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad7}
SendInput {Numpad5}
Sleep, 261
SendInput {Numpad6}
Sleep, 261
SendInput {Numpad6}
SendInput {Numpad7}
Sleep, 261
SendInput {Numpad5}
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad2}
SendInput {F3}
SendInput {Numpad6}
Sleep, 201
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad2}
Sleep, 201
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad6}
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad7}
SendInput {Numpad2}
Sleep, 201
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad3}
Sleep, 261
SendInput {F3}
Sleep, 201
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad5}
SendInput {Numpad7}
Sleep, 261
SendInput {Numpad2}
SendInput {F3}
SendInput {Numpad6}
SendInput {Numpad7}
Sleep, 201
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad7}
Sleep, 261
SendInput {Numpad7}
Sleep, 201
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad7}
SendInput {Numpad3}
Sleep, 201
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad7}
Sleep, 261
SendInput {Numpad7}
Sleep, 201
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad5}
SendInput {Numpad7}
SendInput {Numpad1}
Sleep, 201
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad1}
Sleep, 201
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad1}
SendInput {Numpad3}
SendInput {Numpad5}
Sleep, 201
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad1}
Sleep, 261
SendInput {Numpad1}
Sleep, 201
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad1}
SendInput {Numpad5}
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad1}
SendInput {Numpad5}
SendInput {Numpad2}
Sleep, 261
SendInput {F3}
Sleep, 261
SendInput {Numpad5}
Sleep, 201
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad5}
Sleep, 201
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad2}
SendInput {Numpad5}
SendInput {Numpad7}
Sleep, 201
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad5}
Sleep, 201
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad7}
SendInput {Numpad5}
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad6}
SendInput {Numpad5}
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad7}
SendInput {Numpad5}
Sleep, 261
SendInput {Numpad6}
Sleep, 201
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad7}
Sleep, 261
SendInput {Numpad2}
Sleep, 201
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad2}
SendInput {F3}
SendInput {Numpad6}
Sleep, 201
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad2}
Sleep, 27
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad6}
SendInput {Numpad2}
Sleep, 114
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad2}
Sleep, 114
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad7}
Sleep, 27
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad2}
Sleep, 201
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad6}
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad5}
SendInput {Numpad3}
Sleep, 201
SendInput {Numpad9}
Sleep, 60
SendInput {F3}
Sleep, 261
SendInput {Numpad3}
Sleep, 201
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad2}
SendInput {Numpad3}
SendInput {Numpad5}
SendInput {Numpad7}
Sleep, 261
SendInput {Numpad3}
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad3}
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad3}
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad5}
SendInput {Numpad3}
Sleep, 130
SendInput {Numpad5}
Sleep, 130
SendInput {Numpad5}
SendInput {F3}
Sleep, 201
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad5}
Sleep, 201
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad5}
SendInput {Numpad1}
Sleep, 261
SendInput {Numpad1}
SendInput {Numpad3}
SendInput {Numpad5}
SendInput {Numpad2}
Sleep, 201
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad1}
Sleep, 141
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad2}
SendInput {Numpad1}
Sleep, 201
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad7}
SendInput {Numpad1}
SendInput {Numpad3}
Sleep, 201
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad1}
Sleep, 201
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad6}
SendInput {F3}
SendInput {Numpad3}
Sleep, 201
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad5}
Sleep, 261
SendInput {Numpad5}
Sleep, 201
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad2}
SendInput {Numpad5}
SendInput {Numpad7}
Sleep, 201
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad5}
Sleep, 201
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad7}
SendInput {Numpad5}
Sleep, 201
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad2}
SendInput {Numpad5}
SendInput {Numpad7}
Sleep, 261
SendInput {Numpad3}
SendInput {Numpad5}
Sleep, 201
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad7}
SendInput {Numpad6}
Sleep, 201
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad7}
Sleep, 201
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad7}
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad2}
SendInput {F3}
SendInput {Numpad6}
Sleep, 261
SendInput {Numpad6}
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad6}
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad5}
SendInput {Numpad2}
Sleep, 201
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad3}
Sleep, 27
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad5}
Sleep, 114
SendInput {Numpad9}
Sleep, 60
SendInput {F3}
Sleep, 114
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad5}
Sleep, 27
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad7}
Sleep, 201
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad2}
SendInput {F3}
SendInput {Numpad6}
SendInput {Numpad7}
Sleep, 201
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad7}
Sleep, 201
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad7}
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad6}
SendInput {Numpad7}
SendInput {Numpad2}
Sleep, 201
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad7}
Sleep, 261
SendInput {Numpad7}
Sleep, 201
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad7}
Sleep, 261
SendInput {Numpad6}
SendInput {Numpad7}
Sleep, 261
SendInput {Numpad1}
SendInput {Numpad3}
SendInput {Numpad5}
Sleep, 201
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad1}
Sleep, 201
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad7}
SendInput {Numpad1}
Sleep, 261
SendInput {Numpad7}
SendInput {Numpad1}
Sleep, 130
SendInput {Numpad6}
Sleep, 130
SendInput {Numpad5}
SendInput {Numpad1}
SendInput {Numpad3}
Sleep, 201
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad1}
Sleep, 261
SendInput {Numpad1}
Sleep, 261
SendInput {Numpad1}
Sleep, 201
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad2}
SendInput {F3}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 201
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad1}
Sleep, 261
SendInput {Numpad1}
Sleep, 201
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad1}
SendInput {Numpad3}
SendInput {Numpad5}
Sleep, 201
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad1}
Sleep, 261
SendInput {Numpad1}
Sleep, 261
SendInput {Numpad1}
Sleep, 261
SendInput {Numpad1}
Sleep, 201
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad2}
SendInput {F3}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 201
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad1}
Sleep, 261
SendInput {Numpad1}
Sleep, 201
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad2}
SendInput {Numpad5}
SendInput {Numpad7}
SendInput {Numpad1}
Sleep, 201
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad7}
Sleep, 261
SendInput {Numpad6}
Sleep, 261
SendInput {Numpad5}
Sleep, 261
SendInput {Numpad2}
Sleep, 201
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad2}
SendInput {F3}
SendInput {Numpad6}
SendInput {Numpad5}
Sleep, 201
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad5}
SendInput {Numpad6}
SendInput {F3}
Sleep, 201
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad2}
SendInput {Numpad5}
SendInput {Numpad7}
SendInput {Numpad6}
Sleep, 201
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad5}
SendInput {Numpad7}
Sleep, 201
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad5}
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad5}
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad5}
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad5}
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad2}
SendInput {F3}
SendInput {Numpad6}
SendInput {Numpad5}
Sleep, 201
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad5}
Sleep, 141
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad1}
SendInput {F3}
Sleep, 201
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad2}
SendInput {Numpad5}
SendInput {Numpad7}
Sleep, 201
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad5}
Sleep, 261
SendInput {Numpad5}
Sleep, 201
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad6}
SendInput {F3}
Sleep, 201
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad5}
Sleep, 201
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad2}
SendInput {F3}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 201
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad1}
Sleep, 261
SendInput {Numpad1}
Sleep, 201
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad1}
SendInput {Numpad3}
SendInput {Numpad5}
Sleep, 201
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad1}
Sleep, 261
SendInput {Numpad1}
Sleep, 261
SendInput {Numpad1}
Sleep, 261
SendInput {Numpad1}
Sleep, 201
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad2}
SendInput {F3}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 201
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad1}
Sleep, 261
SendInput {Numpad1}
Sleep, 201
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad2}
SendInput {Numpad5}
SendInput {Numpad7}
SendInput {Numpad1}
Sleep, 201
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad7}
Sleep, 201
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad6}
Sleep, 261
SendInput {Numpad5}
Sleep, 201
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad2}
Sleep, 201
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad2}
SendInput {F3}
SendInput {Numpad6}
Sleep, 783
SendInput {Numpad2}
SendInput {Numpad5}
SendInput {Numpad7}
Sleep, 1304
SendInput {Numpad2}
SendInput {F3}
SendInput {Numpad6}
Sleep, 522
SendInput {Numpad2}
SendInput {Numpad5}
SendInput {Numpad7}
Sleep, 261
SendInput {Numpad1}
SendInput {Numpad3}
SendInput {Numpad5}
Sleep, 1304
SendInput {Numpad2}
SendInput {Numpad5}
SendInput {Numpad7}
SendInput {Numpad1}
Sleep, 201
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad5}
Sleep, 261
SendInput {Numpad5}
Sleep, 201
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad5}
SendInput {Numpad2}
SendInput {Numpad7}
Sleep, 201
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad5}
Sleep, 261
SendInput {Numpad6}
Sleep, 201
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad7}
SendInput {Numpad6}
Sleep, 261
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 261
SendInput {Numpad2}
SendInput {F3}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 201
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad2}
Sleep, 201
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad2}
SendInput {Numpad7}
Sleep, 201
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad3}
Sleep, 261
SendInput {F3}
Sleep, 261
SendInput {Numpad3}
Sleep, 201
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad3}
SendInput {Numpad7}
Sleep, 201
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad3}
Sleep, 261
SendInput {Numpad3}
Sleep, 261
SendInput {Numpad3}
Sleep, 141
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad3}
SendInput {Numpad1}
Sleep, 201
SendInput {Numpad9}
Sleep, 60
SendInput {F3}
SendInput {Numpad7}
Sleep, 261
SendInput {Numpad5}
SendInput {Numpad6}
Sleep, 261
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 261
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 201
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad1}
Sleep, 201
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 261
SendInput {Numpad1}
SendInput {Numpad3}
Sleep, 201
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad1}
Sleep, 261
SendInput {F3}
Sleep, 201
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad5}
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad5}
SendInput {Numpad1}
Sleep, 201
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad5}
SendInput {Numpad1}
Sleep, 141
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad5}
Sleep, 201
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad5}
SendInput {Numpad7}
Sleep, 261
SendInput {Numpad5}
SendInput {Numpad2}
SendInput {Numpad7}
Sleep, 201
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad5}
Sleep, 261
SendInput {Numpad6}
Sleep, 201
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad7}
SendInput {Numpad6}
Sleep, 261
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 261
SendInput {Numpad2}
SendInput {F3}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 201
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad2}
Sleep, 201
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad2}
SendInput {Numpad7}
Sleep, 201
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad2}
Sleep, 201
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 261
SendInput {F3}
SendInput {Numpad5}
Sleep, 201
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad7}
SendInput {Numpad2}
Sleep, 201
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad2}
SendInput {F3}
SendInput {Numpad7}
Sleep, 201
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad7}
Sleep, 261
SendInput {Numpad7}
Sleep, 261
SendInput {Numpad7}
Sleep, 261
SendInput {Numpad7}
Sleep, 141
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad3}
SendInput {Numpad7}
Sleep, 141
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad7}
Sleep, 141
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad5}
SendInput {Numpad1}
Sleep, 201
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad1}
SendInput {Numpad3}
SendInput {Numpad5}
Sleep, 201
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad1}
Sleep, 261
SendInput {Numpad1}
Sleep, 261
SendInput {Numpad1}
Sleep, 261
SendInput {Numpad1}
Sleep, 261
SendInput {F3}
Sleep, 261
SendInput {Numpad5}
Sleep, 462
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad1}
SendInput {F2}
SendInput {F4}
SendInput {F1}
Sleep, 201
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad1}
SendInput {F4}
Sleep, 201
SendInput {Numpad9}
Sleep, 60
SendInput {F4}
SendInput {F2}
Sleep, 201
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad1}
SendInput {F4}
Sleep, 141
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {F4}
Sleep, 261
SendInput {F5}
Sleep, 261
SendInput {Numpad1}
Sleep, 201
SendInput {Numpad0}
Sleep, 60
SendInput {F5}
SendInput {F2}
Sleep, 261
SendInput {F2}
SendInput {Numpad5}
SendInput {F5}
SendInput {F1}
Sleep, 201
SendInput {Numpad9}
Sleep, 60
SendInput {F2}
Sleep, 141
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad1}
SendInput {F2}
Sleep, 261
SendInput {Numpad1}
SendInput {F2}
Sleep, 141
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {F2}
Sleep, 261
SendInput {Numpad4}
Sleep, 261
SendInput {Numpad5}
Sleep, 261
SendInput {Numpad4}
Sleep, 201
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad1}
SendInput {F2}
SendInput {Numpad4}
SendInput {F4}
Sleep, 201
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad4}
Sleep, 201
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad4}
SendInput {F4}
SendInput {F2}
Sleep, 201
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad4}
Sleep, 141
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {F1}
SendInput {Numpad4}
Sleep, 261
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 261
SendInput {F1}
SendInput {F4}
Sleep, 261
SendInput {F2}
SendInput {F1}
Sleep, 201
SendInput {Numpad9}
Sleep, 60
SendInput {F1}
SendInput {Numpad4}
SendInput {F4}
Sleep, 201
SendInput {Numpad9}
Sleep, 60
SendInput {F1}
Sleep, 141
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {F2}
SendInput {F1}
Sleep, 130
SendInput {Numpad4}
Sleep, 130
SendInput {Numpad1}
SendInput {F1}
SendInput {F4}
Sleep, 141
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {F1}
Sleep, 261
SendInput {Numpad5}
Sleep, 27
SendInput {Numpad0}
Sleep, 60
SendInput {F5}
Sleep, 114
SendInput {Numpad9}
Sleep, 60
SendInput {F4}
Sleep, 114
SendInput {Numpad0}
Sleep, 60
SendInput {F4}
Sleep, 27
SendInput {Numpad9}
Sleep, 60
SendInput {F4}
Sleep, 201
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad1}
SendInput {F2}
SendInput {F4}
SendInput {F1}
Sleep, 201
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad1}
SendInput {F4}
Sleep, 201
SendInput {Numpad9}
Sleep, 60
SendInput {F4}
SendInput {F2}
Sleep, 201
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad1}
SendInput {F4}
Sleep, 141
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {F4}
Sleep, 261
SendInput {F5}
Sleep, 261
SendInput {Numpad1}
Sleep, 261
SendInput {F2}
Sleep, 201
SendInput {Numpad0}
Sleep, 60
SendInput {F2}
SendInput {Numpad5}
SendInput {F5}
SendInput {F1}
Sleep, 201
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad1}
SendInput {F2}
Sleep, 141
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {F2}
Sleep, 141
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad1}
SendInput {F2}
Sleep, 141
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {F2}
Sleep, 261
SendInput {Numpad4}
Sleep, 27
SendInput {Numpad0}
Sleep, 60
SendInput {F5}
Sleep, 114
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad5}
Sleep, 114
SendInput {Numpad0}
Sleep, 60
SendInput {F4}
Sleep, 27
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad1}
Sleep, 201
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad1}
SendInput {F2}
SendInput {Numpad5}
Sleep, 261
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 261
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 261
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 261
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 261
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 261
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 261
SendInput {F1}
SendInput {F4}
Sleep, 261
SendInput {F1}
SendInput {Numpad4}
SendInput {F4}
Sleep, 261
SendInput {F1}
SendInput {F4}
Sleep, 261
SendInput {F1}
SendInput {F4}
Sleep, 261
SendInput {F1}
SendInput {F4}
Sleep, 261
SendInput {F1}
SendInput {F4}
Sleep, 201
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad5}
Sleep, 261
SendInput {F4}
Sleep, 261
SendInput {F4}
Sleep, 201
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad1}
SendInput {F2}
SendInput {F4}
SendInput {F1}
Sleep, 201
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad1}
SendInput {F4}
Sleep, 201
SendInput {Numpad9}
Sleep, 60
SendInput {F4}
SendInput {F2}
Sleep, 201
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad1}
SendInput {F4}
Sleep, 141
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {F4}
Sleep, 261
SendInput {F5}
Sleep, 261
SendInput {Numpad1}
Sleep, 201
SendInput {Numpad0}
Sleep, 60
SendInput {F5}
SendInput {F2}
Sleep, 261
SendInput {F2}
SendInput {Numpad5}
SendInput {F5}
SendInput {F1}
Sleep, 201
SendInput {Numpad9}
Sleep, 60
SendInput {F2}
Sleep, 141
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad1}
SendInput {F2}
Sleep, 261
SendInput {Numpad1}
SendInput {F2}
Sleep, 141
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {F2}
Sleep, 261
SendInput {Numpad4}
Sleep, 261
SendInput {Numpad5}
Sleep, 261
SendInput {Numpad4}
Sleep, 201
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad1}
SendInput {F2}
SendInput {Numpad4}
SendInput {F4}
Sleep, 201
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad4}
Sleep, 201
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad4}
SendInput {F4}
SendInput {F2}
Sleep, 201
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad4}
Sleep, 141
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {F1}
SendInput {Numpad4}
Sleep, 261
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 261
SendInput {F1}
SendInput {F4}
Sleep, 261
SendInput {F2}
SendInput {F1}
Sleep, 201
SendInput {Numpad9}
Sleep, 60
SendInput {F1}
SendInput {Numpad4}
SendInput {F4}
Sleep, 201
SendInput {Numpad9}
Sleep, 60
SendInput {F1}
Sleep, 141
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {F2}
SendInput {F1}
Sleep, 130
SendInput {Numpad4}
Sleep, 130
SendInput {Numpad1}
SendInput {F1}
SendInput {F4}
Sleep, 141
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {F1}
Sleep, 261
SendInput {Numpad5}
Sleep, 27
SendInput {Numpad0}
Sleep, 60
SendInput {F5}
Sleep, 114
SendInput {Numpad9}
Sleep, 60
SendInput {F4}
Sleep, 114
SendInput {Numpad0}
Sleep, 60
SendInput {F4}
Sleep, 27
SendInput {Numpad9}
Sleep, 60
SendInput {F4}
Sleep, 201
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad1}
SendInput {F2}
SendInput {F4}
SendInput {F1}
Sleep, 201
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad1}
SendInput {F4}
Sleep, 201
SendInput {Numpad9}
Sleep, 60
SendInput {F4}
SendInput {F2}
Sleep, 201
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad1}
SendInput {F4}
Sleep, 141
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {F4}
Sleep, 261
SendInput {F5}
Sleep, 261
SendInput {Numpad1}
Sleep, 261
SendInput {F2}
Sleep, 201
SendInput {Numpad0}
Sleep, 60
SendInput {F2}
SendInput {Numpad5}
SendInput {F5}
SendInput {F1}
Sleep, 201
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad1}
SendInput {F2}
Sleep, 141
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {F2}
Sleep, 141
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad1}
SendInput {F2}
Sleep, 141
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {F2}
Sleep, 261
SendInput {Numpad4}
Sleep, 27
SendInput {Numpad0}
Sleep, 60
SendInput {F5}
Sleep, 114
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad5}
Sleep, 114
SendInput {Numpad0}
Sleep, 60
SendInput {F4}
Sleep, 27
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad1}
Sleep, 201
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad1}
SendInput {F2}
SendInput {Numpad5}
Sleep, 261
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 261
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 261
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 261
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 261
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 261
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 261
SendInput {F1}
SendInput {F4}
Sleep, 261
SendInput {F1}
SendInput {Numpad4}
SendInput {F4}
Sleep, 261
SendInput {F1}
SendInput {F4}
Sleep, 261
SendInput {F1}
SendInput {F4}
Sleep, 261
SendInput {F1}
SendInput {F4}
Sleep, 261
SendInput {F1}
SendInput {F4}
Sleep, 201
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad5}
Sleep, 261
SendInput {F4}
Sleep, 261
SendInput {F4}
Sleep, 201
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad1}
SendInput {F2}
SendInput {F4}
SendInput {F1}
Sleep, 201
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad1}
SendInput {F4}
Sleep, 141
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {F4}
Sleep, 141
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad1}
SendInput {F4}
Sleep, 1000
