; title: Gangster's Paradise
; author: Coolio
; instrument: Piano
; Converted by Serenade Music Converter

SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 600
SendInput {Numpad6}
Sleep, 600
SendInput {Numpad2}
SendInput {Numpad6}
Sleep, 600
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 600
SendInput {Numpad9}
SendInput {Numpad3}
SendInput {F4}
Sleep, 600
SendInput {F4}
Sleep, 600
SendInput {Numpad6}
Sleep, 600
SendInput {Numpad5}
SendInput {Numpad3}
Sleep, 600
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 600
SendInput {Numpad6}
Sleep, 600
SendInput {Numpad2}
SendInput {Numpad6}
Sleep, 600
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 600
SendInput {Numpad9}
SendInput {Numpad3}
SendInput {F4}
Sleep, 600
SendInput {F4}
Sleep, 600
SendInput {Numpad6}
Sleep, 600
SendInput {Numpad0}
SendInput {Numpad5}
SendInput {Numpad1}
Sleep, 600
SendInput {Numpad9}
SendInput {Numpad4}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 600
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 600
SendInput {Numpad2}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 600
SendInput {Numpad0}
SendInput {Numpad1}
SendInput {Numpad3}
Sleep, 600
SendInput {Numpad9}
SendInput {Numpad3}
SendInput {F4}
SendInput {Numpad7}
Sleep, 600
SendInput {F4}
SendInput {Numpad7}
Sleep, 600
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 600
SendInput {Numpad5}
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 600
SendInput {Numpad0}
SendInput {Numpad4}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 600
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 600
SendInput {Numpad2}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 600
SendInput {Numpad1}
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 600
SendInput {Numpad9}
SendInput {Numpad3}
SendInput {F4}
SendInput {Numpad7}
Sleep, 600
SendInput {F4}
SendInput {Numpad7}
Sleep, 600
SendInput {Numpad0}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 600
SendInput {Numpad9}
SendInput {Numpad5}
SendInput {Numpad3}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 600
SendInput {Numpad4}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 150
SendInput {Numpad4}
Sleep, 150
SendInput {Numpad4}
Sleep, 150
SendInput {Numpad4}
Sleep, 150
SendInput {Numpad4}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad4}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad2}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 200
SendInput {Numpad2}
Sleep, 200
SendInput {Numpad2}
Sleep, 200
SendInput {Numpad2}
SendInput {Numpad4}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad2}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad3}
SendInput {F4}
SendInput {Numpad7}
Sleep, 150
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad3}
SendInput {F4}
SendInput {Numpad7}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad3}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad6}
SendInput {Numpad3}
SendInput {Numpad1}
Sleep, 600
SendInput {Numpad0}
SendInput {Numpad5}
SendInput {Numpad2}
SendInput {Numpad1}
SendInput {Numpad3}
Sleep, 600
SendInput {Numpad9}
SendInput {Numpad4}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 150
SendInput {Numpad4}
Sleep, 150
SendInput {Numpad4}
Sleep, 150
SendInput {Numpad4}
Sleep, 150
SendInput {Numpad4}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad4}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad2}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 200
SendInput {Numpad2}
Sleep, 200
SendInput {Numpad2}
Sleep, 200
SendInput {Numpad2}
SendInput {Numpad4}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad2}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad3}
SendInput {F4}
SendInput {Numpad7}
Sleep, 150
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad3}
SendInput {F4}
SendInput {Numpad7}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad3}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad6}
SendInput {Numpad3}
SendInput {Numpad1}
Sleep, 600
SendInput {Numpad9}
SendInput {Numpad5}
SendInput {Numpad2}
SendInput {Numpad7}
Sleep, 600
SendInput {Numpad4}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 150
SendInput {Numpad4}
Sleep, 150
SendInput {Numpad4}
Sleep, 150
SendInput {Numpad4}
Sleep, 150
SendInput {Numpad4}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad4}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad2}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 200
SendInput {Numpad2}
Sleep, 200
SendInput {Numpad2}
Sleep, 200
SendInput {Numpad2}
SendInput {Numpad4}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad2}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad3}
SendInput {F4}
SendInput {Numpad7}
Sleep, 150
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad3}
SendInput {F4}
SendInput {Numpad7}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad3}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad6}
SendInput {Numpad3}
SendInput {Numpad1}
Sleep, 600
SendInput {Numpad5}
SendInput {Numpad2}
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 600
SendInput {Numpad4}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 150
SendInput {Numpad4}
Sleep, 150
SendInput {Numpad4}
Sleep, 150
SendInput {Numpad4}
Sleep, 150
SendInput {Numpad4}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad4}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad2}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 200
SendInput {Numpad2}
Sleep, 200
SendInput {Numpad2}
Sleep, 200
SendInput {Numpad2}
SendInput {Numpad4}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad2}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad3}
SendInput {F4}
SendInput {Numpad7}
Sleep, 150
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad3}
SendInput {F4}
SendInput {Numpad7}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad3}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad6}
SendInput {Numpad3}
SendInput {Numpad1}
Sleep, 600
SendInput {Numpad5}
SendInput {Numpad2}
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 600
SendInput {Numpad0}
SendInput {Numpad4}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 150
SendInput {Numpad1}
Sleep, 150
SendInput {Numpad4}
Sleep, 150
SendInput {Numpad4}
Sleep, 150
SendInput {Numpad1}
SendInput {Numpad6}
Sleep, 150
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad4}
Sleep, 150
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad2}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 150
SendInput {Numpad6}
Sleep, 150
SendInput {Numpad2}
Sleep, 150
SendInput {Numpad2}
Sleep, 150
SendInput {Numpad6}
SendInput {Numpad1}
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad2}
Sleep, 150
SendInput {Numpad2}
Sleep, 150
SendInput {Numpad2}
Sleep, 150
SendInput {Numpad3}
SendInput {F4}
SendInput {Numpad7}
Sleep, 150
SendInput {Numpad7}
Sleep, 150
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad7}
SendInput {F4}
Sleep, 150
SendInput {Numpad2}
Sleep, 150
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 150
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad6}
Sleep, 150
SendInput {Numpad5}
Sleep, 150
SendInput {Numpad9}
SendInput {Numpad7}
SendInput {Numpad3}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 150
SendInput {Numpad2}
Sleep, 150
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad5}
Sleep, 150
SendInput {Numpad4}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 150
SendInput {Numpad1}
Sleep, 150
SendInput {Numpad4}
Sleep, 150
SendInput {Numpad4}
Sleep, 150
SendInput {Numpad1}
SendInput {Numpad6}
Sleep, 150
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad4}
Sleep, 150
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad2}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 150
SendInput {Numpad6}
Sleep, 150
SendInput {Numpad2}
Sleep, 150
SendInput {Numpad2}
Sleep, 150
SendInput {Numpad6}
SendInput {Numpad1}
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad2}
Sleep, 150
SendInput {Numpad2}
Sleep, 150
SendInput {Numpad2}
Sleep, 150
SendInput {Numpad3}
SendInput {F4}
SendInput {Numpad7}
Sleep, 150
SendInput {Numpad7}
Sleep, 150
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad7}
SendInput {F4}
Sleep, 150
SendInput {Numpad2}
Sleep, 150
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 150
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad6}
Sleep, 150
SendInput {Numpad5}
Sleep, 150
SendInput {Numpad7}
SendInput {Numpad6}
SendInput {Numpad1}
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad2}
Sleep, 150
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad5}
Sleep, 150
SendInput {Numpad4}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 150
SendInput {Numpad1}
Sleep, 150
SendInput {Numpad4}
Sleep, 150
SendInput {Numpad4}
Sleep, 150
SendInput {Numpad1}
SendInput {Numpad6}
Sleep, 150
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad4}
Sleep, 150
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad2}
SendInput {Numpad1}
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 150
SendInput {Numpad6}
Sleep, 150
SendInput {Numpad2}
Sleep, 150
SendInput {Numpad2}
Sleep, 150
SendInput {Numpad6}
SendInput {Numpad1}
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad2}
Sleep, 150
SendInput {Numpad2}
Sleep, 150
SendInput {Numpad2}
Sleep, 150
SendInput {Numpad3}
SendInput {F4}
SendInput {Numpad7}
Sleep, 150
SendInput {Numpad7}
Sleep, 150
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad7}
SendInput {F4}
Sleep, 150
SendInput {Numpad2}
Sleep, 150
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 150
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad6}
Sleep, 150
SendInput {Numpad5}
Sleep, 150
SendInput {Numpad7}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 150
SendInput {Numpad2}
Sleep, 150
SendInput {Numpad1}
Sleep, 150
SendInput {Numpad7}
Sleep, 150
SendInput {Numpad4}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 150
SendInput {Numpad1}
Sleep, 150
SendInput {Numpad4}
Sleep, 150
SendInput {Numpad4}
Sleep, 150
SendInput {Numpad1}
SendInput {Numpad6}
Sleep, 150
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad4}
Sleep, 150
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad2}
SendInput {Numpad1}
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 150
SendInput {Numpad6}
Sleep, 150
SendInput {Numpad2}
Sleep, 150
SendInput {Numpad2}
Sleep, 150
SendInput {Numpad6}
SendInput {Numpad1}
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad2}
Sleep, 150
SendInput {Numpad2}
Sleep, 150
SendInput {Numpad2}
Sleep, 150
SendInput {Numpad3}
SendInput {F4}
SendInput {Numpad7}
Sleep, 150
SendInput {Numpad7}
Sleep, 150
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad7}
SendInput {F4}
Sleep, 150
SendInput {Numpad2}
Sleep, 150
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 150
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad6}
Sleep, 150
SendInput {Numpad5}
Sleep, 150
SendInput {Numpad7}
SendInput {Numpad6}
SendInput {Numpad1}
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad2}
Sleep, 150
SendInput {Numpad1}
Sleep, 150
SendInput {Numpad7}
Sleep, 150
SendInput {Numpad4}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 150
SendInput {Numpad1}
Sleep, 150
SendInput {Numpad4}
Sleep, 150
SendInput {Numpad4}
Sleep, 150
SendInput {Numpad1}
SendInput {Numpad6}
Sleep, 150
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad4}
Sleep, 150
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad2}
SendInput {Numpad6}
SendInput {Numpad1}
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad6}
Sleep, 150
SendInput {Numpad2}
Sleep, 150
SendInput {Numpad2}
Sleep, 150
SendInput {Numpad6}
SendInput {Numpad1}
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad2}
Sleep, 150
SendInput {Numpad2}
Sleep, 150
SendInput {Numpad2}
Sleep, 150
SendInput {Numpad3}
SendInput {F4}
SendInput {Numpad7}
Sleep, 150
SendInput {Numpad7}
Sleep, 150
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad7}
SendInput {F4}
Sleep, 150
SendInput {Numpad2}
Sleep, 150
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 150
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad6}
Sleep, 150
SendInput {Numpad5}
Sleep, 150
SendInput {Numpad7}
SendInput {Numpad3}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 150
SendInput {Numpad2}
Sleep, 150
SendInput {Numpad1}
Sleep, 150
SendInput {Numpad7}
Sleep, 150
SendInput {Numpad4}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 150
SendInput {Numpad1}
Sleep, 150
SendInput {Numpad4}
Sleep, 150
SendInput {Numpad4}
Sleep, 150
SendInput {Numpad1}
SendInput {Numpad6}
Sleep, 150
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad4}
Sleep, 150
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad2}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 150
SendInput {Numpad6}
Sleep, 150
SendInput {Numpad2}
Sleep, 150
SendInput {Numpad2}
Sleep, 150
SendInput {Numpad6}
SendInput {Numpad1}
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad2}
Sleep, 150
SendInput {Numpad2}
Sleep, 150
SendInput {Numpad2}
Sleep, 150
SendInput {Numpad3}
SendInput {F4}
SendInput {Numpad7}
Sleep, 150
SendInput {Numpad7}
Sleep, 150
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad7}
SendInput {F4}
Sleep, 150
SendInput {Numpad2}
Sleep, 150
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 150
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad6}
Sleep, 150
SendInput {Numpad5}
Sleep, 150
SendInput {Numpad7}
SendInput {Numpad6}
SendInput {Numpad1}
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad2}
Sleep, 150
SendInput {Numpad1}
Sleep, 150
SendInput {Numpad7}
Sleep, 150
SendInput {Numpad4}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 150
SendInput {Numpad1}
Sleep, 150
SendInput {Numpad4}
Sleep, 150
SendInput {Numpad4}
Sleep, 150
SendInput {Numpad1}
Sleep, 150
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad4}
Sleep, 150
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad2}
SendInput {Numpad6}
Sleep, 150
SendInput {Numpad6}
Sleep, 150
SendInput {Numpad2}
Sleep, 150
SendInput {Numpad2}
Sleep, 150
SendInput {Numpad6}
SendInput {Numpad2}
SendInput {Numpad3}
SendInput {Numpad7}
Sleep, 150
SendInput {Numpad2}
Sleep, 150
SendInput {Numpad2}
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 150
SendInput {Numpad2}
Sleep, 150
SendInput {Numpad3}
SendInput {Numpad7}
SendInput {F4}
Sleep, 150
SendInput {Numpad7}
Sleep, 150
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad7}
Sleep, 150
SendInput {Numpad2}
Sleep, 150
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 150
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad6}
Sleep, 150
SendInput {Numpad5}
Sleep, 150
SendInput {Numpad7}
SendInput {Numpad2}
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad2}
Sleep, 150
SendInput {Numpad1}
SendInput {Numpad2}
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad7}
Sleep, 150
SendInput {Numpad4}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 150
SendInput {Numpad1}
Sleep, 150
SendInput {Numpad4}
Sleep, 150
SendInput {Numpad4}
Sleep, 150
SendInput {Numpad1}
Sleep, 150
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad4}
Sleep, 150
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad2}
SendInput {Numpad6}
Sleep, 150
SendInput {Numpad6}
Sleep, 150
SendInput {Numpad2}
Sleep, 150
SendInput {Numpad2}
Sleep, 150
SendInput {Numpad6}
SendInput {Numpad1}
SendInput {Numpad3}
SendInput {Numpad7}
Sleep, 150
SendInput {Numpad2}
Sleep, 150
SendInput {Numpad2}
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 150
SendInput {Numpad2}
Sleep, 150
SendInput {Numpad3}
SendInput {Numpad7}
SendInput {F4}
Sleep, 150
SendInput {Numpad7}
Sleep, 150
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad7}
Sleep, 150
SendInput {Numpad2}
Sleep, 150
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 150
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad6}
Sleep, 150
SendInput {Numpad5}
Sleep, 150
SendInput {Numpad7}
SendInput {Numpad2}
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad2}
Sleep, 150
SendInput {Numpad1}
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad7}
Sleep, 150
SendInput {Numpad4}
SendInput {Numpad6}
SendInput {Numpad1}
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad1}
Sleep, 150
SendInput {Numpad4}
Sleep, 150
SendInput {Numpad4}
Sleep, 150
SendInput {Numpad1}
SendInput {Numpad6}
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad4}
Sleep, 150
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad2}
SendInput {Numpad6}
Sleep, 150
SendInput {Numpad6}
Sleep, 150
SendInput {Numpad2}
Sleep, 150
SendInput {Numpad2}
Sleep, 150
SendInput {Numpad6}
SendInput {Numpad2}
SendInput {Numpad3}
SendInput {Numpad7}
Sleep, 150
SendInput {Numpad2}
Sleep, 150
SendInput {Numpad2}
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 150
SendInput {Numpad2}
Sleep, 150
SendInput {Numpad3}
SendInput {Numpad7}
SendInput {F4}
Sleep, 150
SendInput {Numpad7}
Sleep, 150
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad7}
SendInput {Numpad2}
SendInput {Numpad3}
SendInput {F4}
Sleep, 150
SendInput {Numpad2}
Sleep, 150
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 150
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad6}
Sleep, 150
SendInput {Numpad5}
Sleep, 150
SendInput {Numpad7}
SendInput {Numpad2}
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad2}
Sleep, 150
SendInput {Numpad1}
SendInput {Numpad2}
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad7}
Sleep, 150
SendInput {Numpad4}
SendInput {Numpad6}
SendInput {Numpad1}
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad1}
Sleep, 150
SendInput {Numpad4}
Sleep, 150
SendInput {Numpad4}
Sleep, 150
SendInput {Numpad1}
SendInput {Numpad6}
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad4}
Sleep, 150
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad2}
SendInput {Numpad6}
Sleep, 150
SendInput {Numpad6}
Sleep, 150
SendInput {Numpad2}
Sleep, 150
SendInput {Numpad2}
Sleep, 150
SendInput {Numpad6}
SendInput {Numpad2}
SendInput {Numpad3}
SendInput {Numpad7}
Sleep, 150
SendInput {Numpad2}
Sleep, 150
SendInput {Numpad2}
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 150
SendInput {Numpad2}
Sleep, 150
SendInput {Numpad3}
SendInput {Numpad7}
SendInput {F4}
Sleep, 150
SendInput {Numpad7}
Sleep, 150
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad7}
Sleep, 150
SendInput {Numpad2}
Sleep, 150
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad7}
Sleep, 150
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad1}
Sleep, 150
SendInput {Numpad7}
Sleep, 150
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad4}
SendInput {Numpad1}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 150
SendInput {Numpad4}
SendInput {Numpad1}
Sleep, 150
SendInput {Numpad2}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad4}
SendInput {Numpad1}
Sleep, 150
SendInput {Numpad7}
Sleep, 150
SendInput {Numpad2}
SendInput {Numpad6}
Sleep, 150
SendInput {Numpad6}
Sleep, 300
SendInput {Numpad2}
SendInput {Numpad6}
Sleep, 300
SendInput {Numpad6}
Sleep, 150
SendInput {Numpad2}
SendInput {Numpad6}
Sleep, 300
SendInput {Numpad3}
SendInput {Numpad7}
SendInput {F4}
Sleep, 300
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad3}
SendInput {Numpad7}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 150
SendInput {Numpad3}
SendInput {Numpad7}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad6}
SendInput {Numpad3}
SendInput {Numpad7}
Sleep, 300
SendInput {Numpad6}
Sleep, 150
SendInput {Numpad5}
SendInput {Numpad2}
SendInput {Numpad6}
Sleep, 450
SendInput {Numpad5}
SendInput {Numpad2}
Sleep, 300
SendInput {Numpad4}
SendInput {Numpad1}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 150
SendInput {Numpad4}
SendInput {Numpad1}
Sleep, 150
SendInput {Numpad2}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad4}
SendInput {Numpad1}
Sleep, 150
SendInput {Numpad7}
Sleep, 150
SendInput {Numpad2}
SendInput {Numpad6}
Sleep, 150
SendInput {Numpad6}
Sleep, 300
SendInput {Numpad2}
SendInput {Numpad6}
Sleep, 300
SendInput {Numpad6}
Sleep, 150
SendInput {Numpad2}
SendInput {Numpad6}
Sleep, 150
SendInput {Numpad6}
Sleep, 150
SendInput {Numpad3}
SendInput {Numpad7}
SendInput {F4}
Sleep, 300
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad3}
SendInput {Numpad7}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 150
SendInput {Numpad3}
SendInput {Numpad7}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad6}
SendInput {Numpad3}
SendInput {Numpad7}
Sleep, 150
SendInput {Numpad6}
Sleep, 150
SendInput {Numpad5}
Sleep, 150
SendInput {Numpad5}
SendInput {Numpad2}
SendInput {Numpad6}
Sleep, 450
SendInput {Numpad5}
SendInput {Numpad2}
Sleep, 300
SendInput {Numpad4}
SendInput {Numpad1}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 150
SendInput {Numpad4}
SendInput {Numpad1}
Sleep, 150
SendInput {Numpad2}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad4}
SendInput {Numpad1}
Sleep, 150
SendInput {Numpad7}
Sleep, 150
SendInput {Numpad2}
SendInput {Numpad6}
Sleep, 150
SendInput {Numpad6}
Sleep, 300
SendInput {Numpad2}
SendInput {Numpad6}
Sleep, 300
SendInput {Numpad6}
Sleep, 150
SendInput {Numpad2}
SendInput {Numpad6}
Sleep, 150
SendInput {Numpad6}
Sleep, 150
SendInput {Numpad3}
SendInput {Numpad7}
SendInput {F4}
Sleep, 300
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad3}
SendInput {Numpad7}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 150
SendInput {Numpad3}
SendInput {Numpad7}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad6}
SendInput {Numpad3}
SendInput {Numpad7}
Sleep, 150
SendInput {Numpad6}
Sleep, 150
SendInput {Numpad5}
Sleep, 150
SendInput {Numpad5}
SendInput {Numpad2}
SendInput {Numpad6}
Sleep, 450
SendInput {Numpad5}
SendInput {Numpad2}
Sleep, 300
SendInput {Numpad4}
SendInput {Numpad1}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad1}
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad4}
SendInput {Numpad1}
Sleep, 150
SendInput {Numpad2}
SendInput {Numpad3}
Sleep, 300
SendInput {Numpad4}
SendInput {Numpad1}
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad7}
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad2}
SendInput {Numpad6}
Sleep, 150
SendInput {Numpad6}
SendInput {Numpad3}
Sleep, 300
SendInput {Numpad2}
SendInput {Numpad6}
SendInput {Numpad3}
Sleep, 300
SendInput {Numpad6}
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad2}
SendInput {Numpad6}
Sleep, 150
SendInput {Numpad9}
SendInput {Numpad6}
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad3}
SendInput {Numpad7}
SendInput {F4}
SendInput {Numpad2}
Sleep, 300
SendInput {Numpad3}
SendInput {Numpad2}
Sleep, 150
SendInput {Numpad3}
SendInput {Numpad7}
SendInput {Numpad2}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad1}
SendInput {Numpad2}
Sleep, 150
SendInput {Numpad3}
SendInput {Numpad7}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad6}
SendInput {Numpad3}
SendInput {Numpad7}
Sleep, 150
SendInput {Numpad6}
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad5}
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad5}
SendInput {Numpad2}
SendInput {Numpad6}
SendInput {Numpad3}
Sleep, 450
SendInput {Numpad5}
SendInput {Numpad2}
Sleep, 300
SendInput {Numpad4}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 150
SendInput {Numpad4}
Sleep, 150
SendInput {Numpad4}
Sleep, 150
SendInput {Numpad4}
Sleep, 150
SendInput {Numpad4}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad4}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad2}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 200
SendInput {Numpad2}
Sleep, 200
SendInput {Numpad2}
Sleep, 200
SendInput {Numpad2}
SendInput {Numpad4}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad2}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad3}
SendInput {F4}
SendInput {Numpad7}
Sleep, 150
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad3}
SendInput {F4}
SendInput {Numpad7}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad3}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad6}
SendInput {Numpad3}
SendInput {Numpad1}
Sleep, 200
SendInput {Numpad6}
SendInput {Numpad3}
Sleep, 200
SendInput {Numpad6}
SendInput {Numpad3}
Sleep, 200
SendInput {Numpad5}
SendInput {Numpad2}
SendInput {Numpad1}
SendInput {Numpad3}
Sleep, 300
SendInput {Numpad5}
Sleep, 300
SendInput {Numpad4}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 150
SendInput {Numpad4}
Sleep, 150
SendInput {Numpad4}
Sleep, 150
SendInput {Numpad4}
Sleep, 150
SendInput {Numpad4}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad4}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad2}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 200
SendInput {Numpad2}
Sleep, 200
SendInput {Numpad2}
Sleep, 200
SendInput {Numpad2}
SendInput {Numpad4}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad2}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad3}
SendInput {F4}
SendInput {Numpad7}
Sleep, 150
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad3}
SendInput {F4}
SendInput {Numpad7}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad3}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad6}
SendInput {Numpad3}
SendInput {Numpad1}
Sleep, 200
SendInput {Numpad9}
SendInput {Numpad6}
SendInput {Numpad3}
Sleep, 200
SendInput {Numpad6}
SendInput {Numpad3}
Sleep, 200
SendInput {Numpad5}
SendInput {Numpad2}
SendInput {Numpad7}
Sleep, 300
SendInput {Numpad5}
Sleep, 300
SendInput {Numpad4}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 150
SendInput {Numpad4}
Sleep, 150
SendInput {Numpad4}
Sleep, 150
SendInput {Numpad4}
Sleep, 150
SendInput {Numpad4}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad4}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad2}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 200
SendInput {Numpad2}
Sleep, 200
SendInput {Numpad2}
Sleep, 200
SendInput {Numpad2}
SendInput {Numpad4}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad2}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad3}
SendInput {F4}
SendInput {Numpad7}
Sleep, 150
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad3}
SendInput {F4}
SendInput {Numpad7}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad3}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad6}
SendInput {Numpad3}
SendInput {Numpad1}
Sleep, 200
SendInput {Numpad6}
SendInput {Numpad3}
Sleep, 200
SendInput {Numpad6}
SendInput {Numpad3}
Sleep, 200
SendInput {Numpad5}
SendInput {Numpad2}
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 300
SendInput {Numpad5}
Sleep, 300
SendInput {Numpad4}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 150
SendInput {Numpad4}
Sleep, 150
SendInput {Numpad4}
Sleep, 150
SendInput {Numpad4}
Sleep, 150
SendInput {Numpad4}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad4}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad2}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 200
SendInput {Numpad2}
Sleep, 200
SendInput {Numpad2}
Sleep, 200
SendInput {Numpad2}
SendInput {Numpad4}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad2}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad3}
SendInput {F4}
SendInput {Numpad7}
Sleep, 150
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad3}
SendInput {F4}
SendInput {Numpad7}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad3}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad6}
SendInput {Numpad3}
SendInput {Numpad1}
Sleep, 200
SendInput {Numpad6}
SendInput {Numpad3}
Sleep, 200
SendInput {Numpad6}
SendInput {Numpad3}
Sleep, 200
SendInput {Numpad5}
SendInput {Numpad2}
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad5}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad4}
SendInput {Numpad1}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 150
SendInput {Numpad4}
SendInput {Numpad1}
Sleep, 150
SendInput {Numpad2}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad4}
SendInput {Numpad1}
Sleep, 150
SendInput {Numpad7}
Sleep, 150
SendInput {Numpad2}
SendInput {Numpad6}
Sleep, 150
SendInput {Numpad6}
Sleep, 300
SendInput {Numpad2}
SendInput {Numpad6}
Sleep, 300
SendInput {Numpad6}
Sleep, 150
SendInput {Numpad2}
SendInput {Numpad6}
Sleep, 300
SendInput {Numpad3}
SendInput {Numpad7}
SendInput {F4}
Sleep, 300
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad3}
SendInput {Numpad7}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 150
SendInput {Numpad3}
SendInput {Numpad7}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad6}
SendInput {Numpad3}
SendInput {Numpad7}
Sleep, 300
SendInput {Numpad6}
Sleep, 150
SendInput {Numpad5}
SendInput {Numpad2}
SendInput {Numpad6}
Sleep, 450
SendInput {Numpad5}
SendInput {Numpad2}
Sleep, 300
SendInput {Numpad4}
SendInput {Numpad1}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 150
SendInput {Numpad4}
SendInput {Numpad1}
Sleep, 150
SendInput {Numpad2}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad4}
SendInput {Numpad1}
Sleep, 150
SendInput {Numpad7}
Sleep, 150
SendInput {Numpad2}
SendInput {Numpad6}
Sleep, 150
SendInput {Numpad6}
Sleep, 300
SendInput {Numpad2}
SendInput {Numpad6}
Sleep, 300
SendInput {Numpad6}
Sleep, 150
SendInput {Numpad2}
SendInput {Numpad6}
Sleep, 150
SendInput {Numpad6}
Sleep, 150
SendInput {Numpad3}
SendInput {Numpad7}
SendInput {F4}
Sleep, 300
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad3}
SendInput {Numpad7}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 150
SendInput {Numpad3}
SendInput {Numpad7}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad6}
SendInput {Numpad3}
SendInput {Numpad7}
Sleep, 150
SendInput {Numpad6}
Sleep, 150
SendInput {Numpad5}
Sleep, 150
SendInput {Numpad5}
SendInput {Numpad2}
SendInput {Numpad6}
Sleep, 450
SendInput {Numpad5}
SendInput {Numpad2}
Sleep, 300
SendInput {Numpad4}
SendInput {Numpad1}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 150
SendInput {Numpad4}
SendInput {Numpad1}
Sleep, 150
SendInput {Numpad2}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad4}
SendInput {Numpad1}
Sleep, 150
SendInput {Numpad7}
Sleep, 150
SendInput {Numpad2}
SendInput {Numpad6}
Sleep, 150
SendInput {Numpad6}
Sleep, 300
SendInput {Numpad2}
SendInput {Numpad6}
Sleep, 300
SendInput {Numpad6}
Sleep, 150
SendInput {Numpad2}
SendInput {Numpad6}
Sleep, 150
SendInput {Numpad6}
Sleep, 150
SendInput {Numpad3}
SendInput {Numpad7}
SendInput {F4}
Sleep, 300
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad3}
SendInput {Numpad7}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 150
SendInput {Numpad3}
SendInput {Numpad7}
Sleep, 150
SendInput {F2}
Sleep, 150
SendInput {Numpad6}
SendInput {Numpad3}
SendInput {F2}
Sleep, 150
SendInput {Numpad2}
Sleep, 150
SendInput {Numpad1}
Sleep, 150
SendInput {Numpad5}
SendInput {Numpad2}
SendInput {Numpad6}
Sleep, 450
SendInput {Numpad5}
SendInput {Numpad2}
Sleep, 300
SendInput {Numpad4}
SendInput {Numpad1}
Sleep, 300
SendInput {Numpad1}
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad4}
SendInput {Numpad1}
Sleep, 150
SendInput {Numpad2}
SendInput {Numpad3}
Sleep, 300
SendInput {Numpad4}
SendInput {Numpad1}
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad7}
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad2}
SendInput {Numpad6}
Sleep, 150
SendInput {Numpad6}
SendInput {Numpad3}
Sleep, 300
SendInput {Numpad2}
SendInput {Numpad6}
SendInput {Numpad3}
Sleep, 300
SendInput {Numpad6}
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad2}
SendInput {Numpad6}
Sleep, 150
SendInput {Numpad9}
SendInput {Numpad6}
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad3}
SendInput {Numpad7}
SendInput {F4}
SendInput {Numpad2}
Sleep, 300
SendInput {Numpad3}
SendInput {Numpad2}
Sleep, 150
SendInput {Numpad3}
SendInput {Numpad7}
SendInput {Numpad2}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad1}
SendInput {Numpad2}
Sleep, 150
SendInput {Numpad3}
SendInput {Numpad7}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad6}
SendInput {Numpad3}
SendInput {Numpad7}
Sleep, 150
SendInput {Numpad6}
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad5}
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad5}
SendInput {Numpad2}
SendInput {Numpad6}
SendInput {Numpad3}
Sleep, 450
SendInput {Numpad5}
SendInput {Numpad2}
Sleep, 300
SendInput {Numpad4}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 150
SendInput {Numpad1}
Sleep, 150
SendInput {Numpad4}
Sleep, 150
SendInput {Numpad4}
Sleep, 150
SendInput {Numpad1}
Sleep, 150
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad4}
Sleep, 150
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad2}
SendInput {Numpad6}
Sleep, 150
SendInput {Numpad6}
Sleep, 150
SendInput {Numpad2}
Sleep, 150
SendInput {Numpad2}
Sleep, 150
SendInput {Numpad6}
SendInput {Numpad2}
SendInput {Numpad3}
SendInput {Numpad7}
Sleep, 150
SendInput {Numpad2}
Sleep, 150
SendInput {Numpad2}
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 150
SendInput {Numpad2}
Sleep, 150
SendInput {Numpad3}
SendInput {Numpad7}
SendInput {F4}
Sleep, 150
SendInput {Numpad7}
Sleep, 150
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad7}
Sleep, 150
SendInput {Numpad2}
Sleep, 150
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 150
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad6}
Sleep, 150
SendInput {Numpad5}
Sleep, 150
SendInput {Numpad7}
SendInput {Numpad2}
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad2}
Sleep, 150
SendInput {Numpad1}
SendInput {Numpad2}
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad7}
Sleep, 150
SendInput {Numpad4}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 150
SendInput {Numpad1}
Sleep, 150
SendInput {Numpad4}
Sleep, 150
SendInput {Numpad4}
Sleep, 150
SendInput {Numpad1}
Sleep, 150
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad4}
Sleep, 150
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad2}
SendInput {Numpad6}
Sleep, 150
SendInput {Numpad6}
Sleep, 150
SendInput {Numpad2}
Sleep, 150
SendInput {Numpad2}
Sleep, 150
SendInput {Numpad6}
SendInput {Numpad1}
SendInput {Numpad3}
SendInput {Numpad7}
Sleep, 150
SendInput {Numpad2}
Sleep, 150
SendInput {Numpad2}
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 150
SendInput {Numpad2}
Sleep, 150
SendInput {Numpad3}
SendInput {Numpad7}
SendInput {F4}
Sleep, 150
SendInput {Numpad7}
Sleep, 150
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad7}
Sleep, 150
SendInput {Numpad2}
Sleep, 150
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 150
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad6}
Sleep, 150
SendInput {Numpad5}
Sleep, 150
SendInput {Numpad7}
SendInput {Numpad2}
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad2}
Sleep, 150
SendInput {Numpad1}
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad7}
Sleep, 150
SendInput {Numpad4}
SendInput {Numpad6}
SendInput {Numpad1}
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad1}
Sleep, 150
SendInput {Numpad4}
Sleep, 150
SendInput {Numpad4}
Sleep, 150
SendInput {Numpad1}
SendInput {Numpad6}
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad4}
Sleep, 150
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad2}
SendInput {Numpad6}
Sleep, 150
SendInput {Numpad6}
Sleep, 150
SendInput {Numpad2}
Sleep, 150
SendInput {Numpad2}
Sleep, 150
SendInput {Numpad6}
SendInput {Numpad2}
SendInput {Numpad3}
SendInput {Numpad7}
Sleep, 150
SendInput {Numpad2}
Sleep, 150
SendInput {Numpad2}
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 150
SendInput {Numpad2}
Sleep, 150
SendInput {Numpad3}
SendInput {Numpad7}
SendInput {F4}
Sleep, 150
SendInput {Numpad7}
Sleep, 150
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad7}
SendInput {Numpad2}
SendInput {Numpad3}
SendInput {F4}
Sleep, 150
SendInput {Numpad2}
Sleep, 150
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 150
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad6}
Sleep, 150
SendInput {Numpad5}
Sleep, 150
SendInput {Numpad7}
SendInput {Numpad2}
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad2}
Sleep, 150
SendInput {Numpad1}
SendInput {Numpad2}
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad7}
Sleep, 150
SendInput {Numpad4}
SendInput {Numpad6}
SendInput {Numpad1}
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad1}
Sleep, 150
SendInput {Numpad4}
Sleep, 150
SendInput {Numpad4}
Sleep, 150
SendInput {Numpad1}
SendInput {Numpad6}
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad4}
Sleep, 150
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad2}
SendInput {Numpad6}
Sleep, 150
SendInput {Numpad6}
Sleep, 150
SendInput {Numpad2}
Sleep, 150
SendInput {Numpad2}
Sleep, 150
SendInput {Numpad6}
SendInput {Numpad2}
SendInput {Numpad3}
SendInput {Numpad7}
Sleep, 150
SendInput {Numpad2}
Sleep, 150
SendInput {Numpad2}
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 150
SendInput {Numpad2}
Sleep, 150
SendInput {Numpad3}
SendInput {Numpad7}
SendInput {F4}
Sleep, 150
SendInput {Numpad7}
Sleep, 150
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad7}
Sleep, 150
SendInput {Numpad2}
Sleep, 150
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad7}
Sleep, 150
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad1}
Sleep, 150
SendInput {Numpad7}
Sleep, 150
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad4}
SendInput {Numpad1}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 150
SendInput {Numpad4}
SendInput {Numpad1}
Sleep, 150
SendInput {Numpad2}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad4}
SendInput {Numpad1}
Sleep, 150
SendInput {Numpad7}
Sleep, 150
SendInput {Numpad2}
SendInput {Numpad6}
Sleep, 150
SendInput {Numpad6}
Sleep, 300
SendInput {Numpad2}
SendInput {Numpad6}
Sleep, 300
SendInput {Numpad6}
Sleep, 150
SendInput {Numpad2}
SendInput {Numpad6}
Sleep, 300
SendInput {Numpad3}
SendInput {Numpad7}
SendInput {F4}
Sleep, 300
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad3}
SendInput {Numpad7}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 150
SendInput {Numpad3}
SendInput {Numpad7}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad6}
SendInput {Numpad3}
SendInput {Numpad7}
Sleep, 300
SendInput {Numpad6}
Sleep, 150
SendInput {Numpad5}
SendInput {Numpad2}
SendInput {Numpad6}
Sleep, 450
SendInput {Numpad5}
SendInput {Numpad2}
Sleep, 300
SendInput {Numpad4}
SendInput {Numpad1}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 150
SendInput {Numpad4}
SendInput {Numpad1}
Sleep, 150
SendInput {Numpad2}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad4}
SendInput {Numpad1}
Sleep, 150
SendInput {Numpad7}
Sleep, 150
SendInput {Numpad2}
SendInput {Numpad6}
Sleep, 150
SendInput {Numpad6}
Sleep, 300
SendInput {Numpad2}
SendInput {Numpad6}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad2}
Sleep, 150
SendInput {Numpad2}
SendInput {Numpad6}
Sleep, 150
SendInput {F2}
Sleep, 150
SendInput {Numpad3}
SendInput {Numpad7}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad3}
SendInput {Numpad7}
SendInput {Numpad2}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad3}
SendInput {Numpad7}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad6}
SendInput {Numpad3}
SendInput {F2}
Sleep, 150
SendInput {Numpad2}
Sleep, 150
SendInput {Numpad1}
Sleep, 150
SendInput {Numpad5}
SendInput {Numpad2}
SendInput {Numpad6}
Sleep, 450
SendInput {Numpad5}
SendInput {Numpad2}
Sleep, 300
SendInput {Numpad4}
SendInput {Numpad1}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 150
SendInput {Numpad4}
SendInput {Numpad1}
Sleep, 150
SendInput {Numpad2}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad4}
SendInput {Numpad1}
Sleep, 150
SendInput {Numpad7}
Sleep, 150
SendInput {Numpad2}
SendInput {Numpad6}
Sleep, 150
SendInput {Numpad6}
Sleep, 300
SendInput {Numpad2}
SendInput {Numpad6}
Sleep, 300
SendInput {Numpad6}
Sleep, 150
SendInput {Numpad2}
SendInput {Numpad6}
Sleep, 150
SendInput {Numpad6}
Sleep, 150
SendInput {Numpad3}
SendInput {Numpad7}
SendInput {F4}
Sleep, 300
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad3}
SendInput {Numpad7}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 150
SendInput {Numpad3}
SendInput {Numpad7}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad6}
SendInput {Numpad3}
SendInput {Numpad7}
Sleep, 150
SendInput {Numpad6}
Sleep, 150
SendInput {Numpad5}
Sleep, 150
SendInput {Numpad5}
SendInput {Numpad2}
SendInput {Numpad6}
Sleep, 450
SendInput {Numpad5}
SendInput {Numpad2}
Sleep, 300
SendInput {Numpad4}
SendInput {Numpad1}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad1}
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad4}
SendInput {Numpad1}
Sleep, 150
SendInput {Numpad2}
SendInput {Numpad3}
Sleep, 300
SendInput {Numpad4}
SendInput {Numpad1}
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad7}
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad2}
SendInput {Numpad6}
Sleep, 150
SendInput {Numpad6}
SendInput {Numpad3}
Sleep, 300
SendInput {Numpad2}
SendInput {Numpad6}
SendInput {Numpad3}
Sleep, 300
SendInput {Numpad6}
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad2}
SendInput {Numpad6}
Sleep, 150
SendInput {Numpad9}
SendInput {Numpad6}
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad3}
SendInput {Numpad7}
SendInput {F4}
SendInput {Numpad2}
Sleep, 300
SendInput {Numpad3}
SendInput {Numpad2}
Sleep, 150
SendInput {Numpad3}
SendInput {Numpad7}
SendInput {Numpad2}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad1}
SendInput {Numpad2}
Sleep, 150
SendInput {Numpad3}
SendInput {Numpad7}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad6}
SendInput {Numpad3}
SendInput {Numpad7}
Sleep, 150
SendInput {Numpad6}
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad5}
SendInput {Numpad3}
Sleep, 150
SendInput {Numpad5}
SendInput {Numpad2}
SendInput {Numpad6}
SendInput {Numpad3}
Sleep, 450
SendInput {Numpad5}
SendInput {Numpad2}
Sleep, 300
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 600
SendInput {Numpad6}
Sleep, 600
SendInput {Numpad2}
SendInput {Numpad6}
Sleep, 600
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 600
SendInput {Numpad9}
SendInput {Numpad3}
SendInput {F4}
Sleep, 600
SendInput {F4}
Sleep, 600
SendInput {Numpad6}
Sleep, 600
SendInput {Numpad5}
SendInput {Numpad3}
Sleep, 600
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 600
SendInput {Numpad6}
Sleep, 600
SendInput {Numpad2}
SendInput {Numpad6}
Sleep, 600
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 600
SendInput {Numpad9}
SendInput {Numpad3}
SendInput {F4}
Sleep, 600
SendInput {F4}
Sleep, 600
SendInput {Numpad6}
Sleep, 600
SendInput {Numpad0}
SendInput {Numpad5}
SendInput {Numpad1}
Sleep, 600
SendInput {Numpad9}
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 600
SendInput {Numpad6}
Sleep, 600
SendInput {Numpad2}
SendInput {Numpad6}
Sleep, 600
SendInput {Numpad0}
SendInput {Numpad1}
SendInput {Numpad7}
Sleep, 300
SendInput {Numpad6}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad3}
SendInput {F4}
Sleep, 600
SendInput {F4}
Sleep, 600
SendInput {Numpad6}
Sleep, 600
SendInput {Numpad0}
SendInput {Numpad5}
SendInput {Numpad1}
SendInput {Numpad7}
Sleep, 300
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 600
SendInput {Numpad6}
Sleep, 600
SendInput {Numpad2}
SendInput {Numpad6}
Sleep, 600
SendInput {Numpad0}
SendInput {Numpad1}
SendInput {Numpad7}
Sleep, 300
SendInput {Numpad6}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad3}
SendInput {F4}
Sleep, 600
SendInput {F4}
Sleep, 600
SendInput {Numpad6}
Sleep, 600
SendInput {Numpad0}
SendInput {Numpad5}
SendInput {Numpad1}
SendInput {Numpad7}
Sleep, 300
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 600
SendInput {Numpad6}
Sleep, 600
SendInput {Numpad2}
SendInput {Numpad6}
Sleep, 600
SendInput {Numpad0}
SendInput {Numpad1}
SendInput {Numpad7}
Sleep, 300
SendInput {Numpad6}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad3}
SendInput {F4}
Sleep, 600
SendInput {F4}
Sleep, 600
SendInput {Numpad6}
Sleep, 600
SendInput {Numpad0}
SendInput {Numpad5}
SendInput {Numpad1}
SendInput {Numpad7}
Sleep, 300
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 600
SendInput {Numpad6}
Sleep, 600
SendInput {Numpad2}
SendInput {Numpad6}
Sleep, 600
SendInput {Numpad0}
SendInput {Numpad1}
SendInput {Numpad7}
Sleep, 300
SendInput {Numpad6}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad3}
Sleep, 100
SendInput {Numpad0}
SendInput {F4}
Sleep, 100
SendInput {Numpad7}
Sleep, 100
SendInput {F4}
Sleep, 100
SendInput {Numpad7}
Sleep, 100
SendInput {Numpad2}
Sleep, 100
SendInput {Numpad7}
Sleep, 100
SendInput {Numpad0}
SendInput {Numpad2}
Sleep, 100
SendInput {Numpad3}
Sleep, 100
SendInput {Numpad2}
Sleep, 100
SendInput {Numpad3}
Sleep, 100
SendInput {F4}
Sleep, 100
SendInput {Numpad3}
Sleep, 100
SendInput {F4}
Sleep, 100
SendInput {Numpad7}
Sleep, 100
SendInput {F4}
Sleep, 100
SendInput {Numpad7}
Sleep, 100
Sleep, 100
SendInput {Numpad7}
Sleep, 100
Sleep, 100
Sleep, 100
Sleep, 100
Sleep, 100
Sleep, 100
SendInput {Numpad9}
SendInput {Numpad3}
Sleep, 100
SendInput {F4}
Sleep, 100
SendInput {Numpad7}
Sleep, 100
SendInput {F4}
Sleep, 100
SendInput {Numpad7}
Sleep, 100
SendInput {Numpad2}
Sleep, 100
SendInput {Numpad7}
Sleep, 100
SendInput {Numpad0}
SendInput {Numpad2}
Sleep, 100
SendInput {Numpad3}
Sleep, 100
SendInput {Numpad2}
Sleep, 100
SendInput {Numpad3}
Sleep, 100
SendInput {F4}
Sleep, 100
SendInput {Numpad3}
Sleep, 100
SendInput {F4}
Sleep, 100
SendInput {Numpad7}
Sleep, 100
SendInput {F4}
Sleep, 100
SendInput {Numpad7}
Sleep, 100
Sleep, 100
SendInput {Numpad7}
Sleep, 100
Sleep, 100
Sleep, 100
Sleep, 100
Sleep, 100
Sleep, 100
Sleep, 750
SendInput {Numpad3}
Sleep, 750
SendInput {Numpad1}
Sleep, 94
Sleep, 656
SendInput {Numpad9}
SendInput {Numpad7}
Sleep, 94
SendInput {Numpad7}
Sleep, 656
SendInput {Numpad6}
Sleep, 62
SendInput {Numpad1}
Sleep, 62
SendInput {Numpad3}
Sleep, 62
SendInput {Numpad6}
Sleep, 1000
