; title: I Don't Like Mondays
; author: The Boomtown Rats
; instrument: Piano
; Converted by Serenade Desktop

Sleep, 75
Sleep, 75
Sleep, 75
Sleep, 75
Sleep, 75
SendInput {Numpad9}
SendInput {Numpad7}
Sleep, 75
SendInput {Numpad6}
Sleep, 75
SendInput {Numpad5}
Sleep, 75
SendInput {Numpad3}
Sleep, 75
SendInput {Numpad2}
Sleep, 75
Sleep, 81
Sleep, 83
SendInput {Numpad7}
Sleep, 83
SendInput {Numpad6}
Sleep, 83
SendInput {Numpad5}
Sleep, 83
SendInput {Numpad3}
Sleep, 83
SendInput {Numpad2}
Sleep, 83
SendInput {Numpad7}
Sleep, 83
SendInput {Numpad6}
Sleep, 89
Sleep, 94
Sleep, 94
Sleep, 94
SendInput {Numpad7}
Sleep, 94
SendInput {Numpad6}
Sleep, 94
SendInput {Numpad5}
Sleep, 94
SendInput {Numpad3}
Sleep, 94
SendInput {Numpad2}
Sleep, 94
SendInput {Numpad7}
Sleep, 56
SendInput {Numpad6}
Sleep, 56
SendInput {Numpad5}
Sleep, 56
SendInput {Numpad3}
Sleep, 56
SendInput {Numpad2}
Sleep, 56
SendInput {Numpad0}
SendInput {Numpad7}
Sleep, 56
SendInput {Numpad6}
Sleep, 56
SendInput {Numpad5}
Sleep, 56
SendInput {Numpad3}
Sleep, 56
SendInput {Numpad2}
Sleep, 56
SendInput {Numpad0}
SendInput {Numpad7}
Sleep, 56
SendInput {Numpad6}
Sleep, 56
SendInput {Numpad5}
Sleep, 75
SendInput {Numpad3}
Sleep, 2000
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad6}
Sleep, 750
SendInput {Numpad5}
SendInput {Numpad7}
Sleep, 750
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 1000
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 500
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad3}
Sleep, 250
SendInput {Numpad3}
Sleep, 250
SendInput {Numpad3}
Sleep, 500
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad7}
SendInput {Numpad3}
Sleep, 750
SendInput {Numpad6}
SendInput {Numpad2}
Sleep, 750
SendInput {Numpad0}
SendInput {Numpad5}
SendInput {Numpad7}
Sleep, 1000
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 500
SendInput {Numpad0}
SendInput {Numpad3}
Sleep, 250
SendInput {Numpad3}
Sleep, 250
SendInput {Numpad3}
Sleep, 500
SendInput {Numpad9}
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 500
SendInput {Numpad0}
SendInput {Numpad3}
Sleep, 250
SendInput {Numpad9}
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad3}
Sleep, 500
SendInput {Numpad7}
SendInput {Numpad3}
Sleep, 500
SendInput {Numpad3}
Sleep, 500
SendInput {Numpad6}
SendInput {Numpad2}
SendInput {Numpad3}
Sleep, 500
SendInput {Numpad3}
Sleep, 500
SendInput {Numpad9}
SendInput {F5}
SendInput {Numpad2}
SendInput {Numpad4}
Sleep, 500
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 500
Sleep, 500
SendInput {Numpad9}
SendInput {Numpad4}
SendInput {Numpad1}
Sleep, 250
SendInput {F5}
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad7}
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 250
SendInput {F5}
SendInput {Numpad2}
SendInput {Numpad6}
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad9}
SendInput {F5}
SendInput {Numpad2}
SendInput {Numpad6}
Sleep, 250
Sleep, 250
SendInput {F5}
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 500
Sleep, 500
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad6}
SendInput {Numpad2}
SendInput {Numpad3}
Sleep, 500
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad5}
SendInput {Numpad7}
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad3}
Sleep, 500
SendInput {Numpad9}
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 500
SendInput {Numpad0}
SendInput {Numpad3}
Sleep, 250
SendInput {Numpad9}
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 250
Sleep, 250
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad3}
Sleep, 500
SendInput {Numpad4}
Sleep, 500
SendInput {Numpad9}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 62
SendInput {Numpad1}
Sleep, 62
SendInput {Numpad4}
Sleep, 125
SendInput {Numpad4}
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad6}
SendInput {Numpad1}
SendInput {Numpad4}
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 500
SendInput {Numpad9}
SendInput {Numpad7}
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad7}
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 750
SendInput {Numpad6}
SendInput {Numpad1}
SendInput {Numpad4}
Sleep, 250
SendInput {Numpad6}
SendInput {Numpad1}
SendInput {Numpad4}
Sleep, 500
SendInput {Numpad0}
SendInput {Numpad4}
Sleep, 250
SendInput {Numpad3}
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad3}
Sleep, 250
SendInput {Numpad5}
SendInput {Numpad1}
Sleep, 500
SendInput {Numpad3}
SendInput {Numpad5}
SendInput {Numpad1}
Sleep, 500
SendInput {Numpad9}
SendInput {Numpad2}
SendInput {Numpad1}
Sleep, 500
SendInput {Numpad0}
SendInput {Numpad3}
SendInput {Numpad5}
SendInput {Numpad2}
Sleep, 500
SendInput {Numpad9}
SendInput {Numpad1}
SendInput {Numpad3}
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad3}
SendInput {Numpad5}
SendInput {Numpad7}
Sleep, 250
Sleep, 500
SendInput {Numpad0}
SendInput {Numpad3}
Sleep, 250
SendInput {Numpad9}
SendInput {Numpad7}
Sleep, 250
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 500
SendInput {Numpad0}
SendInput {Numpad4}
Sleep, 250
SendInput {Numpad9}
SendInput {Numpad6}
Sleep, 250
SendInput {Numpad6}
Sleep, 500
SendInput {Numpad3}
SendInput {Numpad4}
Sleep, 500
SendInput {Numpad5}
SendInput {Numpad7}
SendInput {Numpad2}
Sleep, 500
SendInput {Numpad0}
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 250
Sleep, 250
SendInput {Numpad7}
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad9}
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad3}
SendInput {Numpad1}
Sleep, 500
SendInput {Numpad3}
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad3}
Sleep, 250
SendInput {Numpad3}
SendInput {Numpad5}
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad9}
SendInput {Numpad2}
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad3}
SendInput {Numpad5}
SendInput {Numpad2}
Sleep, 500
SendInput {Numpad9}
SendInput {Numpad1}
SendInput {Numpad3}
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad3}
SendInput {Numpad5}
SendInput {Numpad7}
Sleep, 250
Sleep, 500
SendInput {Numpad7}
SendInput {Numpad3}
Sleep, 250
SendInput {Numpad7}
Sleep, 250
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 500
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 500
SendInput {Numpad6}
Sleep, 500
SendInput {Numpad9}
SendInput {Numpad3}
SendInput {Numpad1}
Sleep, 500
SendInput {Numpad0}
SendInput {Numpad5}
SendInput {Numpad7}
SendInput {Numpad2}
Sleep, 500
SendInput {Numpad0}
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad9}
SendInput {Numpad5}
SendInput {Numpad6}
Sleep, 250
Sleep, 500
SendInput {Numpad5}
SendInput {Numpad7}
Sleep, 500
SendInput {Numpad1}
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 250
SendInput {Numpad9}
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad1}
SendInput {Numpad4}
Sleep, 250
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad1}
Sleep, 500
SendInput {Numpad1}
SendInput {Numpad4}
Sleep, 250
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad5}
SendInput {Numpad7}
Sleep, 250
SendInput {Numpad9}
SendInput {Numpad3}
Sleep, 750
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad7}
Sleep, 250
SendInput {Numpad7}
Sleep, 250
SendInput {Numpad7}
Sleep, 250
SendInput {Numpad1}
SendInput {Numpad3}
SendInput {Numpad5}
Sleep, 500
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad5}
SendInput {Numpad1}
Sleep, 500
SendInput {Numpad3}
Sleep, 250
SendInput {Numpad1}
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 250
Sleep, 500
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 500
SendInput {Numpad4}
Sleep, 250
SendInput {Numpad9}
SendInput {Numpad1}
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 250
SendInput {Numpad9}
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad1}
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 500
SendInput {Numpad9}
SendInput {Numpad2}
SendInput {Numpad1}
Sleep, 500
SendInput {Numpad1}
SendInput {Numpad4}
Sleep, 250
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad1}
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 500
SendInput {Numpad9}
SendInput {Numpad2}
SendInput {Numpad4}
Sleep, 500
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad1}
SendInput {Numpad4}
Sleep, 500
SendInput {Numpad0}
SendInput {Numpad1}
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 250
SendInput {Numpad9}
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad1}
SendInput {Numpad4}
Sleep, 250
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad6}
Sleep, 250
SendInput {Numpad6}
Sleep, 250
SendInput {Numpad9}
SendInput {Numpad1}
SendInput {Numpad4}
Sleep, 500
SendInput {Numpad0}
SendInput {Numpad5}
SendInput {Numpad7}
SendInput {Numpad2}
Sleep, 1000
SendInput {Numpad5}
SendInput {Numpad7}
SendInput {Numpad3}
Sleep, 1000
SendInput {Numpad5}
SendInput {Numpad7}
SendInput {Numpad4}
Sleep, 500
SendInput {Numpad5}
SendInput {Numpad7}
SendInput {Numpad3}
Sleep, 500
SendInput {Numpad5}
SendInput {Numpad7}
SendInput {Numpad2}
Sleep, 500
SendInput {Numpad9}
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad3}
SendInput {Numpad5}
SendInput {Numpad1}
Sleep, 500
SendInput {Numpad3}
SendInput {Numpad1}
Sleep, 500
SendInput {Numpad3}
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad3}
SendInput {Numpad5}
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 500
SendInput {Numpad9}
SendInput {Numpad3}
SendInput {Numpad5}
SendInput {Numpad2}
Sleep, 500
Sleep, 250
SendInput {Numpad3}
SendInput {Numpad5}
SendInput {Numpad1}
Sleep, 250
Sleep, 500
SendInput {Numpad9}
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad4}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 500
SendInput {Numpad9}
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad1}
Sleep, 250
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad4}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 250
Sleep, 500
SendInput {Numpad5}
SendInput {Numpad7}
Sleep, 500
SendInput {Numpad0}
SendInput {Numpad5}
Sleep, 500
SendInput {Numpad9}
SendInput {Numpad6}
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad7}
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad9}
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad3}
SendInput {Numpad5}
SendInput {Numpad1}
Sleep, 500
SendInput {Numpad3}
SendInput {Numpad1}
Sleep, 500
SendInput {Numpad3}
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad3}
SendInput {Numpad5}
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 500
SendInput {Numpad9}
SendInput {Numpad3}
SendInput {Numpad5}
SendInput {Numpad2}
Sleep, 500
Sleep, 250
SendInput {Numpad3}
SendInput {Numpad5}
SendInput {Numpad1}
Sleep, 250
Sleep, 250
SendInput {Numpad7}
Sleep, 250
SendInput {Numpad7}
Sleep, 250
SendInput {Numpad7}
Sleep, 250
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 500
SendInput {Numpad0}
SendInput {Numpad4}
Sleep, 500
SendInput {Numpad9}
SendInput {Numpad6}
SendInput {Numpad4}
Sleep, 500
SendInput {Numpad5}
SendInput {Numpad3}
SendInput {Numpad4}
Sleep, 500
SendInput {Numpad2}
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 500
SendInput {Numpad0}
SendInput {Numpad4}
Sleep, 500
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad1}
SendInput {Numpad4}
Sleep, 500
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad4}
Sleep, 500
SendInput {Numpad7}
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 500
SendInput {Numpad7}
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad7}
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad7}
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad9}
SendInput {Numpad7}
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad7}
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad7}
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad7}
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 500
SendInput {Numpad9}
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad9}
SendInput {Numpad4}
Sleep, 750
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad7}
Sleep, 250
SendInput {Numpad9}
SendInput {Numpad1}
Sleep, 500
SendInput {Numpad0}
SendInput {Numpad5}
SendInput {Numpad3}
SendInput {Numpad1}
Sleep, 500
SendInput {Numpad5}
SendInput {Numpad2}
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad5}
SendInput {Numpad3}
Sleep, 250
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad5}
SendInput {Numpad3}
Sleep, 500
SendInput {Numpad5}
SendInput {Numpad3}
Sleep, 500
SendInput {Numpad5}
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad5}
SendInput {Numpad3}
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad3}
Sleep, 250
SendInput {Numpad9}
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad6}
Sleep, 500
SendInput {Numpad6}
SendInput {Numpad3}
SendInput {Numpad4}
Sleep, 500
SendInput {Numpad6}
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad6}
SendInput {Numpad3}
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad4}
Sleep, 250
SendInput {Numpad9}
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad5}
SendInput {Numpad7}
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad5}
SendInput {Numpad7}
SendInput {Numpad2}
Sleep, 750
SendInput {Numpad4}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad4}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 500
SendInput {Numpad4}
Sleep, 250
SendInput {Numpad3}
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad3}
Sleep, 250
SendInput {Numpad5}
SendInput {Numpad1}
Sleep, 500
SendInput {Numpad3}
SendInput {Numpad5}
SendInput {Numpad1}
Sleep, 500
SendInput {Numpad9}
SendInput {Numpad2}
SendInput {Numpad1}
Sleep, 500
SendInput {Numpad0}
SendInput {Numpad3}
SendInput {Numpad5}
SendInput {Numpad2}
Sleep, 500
SendInput {Numpad9}
SendInput {Numpad1}
SendInput {Numpad3}
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad3}
SendInput {Numpad5}
SendInput {Numpad7}
Sleep, 250
Sleep, 500
SendInput {Numpad0}
SendInput {Numpad3}
Sleep, 250
SendInput {Numpad9}
SendInput {Numpad7}
Sleep, 250
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 500
SendInput {Numpad0}
SendInput {Numpad4}
Sleep, 250
SendInput {Numpad9}
SendInput {Numpad6}
Sleep, 250
SendInput {Numpad6}
Sleep, 500
SendInput {Numpad3}
SendInput {Numpad4}
Sleep, 500
SendInput {Numpad5}
SendInput {Numpad7}
SendInput {Numpad2}
Sleep, 500
SendInput {Numpad0}
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 250
Sleep, 250
SendInput {Numpad7}
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad9}
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad3}
SendInput {Numpad1}
Sleep, 500
SendInput {Numpad3}
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad3}
Sleep, 250
SendInput {Numpad3}
SendInput {Numpad5}
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad9}
SendInput {Numpad2}
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad3}
SendInput {Numpad5}
SendInput {Numpad2}
Sleep, 500
SendInput {Numpad9}
SendInput {Numpad1}
SendInput {Numpad3}
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad3}
SendInput {Numpad5}
SendInput {Numpad7}
Sleep, 250
Sleep, 500
SendInput {Numpad7}
SendInput {Numpad3}
Sleep, 250
SendInput {Numpad7}
Sleep, 250
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 500
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 500
SendInput {Numpad6}
Sleep, 500
SendInput {Numpad9}
SendInput {Numpad3}
SendInput {Numpad1}
Sleep, 500
SendInput {Numpad0}
SendInput {Numpad5}
SendInput {Numpad7}
SendInput {Numpad2}
Sleep, 500
SendInput {Numpad0}
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad9}
SendInput {Numpad5}
SendInput {Numpad6}
Sleep, 250
Sleep, 500
SendInput {Numpad5}
SendInput {Numpad7}
Sleep, 500
SendInput {Numpad1}
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 250
SendInput {Numpad9}
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad1}
SendInput {Numpad4}
Sleep, 250
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad1}
Sleep, 500
SendInput {Numpad1}
SendInput {Numpad4}
Sleep, 250
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad5}
SendInput {Numpad7}
Sleep, 250
SendInput {Numpad9}
SendInput {Numpad3}
Sleep, 750
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad7}
Sleep, 250
SendInput {Numpad7}
Sleep, 250
SendInput {Numpad7}
Sleep, 250
SendInput {Numpad1}
SendInput {Numpad3}
SendInput {Numpad5}
Sleep, 500
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad5}
SendInput {Numpad1}
Sleep, 500
SendInput {Numpad3}
Sleep, 250
SendInput {Numpad1}
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 250
Sleep, 500
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 500
SendInput {Numpad4}
Sleep, 250
SendInput {Numpad9}
SendInput {Numpad1}
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 250
SendInput {Numpad9}
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad1}
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 500
SendInput {Numpad9}
SendInput {Numpad2}
SendInput {Numpad1}
Sleep, 500
SendInput {Numpad1}
SendInput {Numpad4}
Sleep, 250
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad1}
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 500
SendInput {Numpad9}
SendInput {Numpad2}
SendInput {Numpad4}
Sleep, 500
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad1}
SendInput {Numpad4}
Sleep, 500
SendInput {Numpad0}
SendInput {Numpad1}
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 250
SendInput {Numpad9}
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad1}
SendInput {Numpad4}
Sleep, 250
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad6}
Sleep, 250
SendInput {Numpad6}
Sleep, 250
SendInput {Numpad9}
SendInput {Numpad1}
SendInput {Numpad4}
Sleep, 500
SendInput {Numpad0}
SendInput {Numpad5}
SendInput {Numpad7}
SendInput {Numpad2}
Sleep, 1000
SendInput {Numpad5}
SendInput {Numpad7}
SendInput {Numpad3}
Sleep, 1000
SendInput {Numpad5}
SendInput {Numpad7}
SendInput {Numpad4}
Sleep, 500
SendInput {Numpad5}
SendInput {Numpad7}
SendInput {Numpad3}
Sleep, 500
SendInput {Numpad5}
SendInput {Numpad7}
SendInput {Numpad2}
Sleep, 500
SendInput {Numpad9}
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad3}
SendInput {Numpad5}
SendInput {Numpad1}
Sleep, 500
SendInput {Numpad3}
SendInput {Numpad1}
Sleep, 500
SendInput {Numpad3}
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad3}
SendInput {Numpad5}
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 500
SendInput {Numpad9}
SendInput {Numpad3}
SendInput {Numpad5}
SendInput {Numpad2}
Sleep, 500
Sleep, 250
SendInput {Numpad3}
SendInput {Numpad5}
SendInput {Numpad1}
Sleep, 250
Sleep, 500
SendInput {Numpad9}
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad4}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 500
SendInput {Numpad9}
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad1}
Sleep, 250
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad4}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 250
Sleep, 500
SendInput {Numpad5}
SendInput {Numpad7}
Sleep, 500
SendInput {Numpad0}
SendInput {Numpad5}
Sleep, 500
SendInput {Numpad9}
SendInput {Numpad6}
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad7}
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad9}
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad3}
SendInput {Numpad5}
SendInput {Numpad1}
Sleep, 500
SendInput {Numpad3}
SendInput {Numpad1}
Sleep, 500
SendInput {Numpad3}
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad3}
SendInput {Numpad5}
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 500
SendInput {Numpad9}
SendInput {Numpad3}
SendInput {Numpad5}
SendInput {Numpad2}
Sleep, 500
Sleep, 250
SendInput {Numpad3}
SendInput {Numpad5}
SendInput {Numpad1}
Sleep, 250
Sleep, 250
SendInput {Numpad7}
Sleep, 250
SendInput {Numpad7}
Sleep, 250
SendInput {Numpad7}
Sleep, 250
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 500
SendInput {Numpad0}
SendInput {Numpad4}
Sleep, 500
SendInput {Numpad9}
SendInput {Numpad6}
SendInput {Numpad4}
Sleep, 500
SendInput {Numpad5}
SendInput {Numpad3}
SendInput {Numpad4}
Sleep, 500
SendInput {Numpad2}
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 500
SendInput {Numpad0}
SendInput {Numpad4}
Sleep, 500
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad1}
SendInput {Numpad4}
Sleep, 500
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad4}
Sleep, 500
SendInput {Numpad7}
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 500
SendInput {Numpad7}
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad9}
SendInput {Numpad7}
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad7}
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad9}
SendInput {Numpad7}
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad7}
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad9}
SendInput {Numpad7}
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad7}
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 500
SendInput {Numpad9}
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad9}
SendInput {Numpad4}
Sleep, 750
SendInput {Numpad3}
Sleep, 500
SendInput {Numpad0}
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 1000
SendInput {Numpad3}
SendInput {Numpad5}
Sleep, 1000
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 1000
SendInput {Numpad3}
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad9}
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad3}
SendInput {Numpad5}
SendInput {Numpad1}
Sleep, 500
SendInput {Numpad0}
SendInput {Numpad5}
Sleep, 500
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad9}
SendInput {Numpad1}
SendInput {Numpad4}
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad1}
SendInput {Numpad4}
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad1}
SendInput {Numpad4}
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad1}
SendInput {Numpad4}
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad1}
SendInput {Numpad3}
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad9}
SendInput {Numpad1}
SendInput {Numpad3}
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 500
SendInput {Numpad5}
Sleep, 500
Sleep, 500
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad6}
SendInput {Numpad2}
SendInput {Numpad3}
Sleep, 500
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad5}
SendInput {Numpad7}
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad3}
Sleep, 500
SendInput {Numpad9}
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 500
SendInput {Numpad0}
SendInput {Numpad3}
Sleep, 250
SendInput {Numpad9}
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 250
Sleep, 250
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad3}
Sleep, 500
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad1}
SendInput {Numpad4}
Sleep, 500
SendInput {Numpad0}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 62
SendInput {Numpad9}
SendInput {Numpad1}
Sleep, 62
SendInput {Numpad4}
Sleep, 125
SendInput {Numpad4}
Sleep, 250
SendInput {Numpad4}
Sleep, 250
SendInput {Numpad6}
SendInput {Numpad1}
SendInput {Numpad4}
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 500
SendInput {Numpad9}
SendInput {Numpad7}
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 500
SendInput {Numpad0}
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad9}
SendInput {Numpad7}
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad7}
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad5}
Sleep, 500
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad9}
SendInput {Numpad5}
Sleep, 250
Sleep, 250
Sleep, 250
SendInput {Numpad1}
Sleep, 250
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad9}
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad9}
SendInput {Numpad5}
Sleep, 250
Sleep, 250
Sleep, 250
SendInput {Numpad1}
Sleep, 250
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad9}
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad9}
SendInput {Numpad5}
Sleep, 250
Sleep, 250
Sleep, 250
SendInput {Numpad1}
Sleep, 250
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad9}
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad9}
SendInput {Numpad5}
Sleep, 250
Sleep, 250
Sleep, 500
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad3}
SendInput {Numpad1}
Sleep, 500
SendInput {Numpad5}
Sleep, 500
SendInput {Numpad5}
SendInput {Numpad1}
Sleep, 500
SendInput {Numpad0}
SendInput {Numpad5}
Sleep, 250
Sleep, 250
SendInput {Numpad9}
SendInput {Numpad5}
SendInput {Numpad3}
Sleep, 500
Sleep, 500
SendInput {Numpad7}
SendInput {Numpad3}
Sleep, 500
SendInput {Numpad0}
SendInput {Numpad7}
Sleep, 250
SendInput {Numpad9}
SendInput {Numpad7}
Sleep, 250
SendInput {Numpad6}
SendInput {Numpad4}
Sleep, 500
SendInput {Numpad6}
Sleep, 500
SendInput {Numpad6}
SendInput {Numpad4}
Sleep, 500
SendInput {Numpad3}
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad3}
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad7}
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad7}
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad7}
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 1000
SendInput {Numpad9}
SendInput {Numpad5}
Sleep, 500
SendInput {Numpad3}
SendInput {Numpad1}
Sleep, 500
SendInput {Numpad3}
Sleep, 500
SendInput {Numpad5}
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad5}
Sleep, 500
SendInput {Numpad9}
SendInput {Numpad5}
SendInput {Numpad3}
Sleep, 500
SendInput {Numpad7}
Sleep, 250
Sleep, 250
SendInput {Numpad3}
Sleep, 250
SendInput {Numpad7}
Sleep, 250
SendInput {Numpad7}
Sleep, 250
SendInput {Numpad7}
Sleep, 250
SendInput {Numpad6}
SendInput {Numpad4}
Sleep, 250
SendInput {Numpad6}
Sleep, 250
SendInput {Numpad6}
Sleep, 250
SendInput {Numpad6}
Sleep, 250
SendInput {Numpad4}
Sleep, 500
SendInput {Numpad1}
Sleep, 500
SendInput {Numpad5}
SendInput {Numpad7}
Sleep, 250
SendInput {Numpad5}
SendInput {Numpad7}
Sleep, 250
SendInput {Numpad5}
SendInput {Numpad7}
Sleep, 2250
SendInput {Numpad0}
SendInput {Numpad7}
Sleep, 300
SendInput {Numpad7}
Sleep, 281
SendInput {Numpad7}
Sleep, 265
SendInput {Numpad1}
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 500
SendInput {Numpad9}
SendInput {Numpad1}
Sleep, 500
SendInput {Numpad0}
SendInput {Numpad1}
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 250
SendInput {Numpad9}
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad1}
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 500
SendInput {Numpad7}
Sleep, 500
SendInput {Numpad6}
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad3}
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad5}
SendInput {Numpad4}
Sleep, 500
SendInput {Numpad0}
SendInput {Numpad7}
SendInput {Numpad3}
Sleep, 250
SendInput {Numpad9}
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad4}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 1000
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad1}
SendInput {Numpad4}
Sleep, 250
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad4}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 500
SendInput {Numpad9}
SendInput {Numpad2}
Sleep, 500
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad4}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 500
SendInput {Numpad9}
SendInput {Numpad2}
Sleep, 500
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad1}
Sleep, 500
SendInput {Numpad0}
SendInput {Numpad4}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad9}
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad6}
Sleep, 500
SendInput {Numpad9}
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad5}
SendInput {Numpad7}
SendInput {Numpad2}
Sleep, 1000
SendInput {Numpad5}
SendInput {Numpad7}
SendInput {Numpad3}
Sleep, 1000
SendInput {Numpad5}
SendInput {Numpad7}
SendInput {Numpad4}
Sleep, 500
SendInput {Numpad5}
SendInput {Numpad7}
SendInput {Numpad3}
Sleep, 500
SendInput {Numpad5}
SendInput {Numpad7}
SendInput {Numpad2}
Sleep, 500
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad1}
SendInput {Numpad3}
Sleep, 250
SendInput {Numpad3}
Sleep, 250
SendInput {Numpad5}
Sleep, 500
SendInput {Numpad3}
SendInput {Numpad5}
SendInput {Numpad1}
Sleep, 500
SendInput {Numpad9}
SendInput {Numpad2}
Sleep, 500
SendInput {Numpad0}
SendInput {Numpad3}
SendInput {Numpad5}
SendInput {Numpad2}
Sleep, 500
SendInput {Numpad9}
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad3}
SendInput {Numpad5}
SendInput {Numpad7}
Sleep, 250
Sleep, 500
SendInput {Numpad7}
Sleep, 500
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 750
SendInput {Numpad6}
Sleep, 250
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 500
SendInput {Numpad4}
Sleep, 500
SendInput {Numpad0}
SendInput {Numpad7}
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad7}
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 750
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad4}
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad4}
Sleep, 250
SendInput {Numpad9}
SendInput {Numpad4}
Sleep, 500
SendInput {Numpad0}
SendInput {Numpad3}
SendInput {Numpad1}
Sleep, 500
SendInput {Numpad3}
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad3}
Sleep, 250
SendInput {Numpad3}
SendInput {Numpad5}
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad9}
SendInput {Numpad2}
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad3}
SendInput {Numpad5}
SendInput {Numpad2}
Sleep, 500
SendInput {Numpad9}
SendInput {Numpad1}
SendInput {Numpad3}
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad3}
SendInput {Numpad5}
SendInput {Numpad7}
Sleep, 250
Sleep, 500
SendInput {Numpad7}
SendInput {Numpad3}
Sleep, 250
SendInput {Numpad7}
Sleep, 250
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 500
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 500
SendInput {Numpad6}
Sleep, 500
SendInput {Numpad9}
SendInput {Numpad3}
SendInput {Numpad1}
Sleep, 500
SendInput {Numpad0}
SendInput {Numpad5}
SendInput {Numpad7}
SendInput {Numpad2}
Sleep, 500
SendInput {Numpad0}
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad9}
SendInput {Numpad5}
SendInput {Numpad6}
Sleep, 250
Sleep, 500
SendInput {Numpad5}
SendInput {Numpad7}
Sleep, 500
SendInput {Numpad1}
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 250
SendInput {Numpad9}
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad1}
SendInput {Numpad4}
Sleep, 250
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad1}
Sleep, 500
SendInput {Numpad1}
SendInput {Numpad4}
Sleep, 250
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad5}
SendInput {Numpad7}
Sleep, 250
SendInput {Numpad3}
Sleep, 750
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad7}
Sleep, 250
SendInput {Numpad7}
Sleep, 250
SendInput {Numpad7}
Sleep, 250
SendInput {Numpad1}
SendInput {Numpad3}
SendInput {Numpad5}
Sleep, 500
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad5}
SendInput {Numpad1}
Sleep, 500
SendInput {Numpad3}
Sleep, 250
SendInput {Numpad1}
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 250
Sleep, 500
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 500
SendInput {Numpad4}
Sleep, 250
SendInput {Numpad9}
SendInput {Numpad1}
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 250
SendInput {Numpad9}
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad1}
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 500
SendInput {Numpad2}
SendInput {Numpad1}
Sleep, 500
SendInput {Numpad1}
SendInput {Numpad4}
Sleep, 250
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad1}
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 500
SendInput {Numpad2}
SendInput {Numpad4}
Sleep, 500
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad1}
SendInput {Numpad4}
Sleep, 500
SendInput {Numpad0}
SendInput {Numpad1}
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 250
SendInput {Numpad9}
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad1}
SendInput {Numpad4}
Sleep, 250
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad6}
Sleep, 250
SendInput {Numpad6}
Sleep, 250
SendInput {Numpad9}
SendInput {Numpad1}
SendInput {Numpad4}
Sleep, 500
SendInput {Numpad0}
SendInput {Numpad5}
SendInput {Numpad7}
SendInput {Numpad2}
Sleep, 1000
SendInput {Numpad5}
SendInput {Numpad7}
SendInput {Numpad3}
Sleep, 1000
SendInput {Numpad5}
SendInput {Numpad7}
SendInput {Numpad4}
Sleep, 500
SendInput {Numpad5}
SendInput {Numpad7}
SendInput {Numpad3}
Sleep, 500
SendInput {Numpad5}
SendInput {Numpad7}
SendInput {Numpad2}
Sleep, 500
SendInput {Numpad9}
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad3}
SendInput {Numpad5}
SendInput {Numpad1}
Sleep, 500
SendInput {Numpad3}
SendInput {Numpad1}
Sleep, 500
SendInput {Numpad3}
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad3}
SendInput {Numpad5}
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 500
SendInput {Numpad9}
SendInput {Numpad3}
SendInput {Numpad5}
SendInput {Numpad2}
Sleep, 500
Sleep, 250
SendInput {Numpad3}
SendInput {Numpad5}
SendInput {Numpad1}
Sleep, 250
Sleep, 500
SendInput {Numpad9}
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad4}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 500
SendInput {Numpad9}
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad1}
Sleep, 250
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad4}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 250
Sleep, 500
SendInput {Numpad5}
SendInput {Numpad7}
Sleep, 500
SendInput {Numpad0}
SendInput {Numpad5}
Sleep, 500
SendInput {Numpad9}
SendInput {Numpad6}
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad7}
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad9}
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad3}
SendInput {Numpad5}
SendInput {Numpad1}
Sleep, 500
SendInput {Numpad9}
SendInput {Numpad3}
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad9}
SendInput {Numpad3}
SendInput {Numpad5}
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 500
SendInput {Numpad9}
SendInput {Numpad3}
SendInput {Numpad5}
SendInput {Numpad1}
Sleep, 500
SendInput {Numpad9}
SendInput {Numpad3}
Sleep, 250
SendInput {Numpad2}
Sleep, 250
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad3}
SendInput {Numpad5}
SendInput {Numpad1}
Sleep, 250
Sleep, 500
SendInput {Numpad4}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 500
SendInput {Numpad9}
SendInput {Numpad4}
Sleep, 250
SendInput {Numpad4}
Sleep, 250
Sleep, 250
SendInput {Numpad6}
SendInput {Numpad1}
SendInput {Numpad4}
Sleep, 250
Sleep, 500
SendInput {Numpad0}
SendInput {Numpad5}
SendInput {Numpad7}
SendInput {Numpad3}
Sleep, 250
SendInput {Numpad9}
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad9}
SendInput {Numpad5}
SendInput {Numpad7}
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad5}
Sleep, 500
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad3}
SendInput {Numpad5}
SendInput {Numpad1}
Sleep, 500
SendInput {Numpad9}
SendInput {Numpad3}
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad3}
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad5}
SendInput {Numpad1}
SendInput {Numpad3}
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 500
SendInput {Numpad9}
SendInput {Numpad3}
SendInput {Numpad5}
SendInput {Numpad7}
Sleep, 500
SendInput {Numpad9}
SendInput {Numpad3}
Sleep, 250
SendInput {Numpad3}
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad3}
Sleep, 250
SendInput {Numpad9}
SendInput {Numpad5}
SendInput {Numpad7}
SendInput {Numpad3}
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad3}
Sleep, 500
SendInput {Numpad9}
SendInput {Numpad4}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 500
SendInput {Numpad9}
SendInput {Numpad4}
Sleep, 250
SendInput {Numpad4}
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad4}
Sleep, 250
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad6}
SendInput {Numpad1}
SendInput {Numpad4}
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad4}
Sleep, 500
SendInput {Numpad9}
SendInput {Numpad5}
SendInput {Numpad7}
SendInput {Numpad2}
Sleep, 500
SendInput {Numpad0}
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad9}
SendInput {Numpad5}
SendInput {Numpad7}
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad5}
Sleep, 500
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad3}
SendInput {Numpad5}
SendInput {Numpad1}
Sleep, 500
SendInput {Numpad3}
SendInput {Numpad1}
Sleep, 500
SendInput {Numpad3}
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad3}
SendInput {Numpad5}
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 500
SendInput {Numpad9}
SendInput {Numpad3}
SendInput {Numpad5}
SendInput {Numpad2}
Sleep, 500
SendInput {Numpad0}
SendInput {Numpad3}
Sleep, 250
SendInput {Numpad9}
SendInput {Numpad3}
SendInput {Numpad5}
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad3}
Sleep, 250
SendInput {Numpad9}
SendInput {Numpad7}
Sleep, 250
SendInput {Numpad7}
SendInput {Numpad3}
Sleep, 250
SendInput {Numpad7}
Sleep, 250
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 500
SendInput {Numpad0}
SendInput {Numpad4}
Sleep, 500
SendInput {Numpad9}
SendInput {Numpad6}
SendInput {Numpad4}
Sleep, 500
SendInput {Numpad5}
SendInput {Numpad3}
SendInput {Numpad4}
Sleep, 500
SendInput {Numpad2}
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 500
SendInput {Numpad0}
SendInput {Numpad4}
Sleep, 500
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad1}
SendInput {Numpad4}
Sleep, 500
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad4}
Sleep, 500
SendInput {Numpad7}
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 500
SendInput {Numpad7}
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad9}
SendInput {Numpad7}
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad7}
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad9}
SendInput {Numpad7}
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad7}
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad9}
SendInput {Numpad7}
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad7}
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 1000
SendInput {Numpad9}
SendInput {Numpad5}
Sleep, 1000
SendInput {Numpad9}
SendInput {Numpad4}
Sleep, 1000
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad7}
Sleep, 750
SendInput {Numpad9}
SendInput {Numpad1}
SendInput {Numpad3}
Sleep, 1000
SendInput {Numpad0}
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad9}
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad3}
Sleep, 500
SendInput {Numpad9}
SendInput {Numpad6}
SendInput {Numpad3}
Sleep, 500
SendInput {Numpad3}
Sleep, 250
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad3}
Sleep, 250
SendInput {Numpad9}
SendInput {Numpad4}
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad7}
Sleep, 250
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad4}
Sleep, 500
SendInput {Numpad4}
Sleep, 250
SendInput {Numpad6}
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad4}
Sleep, 250
SendInput {Numpad9}
SendInput {Numpad4}
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 500
SendInput {Numpad9}
SendInput {Numpad7}
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 500
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad7}
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad9}
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad7}
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 500
SendInput {Numpad1}
SendInput {Numpad3}
SendInput {Numpad5}
Sleep, 500
Sleep, 500
SendInput {Numpad1}
Sleep, 1000
