; title: Never Gonna Give You Up
; author: Mike Stock / Matt Aitken / Peter Waterman
; instrument: Piano
; Converted by Serenade midi2ahk from musescore_liygjuxq.mid

SendInput {Numpad4}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 263
SendInput {Numpad0}
SendInput {Numpad4}
Sleep, 526
SendInput {Numpad9}
SendInput {Numpad5}
SendInput {Numpad7}
SendInput {Numpad2}
Sleep, 526
SendInput {Numpad0}
SendInput {Numpad5}
Sleep, 263
SendInput {Numpad9}
SendInput {Numpad5}
Sleep, 263
SendInput {Numpad0}
SendInput {Numpad5}
Sleep, 263
SendInput {Numpad9}
SendInput {Numpad5}
SendInput {Numpad7}
SendInput {Numpad2}
Sleep, 263
SendInput {Numpad0}
SendInput {Numpad3}
Sleep, 526
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad6}
SendInput {Numpad1}
SendInput {Numpad3}
Sleep, 526
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad6}
Sleep, 263
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad5}
Sleep, 132
SendInput {Numpad4}
Sleep, 132
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 263
SendInput {Numpad0}
SendInput {Numpad4}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 263
SendInput {Numpad0}
SendInput {Numpad4}
Sleep, 526
SendInput {Numpad9}
SendInput {Numpad5}
SendInput {Numpad7}
SendInput {Numpad2}
Sleep, 526
SendInput {Numpad0}
SendInput {Numpad5}
Sleep, 263
SendInput {Numpad9}
SendInput {Numpad5}
Sleep, 263
SendInput {Numpad0}
SendInput {Numpad5}
Sleep, 263
Sleep, 263
SendInput {Numpad4}
Sleep, 526
Sleep, 526
SendInput {Numpad9}
SendInput {Numpad5}
Sleep, 132
SendInput {Numpad5}
Sleep, 132
SendInput {Numpad6}
Sleep, 132
SendInput {Numpad7}
Sleep, 132
SendInput {Numpad5}
Sleep, 132
SendInput {Numpad1}
Sleep, 132
SendInput {Numpad4}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 263
SendInput {Numpad0}
SendInput {Numpad4}
Sleep, 526
SendInput {Numpad9}
SendInput {Numpad5}
SendInput {Numpad7}
SendInput {Numpad2}
Sleep, 526
SendInput {Numpad0}
SendInput {Numpad5}
Sleep, 263
SendInput {Numpad9}
SendInput {Numpad5}
Sleep, 263
SendInput {Numpad0}
SendInput {Numpad5}
Sleep, 263
SendInput {Numpad9}
SendInput {Numpad5}
SendInput {Numpad7}
SendInput {Numpad2}
Sleep, 263
SendInput {Numpad0}
SendInput {Numpad3}
Sleep, 526
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad6}
SendInput {Numpad1}
SendInput {Numpad3}
Sleep, 526
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad6}
Sleep, 263
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad5}
Sleep, 132
SendInput {Numpad4}
Sleep, 132
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 263
SendInput {Numpad0}
SendInput {Numpad4}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 263
SendInput {Numpad0}
SendInput {Numpad4}
Sleep, 526
SendInput {Numpad9}
SendInput {Numpad5}
SendInput {Numpad7}
SendInput {Numpad2}
Sleep, 526
SendInput {Numpad0}
SendInput {Numpad5}
Sleep, 263
SendInput {Numpad9}
SendInput {Numpad5}
Sleep, 263
SendInput {Numpad0}
SendInput {Numpad5}
Sleep, 263
SendInput {Numpad9}
SendInput {Numpad5}
SendInput {Numpad7}
Sleep, 263
SendInput {Numpad9}
SendInput {Numpad1}
SendInput {Numpad3}
Sleep, 263
SendInput {Numpad0}
SendInput {Numpad3}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 263
Sleep, 526
SendInput {Numpad0}
SendInput {Numpad6}
Sleep, 263
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad1}
Sleep, 132
SendInput {Numpad1}
Sleep, 132
SendInput {Numpad6}
Sleep, 132
SendInput {Numpad1}
Sleep, 132
Sleep, 263
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 263
SendInput {Numpad9}
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 263
SendInput {Numpad4}
SendInput {Numpad7}
Sleep, 263
SendInput {Numpad9}
SendInput {Numpad1}
Sleep, 263
SendInput {Numpad0}
SendInput {Numpad4}
SendInput {Numpad1}
Sleep, 263
SendInput {Numpad9}
SendInput {Numpad2}
Sleep, 263
SendInput {Numpad0}
SendInput {Numpad5}
SendInput {Numpad7}
Sleep, 395
SendInput {Numpad6}
Sleep, 132
SendInput {Numpad5}
Sleep, 526
SendInput {Numpad0}
SendInput {Numpad5}
Sleep, 263
SendInput {Numpad5}
Sleep, 526
SendInput {F3}
Sleep, 526
Sleep, 263
SendInput {Numpad9}
SendInput {Numpad4}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 263
SendInput {Numpad6}
SendInput {Numpad4}
Sleep, 263
SendInput {Numpad7}
Sleep, 263
SendInput {Numpad9}
SendInput {Numpad1}
Sleep, 263
SendInput {Numpad0}
SendInput {Numpad6}
Sleep, 263
SendInput {Numpad0}
SendInput {Numpad4}
Sleep, 263
SendInput {Numpad9}
SendInput {Numpad5}
Sleep, 263
SendInput {Numpad5}
Sleep, 526
SendInput {Numpad9}
SendInput {Numpad5}
Sleep, 263
SendInput {Numpad2}
Sleep, 1316
Sleep, 263
SendInput {Numpad0}
SendInput {Numpad4}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 263
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 263
SendInput {Numpad4}
SendInput {Numpad7}
Sleep, 263
SendInput {Numpad9}
SendInput {Numpad1}
Sleep, 263
SendInput {Numpad0}
SendInput {Numpad6}
Sleep, 263
SendInput {Numpad4}
SendInput {Numpad1}
Sleep, 263
SendInput {Numpad9}
SendInput {Numpad2}
Sleep, 263
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad5}
Sleep, 263
SendInput {Numpad9}
SendInput {Numpad5}
SendInput {Numpad7}
Sleep, 263
SendInput {Numpad6}
Sleep, 263
SendInput {Numpad5}
Sleep, 789
SendInput {Numpad0}
SendInput {F3}
Sleep, 526
Sleep, 263
SendInput {Numpad9}
SendInput {Numpad4}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 263
SendInput {Numpad6}
SendInput {Numpad4}
Sleep, 263
SendInput {Numpad7}
Sleep, 263
SendInput {Numpad4}
SendInput {Numpad1}
SendInput {Numpad2}
Sleep, 263
SendInput {Numpad6}
Sleep, 263
SendInput {Numpad5}
Sleep, 526
SendInput {Numpad2}
SendInput {Numpad5}
SendInput {Numpad7}
Sleep, 263
SendInput {Numpad9}
SendInput {Numpad2}
Sleep, 263
SendInput {Numpad2}
Sleep, 263
SendInput {Numpad3}
Sleep, 263
SendInput {Numpad2}
Sleep, 526
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {F3}
Sleep, 526
SendInput {Numpad9}
SendInput {Numpad4}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 263
SendInput {Numpad0}
SendInput {Numpad4}
Sleep, 263
Sleep, 263
SendInput {Numpad4}
Sleep, 263
Sleep, 263
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad2}
SendInput {Numpad4}
Sleep, 263
SendInput {Numpad3}
Sleep, 263
SendInput {Numpad1}
SendInput {Numpad4}
Sleep, 263
SendInput {Numpad0}
SendInput {Numpad2}
SendInput {Numpad5}
SendInput {Numpad7}
Sleep, 263
SendInput {Numpad9}
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 263
SendInput {Numpad2}
Sleep, 263
SendInput {Numpad3}
SendInput {Numpad5}
Sleep, 263
SendInput {Numpad2}
Sleep, 263
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad5}
Sleep, 263
SendInput {Numpad9}
SendInput {Numpad5}
Sleep, 263
SendInput {Numpad0}
SendInput {Numpad5}
Sleep, 263
Sleep, 263
SendInput {Numpad4}
Sleep, 263
Sleep, 263
SendInput {Numpad4}
Sleep, 263
SendInput {Numpad9}
SendInput {Numpad6}
SendInput {Numpad4}
Sleep, 263
SendInput {Numpad7}
SendInput {Numpad4}
Sleep, 263
SendInput {Numpad9}
SendInput {Numpad1}
Sleep, 263
SendInput {Numpad0}
SendInput {Numpad6}
SendInput {Numpad4}
Sleep, 263
SendInput {Numpad0}
SendInput {Numpad5}
Sleep, 263
SendInput {Numpad9}
SendInput {Numpad2}
SendInput {Numpad5}
SendInput {Numpad7}
Sleep, 263
SendInput {Numpad9}
SendInput {Numpad3}
Sleep, 263
SendInput {Numpad2}
Sleep, 789
SendInput {Numpad0}
SendInput {Numpad5}
Sleep, 132
SendInput {Numpad6}
Sleep, 132
SendInput {Numpad1}
Sleep, 132
SendInput {Numpad6}
Sleep, 132
SendInput {Numpad6}
SendInput {Numpad1}
SendInput {Numpad3}
SendInput {Numpad4}
Sleep, 395
SendInput {Numpad6}
SendInput {Numpad1}
SendInput {Numpad3}
SendInput {Numpad4}
Sleep, 395
SendInput {Numpad5}
SendInput {Numpad7}
SendInput {Numpad2}
Sleep, 789
SendInput {Numpad5}
Sleep, 132
SendInput {Numpad6}
Sleep, 132
SendInput {Numpad1}
Sleep, 132
SendInput {Numpad6}
Sleep, 132
SendInput {Numpad5}
SendInput {Numpad7}
SendInput {Numpad2}
SendInput {Numpad3}
Sleep, 395
SendInput {Numpad5}
SendInput {Numpad7}
SendInput {Numpad2}
SendInput {Numpad3}
Sleep, 395
SendInput {Numpad3}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 395
SendInput {Numpad7}
Sleep, 132
SendInput {Numpad6}
Sleep, 263
SendInput {Numpad5}
Sleep, 132
SendInput {Numpad6}
Sleep, 132
SendInput {Numpad1}
Sleep, 132
SendInput {Numpad6}
Sleep, 132
SendInput {Numpad4}
SendInput {Numpad6}
SendInput {Numpad1}
SendInput {Numpad2}
Sleep, 526
SendInput {Numpad9}
SendInput {Numpad2}
Sleep, 263
SendInput {Numpad0}
SendInput {Numpad5}
SendInput {Numpad7}
Sleep, 395
SendInput {Numpad6}
Sleep, 132
SendInput {Numpad5}
Sleep, 263
SendInput {Numpad0}
SendInput {Numpad5}
Sleep, 263
SendInput {Numpad9}
SendInput {Numpad5}
Sleep, 263
SendInput {Numpad3}
SendInput {Numpad5}
SendInput {Numpad2}
SendInput {Numpad7}
Sleep, 526
SendInput {Numpad3}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 1053
SendInput {Numpad5}
Sleep, 132
SendInput {Numpad6}
Sleep, 132
SendInput {Numpad1}
Sleep, 132
SendInput {Numpad6}
Sleep, 132
SendInput {Numpad6}
SendInput {Numpad1}
SendInput {Numpad3}
SendInput {Numpad4}
Sleep, 395
SendInput {Numpad6}
SendInput {Numpad1}
SendInput {Numpad3}
SendInput {Numpad4}
Sleep, 395
SendInput {Numpad5}
SendInput {Numpad7}
SendInput {Numpad2}
Sleep, 789
SendInput {Numpad5}
Sleep, 132
SendInput {Numpad6}
Sleep, 132
SendInput {Numpad1}
Sleep, 132
SendInput {Numpad6}
Sleep, 132
SendInput {Numpad5}
SendInput {Numpad3}
Sleep, 526
SendInput {Numpad7}
SendInput {Numpad3}
Sleep, 263
SendInput {Numpad9}
SendInput {Numpad1}
SendInput {Numpad6}
Sleep, 395
SendInput {Numpad0}
SendInput {Numpad7}
Sleep, 132
SendInput {Numpad6}
Sleep, 263
SendInput {Numpad5}
Sleep, 132
SendInput {Numpad6}
Sleep, 132
SendInput {Numpad1}
Sleep, 132
SendInput {Numpad6}
Sleep, 132
SendInput {Numpad4}
SendInput {Numpad6}
SendInput {Numpad1}
SendInput {Numpad2}
Sleep, 526
SendInput {Numpad9}
SendInput {Numpad2}
Sleep, 263
SendInput {Numpad0}
SendInput {Numpad5}
SendInput {Numpad7}
Sleep, 395
SendInput {Numpad6}
Sleep, 132
SendInput {Numpad5}
Sleep, 263
SendInput {Numpad0}
SendInput {Numpad5}
Sleep, 263
SendInput {Numpad9}
SendInput {Numpad5}
Sleep, 263
SendInput {Numpad3}
SendInput {Numpad5}
SendInput {Numpad2}
SendInput {Numpad7}
Sleep, 526
SendInput {Numpad3}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 1579
Sleep, 263
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 263
SendInput {Numpad9}
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 263
SendInput {Numpad4}
SendInput {Numpad7}
Sleep, 263
SendInput {Numpad9}
SendInput {Numpad1}
Sleep, 263
SendInput {Numpad0}
SendInput {Numpad4}
SendInput {Numpad1}
Sleep, 263
SendInput {Numpad9}
SendInput {Numpad2}
Sleep, 263
SendInput {Numpad0}
SendInput {Numpad5}
SendInput {Numpad7}
Sleep, 395
SendInput {Numpad6}
Sleep, 132
SendInput {Numpad5}
Sleep, 526
SendInput {Numpad0}
SendInput {Numpad5}
Sleep, 263
SendInput {Numpad5}
Sleep, 526
SendInput {F3}
Sleep, 526
Sleep, 263
SendInput {Numpad9}
SendInput {Numpad4}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 263
SendInput {Numpad6}
SendInput {Numpad4}
Sleep, 263
SendInput {Numpad7}
Sleep, 263
SendInput {Numpad9}
SendInput {Numpad1}
Sleep, 263
SendInput {Numpad0}
SendInput {Numpad6}
Sleep, 263
SendInput {Numpad0}
SendInput {Numpad4}
Sleep, 263
SendInput {Numpad9}
SendInput {Numpad5}
Sleep, 263
SendInput {Numpad5}
Sleep, 526
SendInput {Numpad9}
SendInput {Numpad5}
Sleep, 263
SendInput {Numpad2}
Sleep, 263
SendInput {Numpad0}
SendInput {Numpad5}
SendInput {Numpad7}
Sleep, 263
SendInput {Numpad9}
SendInput {Numpad3}
Sleep, 263
SendInput {Numpad2}
Sleep, 263
SendInput {Numpad1}
Sleep, 263
Sleep, 263
SendInput {Numpad0}
SendInput {Numpad4}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 263
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 263
SendInput {Numpad4}
SendInput {Numpad7}
Sleep, 263
SendInput {Numpad9}
SendInput {Numpad1}
Sleep, 263
SendInput {Numpad0}
SendInput {Numpad6}
Sleep, 263
SendInput {Numpad4}
SendInput {Numpad1}
Sleep, 263
SendInput {Numpad9}
SendInput {Numpad2}
Sleep, 263
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad5}
Sleep, 263
SendInput {Numpad9}
SendInput {Numpad5}
SendInput {Numpad7}
Sleep, 263
SendInput {Numpad6}
Sleep, 263
SendInput {Numpad5}
Sleep, 789
SendInput {Numpad0}
SendInput {F3}
Sleep, 526
Sleep, 263
SendInput {Numpad9}
SendInput {Numpad4}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 263
SendInput {Numpad6}
SendInput {Numpad4}
Sleep, 263
SendInput {Numpad7}
Sleep, 263
SendInput {Numpad4}
SendInput {Numpad1}
SendInput {Numpad2}
Sleep, 263
SendInput {Numpad6}
Sleep, 263
SendInput {Numpad5}
Sleep, 526
SendInput {Numpad2}
SendInput {Numpad5}
SendInput {Numpad7}
Sleep, 263
SendInput {Numpad9}
SendInput {Numpad2}
Sleep, 263
SendInput {Numpad2}
Sleep, 263
SendInput {Numpad3}
Sleep, 263
SendInput {Numpad2}
Sleep, 526
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {F3}
Sleep, 526
SendInput {Numpad9}
SendInput {Numpad4}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 263
SendInput {Numpad0}
SendInput {Numpad4}
Sleep, 263
Sleep, 263
SendInput {Numpad4}
Sleep, 263
Sleep, 263
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad2}
SendInput {Numpad4}
Sleep, 263
SendInput {Numpad3}
Sleep, 263
SendInput {Numpad1}
SendInput {Numpad4}
Sleep, 263
SendInput {Numpad0}
SendInput {Numpad2}
SendInput {Numpad5}
SendInput {Numpad7}
Sleep, 263
SendInput {Numpad9}
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 263
SendInput {Numpad2}
Sleep, 263
SendInput {Numpad3}
SendInput {Numpad5}
Sleep, 263
SendInput {Numpad2}
Sleep, 263
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad5}
Sleep, 263
SendInput {Numpad9}
SendInput {Numpad5}
Sleep, 263
SendInput {Numpad0}
SendInput {Numpad5}
Sleep, 263
Sleep, 263
SendInput {Numpad4}
Sleep, 263
Sleep, 263
SendInput {Numpad4}
Sleep, 263
SendInput {Numpad9}
SendInput {Numpad6}
SendInput {Numpad4}
Sleep, 263
SendInput {Numpad7}
SendInput {Numpad4}
Sleep, 263
SendInput {Numpad9}
SendInput {Numpad1}
Sleep, 263
SendInput {Numpad0}
SendInput {Numpad6}
SendInput {Numpad4}
Sleep, 263
SendInput {Numpad0}
SendInput {Numpad5}
Sleep, 263
SendInput {Numpad9}
SendInput {Numpad2}
SendInput {Numpad5}
SendInput {Numpad7}
Sleep, 263
SendInput {Numpad9}
SendInput {Numpad3}
Sleep, 263
SendInput {Numpad2}
Sleep, 789
SendInput {Numpad0}
SendInput {Numpad5}
Sleep, 132
SendInput {Numpad6}
Sleep, 132
SendInput {Numpad1}
Sleep, 132
SendInput {Numpad6}
Sleep, 132
SendInput {Numpad6}
SendInput {Numpad1}
SendInput {Numpad3}
SendInput {Numpad4}
Sleep, 395
SendInput {Numpad6}
SendInput {Numpad1}
SendInput {Numpad3}
SendInput {Numpad4}
Sleep, 395
SendInput {Numpad5}
SendInput {Numpad7}
SendInput {Numpad2}
Sleep, 789
SendInput {Numpad5}
Sleep, 132
SendInput {Numpad6}
Sleep, 132
SendInput {Numpad1}
Sleep, 132
SendInput {Numpad6}
Sleep, 132
SendInput {Numpad5}
SendInput {Numpad7}
SendInput {Numpad2}
SendInput {Numpad3}
Sleep, 395
SendInput {Numpad5}
SendInput {Numpad7}
SendInput {Numpad2}
SendInput {Numpad3}
Sleep, 395
SendInput {Numpad3}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 395
SendInput {Numpad7}
Sleep, 132
SendInput {Numpad6}
Sleep, 263
SendInput {Numpad5}
Sleep, 132
SendInput {Numpad6}
Sleep, 132
SendInput {Numpad1}
Sleep, 132
SendInput {Numpad6}
Sleep, 132
SendInput {Numpad4}
SendInput {Numpad6}
SendInput {Numpad1}
SendInput {Numpad2}
Sleep, 526
SendInput {Numpad9}
SendInput {Numpad2}
Sleep, 263
SendInput {Numpad0}
SendInput {Numpad5}
SendInput {Numpad7}
Sleep, 395
SendInput {Numpad6}
Sleep, 132
SendInput {Numpad5}
Sleep, 263
SendInput {Numpad0}
SendInput {Numpad5}
Sleep, 263
SendInput {Numpad9}
SendInput {Numpad5}
Sleep, 263
SendInput {Numpad3}
SendInput {Numpad5}
SendInput {Numpad2}
SendInput {Numpad7}
Sleep, 526
SendInput {Numpad3}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 1053
SendInput {Numpad5}
Sleep, 132
SendInput {Numpad6}
Sleep, 132
SendInput {Numpad1}
Sleep, 132
SendInput {Numpad6}
Sleep, 132
SendInput {Numpad6}
SendInput {Numpad1}
SendInput {Numpad3}
SendInput {Numpad4}
Sleep, 395
SendInput {Numpad6}
SendInput {Numpad1}
SendInput {Numpad3}
SendInput {Numpad4}
Sleep, 395
SendInput {Numpad5}
SendInput {Numpad7}
SendInput {Numpad2}
Sleep, 789
SendInput {Numpad5}
Sleep, 132
SendInput {Numpad6}
Sleep, 132
SendInput {Numpad1}
Sleep, 132
SendInput {Numpad6}
Sleep, 132
SendInput {Numpad5}
SendInput {Numpad3}
Sleep, 526
SendInput {Numpad7}
SendInput {Numpad3}
Sleep, 263
SendInput {Numpad9}
SendInput {Numpad1}
SendInput {Numpad6}
Sleep, 395
SendInput {Numpad0}
SendInput {Numpad7}
Sleep, 132
SendInput {Numpad6}
Sleep, 263
SendInput {Numpad5}
Sleep, 132
SendInput {Numpad6}
Sleep, 132
SendInput {Numpad1}
Sleep, 132
SendInput {Numpad6}
Sleep, 132
SendInput {Numpad4}
SendInput {Numpad6}
SendInput {Numpad1}
SendInput {Numpad2}
Sleep, 526
SendInput {Numpad9}
SendInput {Numpad2}
Sleep, 263
SendInput {Numpad0}
SendInput {Numpad5}
SendInput {Numpad7}
Sleep, 395
SendInput {Numpad6}
Sleep, 132
SendInput {Numpad5}
Sleep, 263
SendInput {Numpad0}
SendInput {Numpad5}
Sleep, 263
SendInput {Numpad9}
SendInput {Numpad5}
Sleep, 263
SendInput {Numpad3}
SendInput {Numpad5}
SendInput {Numpad2}
SendInput {Numpad7}
Sleep, 526
SendInput {Numpad3}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 1053
SendInput {Numpad5}
Sleep, 132
SendInput {Numpad6}
Sleep, 132
SendInput {Numpad1}
Sleep, 132
SendInput {Numpad6}
Sleep, 132
SendInput {Numpad6}
SendInput {Numpad1}
SendInput {Numpad3}
SendInput {Numpad4}
Sleep, 395
SendInput {Numpad6}
SendInput {Numpad1}
SendInput {Numpad3}
SendInput {Numpad4}
Sleep, 395
SendInput {Numpad5}
SendInput {Numpad7}
SendInput {Numpad2}
Sleep, 789
SendInput {Numpad5}
Sleep, 132
SendInput {Numpad6}
Sleep, 132
SendInput {Numpad1}
Sleep, 132
SendInput {Numpad6}
Sleep, 132
SendInput {Numpad5}
SendInput {Numpad7}
SendInput {Numpad2}
SendInput {Numpad3}
Sleep, 395
SendInput {Numpad5}
SendInput {Numpad7}
SendInput {Numpad2}
SendInput {Numpad3}
Sleep, 395
SendInput {Numpad3}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 395
SendInput {Numpad7}
Sleep, 132
SendInput {Numpad6}
Sleep, 263
SendInput {Numpad5}
Sleep, 132
SendInput {Numpad6}
Sleep, 132
SendInput {Numpad1}
Sleep, 132
SendInput {Numpad6}
Sleep, 132
SendInput {Numpad4}
SendInput {Numpad6}
SendInput {Numpad1}
SendInput {Numpad2}
Sleep, 526
SendInput {Numpad9}
SendInput {Numpad2}
Sleep, 263
SendInput {Numpad0}
SendInput {Numpad5}
SendInput {Numpad7}
Sleep, 395
SendInput {Numpad6}
Sleep, 132
SendInput {Numpad5}
Sleep, 263
SendInput {Numpad0}
SendInput {Numpad5}
Sleep, 263
SendInput {Numpad9}
SendInput {Numpad5}
Sleep, 263
SendInput {Numpad3}
SendInput {Numpad5}
SendInput {Numpad2}
SendInput {Numpad7}
Sleep, 526
SendInput {Numpad3}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 1053
SendInput {Numpad5}
Sleep, 132
SendInput {Numpad6}
Sleep, 132
SendInput {Numpad1}
Sleep, 132
SendInput {Numpad6}
Sleep, 132
SendInput {Numpad6}
SendInput {Numpad1}
SendInput {Numpad3}
SendInput {Numpad4}
Sleep, 395
SendInput {Numpad6}
SendInput {Numpad1}
SendInput {Numpad3}
SendInput {Numpad4}
Sleep, 395
SendInput {Numpad5}
SendInput {Numpad7}
SendInput {Numpad2}
Sleep, 789
SendInput {Numpad5}
Sleep, 132
SendInput {Numpad6}
Sleep, 132
SendInput {Numpad1}
Sleep, 132
SendInput {Numpad6}
Sleep, 132
SendInput {Numpad5}
SendInput {Numpad3}
Sleep, 526
SendInput {Numpad7}
SendInput {Numpad3}
Sleep, 263
SendInput {Numpad9}
SendInput {Numpad1}
SendInput {Numpad6}
Sleep, 395
SendInput {Numpad0}
SendInput {Numpad7}
Sleep, 132
SendInput {Numpad6}
Sleep, 263
SendInput {Numpad5}
Sleep, 132
SendInput {Numpad6}
Sleep, 132
SendInput {Numpad1}
Sleep, 132
SendInput {Numpad6}
Sleep, 132
SendInput {Numpad4}
SendInput {Numpad6}
SendInput {Numpad1}
SendInput {Numpad2}
Sleep, 526
SendInput {Numpad9}
SendInput {Numpad2}
Sleep, 263
SendInput {Numpad0}
SendInput {Numpad5}
SendInput {Numpad7}
Sleep, 395
SendInput {Numpad6}
Sleep, 132
SendInput {Numpad5}
Sleep, 263
SendInput {Numpad0}
SendInput {Numpad5}
Sleep, 263
SendInput {Numpad9}
SendInput {Numpad5}
Sleep, 263
SendInput {Numpad3}
SendInput {Numpad5}
SendInput {Numpad2}
SendInput {Numpad7}
Sleep, 526
SendInput {Numpad3}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 1579
SendInput {Numpad5}
SendInput {Numpad4}
Sleep, 395
SendInput {Numpad0}
SendInput {Numpad4}
Sleep, 658
SendInput {Numpad4}
Sleep, 395
SendInput {Numpad4}
Sleep, 658
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad1}
SendInput {Numpad4}
Sleep, 395
SendInput {Numpad1}
SendInput {Numpad4}
Sleep, 395
SendInput {Numpad0}
SendInput {Numpad7}
SendInput {Numpad5}
Sleep, 1316
SendInput {Numpad5}
SendInput {Numpad4}
Sleep, 395
SendInput {Numpad0}
SendInput {Numpad4}
Sleep, 658
SendInput {Numpad4}
Sleep, 395
SendInput {Numpad4}
Sleep, 658
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad1}
SendInput {Numpad4}
Sleep, 395
SendInput {Numpad1}
SendInput {Numpad4}
Sleep, 395
SendInput {Numpad0}
SendInput {Numpad7}
SendInput {Numpad5}
Sleep, 1316
Sleep, 263
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 263
SendInput {Numpad9}
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 263
SendInput {Numpad4}
SendInput {Numpad7}
Sleep, 263
SendInput {Numpad9}
SendInput {Numpad1}
Sleep, 263
SendInput {Numpad0}
SendInput {Numpad4}
SendInput {Numpad1}
Sleep, 263
SendInput {Numpad9}
SendInput {Numpad2}
Sleep, 263
SendInput {Numpad0}
SendInput {Numpad5}
SendInput {Numpad7}
Sleep, 395
SendInput {Numpad6}
Sleep, 132
SendInput {Numpad5}
Sleep, 526
SendInput {Numpad0}
SendInput {Numpad5}
Sleep, 263
SendInput {Numpad5}
Sleep, 526
SendInput {F3}
Sleep, 526
Sleep, 263
SendInput {Numpad9}
SendInput {Numpad4}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 263
SendInput {Numpad6}
SendInput {Numpad4}
Sleep, 263
SendInput {Numpad7}
Sleep, 263
SendInput {Numpad9}
SendInput {Numpad1}
Sleep, 263
SendInput {Numpad0}
SendInput {Numpad6}
Sleep, 263
SendInput {Numpad0}
SendInput {Numpad4}
Sleep, 263
SendInput {Numpad9}
SendInput {Numpad5}
Sleep, 263
SendInput {Numpad5}
Sleep, 526
SendInput {Numpad9}
SendInput {Numpad5}
Sleep, 263
SendInput {Numpad2}
Sleep, 263
SendInput {Numpad0}
SendInput {Numpad5}
SendInput {Numpad7}
Sleep, 263
SendInput {Numpad9}
SendInput {Numpad3}
Sleep, 263
SendInput {Numpad2}
Sleep, 263
SendInput {Numpad1}
Sleep, 263
Sleep, 263
SendInput {Numpad0}
SendInput {Numpad4}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 263
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 263
SendInput {Numpad4}
SendInput {Numpad7}
Sleep, 263
SendInput {Numpad9}
SendInput {Numpad1}
Sleep, 263
SendInput {Numpad0}
SendInput {Numpad6}
Sleep, 263
SendInput {Numpad4}
SendInput {Numpad1}
Sleep, 263
SendInput {Numpad9}
SendInput {Numpad2}
Sleep, 263
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad5}
Sleep, 263
SendInput {Numpad9}
SendInput {Numpad5}
SendInput {Numpad7}
Sleep, 263
SendInput {Numpad6}
Sleep, 263
SendInput {Numpad5}
Sleep, 789
SendInput {Numpad0}
SendInput {F3}
Sleep, 526
Sleep, 263
SendInput {Numpad9}
SendInput {Numpad4}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 263
SendInput {Numpad6}
SendInput {Numpad4}
Sleep, 263
SendInput {Numpad7}
Sleep, 263
SendInput {Numpad4}
SendInput {Numpad1}
SendInput {Numpad2}
Sleep, 263
SendInput {Numpad6}
Sleep, 263
SendInput {Numpad5}
Sleep, 526
SendInput {Numpad2}
SendInput {Numpad5}
SendInput {Numpad7}
Sleep, 263
SendInput {Numpad9}
SendInput {Numpad2}
Sleep, 263
SendInput {Numpad2}
Sleep, 263
SendInput {Numpad3}
Sleep, 263
SendInput {Numpad2}
Sleep, 526
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {F3}
Sleep, 526
SendInput {Numpad9}
SendInput {Numpad4}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 263
SendInput {Numpad0}
SendInput {Numpad4}
Sleep, 263
Sleep, 263
SendInput {Numpad4}
Sleep, 263
Sleep, 263
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad2}
SendInput {Numpad4}
Sleep, 263
SendInput {Numpad3}
Sleep, 263
SendInput {Numpad1}
SendInput {Numpad4}
Sleep, 263
SendInput {Numpad0}
SendInput {Numpad2}
SendInput {Numpad5}
SendInput {Numpad7}
Sleep, 263
SendInput {Numpad9}
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 263
SendInput {Numpad2}
Sleep, 263
SendInput {Numpad3}
SendInput {Numpad5}
Sleep, 263
SendInput {Numpad2}
Sleep, 263
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad5}
Sleep, 263
SendInput {Numpad9}
SendInput {Numpad5}
Sleep, 263
SendInput {Numpad0}
SendInput {Numpad5}
Sleep, 263
Sleep, 263
SendInput {Numpad4}
Sleep, 263
Sleep, 263
SendInput {Numpad4}
Sleep, 263
SendInput {Numpad9}
SendInput {Numpad6}
SendInput {Numpad4}
Sleep, 263
SendInput {Numpad7}
SendInput {Numpad4}
Sleep, 263
SendInput {Numpad9}
SendInput {Numpad1}
Sleep, 263
SendInput {Numpad0}
SendInput {Numpad6}
SendInput {Numpad4}
Sleep, 263
SendInput {Numpad0}
SendInput {Numpad5}
Sleep, 263
SendInput {Numpad9}
SendInput {Numpad2}
SendInput {Numpad5}
SendInput {Numpad7}
Sleep, 263
SendInput {Numpad9}
SendInput {Numpad3}
Sleep, 263
SendInput {Numpad2}
Sleep, 789
SendInput {Numpad0}
SendInput {Numpad5}
Sleep, 132
SendInput {Numpad6}
Sleep, 132
SendInput {Numpad1}
Sleep, 132
SendInput {Numpad6}
Sleep, 132
SendInput {Numpad6}
SendInput {Numpad1}
SendInput {Numpad3}
SendInput {Numpad4}
Sleep, 395
SendInput {Numpad6}
SendInput {Numpad1}
SendInput {Numpad3}
SendInput {Numpad4}
Sleep, 395
SendInput {Numpad5}
SendInput {Numpad7}
SendInput {Numpad2}
Sleep, 789
SendInput {Numpad5}
Sleep, 132
SendInput {Numpad6}
Sleep, 132
SendInput {Numpad1}
Sleep, 132
SendInput {Numpad6}
Sleep, 132
SendInput {Numpad5}
SendInput {Numpad7}
SendInput {Numpad2}
SendInput {Numpad3}
Sleep, 395
SendInput {Numpad5}
SendInput {Numpad7}
SendInput {Numpad2}
SendInput {Numpad3}
Sleep, 395
SendInput {Numpad3}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 395
SendInput {Numpad7}
Sleep, 132
SendInput {Numpad6}
Sleep, 263
SendInput {Numpad5}
Sleep, 132
SendInput {Numpad6}
Sleep, 132
SendInput {Numpad1}
Sleep, 132
SendInput {Numpad6}
Sleep, 132
SendInput {Numpad4}
SendInput {Numpad6}
SendInput {Numpad1}
SendInput {Numpad2}
Sleep, 526
SendInput {Numpad9}
SendInput {Numpad2}
Sleep, 263
SendInput {Numpad0}
SendInput {Numpad5}
SendInput {Numpad7}
Sleep, 395
SendInput {Numpad6}
Sleep, 132
SendInput {Numpad5}
Sleep, 263
SendInput {Numpad0}
SendInput {Numpad5}
Sleep, 263
SendInput {Numpad9}
SendInput {Numpad5}
Sleep, 263
SendInput {Numpad3}
SendInput {Numpad5}
SendInput {Numpad2}
SendInput {Numpad7}
Sleep, 526
SendInput {Numpad3}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 1053
SendInput {Numpad5}
Sleep, 132
SendInput {Numpad6}
Sleep, 132
SendInput {Numpad1}
Sleep, 132
SendInput {Numpad6}
Sleep, 132
SendInput {Numpad6}
SendInput {Numpad1}
SendInput {Numpad3}
SendInput {Numpad4}
Sleep, 395
SendInput {Numpad6}
SendInput {Numpad1}
SendInput {Numpad3}
SendInput {Numpad4}
Sleep, 395
SendInput {Numpad5}
SendInput {Numpad7}
SendInput {Numpad2}
Sleep, 789
SendInput {Numpad5}
Sleep, 132
SendInput {Numpad6}
Sleep, 132
SendInput {Numpad1}
Sleep, 132
SendInput {Numpad6}
Sleep, 132
SendInput {Numpad5}
SendInput {Numpad3}
Sleep, 526
SendInput {Numpad7}
SendInput {Numpad3}
Sleep, 263
SendInput {Numpad9}
SendInput {Numpad1}
SendInput {Numpad6}
Sleep, 395
SendInput {Numpad0}
SendInput {Numpad7}
Sleep, 132
SendInput {Numpad6}
Sleep, 263
SendInput {Numpad5}
Sleep, 132
SendInput {Numpad6}
Sleep, 132
SendInput {Numpad1}
Sleep, 132
SendInput {Numpad6}
Sleep, 132
SendInput {Numpad4}
SendInput {Numpad6}
SendInput {Numpad1}
SendInput {Numpad2}
Sleep, 526
SendInput {Numpad9}
SendInput {Numpad2}
Sleep, 263
SendInput {Numpad0}
SendInput {Numpad5}
SendInput {Numpad7}
Sleep, 395
SendInput {Numpad6}
Sleep, 132
SendInput {Numpad5}
Sleep, 263
SendInput {Numpad0}
SendInput {Numpad5}
Sleep, 263
SendInput {Numpad9}
SendInput {Numpad5}
Sleep, 263
SendInput {Numpad3}
SendInput {Numpad5}
SendInput {Numpad2}
SendInput {Numpad7}
Sleep, 526
SendInput {Numpad3}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 1053
SendInput {Numpad5}
Sleep, 132
SendInput {Numpad6}
Sleep, 132
SendInput {Numpad1}
Sleep, 132
SendInput {Numpad6}
Sleep, 132
SendInput {Numpad6}
SendInput {Numpad1}
SendInput {Numpad3}
SendInput {Numpad4}
Sleep, 395
SendInput {Numpad6}
SendInput {Numpad1}
SendInput {Numpad3}
SendInput {Numpad4}
Sleep, 395
SendInput {Numpad5}
SendInput {Numpad7}
SendInput {Numpad2}
Sleep, 789
SendInput {Numpad5}
Sleep, 132
SendInput {Numpad6}
Sleep, 132
SendInput {Numpad1}
Sleep, 132
SendInput {Numpad6}
Sleep, 132
SendInput {Numpad5}
SendInput {Numpad7}
SendInput {Numpad2}
SendInput {Numpad3}
Sleep, 395
SendInput {Numpad5}
SendInput {Numpad7}
SendInput {Numpad2}
SendInput {Numpad3}
Sleep, 395
SendInput {Numpad3}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 395
SendInput {Numpad7}
Sleep, 132
SendInput {Numpad6}
Sleep, 263
SendInput {Numpad5}
Sleep, 132
SendInput {Numpad6}
Sleep, 132
SendInput {Numpad1}
Sleep, 132
SendInput {Numpad6}
Sleep, 132
SendInput {Numpad4}
SendInput {Numpad6}
SendInput {Numpad1}
SendInput {Numpad2}
Sleep, 526
SendInput {Numpad9}
SendInput {Numpad2}
Sleep, 263
SendInput {Numpad0}
SendInput {Numpad5}
SendInput {Numpad7}
Sleep, 395
SendInput {Numpad6}
Sleep, 132
SendInput {Numpad5}
Sleep, 263
SendInput {Numpad0}
SendInput {Numpad5}
Sleep, 263
SendInput {Numpad9}
SendInput {Numpad5}
Sleep, 263
SendInput {Numpad3}
SendInput {Numpad5}
SendInput {Numpad2}
SendInput {Numpad7}
Sleep, 526
SendInput {Numpad3}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 1053
SendInput {Numpad5}
Sleep, 132
SendInput {Numpad6}
Sleep, 132
SendInput {Numpad1}
Sleep, 132
SendInput {Numpad6}
Sleep, 132
SendInput {Numpad6}
SendInput {Numpad1}
SendInput {Numpad3}
SendInput {Numpad4}
Sleep, 395
SendInput {Numpad6}
SendInput {Numpad1}
SendInput {Numpad3}
SendInput {Numpad4}
Sleep, 395
SendInput {Numpad5}
SendInput {Numpad7}
SendInput {Numpad2}
Sleep, 789
SendInput {Numpad5}
Sleep, 132
SendInput {Numpad6}
Sleep, 132
SendInput {Numpad1}
Sleep, 132
SendInput {Numpad6}
Sleep, 132
SendInput {Numpad5}
SendInput {Numpad3}
Sleep, 526
SendInput {Numpad7}
SendInput {Numpad3}
Sleep, 263
SendInput {Numpad9}
SendInput {Numpad1}
SendInput {Numpad6}
Sleep, 395
SendInput {Numpad0}
SendInput {Numpad7}
Sleep, 132
SendInput {Numpad6}
Sleep, 263
SendInput {Numpad5}
Sleep, 132
SendInput {Numpad6}
Sleep, 132
SendInput {Numpad1}
Sleep, 132
SendInput {Numpad6}
Sleep, 132
SendInput {Numpad4}
SendInput {Numpad6}
SendInput {Numpad1}
SendInput {Numpad2}
Sleep, 526
SendInput {Numpad9}
SendInput {Numpad2}
Sleep, 263
SendInput {Numpad0}
SendInput {Numpad5}
SendInput {Numpad7}
Sleep, 395
SendInput {Numpad6}
Sleep, 132
SendInput {Numpad5}
Sleep, 263
SendInput {Numpad0}
SendInput {Numpad5}
Sleep, 263
SendInput {Numpad9}
SendInput {Numpad5}
Sleep, 263
SendInput {Numpad3}
SendInput {Numpad5}
SendInput {Numpad2}
SendInput {Numpad7}
Sleep, 526
SendInput {Numpad3}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 1053
SendInput {Numpad5}
Sleep, 132
SendInput {Numpad6}
Sleep, 132
SendInput {Numpad1}
Sleep, 132
SendInput {Numpad6}
Sleep, 132
SendInput {Numpad6}
SendInput {Numpad1}
SendInput {Numpad3}
SendInput {Numpad4}
Sleep, 395
SendInput {Numpad6}
SendInput {Numpad1}
SendInput {Numpad3}
SendInput {Numpad4}
Sleep, 395
SendInput {Numpad5}
SendInput {Numpad7}
SendInput {Numpad2}
Sleep, 789
SendInput {Numpad5}
Sleep, 132
SendInput {Numpad6}
Sleep, 132
SendInput {Numpad1}
Sleep, 132
SendInput {Numpad6}
Sleep, 132
SendInput {Numpad5}
SendInput {Numpad7}
SendInput {Numpad2}
SendInput {Numpad3}
Sleep, 395
SendInput {Numpad5}
SendInput {Numpad7}
SendInput {Numpad2}
SendInput {Numpad3}
Sleep, 395
SendInput {Numpad3}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 395
SendInput {Numpad7}
Sleep, 132
SendInput {Numpad6}
Sleep, 263
SendInput {Numpad5}
Sleep, 132
SendInput {Numpad6}
Sleep, 132
SendInput {Numpad1}
Sleep, 132
SendInput {Numpad6}
Sleep, 132
SendInput {Numpad4}
SendInput {Numpad6}
SendInput {Numpad1}
SendInput {Numpad2}
Sleep, 526
SendInput {Numpad9}
SendInput {Numpad2}
Sleep, 263
SendInput {Numpad0}
SendInput {Numpad5}
SendInput {Numpad7}
Sleep, 395
SendInput {Numpad6}
Sleep, 132
SendInput {Numpad5}
Sleep, 263
SendInput {Numpad0}
SendInput {Numpad5}
Sleep, 263
SendInput {Numpad9}
SendInput {Numpad5}
Sleep, 263
SendInput {Numpad3}
SendInput {Numpad5}
SendInput {Numpad2}
SendInput {Numpad7}
Sleep, 526
SendInput {Numpad3}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 1053
SendInput {Numpad5}
Sleep, 132
SendInput {Numpad6}
Sleep, 132
SendInput {Numpad1}
Sleep, 132
SendInput {Numpad6}
Sleep, 132
SendInput {Numpad6}
SendInput {Numpad1}
SendInput {Numpad3}
SendInput {Numpad4}
Sleep, 395
SendInput {Numpad6}
SendInput {Numpad1}
SendInput {Numpad3}
SendInput {Numpad4}
Sleep, 395
SendInput {Numpad5}
SendInput {Numpad7}
SendInput {Numpad2}
Sleep, 789
SendInput {Numpad5}
Sleep, 132
SendInput {Numpad6}
Sleep, 132
SendInput {Numpad1}
Sleep, 132
SendInput {Numpad6}
Sleep, 132
SendInput {Numpad5}
SendInput {Numpad3}
Sleep, 526
SendInput {Numpad7}
SendInput {Numpad3}
Sleep, 263
SendInput {Numpad9}
SendInput {Numpad1}
SendInput {Numpad6}
Sleep, 395
SendInput {Numpad0}
SendInput {Numpad7}
Sleep, 132
SendInput {Numpad6}
Sleep, 263
SendInput {Numpad5}
Sleep, 132
SendInput {Numpad6}
Sleep, 132
SendInput {Numpad1}
Sleep, 132
SendInput {Numpad6}
Sleep, 132
SendInput {Numpad4}
SendInput {Numpad6}
SendInput {Numpad1}
SendInput {Numpad2}
Sleep, 526
SendInput {Numpad9}
SendInput {Numpad2}
Sleep, 263
SendInput {Numpad0}
SendInput {Numpad5}
SendInput {Numpad7}
Sleep, 395
SendInput {Numpad6}
Sleep, 132
SendInput {Numpad5}
Sleep, 263
SendInput {Numpad0}
SendInput {Numpad5}
Sleep, 263
SendInput {Numpad9}
SendInput {Numpad5}
Sleep, 263
SendInput {Numpad3}
SendInput {Numpad5}
SendInput {Numpad2}
SendInput {Numpad7}
Sleep, 526
SendInput {Numpad3}
SendInput {Numpad6}
SendInput {Numpad1}
