; title: Never Gonna Give You Up
; author: Rick Astley
; instrument: Piano
; Converted by Serenade midi2ahk from Never Gonna Give You Up by Rick Astley.mid

Sleep, 2124
SendInput {Numpad1}
SendInput {Numpad6}
SendInput {Numpad3}
SendInput {Numpad4}
Sleep, 796
SendInput {Numpad0}
SendInput {Numpad2}
SendInput {Numpad7}
SendInput {Numpad5}
SendInput {Numpad3}
Sleep, 1327
SendInput {Numpad2}
SendInput {Numpad5}
SendInput {Numpad3}
SendInput {Numpad7}
Sleep, 796
SendInput {Numpad1}
SendInput {Numpad6}
SendInput {Numpad3}
Sleep, 1327
SendInput {Numpad9}
SendInput {Numpad1}
SendInput {Numpad6}
SendInput {Numpad3}
SendInput {Numpad4}
Sleep, 796
SendInput {Numpad0}
SendInput {Numpad2}
SendInput {Numpad7}
SendInput {Numpad5}
SendInput {Numpad3}
Sleep, 1327
SendInput {Numpad2}
SendInput {Numpad7}
SendInput {Numpad5}
SendInput {Numpad3}
Sleep, 531
Sleep, 265
SendInput {Numpad9}
SendInput {Numpad1}
SendInput {Numpad6}
SendInput {Numpad3}
Sleep, 531
SendInput {Numpad9}
SendInput {Numpad5}
Sleep, 133
SendInput {Numpad5}
Sleep, 133
SendInput {Numpad6}
Sleep, 133
SendInput {Numpad1}
Sleep, 133
SendInput {Numpad6}
Sleep, 133
SendInput {Numpad1}
Sleep, 133
SendInput {Numpad1}
SendInput {Numpad6}
SendInput {Numpad3}
SendInput {Numpad4}
Sleep, 796
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad2}
SendInput {Numpad7}
SendInput {Numpad5}
SendInput {Numpad3}
Sleep, 1327
SendInput {Numpad2}
SendInput {Numpad5}
SendInput {Numpad3}
SendInput {Numpad7}
Sleep, 796
SendInput {Numpad1}
SendInput {Numpad6}
SendInput {Numpad3}
Sleep, 1327
SendInput {Numpad9}
SendInput {Numpad1}
SendInput {Numpad6}
SendInput {Numpad3}
SendInput {Numpad4}
Sleep, 796
SendInput {Numpad0}
SendInput {Numpad3}
SendInput {Numpad5}
SendInput {Numpad7}
SendInput {Numpad2}
Sleep, 1062
SendInput {Numpad2}
SendInput {Numpad7}
SendInput {Numpad5}
SendInput {Numpad3}
Sleep, 265
Sleep, 265
SendInput {Numpad9}
SendInput {Numpad3}
SendInput {Numpad1}
SendInput {Numpad6}
Sleep, 265
SendInput {Numpad1}
SendInput {Numpad6}
SendInput {Numpad3}
Sleep, 531
SendInput {Numpad9}
SendInput {Numpad5}
Sleep, 133
SendInput {Numpad5}
Sleep, 265
SendInput {Numpad5}
Sleep, 133
SendInput {Numpad5}
Sleep, 133
SendInput {Numpad5}
Sleep, 265
SendInput {Numpad4}
Sleep, 133
SendInput {Numpad1}
SendInput {Numpad6}
SendInput {Numpad3}
SendInput {Numpad4}
Sleep, 531
SendInput {Numpad6}
Sleep, 265
SendInput {Numpad7}
Sleep, 265
SendInput {Numpad1}
Sleep, 265
SendInput {Numpad1}
Sleep, 265
SendInput {Numpad2}
Sleep, 265
SendInput {Numpad7}
Sleep, 265
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad6}
SendInput {Numpad7}
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 133
SendInput {Numpad6}
Sleep, 133
SendInput {Numpad5}
Sleep, 1858
SendInput {Numpad9}
SendInput {Numpad1}
SendInput {Numpad6}
SendInput {Numpad3}
SendInput {Numpad4}
Sleep, 265
SendInput {Numpad9}
SendInput {Numpad6}
Sleep, 265
SendInput {Numpad6}
Sleep, 265
SendInput {Numpad7}
Sleep, 265
SendInput {Numpad1}
Sleep, 265
SendInput {Numpad6}
Sleep, 531
SendInput {Numpad5}
Sleep, 265
SendInput {Numpad0}
SendInput {Numpad5}
SendInput {Numpad3}
SendInput {Numpad1}
SendInput {Numpad6}
Sleep, 531
SendInput {Numpad9}
SendInput {Numpad5}
Sleep, 265
SendInput {Numpad0}
SendInput {Numpad2}
SendInput {Numpad7}
SendInput {Numpad6}
SendInput {Numpad5}
Sleep, 1327
SendInput {Numpad1}
SendInput {Numpad6}
SendInput {Numpad3}
SendInput {Numpad4}
Sleep, 265
SendInput {Numpad9}
SendInput {Numpad6}
Sleep, 265
SendInput {Numpad6}
Sleep, 265
SendInput {Numpad7}
Sleep, 265
SendInput {Numpad1}
Sleep, 265
SendInput {Numpad6}
Sleep, 265
SendInput {Numpad1}
Sleep, 265
SendInput {Numpad2}
Sleep, 265
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad6}
SendInput {Numpad7}
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 232
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {F5}
Sleep, 33
SendInput {Numpad7}
Sleep, 265
SendInput {Numpad6}
Sleep, 265
SendInput {Numpad6}
Sleep, 265
SendInput {Numpad5}
Sleep, 1062
SendInput {Numpad0}
SendInput {Numpad1}
SendInput {Numpad6}
SendInput {Numpad3}
SendInput {Numpad4}
Sleep, 265
SendInput {Numpad9}
SendInput {Numpad6}
Sleep, 265
SendInput {Numpad6}
Sleep, 265
SendInput {Numpad7}
Sleep, 265
SendInput {Numpad1}
Sleep, 265
SendInput {Numpad6}
Sleep, 265
SendInput {Numpad5}
Sleep, 531
SendInput {Numpad0}
SendInput {Numpad5}
SendInput {Numpad3}
SendInput {Numpad1}
SendInput {Numpad6}
Sleep, 265
SendInput {Numpad9}
SendInput {Numpad3}
SendInput {Numpad2}
Sleep, 265
SendInput {Numpad2}
Sleep, 265
SendInput {Numpad0}
SendInput {Numpad2}
SendInput {Numpad7}
SendInput {Numpad6}
SendInput {Numpad5}
Sleep, 265
SendInput {Numpad9}
SendInput {Numpad2}
Sleep, 265
SendInput {Numpad1}
Sleep, 531
SendInput {Numpad6}
Sleep, 265
SendInput {Numpad0}
SendInput {Numpad1}
SendInput {Numpad6}
SendInput {Numpad3}
SendInput {Numpad4}
Sleep, 265
SendInput {Numpad5}
Sleep, 398
SendInput {Numpad5}
Sleep, 265
SendInput {Numpad5}
Sleep, 398
SendInput {Numpad9}
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 265
SendInput {Numpad3}
Sleep, 133
SendInput {Numpad5}
Sleep, 133
SendInput {Numpad1}
Sleep, 133
SendInput {Numpad5}
Sleep, 133
SendInput {Numpad6}
SendInput {Numpad7}
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 265
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 265
SendInput {Numpad2}
Sleep, 133
SendInput {Numpad5}
Sleep, 133
SendInput {Numpad3}
Sleep, 133
SendInput {Numpad5}
Sleep, 133
SendInput {Numpad2}
Sleep, 265
SendInput {Numpad0}
SendInput {Numpad5}
Sleep, 265
SendInput {Numpad9}
SendInput {Numpad5}
Sleep, 133
SendInput {Numpad0}
SendInput {Numpad5}
Sleep, 265
SendInput {Numpad5}
Sleep, 133
SendInput {Numpad1}
SendInput {Numpad6}
SendInput {Numpad3}
SendInput {Numpad4}
Sleep, 265
SendInput {Numpad5}
Sleep, 398
SendInput {Numpad5}
Sleep, 265
SendInput {Numpad5}
Sleep, 133
SendInput {Numpad6}
Sleep, 265
SendInput {Numpad7}
SendInput {Numpad5}
Sleep, 265
SendInput {Numpad9}
SendInput {Numpad1}
Sleep, 133
SendInput {Numpad5}
Sleep, 133
SendInput {Numpad6}
Sleep, 133
SendInput {Numpad5}
Sleep, 133
SendInput {Numpad5}
SendInput {Numpad3}
SendInput {Numpad1}
SendInput {Numpad6}
Sleep, 265
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 133
SendInput {Numpad6}
SendInput {Numpad3}
SendInput {Numpad1}
Sleep, 133
SendInput {Numpad3}
Sleep, 133
SendInput {Numpad0}
SendInput {Numpad5}
Sleep, 133
SendInput {Numpad2}
SendInput {Numpad7}
SendInput {Numpad6}
SendInput {Numpad5}
Sleep, 133
SendInput {Numpad5}
Sleep, 398
SendInput {Numpad5}
Sleep, 133
SendInput {Numpad9}
SendInput {Numpad5}
Sleep, 133
SendInput {Numpad6}
SendInput {Numpad5}
Sleep, 133
SendInput {Numpad1}
SendInput {Numpad6}
SendInput {Numpad5}
Sleep, 133
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 133
SendInput {Numpad1}
SendInput {Numpad6}
SendInput {Numpad5}
Sleep, 133
SendInput {Numpad1}
SendInput {Numpad6}
SendInput {Numpad3}
SendInput {Numpad4}
Sleep, 398
SendInput {Numpad3}
Sleep, 398
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad2}
SendInput {Numpad7}
SendInput {Numpad5}
SendInput {Numpad3}
Sleep, 796
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad5}
Sleep, 133
SendInput {Numpad6}
Sleep, 133
SendInput {Numpad1}
Sleep, 133
SendInput {Numpad6}
Sleep, 133
SendInput {Numpad2}
SendInput {Numpad5}
SendInput {Numpad3}
SendInput {Numpad7}
Sleep, 398
SendInput {Numpad2}
Sleep, 398
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad1}
SendInput {Numpad6}
SendInput {Numpad3}
Sleep, 398
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad7}
Sleep, 133
SendInput {Numpad6}
Sleep, 265
SendInput {Numpad5}
Sleep, 133
SendInput {Numpad6}
Sleep, 133
SendInput {Numpad1}
Sleep, 133
SendInput {Numpad6}
Sleep, 133
SendInput {Numpad1}
SendInput {Numpad6}
SendInput {Numpad3}
SendInput {Numpad4}
Sleep, 531
SendInput {Numpad2}
Sleep, 265
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad2}
SendInput {Numpad7}
SendInput {Numpad5}
SendInput {Numpad3}
Sleep, 398
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad6}
Sleep, 133
SendInput {Numpad5}
Sleep, 531
SendInput {Numpad5}
Sleep, 265
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad2}
SendInput {Numpad7}
SendInput {Numpad5}
SendInput {Numpad3}
Sleep, 531
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad1}
Sleep, 265
SendInput {Numpad0}
SendInput {Numpad1}
SendInput {Numpad6}
SendInput {Numpad3}
Sleep, 531
SendInput {Numpad9}
SendInput {Numpad5}
Sleep, 133
SendInput {Numpad5}
Sleep, 133
SendInput {Numpad6}
SendInput {Numpad5}
Sleep, 133
SendInput {Numpad1}
SendInput {Numpad6}
Sleep, 133
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 133
SendInput {Numpad1}
SendInput {Numpad6}
Sleep, 133
SendInput {Numpad1}
SendInput {Numpad6}
SendInput {Numpad3}
SendInput {Numpad4}
Sleep, 398
SendInput {Numpad3}
Sleep, 398
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad2}
SendInput {Numpad7}
SendInput {Numpad5}
SendInput {Numpad3}
Sleep, 796
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad5}
Sleep, 133
SendInput {Numpad6}
Sleep, 133
SendInput {Numpad1}
Sleep, 133
SendInput {Numpad6}
Sleep, 133
SendInput {Numpad2}
SendInput {Numpad5}
SendInput {Numpad3}
SendInput {Numpad7}
Sleep, 531
SendInput {Numpad7}
Sleep, 265
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad1}
SendInput {Numpad6}
SendInput {Numpad3}
Sleep, 398
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad7}
Sleep, 133
SendInput {Numpad6}
Sleep, 265
SendInput {Numpad5}
Sleep, 133
SendInput {Numpad6}
Sleep, 133
SendInput {Numpad1}
Sleep, 133
SendInput {Numpad6}
Sleep, 133
SendInput {Numpad1}
SendInput {Numpad6}
SendInput {Numpad3}
SendInput {Numpad4}
Sleep, 531
SendInput {Numpad2}
Sleep, 265
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad2}
SendInput {Numpad7}
SendInput {Numpad5}
SendInput {Numpad3}
Sleep, 398
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad6}
Sleep, 133
SendInput {Numpad5}
Sleep, 531
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad2}
SendInput {Numpad7}
SendInput {Numpad5}
SendInput {Numpad3}
Sleep, 265
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad2}
Sleep, 265
SendInput {Numpad0}
SendInput {Numpad3}
SendInput {Numpad1}
SendInput {Numpad6}
Sleep, 265
SendInput {Numpad1}
SendInput {Numpad6}
SendInput {Numpad3}
Sleep, 531
SendInput {Numpad9}
SendInput {Numpad5}
Sleep, 133
SendInput {Numpad5}
Sleep, 265
SendInput {Numpad5}
Sleep, 133
SendInput {Numpad5}
Sleep, 133
SendInput {Numpad5}
Sleep, 265
SendInput {Numpad4}
Sleep, 133
SendInput {Numpad1}
SendInput {Numpad6}
SendInput {Numpad3}
SendInput {Numpad4}
Sleep, 265
SendInput {Numpad1}
Sleep, 265
SendInput {Numpad1}
Sleep, 265
SendInput {Numpad6}
Sleep, 265
SendInput {Numpad1}
Sleep, 265
SendInput {Numpad2}
Sleep, 796
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad6}
SendInput {Numpad7}
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 232
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {F5}
Sleep, 33
SendInput {Numpad7}
Sleep, 265
SendInput {Numpad6}
Sleep, 265
SendInput {Numpad6}
Sleep, 265
SendInput {Numpad5}
Sleep, 1062
SendInput {Numpad0}
SendInput {Numpad1}
SendInput {Numpad6}
SendInput {Numpad3}
SendInput {Numpad4}
Sleep, 265
SendInput {Numpad6}
Sleep, 265
SendInput {Numpad9}
SendInput {Numpad6}
Sleep, 265
SendInput {Numpad7}
Sleep, 265
SendInput {Numpad1}
Sleep, 265
SendInput {Numpad6}
Sleep, 265
SendInput {Numpad5}
Sleep, 531
SendInput {Numpad0}
SendInput {Numpad5}
SendInput {Numpad3}
SendInput {Numpad1}
SendInput {Numpad6}
Sleep, 265
SendInput {Numpad9}
SendInput {Numpad5}
Sleep, 265
SendInput {Numpad5}
Sleep, 265
SendInput {Numpad0}
SendInput {Numpad2}
SendInput {Numpad7}
SendInput {Numpad6}
SendInput {Numpad5}
Sleep, 531
SendInput {Numpad9}
SendInput {Numpad3}
Sleep, 265
SendInput {Numpad2}
Sleep, 265
SendInput {Numpad1}
Sleep, 265
SendInput {Numpad0}
SendInput {Numpad1}
SendInput {Numpad6}
SendInput {Numpad3}
SendInput {Numpad4}
Sleep, 265
SendInput {Numpad9}
SendInput {Numpad1}
Sleep, 265
SendInput {Numpad1}
Sleep, 265
SendInput {Numpad6}
Sleep, 265
SendInput {Numpad1}
Sleep, 265
SendInput {Numpad6}
Sleep, 265
SendInput {Numpad1}
Sleep, 265
SendInput {Numpad2}
Sleep, 265
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad6}
SendInput {Numpad7}
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 232
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {F5}
Sleep, 33
SendInput {Numpad7}
Sleep, 265
SendInput {Numpad6}
Sleep, 265
SendInput {Numpad6}
Sleep, 265
SendInput {Numpad5}
Sleep, 1062
SendInput {Numpad0}
SendInput {Numpad1}
SendInput {Numpad6}
SendInput {Numpad3}
SendInput {Numpad4}
Sleep, 265
SendInput {Numpad9}
SendInput {Numpad6}
Sleep, 265
SendInput {Numpad6}
Sleep, 265
SendInput {Numpad7}
Sleep, 265
SendInput {Numpad1}
Sleep, 265
SendInput {Numpad6}
Sleep, 265
SendInput {Numpad5}
Sleep, 531
SendInput {Numpad0}
SendInput {Numpad5}
SendInput {Numpad3}
SendInput {Numpad1}
SendInput {Numpad6}
Sleep, 265
SendInput {Numpad9}
SendInput {Numpad3}
SendInput {Numpad2}
Sleep, 265
SendInput {Numpad3}
Sleep, 265
SendInput {Numpad0}
SendInput {Numpad2}
SendInput {Numpad7}
SendInput {Numpad6}
SendInput {Numpad5}
Sleep, 531
SendInput {Numpad9}
SendInput {Numpad1}
SendInput {Numpad2}
Sleep, 531
SendInput {Numpad6}
Sleep, 265
SendInput {Numpad0}
SendInput {Numpad1}
SendInput {Numpad6}
SendInput {Numpad3}
SendInput {Numpad4}
Sleep, 265
SendInput {Numpad5}
Sleep, 398
SendInput {Numpad5}
Sleep, 265
SendInput {Numpad5}
Sleep, 398
SendInput {Numpad9}
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 265
SendInput {Numpad3}
Sleep, 133
SendInput {Numpad5}
Sleep, 133
SendInput {Numpad2}
Sleep, 133
SendInput {Numpad5}
Sleep, 133
SendInput {Numpad6}
SendInput {Numpad7}
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 265
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 265
SendInput {Numpad2}
Sleep, 133
SendInput {Numpad5}
Sleep, 133
SendInput {Numpad3}
Sleep, 133
SendInput {Numpad5}
Sleep, 133
SendInput {Numpad2}
Sleep, 265
SendInput {Numpad0}
SendInput {Numpad5}
Sleep, 265
SendInput {Numpad9}
SendInput {Numpad5}
Sleep, 133
SendInput {Numpad0}
SendInput {Numpad5}
Sleep, 265
SendInput {Numpad5}
Sleep, 133
SendInput {Numpad1}
SendInput {Numpad6}
SendInput {Numpad3}
SendInput {Numpad4}
Sleep, 265
SendInput {Numpad5}
Sleep, 398
SendInput {Numpad5}
Sleep, 133
SendInput {Numpad6}
Sleep, 133
SendInput {Numpad5}
Sleep, 133
SendInput {Numpad6}
Sleep, 265
SendInput {Numpad7}
SendInput {Numpad5}
Sleep, 265
SendInput {Numpad9}
SendInput {Numpad1}
Sleep, 133
SendInput {Numpad5}
Sleep, 133
SendInput {Numpad6}
Sleep, 133
SendInput {Numpad5}
Sleep, 133
SendInput {Numpad5}
SendInput {Numpad3}
SendInput {Numpad1}
SendInput {Numpad6}
Sleep, 265
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 133
SendInput {Numpad6}
SendInput {Numpad3}
SendInput {Numpad1}
Sleep, 133
SendInput {Numpad3}
Sleep, 133
SendInput {Numpad0}
SendInput {Numpad5}
Sleep, 133
SendInput {Numpad2}
SendInput {Numpad7}
SendInput {Numpad6}
SendInput {Numpad5}
Sleep, 133
SendInput {Numpad5}
Sleep, 398
SendInput {Numpad5}
Sleep, 133
SendInput {Numpad9}
SendInput {Numpad5}
Sleep, 133
SendInput {Numpad6}
SendInput {Numpad5}
Sleep, 133
SendInput {Numpad1}
SendInput {Numpad6}
SendInput {Numpad5}
Sleep, 133
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 133
SendInput {Numpad1}
SendInput {Numpad6}
SendInput {Numpad5}
Sleep, 133
SendInput {Numpad1}
SendInput {Numpad6}
SendInput {Numpad3}
SendInput {Numpad4}
Sleep, 398
SendInput {Numpad3}
Sleep, 398
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad2}
SendInput {Numpad7}
SendInput {Numpad5}
SendInput {Numpad3}
Sleep, 796
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad5}
Sleep, 133
SendInput {Numpad6}
Sleep, 133
SendInput {Numpad1}
Sleep, 133
SendInput {Numpad6}
Sleep, 133
SendInput {Numpad2}
SendInput {Numpad5}
SendInput {Numpad3}
SendInput {Numpad7}
Sleep, 398
SendInput {Numpad2}
Sleep, 398
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad1}
SendInput {Numpad6}
SendInput {Numpad3}
Sleep, 398
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad7}
Sleep, 133
SendInput {Numpad6}
Sleep, 265
SendInput {Numpad5}
Sleep, 133
SendInput {Numpad6}
Sleep, 133
SendInput {Numpad1}
Sleep, 133
SendInput {Numpad6}
Sleep, 133
SendInput {Numpad1}
SendInput {Numpad6}
SendInput {Numpad3}
SendInput {Numpad4}
Sleep, 531
SendInput {Numpad2}
Sleep, 265
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad2}
SendInput {Numpad7}
SendInput {Numpad5}
SendInput {Numpad3}
Sleep, 398
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad6}
Sleep, 133
SendInput {Numpad5}
Sleep, 531
SendInput {Numpad5}
Sleep, 265
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad2}
SendInput {Numpad7}
SendInput {Numpad5}
SendInput {Numpad3}
Sleep, 531
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad1}
Sleep, 265
SendInput {Numpad0}
SendInput {Numpad1}
SendInput {Numpad6}
SendInput {Numpad3}
Sleep, 531
SendInput {Numpad9}
SendInput {Numpad5}
Sleep, 133
SendInput {Numpad5}
Sleep, 133
SendInput {Numpad6}
SendInput {Numpad5}
Sleep, 133
SendInput {Numpad1}
SendInput {Numpad6}
Sleep, 133
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 133
SendInput {Numpad1}
SendInput {Numpad6}
Sleep, 133
SendInput {Numpad1}
SendInput {Numpad6}
SendInput {Numpad3}
SendInput {Numpad4}
Sleep, 398
SendInput {Numpad3}
Sleep, 398
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad2}
SendInput {Numpad7}
SendInput {Numpad5}
SendInput {Numpad3}
Sleep, 796
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad5}
Sleep, 133
SendInput {Numpad6}
Sleep, 133
SendInput {Numpad1}
Sleep, 133
SendInput {Numpad6}
Sleep, 133
SendInput {Numpad2}
SendInput {Numpad5}
SendInput {Numpad3}
SendInput {Numpad7}
Sleep, 531
SendInput {Numpad7}
Sleep, 265
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad1}
SendInput {Numpad6}
SendInput {Numpad3}
Sleep, 398
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad7}
Sleep, 133
SendInput {Numpad6}
Sleep, 265
SendInput {Numpad5}
Sleep, 133
SendInput {Numpad6}
Sleep, 133
SendInput {Numpad1}
Sleep, 133
SendInput {Numpad6}
Sleep, 133
SendInput {Numpad1}
SendInput {Numpad6}
SendInput {Numpad3}
SendInput {Numpad4}
Sleep, 531
SendInput {Numpad2}
Sleep, 265
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad2}
SendInput {Numpad7}
SendInput {Numpad5}
SendInput {Numpad3}
Sleep, 398
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad6}
Sleep, 133
SendInput {Numpad5}
Sleep, 531
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad2}
SendInput {Numpad7}
SendInput {Numpad5}
SendInput {Numpad3}
Sleep, 265
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad2}
Sleep, 265
SendInput {Numpad0}
SendInput {Numpad3}
SendInput {Numpad1}
SendInput {Numpad6}
Sleep, 265
SendInput {Numpad1}
SendInput {Numpad6}
SendInput {Numpad3}
Sleep, 531
SendInput {Numpad9}
SendInput {Numpad5}
Sleep, 133
SendInput {Numpad5}
Sleep, 265
SendInput {Numpad5}
Sleep, 133
SendInput {Numpad5}
Sleep, 133
SendInput {Numpad5}
SendInput {Numpad6}
Sleep, 133
SendInput {Numpad1}
Sleep, 133
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 133
SendInput {Numpad1}
SendInput {Numpad6}
SendInput {Numpad3}
SendInput {Numpad4}
Sleep, 398
SendInput {Numpad3}
Sleep, 398
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad2}
SendInput {Numpad7}
SendInput {Numpad5}
SendInput {Numpad3}
Sleep, 796
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad5}
Sleep, 133
SendInput {Numpad6}
Sleep, 133
SendInput {Numpad1}
Sleep, 133
SendInput {Numpad6}
Sleep, 133
SendInput {Numpad2}
SendInput {Numpad5}
SendInput {Numpad3}
SendInput {Numpad7}
Sleep, 398
SendInput {Numpad2}
Sleep, 398
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad1}
SendInput {Numpad6}
SendInput {Numpad3}
Sleep, 398
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad7}
Sleep, 133
SendInput {Numpad6}
Sleep, 265
SendInput {Numpad5}
Sleep, 133
SendInput {Numpad6}
Sleep, 133
SendInput {Numpad1}
Sleep, 133
SendInput {Numpad6}
Sleep, 133
SendInput {Numpad1}
SendInput {Numpad6}
SendInput {Numpad3}
SendInput {Numpad4}
Sleep, 531
SendInput {Numpad2}
Sleep, 265
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad2}
SendInput {Numpad7}
SendInput {Numpad5}
SendInput {Numpad3}
Sleep, 398
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad6}
Sleep, 133
SendInput {Numpad5}
Sleep, 531
SendInput {Numpad5}
Sleep, 265
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad2}
SendInput {Numpad7}
SendInput {Numpad5}
SendInput {Numpad3}
Sleep, 531
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad1}
Sleep, 265
SendInput {Numpad0}
SendInput {Numpad1}
SendInput {Numpad6}
SendInput {Numpad3}
Sleep, 531
SendInput {Numpad9}
SendInput {Numpad5}
Sleep, 133
SendInput {Numpad5}
Sleep, 133
SendInput {Numpad6}
SendInput {Numpad5}
Sleep, 133
SendInput {Numpad1}
SendInput {Numpad6}
Sleep, 133
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 133
SendInput {Numpad1}
SendInput {Numpad6}
Sleep, 133
SendInput {Numpad1}
SendInput {Numpad6}
SendInput {Numpad3}
SendInput {Numpad4}
Sleep, 398
SendInput {Numpad3}
Sleep, 398
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad2}
SendInput {Numpad7}
SendInput {Numpad5}
SendInput {Numpad3}
Sleep, 796
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad5}
Sleep, 133
SendInput {Numpad6}
Sleep, 133
SendInput {Numpad1}
Sleep, 133
SendInput {Numpad6}
Sleep, 133
SendInput {Numpad2}
SendInput {Numpad5}
SendInput {Numpad3}
SendInput {Numpad7}
Sleep, 531
SendInput {Numpad7}
Sleep, 265
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad1}
SendInput {Numpad6}
SendInput {Numpad3}
Sleep, 398
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad7}
Sleep, 133
SendInput {Numpad6}
Sleep, 265
SendInput {Numpad5}
Sleep, 133
SendInput {Numpad6}
Sleep, 133
SendInput {Numpad1}
Sleep, 133
SendInput {Numpad6}
Sleep, 133
SendInput {Numpad1}
SendInput {Numpad6}
SendInput {Numpad3}
SendInput {Numpad4}
Sleep, 531
SendInput {Numpad2}
Sleep, 265
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad2}
SendInput {Numpad7}
SendInput {Numpad5}
SendInput {Numpad3}
Sleep, 398
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad6}
Sleep, 133
SendInput {Numpad5}
Sleep, 531
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad2}
SendInput {Numpad7}
SendInput {Numpad5}
SendInput {Numpad3}
Sleep, 265
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad2}
Sleep, 265
SendInput {Numpad0}
SendInput {Numpad3}
SendInput {Numpad1}
SendInput {Numpad6}
Sleep, 265
SendInput {Numpad1}
SendInput {Numpad6}
SendInput {Numpad3}
Sleep, 531
SendInput {Numpad9}
SendInput {Numpad5}
Sleep, 133
SendInput {Numpad5}
Sleep, 133
SendInput {Numpad2}
Sleep, 88
SendInput {Numpad5}
Sleep, 44
SendInput {Numpad5}
Sleep, 44
SendInput {Numpad6}
Sleep, 44
SendInput {Numpad1}
Sleep, 44
SendInput {Numpad5}
Sleep, 88
SendInput {Numpad1}
SendInput {Numpad6}
Sleep, 44
SendInput {Numpad5}
Sleep, 265
SendInput {Numpad4}
Sleep, 133
SendInput {Numpad3}
SendInput {Numpad6}
SendInput {Numpad5}
Sleep, 398
SendInput {Numpad6}
SendInput {Numpad4}
Sleep, 398
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 265
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 133
SendInput {Numpad2}
Sleep, 133
SendInput {Numpad3}
Sleep, 133
SendInput {Numpad6}
SendInput {Numpad4}
SendInput {Numpad5}
Sleep, 133
SendInput {Numpad5}
Sleep, 133
SendInput {Numpad6}
Sleep, 133
SendInput {Numpad6}
SendInput {Numpad4}
Sleep, 133
SendInput {Numpad6}
Sleep, 133
SendInput {Numpad4}
SendInput {Numpad6}
SendInput {Numpad2}
Sleep, 265
SendInput {Numpad3}
SendInput {Numpad1}
Sleep, 133
SendInput {Numpad3}
SendInput {Numpad1}
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 398
SendInput {Numpad3}
SendInput {Numpad1}
SendInput {Numpad7}
SendInput {Numpad5}
Sleep, 133
SendInput {Numpad3}
SendInput {Numpad1}
Sleep, 398
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad6}
Sleep, 133
SendInput {Numpad6}
Sleep, 133
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 133
SendInput {Numpad2}
Sleep, 265
SendInput {Numpad2}
Sleep, 133
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad3}
SendInput {Numpad6}
SendInput {Numpad5}
Sleep, 398
SendInput {Numpad6}
SendInput {Numpad4}
Sleep, 398
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 265
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 133
SendInput {Numpad2}
Sleep, 133
SendInput {Numpad3}
Sleep, 133
SendInput {Numpad6}
SendInput {Numpad4}
SendInput {Numpad5}
Sleep, 133
SendInput {Numpad5}
Sleep, 133
SendInput {Numpad6}
Sleep, 133
SendInput {Numpad6}
SendInput {Numpad4}
Sleep, 133
SendInput {Numpad6}
Sleep, 133
SendInput {Numpad4}
SendInput {Numpad6}
SendInput {Numpad2}
Sleep, 265
SendInput {Numpad3}
SendInput {Numpad1}
Sleep, 133
SendInput {Numpad3}
SendInput {Numpad1}
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 398
SendInput {Numpad3}
SendInput {Numpad1}
SendInput {Numpad7}
SendInput {Numpad5}
Sleep, 133
SendInput {Numpad3}
SendInput {Numpad1}
Sleep, 398
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad6}
Sleep, 133
SendInput {Numpad6}
Sleep, 133
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 133
SendInput {Numpad2}
Sleep, 265
SendInput {Numpad2}
Sleep, 133
SendInput {Numpad3}
SendInput {Numpad6}
SendInput {Numpad5}
Sleep, 265
SendInput {Numpad9}
SendInput {Numpad5}
Sleep, 133
SendInput {Numpad6}
SendInput {Numpad4}
Sleep, 133
SendInput {Numpad1}
Sleep, 133
SendInput {Numpad6}
Sleep, 133
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 265
SendInput {Numpad5}
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 133
SendInput {Numpad6}
SendInput {Numpad2}
Sleep, 133
SendInput {Numpad1}
SendInput {Numpad3}
Sleep, 133
SendInput {Numpad6}
SendInput {Numpad4}
SendInput {Numpad5}
Sleep, 133
SendInput {Numpad3}
SendInput {Numpad5}
Sleep, 133
SendInput {Numpad6}
Sleep, 133
SendInput {Numpad6}
SendInput {Numpad4}
Sleep, 133
SendInput {Numpad6}
Sleep, 133
SendInput {Numpad9}
SendInput {Numpad4}
SendInput {Numpad6}
SendInput {Numpad2}
Sleep, 265
SendInput {Numpad3}
SendInput {Numpad1}
Sleep, 133
SendInput {Numpad3}
SendInput {Numpad1}
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 398
SendInput {Numpad3}
SendInput {Numpad1}
SendInput {Numpad7}
SendInput {Numpad5}
Sleep, 133
SendInput {Numpad3}
SendInput {Numpad1}
Sleep, 398
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad6}
Sleep, 133
SendInput {Numpad6}
Sleep, 133
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 133
SendInput {Numpad2}
Sleep, 265
SendInput {Numpad2}
Sleep, 133
SendInput {Numpad3}
SendInput {Numpad6}
SendInput {Numpad5}
Sleep, 265
SendInput {Numpad9}
SendInput {Numpad5}
Sleep, 133
SendInput {Numpad6}
SendInput {Numpad4}
Sleep, 133
SendInput {Numpad1}
Sleep, 133
SendInput {Numpad6}
Sleep, 133
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 265
SendInput {Numpad5}
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 133
SendInput {Numpad6}
SendInput {Numpad2}
Sleep, 133
SendInput {Numpad1}
SendInput {Numpad3}
Sleep, 133
SendInput {Numpad6}
SendInput {Numpad4}
SendInput {Numpad5}
Sleep, 133
SendInput {Numpad3}
SendInput {Numpad5}
Sleep, 133
SendInput {Numpad6}
Sleep, 133
SendInput {Numpad6}
SendInput {Numpad4}
Sleep, 133
SendInput {Numpad6}
Sleep, 133
SendInput {Numpad9}
SendInput {Numpad4}
SendInput {Numpad6}
SendInput {Numpad2}
Sleep, 265
SendInput {Numpad3}
SendInput {Numpad1}
Sleep, 133
SendInput {Numpad3}
SendInput {Numpad1}
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 398
SendInput {Numpad3}
SendInput {Numpad1}
SendInput {Numpad7}
SendInput {Numpad5}
Sleep, 133
SendInput {Numpad3}
SendInput {Numpad1}
Sleep, 398
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad6}
Sleep, 133
SendInput {Numpad6}
Sleep, 133
SendInput {Numpad1}
Sleep, 133
SendInput {Numpad2}
Sleep, 265
SendInput {Numpad2}
Sleep, 398
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad1}
Sleep, 265
SendInput {Numpad1}
Sleep, 265
SendInput {Numpad6}
Sleep, 265
SendInput {Numpad1}
Sleep, 265
SendInput {Numpad2}
Sleep, 1029
SendInput {F5}
Sleep, 33
SendInput {Numpad7}
Sleep, 265
SendInput {Numpad6}
Sleep, 265
SendInput {Numpad6}
Sleep, 265
SendInput {Numpad5}
Sleep, 1327
SendInput {Numpad0}
SendInput {Numpad6}
Sleep, 265
SendInput {Numpad9}
SendInput {Numpad6}
Sleep, 265
SendInput {Numpad7}
Sleep, 265
SendInput {Numpad1}
Sleep, 265
SendInput {Numpad6}
Sleep, 265
SendInput {Numpad5}
Sleep, 531
SendInput {Numpad0}
SendInput {Numpad1}
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 265
SendInput {Numpad9}
SendInput {Numpad5}
Sleep, 265
SendInput {Numpad5}
Sleep, 265
SendInput {Numpad0}
SendInput {Numpad2}
SendInput {Numpad7}
SendInput {Numpad5}
Sleep, 531
SendInput {Numpad9}
SendInput {Numpad3}
Sleep, 265
SendInput {Numpad2}
Sleep, 265
SendInput {Numpad1}
Sleep, 265
SendInput {Numpad2}
Sleep, 265
SendInput {Numpad1}
Sleep, 265
SendInput {Numpad1}
Sleep, 265
SendInput {Numpad6}
Sleep, 265
SendInput {Numpad1}
Sleep, 265
SendInput {Numpad6}
Sleep, 265
SendInput {Numpad1}
Sleep, 265
SendInput {Numpad2}
Sleep, 498
SendInput {F5}
Sleep, 33
SendInput {Numpad7}
Sleep, 265
SendInput {Numpad6}
Sleep, 265
SendInput {Numpad6}
Sleep, 265
SendInput {Numpad5}
Sleep, 1327
SendInput {Numpad6}
Sleep, 265
SendInput {Numpad6}
Sleep, 265
SendInput {Numpad7}
Sleep, 265
SendInput {Numpad1}
Sleep, 265
SendInput {Numpad6}
Sleep, 265
SendInput {Numpad5}
Sleep, 531
SendInput {Numpad0}
SendInput {Numpad1}
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 265
SendInput {Numpad9}
SendInput {Numpad2}
Sleep, 265
SendInput {Numpad3}
Sleep, 265
SendInput {Numpad0}
SendInput {Numpad2}
SendInput {Numpad7}
SendInput {Numpad5}
SendInput {Numpad3}
Sleep, 531
SendInput {Numpad9}
SendInput {Numpad2}
Sleep, 796
SendInput {Numpad0}
SendInput {Numpad1}
SendInput {Numpad6}
SendInput {Numpad3}
SendInput {Numpad4}
Sleep, 265
SendInput {Numpad5}
Sleep, 398
SendInput {Numpad5}
Sleep, 265
SendInput {Numpad5}
Sleep, 398
SendInput {Numpad9}
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 265
SendInput {Numpad3}
Sleep, 133
SendInput {Numpad5}
Sleep, 133
SendInput {Numpad1}
Sleep, 133
SendInput {Numpad5}
Sleep, 133
SendInput {Numpad6}
SendInput {Numpad7}
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 265
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 265
SendInput {Numpad2}
Sleep, 133
SendInput {Numpad5}
Sleep, 133
SendInput {Numpad3}
Sleep, 133
SendInput {Numpad5}
Sleep, 133
SendInput {Numpad2}
Sleep, 265
SendInput {Numpad0}
SendInput {Numpad5}
Sleep, 265
SendInput {Numpad9}
SendInput {Numpad5}
Sleep, 133
SendInput {Numpad0}
SendInput {Numpad5}
Sleep, 265
SendInput {Numpad5}
Sleep, 133
SendInput {Numpad1}
SendInput {Numpad6}
SendInput {Numpad3}
SendInput {Numpad4}
Sleep, 265
SendInput {Numpad5}
Sleep, 398
SendInput {Numpad5}
Sleep, 265
SendInput {Numpad5}
Sleep, 133
SendInput {Numpad6}
Sleep, 265
SendInput {Numpad7}
SendInput {Numpad5}
Sleep, 265
SendInput {Numpad9}
SendInput {Numpad1}
Sleep, 133
SendInput {Numpad5}
Sleep, 133
SendInput {Numpad6}
Sleep, 133
SendInput {Numpad5}
Sleep, 133
SendInput {Numpad5}
SendInput {Numpad3}
SendInput {Numpad1}
SendInput {Numpad6}
Sleep, 265
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 133
SendInput {Numpad6}
SendInput {Numpad3}
SendInput {Numpad1}
Sleep, 133
SendInput {Numpad3}
Sleep, 133
SendInput {Numpad0}
SendInput {Numpad5}
Sleep, 133
SendInput {Numpad2}
SendInput {Numpad7}
SendInput {Numpad6}
SendInput {Numpad5}
Sleep, 133
SendInput {Numpad5}
Sleep, 398
SendInput {Numpad5}
Sleep, 133
SendInput {Numpad9}
SendInput {Numpad5}
Sleep, 133
SendInput {Numpad6}
SendInput {Numpad5}
Sleep, 133
SendInput {Numpad1}
SendInput {Numpad6}
SendInput {Numpad5}
Sleep, 133
SendInput {Numpad1}
Sleep, 133
SendInput {Numpad1}
SendInput {Numpad6}
SendInput {Numpad5}
Sleep, 133
SendInput {Numpad1}
SendInput {Numpad6}
SendInput {Numpad3}
SendInput {Numpad4}
Sleep, 398
SendInput {Numpad3}
Sleep, 398
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad2}
SendInput {Numpad7}
SendInput {Numpad5}
SendInput {Numpad3}
Sleep, 796
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad5}
Sleep, 133
SendInput {Numpad6}
Sleep, 133
SendInput {Numpad1}
Sleep, 133
SendInput {Numpad6}
Sleep, 133
SendInput {Numpad2}
SendInput {Numpad5}
SendInput {Numpad3}
SendInput {Numpad7}
Sleep, 398
SendInput {Numpad2}
Sleep, 398
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad1}
SendInput {Numpad6}
SendInput {Numpad3}
Sleep, 398
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad7}
Sleep, 133
SendInput {Numpad6}
Sleep, 265
SendInput {Numpad5}
Sleep, 133
SendInput {Numpad6}
Sleep, 133
SendInput {Numpad1}
Sleep, 133
SendInput {Numpad6}
Sleep, 133
SendInput {Numpad1}
SendInput {Numpad6}
SendInput {Numpad3}
SendInput {Numpad4}
Sleep, 531
SendInput {Numpad2}
Sleep, 265
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad2}
SendInput {Numpad7}
SendInput {Numpad5}
SendInput {Numpad3}
Sleep, 398
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad6}
Sleep, 133
SendInput {Numpad5}
Sleep, 531
SendInput {Numpad5}
Sleep, 265
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad2}
SendInput {Numpad7}
SendInput {Numpad5}
SendInput {Numpad3}
Sleep, 531
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad1}
Sleep, 265
SendInput {Numpad0}
SendInput {Numpad1}
SendInput {Numpad6}
SendInput {Numpad3}
Sleep, 531
SendInput {Numpad9}
SendInput {Numpad5}
Sleep, 133
SendInput {Numpad5}
Sleep, 133
SendInput {Numpad6}
SendInput {Numpad5}
Sleep, 133
SendInput {Numpad1}
SendInput {Numpad6}
Sleep, 133
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 133
SendInput {Numpad1}
SendInput {Numpad6}
Sleep, 133
SendInput {Numpad1}
SendInput {Numpad6}
SendInput {Numpad3}
SendInput {Numpad4}
Sleep, 398
SendInput {Numpad3}
Sleep, 398
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad2}
SendInput {Numpad7}
SendInput {Numpad5}
SendInput {Numpad3}
Sleep, 796
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad5}
Sleep, 133
SendInput {Numpad6}
Sleep, 133
SendInput {Numpad1}
Sleep, 133
SendInput {Numpad6}
Sleep, 133
SendInput {Numpad2}
SendInput {Numpad5}
SendInput {Numpad3}
SendInput {Numpad7}
Sleep, 531
SendInput {Numpad7}
Sleep, 265
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad1}
SendInput {Numpad6}
SendInput {Numpad3}
Sleep, 398
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad7}
Sleep, 133
SendInput {Numpad6}
Sleep, 265
SendInput {Numpad5}
Sleep, 133
SendInput {Numpad6}
Sleep, 133
SendInput {Numpad1}
Sleep, 133
SendInput {Numpad6}
Sleep, 133
SendInput {Numpad1}
SendInput {Numpad6}
SendInput {Numpad3}
SendInput {Numpad4}
Sleep, 531
SendInput {Numpad2}
Sleep, 265
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad2}
SendInput {Numpad7}
SendInput {Numpad5}
SendInput {Numpad3}
Sleep, 398
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad6}
Sleep, 133
SendInput {Numpad5}
Sleep, 531
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad2}
SendInput {Numpad7}
SendInput {Numpad5}
SendInput {Numpad3}
Sleep, 265
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad2}
Sleep, 265
SendInput {Numpad0}
SendInput {Numpad3}
SendInput {Numpad1}
SendInput {Numpad6}
Sleep, 265
SendInput {Numpad1}
SendInput {Numpad6}
SendInput {Numpad3}
Sleep, 531
SendInput {Numpad9}
SendInput {Numpad5}
Sleep, 133
SendInput {Numpad5}
Sleep, 265
SendInput {Numpad5}
Sleep, 133
SendInput {Numpad5}
Sleep, 133
SendInput {Numpad5}
SendInput {Numpad6}
Sleep, 133
SendInput {Numpad1}
Sleep, 133
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 133
SendInput {Numpad1}
SendInput {Numpad6}
SendInput {Numpad3}
SendInput {Numpad4}
Sleep, 398
SendInput {Numpad3}
Sleep, 398
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad2}
SendInput {Numpad7}
SendInput {Numpad5}
SendInput {Numpad3}
Sleep, 796
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad5}
Sleep, 133
SendInput {Numpad6}
Sleep, 133
SendInput {Numpad1}
Sleep, 133
SendInput {Numpad6}
Sleep, 133
SendInput {Numpad2}
SendInput {Numpad5}
SendInput {Numpad3}
SendInput {Numpad7}
Sleep, 398
SendInput {Numpad2}
Sleep, 398
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad1}
SendInput {Numpad6}
SendInput {Numpad3}
Sleep, 398
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad7}
Sleep, 133
SendInput {Numpad6}
Sleep, 265
SendInput {Numpad5}
Sleep, 133
SendInput {Numpad6}
Sleep, 133
SendInput {Numpad1}
Sleep, 133
SendInput {Numpad6}
Sleep, 133
SendInput {Numpad1}
SendInput {Numpad6}
SendInput {Numpad3}
SendInput {Numpad4}
Sleep, 531
SendInput {Numpad2}
Sleep, 265
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad2}
SendInput {Numpad7}
SendInput {Numpad5}
SendInput {Numpad3}
Sleep, 398
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad6}
Sleep, 133
SendInput {Numpad5}
Sleep, 531
SendInput {Numpad5}
Sleep, 265
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad2}
SendInput {Numpad7}
SendInput {Numpad5}
SendInput {Numpad3}
Sleep, 531
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad1}
Sleep, 265
SendInput {Numpad0}
SendInput {Numpad1}
SendInput {Numpad6}
SendInput {Numpad3}
Sleep, 531
SendInput {Numpad9}
SendInput {Numpad5}
Sleep, 133
SendInput {Numpad5}
Sleep, 133
SendInput {Numpad6}
SendInput {Numpad5}
Sleep, 133
SendInput {Numpad1}
SendInput {Numpad6}
Sleep, 133
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 133
SendInput {Numpad1}
SendInput {Numpad6}
Sleep, 133
SendInput {Numpad1}
SendInput {Numpad6}
SendInput {Numpad3}
SendInput {Numpad4}
Sleep, 398
SendInput {Numpad3}
Sleep, 398
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad2}
SendInput {Numpad7}
SendInput {Numpad5}
SendInput {Numpad3}
Sleep, 796
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad5}
Sleep, 133
SendInput {Numpad6}
Sleep, 133
SendInput {Numpad1}
Sleep, 133
SendInput {Numpad6}
Sleep, 133
SendInput {Numpad2}
SendInput {Numpad5}
SendInput {Numpad3}
SendInput {Numpad7}
Sleep, 531
SendInput {Numpad7}
Sleep, 265
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad1}
SendInput {Numpad6}
SendInput {Numpad3}
Sleep, 398
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad7}
Sleep, 133
SendInput {Numpad6}
Sleep, 265
SendInput {Numpad5}
Sleep, 133
SendInput {Numpad6}
Sleep, 133
SendInput {Numpad1}
Sleep, 133
SendInput {Numpad6}
Sleep, 133
SendInput {Numpad1}
SendInput {Numpad6}
SendInput {Numpad3}
SendInput {Numpad4}
Sleep, 531
SendInput {Numpad2}
Sleep, 265
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad2}
SendInput {Numpad7}
SendInput {Numpad5}
SendInput {Numpad3}
Sleep, 398
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad6}
Sleep, 133
SendInput {Numpad5}
Sleep, 531
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad2}
SendInput {Numpad7}
SendInput {Numpad5}
SendInput {Numpad3}
Sleep, 265
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad2}
Sleep, 265
SendInput {Numpad0}
SendInput {Numpad3}
SendInput {Numpad1}
SendInput {Numpad6}
Sleep, 265
SendInput {Numpad1}
SendInput {Numpad6}
SendInput {Numpad3}
Sleep, 531
SendInput {Numpad9}
SendInput {Numpad5}
Sleep, 133
SendInput {Numpad5}
Sleep, 265
SendInput {Numpad5}
Sleep, 133
SendInput {Numpad5}
Sleep, 133
SendInput {Numpad5}
SendInput {Numpad6}
Sleep, 133
SendInput {Numpad1}
Sleep, 133
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 133
SendInput {Numpad1}
SendInput {Numpad6}
SendInput {Numpad3}
SendInput {Numpad4}
Sleep, 398
SendInput {Numpad3}
Sleep, 398
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad2}
SendInput {Numpad7}
SendInput {Numpad5}
SendInput {Numpad3}
Sleep, 796
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad5}
Sleep, 133
SendInput {Numpad6}
Sleep, 133
SendInput {Numpad1}
Sleep, 133
SendInput {Numpad6}
Sleep, 133
SendInput {Numpad2}
SendInput {Numpad5}
SendInput {Numpad3}
SendInput {Numpad7}
Sleep, 398
SendInput {Numpad2}
Sleep, 398
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad1}
SendInput {Numpad6}
SendInput {Numpad3}
Sleep, 398
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad7}
Sleep, 133
SendInput {Numpad6}
Sleep, 265
SendInput {Numpad5}
Sleep, 133
SendInput {Numpad6}
Sleep, 133
SendInput {Numpad1}
Sleep, 133
SendInput {Numpad6}
Sleep, 133
SendInput {Numpad1}
SendInput {Numpad6}
SendInput {Numpad3}
SendInput {Numpad4}
Sleep, 531
SendInput {Numpad2}
Sleep, 265
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad2}
SendInput {Numpad7}
SendInput {Numpad5}
SendInput {Numpad3}
Sleep, 398
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad6}
Sleep, 133
SendInput {Numpad5}
Sleep, 531
SendInput {Numpad5}
Sleep, 265
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad2}
SendInput {Numpad7}
SendInput {Numpad5}
SendInput {Numpad3}
Sleep, 531
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad1}
Sleep, 265
SendInput {Numpad0}
SendInput {Numpad1}
SendInput {Numpad6}
SendInput {Numpad3}
Sleep, 531
SendInput {Numpad9}
SendInput {Numpad5}
Sleep, 133
SendInput {Numpad5}
Sleep, 133
SendInput {Numpad6}
SendInput {Numpad5}
Sleep, 133
SendInput {Numpad1}
SendInput {Numpad6}
Sleep, 133
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 133
SendInput {Numpad1}
SendInput {Numpad6}
Sleep, 133
SendInput {Numpad1}
SendInput {Numpad6}
SendInput {Numpad3}
SendInput {Numpad4}
Sleep, 398
SendInput {Numpad3}
Sleep, 398
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad2}
SendInput {Numpad7}
SendInput {Numpad5}
SendInput {Numpad3}
Sleep, 796
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad5}
Sleep, 133
SendInput {Numpad6}
Sleep, 133
SendInput {Numpad1}
Sleep, 133
SendInput {Numpad6}
Sleep, 133
SendInput {Numpad2}
SendInput {Numpad5}
SendInput {Numpad3}
SendInput {Numpad7}
Sleep, 531
SendInput {Numpad7}
Sleep, 265
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad1}
SendInput {Numpad6}
SendInput {Numpad3}
Sleep, 398
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad7}
Sleep, 133
SendInput {Numpad6}
Sleep, 265
SendInput {Numpad5}
Sleep, 133
SendInput {Numpad6}
Sleep, 133
SendInput {Numpad1}
Sleep, 133
SendInput {Numpad6}
Sleep, 133
SendInput {Numpad1}
SendInput {Numpad6}
SendInput {Numpad3}
SendInput {Numpad4}
Sleep, 531
SendInput {Numpad2}
Sleep, 265
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad2}
SendInput {Numpad7}
SendInput {Numpad5}
SendInput {Numpad3}
Sleep, 398
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad6}
Sleep, 133
SendInput {Numpad5}
Sleep, 531
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad2}
SendInput {Numpad7}
SendInput {Numpad5}
SendInput {Numpad3}
Sleep, 265
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad2}
Sleep, 265
SendInput {Numpad0}
SendInput {Numpad3}
SendInput {Numpad1}
SendInput {Numpad6}
Sleep, 265
SendInput {Numpad1}
SendInput {Numpad6}
SendInput {Numpad3}
Sleep, 531
SendInput {Numpad9}
SendInput {Numpad5}
Sleep, 133
SendInput {Numpad5}
Sleep, 265
SendInput {Numpad5}
Sleep, 133
SendInput {Numpad5}
Sleep, 133
SendInput {Numpad5}
SendInput {Numpad6}
Sleep, 133
SendInput {Numpad1}
Sleep, 133
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 133
SendInput {Numpad1}
SendInput {Numpad6}
SendInput {Numpad3}
SendInput {Numpad4}
Sleep, 398
SendInput {Numpad3}
Sleep, 398
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad2}
SendInput {Numpad7}
SendInput {Numpad5}
SendInput {Numpad3}
Sleep, 796
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad5}
Sleep, 133
SendInput {Numpad6}
Sleep, 133
SendInput {Numpad1}
Sleep, 133
SendInput {Numpad6}
Sleep, 133
SendInput {Numpad2}
SendInput {Numpad5}
SendInput {Numpad3}
SendInput {Numpad7}
Sleep, 398
SendInput {Numpad2}
Sleep, 398
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad1}
SendInput {Numpad6}
SendInput {Numpad3}
Sleep, 398
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad7}
Sleep, 133
SendInput {Numpad6}
Sleep, 265
SendInput {Numpad5}
Sleep, 133
SendInput {Numpad6}
Sleep, 133
SendInput {Numpad1}
Sleep, 133
SendInput {Numpad6}
Sleep, 133
SendInput {Numpad1}
SendInput {Numpad6}
SendInput {Numpad3}
SendInput {Numpad4}
Sleep, 531
SendInput {Numpad2}
Sleep, 265
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad2}
SendInput {Numpad7}
SendInput {Numpad5}
SendInput {Numpad3}
Sleep, 398
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad6}
Sleep, 133
SendInput {Numpad5}
Sleep, 531
SendInput {Numpad5}
Sleep, 265
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad2}
SendInput {Numpad7}
SendInput {Numpad5}
SendInput {Numpad3}
Sleep, 531
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad1}
Sleep, 265
SendInput {Numpad0}
SendInput {Numpad1}
SendInput {Numpad6}
SendInput {Numpad3}
Sleep, 531
SendInput {Numpad9}
SendInput {Numpad5}
Sleep, 133
SendInput {Numpad5}
Sleep, 133
SendInput {Numpad6}
SendInput {Numpad5}
Sleep, 133
SendInput {Numpad1}
SendInput {Numpad6}
Sleep, 133
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 133
SendInput {Numpad1}
SendInput {Numpad6}
Sleep, 133
SendInput {Numpad1}
SendInput {Numpad6}
SendInput {Numpad3}
SendInput {Numpad4}
Sleep, 398
SendInput {Numpad3}
Sleep, 398
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad2}
SendInput {Numpad7}
SendInput {Numpad5}
SendInput {Numpad3}
Sleep, 796
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad5}
Sleep, 133
SendInput {Numpad6}
Sleep, 133
SendInput {Numpad1}
Sleep, 133
SendInput {Numpad6}
Sleep, 133
SendInput {Numpad2}
SendInput {Numpad5}
SendInput {Numpad3}
SendInput {Numpad7}
Sleep, 531
SendInput {Numpad7}
Sleep, 265
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad1}
SendInput {Numpad6}
SendInput {Numpad3}
Sleep, 398
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad7}
Sleep, 133
SendInput {Numpad6}
Sleep, 265
SendInput {Numpad5}
Sleep, 133
SendInput {Numpad6}
Sleep, 133
SendInput {Numpad1}
Sleep, 133
SendInput {Numpad6}
Sleep, 133
SendInput {Numpad1}
SendInput {Numpad6}
SendInput {Numpad3}
SendInput {Numpad4}
Sleep, 531
SendInput {Numpad2}
Sleep, 265
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad2}
SendInput {Numpad7}
SendInput {Numpad5}
SendInput {Numpad3}
Sleep, 398
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad6}
Sleep, 133
SendInput {Numpad5}
Sleep, 531
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad2}
SendInput {Numpad7}
SendInput {Numpad5}
SendInput {Numpad3}
Sleep, 265
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad2}
Sleep, 265
SendInput {Numpad0}
SendInput {Numpad3}
SendInput {Numpad1}
SendInput {Numpad6}
Sleep, 265
SendInput {Numpad1}
SendInput {Numpad6}
SendInput {Numpad3}
Sleep, 531
SendInput {Numpad9}
SendInput {Numpad5}
Sleep, 133
SendInput {Numpad5}
Sleep, 265
SendInput {Numpad5}
Sleep, 133
SendInput {Numpad5}
Sleep, 133
SendInput {Numpad5}
Sleep, 265
SendInput {Numpad4}
