; title: Starlight
; author: Muse
; instrument: Piano
; Converted by Serenade Music Converter v1.1.1

SendInput {Numpad9}
Sleep, 60
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 248
SendInput {Numpad1}
Sleep, 248
SendInput {Numpad1}
Sleep, 248
SendInput {Numpad1}
Sleep, 248
SendInput {Numpad1}
Sleep, 248
SendInput {Numpad1}
Sleep, 248
SendInput {Numpad1}
Sleep, 248
SendInput {Numpad1}
Sleep, 248
SendInput {Numpad1}
Sleep, 248
SendInput {Numpad1}
Sleep, 248
SendInput {Numpad1}
Sleep, 248
SendInput {Numpad1}
Sleep, 248
SendInput {Numpad1}
Sleep, 248
SendInput {Numpad1}
Sleep, 248
SendInput {Numpad1}
Sleep, 248
SendInput {Numpad1}
Sleep, 248
SendInput {Numpad1}
Sleep, 248
SendInput {Numpad1}
Sleep, 248
SendInput {Numpad1}
Sleep, 248
SendInput {Numpad1}
Sleep, 248
SendInput {Numpad1}
Sleep, 248
SendInput {Numpad1}
Sleep, 248
SendInput {Numpad1}
Sleep, 248
SendInput {Numpad1}
Sleep, 248
SendInput {Numpad1}
Sleep, 248
SendInput {Numpad1}
Sleep, 248
SendInput {Numpad1}
Sleep, 248
SendInput {Numpad1}
Sleep, 248
SendInput {Numpad1}
Sleep, 248
SendInput {Numpad1}
Sleep, 248
SendInput {Numpad1}
Sleep, 248
SendInput {Numpad1}
Sleep, 128
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad3}
SendInput {Numpad1}
Sleep, 128
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad1}
Sleep, 128
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad1}
Sleep, 128
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad1}
Sleep, 188
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad5}
SendInput {Numpad1}
Sleep, 188
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad1}
Sleep, 128
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad3}
SendInput {Numpad1}
Sleep, 248
SendInput {Numpad4}
SendInput {Numpad2}
Sleep, 128
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad2}
Sleep, 128
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad2}
Sleep, 128
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad2}
Sleep, 188
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad6}
SendInput {Numpad2}
Sleep, 188
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad2}
Sleep, 128
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad4}
SendInput {Numpad1}
Sleep, 248
SendInput {Numpad3}
SendInput {Numpad2}
Sleep, 248
SendInput {Numpad2}
SendInput {Numpad3}
Sleep, 248
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 128
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad6}
Sleep, 128
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad1}
SendInput {Numpad6}
Sleep, 128
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad6}
Sleep, 188
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad6}
Sleep, 188
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad6}
Sleep, 128
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 248
SendInput {Numpad4}
Sleep, 128
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad4}
Sleep, 128
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad1}
SendInput {Numpad4}
Sleep, 128
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad4}
Sleep, 188
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad6}
SendInput {Numpad4}
Sleep, 188
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad4}
Sleep, 128
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad4}
SendInput {Numpad3}
Sleep, 248
SendInput {Numpad3}
SendInput {Numpad4}
Sleep, 248
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 248
SendInput {Numpad3}
SendInput {Numpad1}
Sleep, 128
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad1}
Sleep, 128
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad1}
Sleep, 128
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad1}
Sleep, 188
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad5}
SendInput {Numpad1}
Sleep, 188
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad1}
Sleep, 128
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad3}
SendInput {Numpad1}
Sleep, 248
SendInput {Numpad4}
SendInput {Numpad2}
Sleep, 128
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad2}
Sleep, 128
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad2}
Sleep, 128
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad2}
Sleep, 188
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad6}
SendInput {Numpad2}
Sleep, 188
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad2}
Sleep, 128
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad4}
SendInput {Numpad1}
Sleep, 248
SendInput {Numpad3}
SendInput {Numpad2}
Sleep, 248
SendInput {Numpad2}
SendInput {Numpad3}
Sleep, 248
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 128
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad6}
Sleep, 128
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad1}
SendInput {Numpad6}
Sleep, 128
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad6}
Sleep, 188
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad6}
Sleep, 188
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad6}
Sleep, 128
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 248
SendInput {Numpad4}
Sleep, 128
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad4}
Sleep, 128
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad1}
SendInput {Numpad4}
Sleep, 128
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad4}
Sleep, 188
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad6}
SendInput {Numpad4}
Sleep, 188
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad4}
Sleep, 128
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad4}
SendInput {Numpad3}
Sleep, 248
SendInput {Numpad3}
SendInput {Numpad4}
Sleep, 248
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 248
SendInput {Numpad2}
SendInput {Numpad1}
Sleep, 128
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad1}
Sleep, 248
SendInput {Numpad1}
Sleep, 128
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad1}
Sleep, 248
SendInput {Numpad1}
Sleep, 128
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad1}
Sleep, 248
SendInput {Numpad1}
Sleep, 188
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad6}
SendInput {Numpad2}
Sleep, 188
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad2}
Sleep, 128
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad2}
Sleep, 248
SendInput {Numpad2}
Sleep, 248
SendInput {Numpad1}
SendInput {Numpad2}
Sleep, 248
SendInput {Numpad2}
Sleep, 248
SendInput {Numpad3}
SendInput {Numpad1}
Sleep, 248
SendInput {Numpad2}
Sleep, 128
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad3}
Sleep, 128
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad2}
SendInput {Numpad6}
Sleep, 128
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad6}
Sleep, 248
SendInput {Numpad6}
Sleep, 128
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad1}
SendInput {Numpad6}
Sleep, 248
SendInput {Numpad1}
SendInput {Numpad6}
Sleep, 128
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad6}
Sleep, 248
SendInput {Numpad6}
Sleep, 188
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad6}
SendInput {Numpad4}
Sleep, 188
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad4}
Sleep, 128
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad2}
SendInput {Numpad4}
Sleep, 128
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad4}
Sleep, 128
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad1}
SendInput {Numpad4}
Sleep, 248
SendInput {Numpad2}
SendInput {Numpad4}
Sleep, 248
SendInput {Numpad3}
Sleep, 248
SendInput {Numpad2}
SendInput {Numpad4}
Sleep, 128
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad5}
Sleep, 128
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad2}
SendInput {Numpad1}
Sleep, 128
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad1}
Sleep, 248
SendInput {Numpad1}
Sleep, 128
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad3}
SendInput {Numpad1}
Sleep, 248
SendInput {Numpad3}
SendInput {Numpad1}
Sleep, 128
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad1}
Sleep, 248
SendInput {Numpad1}
Sleep, 188
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad6}
SendInput {Numpad2}
Sleep, 188
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad2}
Sleep, 128
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad3}
SendInput {Numpad2}
Sleep, 128
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad2}
Sleep, 128
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad2}
Sleep, 248
SendInput {Numpad3}
SendInput {Numpad2}
Sleep, 248
SendInput {Numpad4}
SendInput {Numpad1}
Sleep, 248
SendInput {Numpad3}
SendInput {Numpad2}
Sleep, 128
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad3}
Sleep, 128
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 128
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad6}
Sleep, 128
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 248
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 248
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 248
SendInput {Numpad2}
SendInput {Numpad6}
Sleep, 248
SendInput {Numpad1}
SendInput {Numpad6}
Sleep, 248
SendInput {Numpad1}
SendInput {Numpad4}
Sleep, 128
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad4}
Sleep, 248
SendInput {Numpad4}
Sleep, 248
SendInput {Numpad4}
Sleep, 248
SendInput {Numpad4}
Sleep, 248
SendInput {Numpad4}
Sleep, 248
SendInput {Numpad3}
Sleep, 248
SendInput {Numpad4}
Sleep, 248
SendInput {Numpad5}
Sleep, 128
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad2}
SendInput {Numpad1}
Sleep, 128
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad1}
Sleep, 248
SendInput {Numpad1}
Sleep, 128
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad1}
Sleep, 248
SendInput {Numpad1}
Sleep, 128
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad1}
Sleep, 248
SendInput {Numpad1}
Sleep, 188
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad6}
SendInput {Numpad2}
Sleep, 188
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad2}
Sleep, 128
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad2}
Sleep, 248
SendInput {Numpad2}
Sleep, 248
SendInput {Numpad1}
SendInput {Numpad2}
Sleep, 248
SendInput {Numpad2}
Sleep, 248
SendInput {Numpad3}
SendInput {Numpad1}
Sleep, 248
SendInput {Numpad2}
Sleep, 128
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad3}
Sleep, 128
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad2}
SendInput {Numpad6}
Sleep, 128
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad6}
Sleep, 248
SendInput {Numpad6}
Sleep, 128
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad1}
SendInput {Numpad6}
Sleep, 248
SendInput {Numpad1}
SendInput {Numpad6}
Sleep, 128
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad6}
Sleep, 248
SendInput {Numpad6}
Sleep, 188
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad6}
SendInput {Numpad4}
Sleep, 188
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad4}
Sleep, 128
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad2}
SendInput {Numpad4}
Sleep, 248
SendInput {Numpad2}
SendInput {Numpad4}
Sleep, 248
SendInput {Numpad1}
SendInput {Numpad4}
Sleep, 248
SendInput {Numpad2}
SendInput {Numpad4}
Sleep, 248
SendInput {Numpad3}
Sleep, 248
SendInput {Numpad2}
SendInput {Numpad4}
Sleep, 248
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 248
SendInput {Numpad2}
SendInput {Numpad1}
Sleep, 128
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad1}
Sleep, 248
SendInput {Numpad1}
Sleep, 128
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad3}
SendInput {Numpad1}
Sleep, 248
SendInput {Numpad3}
SendInput {Numpad1}
Sleep, 128
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad1}
Sleep, 248
SendInput {Numpad1}
Sleep, 188
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad6}
SendInput {Numpad2}
Sleep, 188
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad2}
Sleep, 128
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad3}
SendInput {Numpad2}
Sleep, 128
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad2}
Sleep, 128
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad2}
Sleep, 248
SendInput {Numpad3}
SendInput {Numpad2}
Sleep, 128
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad1}
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad4}
Sleep, 45
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad2}
Sleep, 45
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad3}
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad3}
Sleep, 128
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 128
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad6}
Sleep, 128
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 248
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 248
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 248
SendInput {Numpad2}
SendInput {Numpad6}
Sleep, 248
SendInput {Numpad1}
SendInput {Numpad6}
Sleep, 248
SendInput {Numpad1}
SendInput {Numpad6}
Sleep, 188
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad6}
SendInput {Numpad4}
Sleep, 188
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad4}
Sleep, 248
SendInput {Numpad4}
Sleep, 248
SendInput {Numpad4}
Sleep, 248
SendInput {Numpad4}
Sleep, 248
SendInput {Numpad3}
Sleep, 248
SendInput {Numpad4}
Sleep, 248
SendInput {Numpad5}
Sleep, 128
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad5}
SendInput {Numpad1}
Sleep, 128
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad1}
Sleep, 128
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad1}
Sleep, 128
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad1}
Sleep, 188
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad5}
SendInput {Numpad1}
Sleep, 188
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad1}
Sleep, 128
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad3}
SendInput {Numpad1}
Sleep, 248
SendInput {Numpad4}
SendInput {Numpad2}
Sleep, 128
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad2}
Sleep, 128
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad2}
Sleep, 128
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad2}
Sleep, 128
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad6}
SendInput {Numpad2}
Sleep, 128
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad2}
Sleep, 128
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad4}
SendInput {Numpad1}
Sleep, 248
SendInput {Numpad3}
SendInput {Numpad2}
Sleep, 248
SendInput {Numpad2}
SendInput {Numpad3}
Sleep, 248
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 128
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad6}
Sleep, 128
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad1}
SendInput {Numpad6}
Sleep, 128
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad6}
Sleep, 188
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad6}
Sleep, 188
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad6}
Sleep, 128
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 248
SendInput {Numpad4}
Sleep, 128
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad4}
Sleep, 128
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad4}
Sleep, 128
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad4}
Sleep, 128
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad3}
SendInput {Numpad4}
Sleep, 248
SendInput {Numpad4}
Sleep, 128
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad3}
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad3}
Sleep, 45
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad4}
Sleep, 45
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad4}
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad5}
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad5}
Sleep, 165
SendInput {Numpad5}
SendInput {Numpad1}
Sleep, 128
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad1}
Sleep, 128
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad1}
Sleep, 128
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad1}
Sleep, 188
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad5}
SendInput {Numpad1}
Sleep, 188
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad1}
Sleep, 128
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad3}
SendInput {Numpad1}
Sleep, 248
SendInput {Numpad4}
SendInput {Numpad2}
Sleep, 128
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad2}
Sleep, 128
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad2}
Sleep, 128
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad2}
Sleep, 128
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad6}
SendInput {Numpad2}
Sleep, 128
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad2}
Sleep, 128
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad4}
SendInput {Numpad1}
Sleep, 248
SendInput {Numpad3}
SendInput {Numpad2}
Sleep, 248
SendInput {Numpad2}
SendInput {Numpad3}
Sleep, 248
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 128
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad6}
Sleep, 128
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad1}
SendInput {Numpad6}
Sleep, 128
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad6}
Sleep, 188
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad6}
Sleep, 188
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad6}
Sleep, 128
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 248
SendInput {Numpad4}
Sleep, 128
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad4}
Sleep, 128
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad1}
SendInput {Numpad4}
Sleep, 128
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad4}
Sleep, 188
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad6}
SendInput {Numpad4}
Sleep, 188
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad4}
Sleep, 128
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad4}
SendInput {Numpad3}
Sleep, 248
SendInput {Numpad3}
SendInput {Numpad4}
Sleep, 248
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 248
SendInput {Numpad2}
SendInput {Numpad1}
Sleep, 128
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad1}
Sleep, 248
SendInput {Numpad1}
Sleep, 128
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad1}
Sleep, 248
SendInput {Numpad1}
Sleep, 128
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad1}
Sleep, 248
SendInput {Numpad1}
Sleep, 188
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad6}
SendInput {Numpad2}
Sleep, 188
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad2}
Sleep, 128
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad2}
Sleep, 128
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad2}
Sleep, 128
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad1}
SendInput {Numpad2}
Sleep, 248
SendInput {Numpad2}
Sleep, 128
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad1}
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad3}
Sleep, 45
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad2}
Sleep, 45
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad2}
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad3}
Sleep, 128
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad2}
SendInput {Numpad6}
Sleep, 128
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad6}
Sleep, 248
SendInput {Numpad6}
Sleep, 128
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad1}
SendInput {Numpad6}
Sleep, 248
SendInput {Numpad1}
SendInput {Numpad6}
Sleep, 128
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad6}
Sleep, 248
SendInput {Numpad6}
Sleep, 188
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad6}
SendInput {Numpad4}
Sleep, 188
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad4}
Sleep, 128
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad2}
SendInput {Numpad4}
Sleep, 128
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad4}
Sleep, 128
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad1}
SendInput {Numpad4}
Sleep, 248
SendInput {Numpad2}
SendInput {Numpad4}
Sleep, 248
SendInput {Numpad3}
Sleep, 248
SendInput {Numpad2}
SendInput {Numpad4}
Sleep, 248
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 248
SendInput {Numpad2}
SendInput {Numpad1}
Sleep, 128
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad1}
Sleep, 248
SendInput {Numpad1}
Sleep, 128
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad3}
SendInput {Numpad1}
Sleep, 248
SendInput {Numpad3}
SendInput {Numpad1}
Sleep, 128
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad1}
Sleep, 248
SendInput {Numpad1}
Sleep, 188
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad6}
SendInput {Numpad2}
Sleep, 188
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad2}
Sleep, 128
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad3}
SendInput {Numpad2}
Sleep, 128
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad2}
Sleep, 128
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad2}
Sleep, 248
SendInput {Numpad3}
SendInput {Numpad2}
Sleep, 128
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad1}
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad4}
Sleep, 45
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad2}
Sleep, 45
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad3}
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad3}
Sleep, 128
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 128
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad6}
Sleep, 128
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 248
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 248
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 248
SendInput {Numpad2}
SendInput {Numpad6}
Sleep, 248
SendInput {Numpad1}
SendInput {Numpad6}
Sleep, 248
SendInput {Numpad1}
SendInput {Numpad4}
Sleep, 128
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad4}
Sleep, 248
SendInput {Numpad4}
Sleep, 248
SendInput {Numpad4}
Sleep, 248
SendInput {Numpad4}
Sleep, 248
SendInput {Numpad6}
SendInput {Numpad4}
Sleep, 248
SendInput {Numpad4}
Sleep, 188
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad1}
SendInput {Numpad4}
Sleep, 248
SendInput {Numpad1}
SendInput {Numpad4}
Sleep, 248
SendInput {Numpad6}
SendInput {Numpad2}
Sleep, 188
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad2}
SendInput {Numpad6}
Sleep, 188
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad6}
SendInput {Numpad4}
SendInput {Numpad2}
Sleep, 188
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad2}
SendInput {Numpad6}
Sleep, 248
SendInput {Numpad2}
SendInput {Numpad6}
Sleep, 248
SendInput {Numpad2}
SendInput {Numpad6}
Sleep, 248
SendInput {Numpad2}
SendInput {Numpad6}
Sleep, 128
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad4}
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 436
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad7}
SendInput {Numpad4}
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 188
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 188
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad7}
SendInput {Numpad3}
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 188
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 188
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad7}
SendInput {Numpad3}
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 248
SendInput {Numpad7}
SendInput {Numpad4}
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 248
SendInput {Numpad7}
SendInput {Numpad3}
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 248
SendInput {Numpad7}
SendInput {Numpad3}
Sleep, 188
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad3}
SendInput {Numpad7}
Sleep, 248
SendInput {Numpad3}
SendInput {Numpad7}
Sleep, 248
SendInput {Numpad3}
SendInput {Numpad7}
Sleep, 188
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad7}
SendInput {Numpad2}
SendInput {Numpad3}
Sleep, 248
SendInput {Numpad7}
SendInput {Numpad3}
Sleep, 188
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad3}
SendInput {Numpad7}
Sleep, 128
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad4}
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 436
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad6}
SendInput {Numpad3}
Sleep, 188
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 188
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad6}
SendInput {Numpad2}
SendInput {Numpad3}
Sleep, 188
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 188
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad6}
SendInput {Numpad1}
SendInput {Numpad3}
Sleep, 188
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 248
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 128
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad2}
SendInput {Numpad4}
SendInput {F5}
Sleep, 128
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad4}
SendInput {F5}
Sleep, 248
SendInput {Numpad4}
SendInput {F5}
Sleep, 248
SendInput {Numpad4}
SendInput {F5}
Sleep, 248
SendInput {Numpad4}
SendInput {F5}
Sleep, 128
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad1}
SendInput {F2}
SendInput {Numpad4}
SendInput {F5}
Sleep, 188
SendInput {Numpad9}
Sleep, 60
SendInput {F5}
SendInput {Numpad2}
SendInput {Numpad4}
Sleep, 188
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad2}
SendInput {Numpad1}
SendInput {Numpad4}
Sleep, 188
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 188
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad1}
SendInput {Numpad4}
Sleep, 248
SendInput {Numpad1}
SendInput {Numpad4}
Sleep, 248
SendInput {Numpad1}
SendInput {Numpad4}
Sleep, 188
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad6}
SendInput {Numpad1}
SendInput {Numpad4}
Sleep, 248
SendInput {Numpad6}
SendInput {Numpad1}
SendInput {Numpad4}
Sleep, 188
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad1}
SendInput {Numpad4}
Sleep, 188
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad4}
SendInput {Numpad2}
SendInput {Numpad1}
Sleep, 248
SendInput {F5}
SendInput {Numpad4}
Sleep, 188
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad4}
SendInput {F5}
Sleep, 248
SendInput {Numpad4}
SendInput {F5}
Sleep, 248
SendInput {Numpad4}
SendInput {F5}
Sleep, 248
SendInput {Numpad4}
SendInput {F5}
Sleep, 248
SendInput {Numpad4}
SendInput {F5}
Sleep, 188
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad4}
SendInput {Numpad2}
SendInput {F5}
Sleep, 188
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad3}
SendInput {Numpad7}
Sleep, 376
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad3}
SendInput {Numpad7}
Sleep, 248
SendInput {Numpad3}
SendInput {Numpad7}
Sleep, 248
SendInput {Numpad3}
SendInput {Numpad7}
Sleep, 248
SendInput {Numpad3}
SendInput {Numpad7}
Sleep, 248
SendInput {Numpad3}
SendInput {Numpad7}
Sleep, 248
SendInput {Numpad3}
SendInput {Numpad7}
Sleep, 436
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 188
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad6}
Sleep, 248
SendInput {Numpad3}
Sleep, 376
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad3}
SendInput {Numpad1}
Sleep, 128
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad6}
Sleep, 248
SendInput {Numpad3}
Sleep, 128
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad3}
Sleep, 188
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad7}
Sleep, 188
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad6}
Sleep, 128
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad3}
Sleep, 496
SendInput {Numpad2}
SendInput {Numpad7}
Sleep, 128
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {F4}
Sleep, 128
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad3}
Sleep, 496
SendInput {Numpad4}
SendInput {Numpad1}
Sleep, 128
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad6}
Sleep, 248
SendInput {Numpad4}
Sleep, 496
SendInput {Numpad1}
Sleep, 128
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad5}
SendInput {Numpad6}
Sleep, 248
SendInput {Numpad4}
Sleep, 248
SendInput {Numpad3}
Sleep, 188
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad5}
Sleep, 188
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad3}
SendInput {Numpad5}
Sleep, 128
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad1}
Sleep, 248
SendInput {Numpad5}
Sleep, 248
SendInput {Numpad4}
Sleep, 248
SendInput {Numpad4}
Sleep, 248
SendInput {Numpad5}
Sleep, 248
SendInput {Numpad4}
Sleep, 188
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 188
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad6}
Sleep, 248
SendInput {Numpad3}
Sleep, 376
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad3}
SendInput {Numpad1}
Sleep, 128
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad6}
Sleep, 248
SendInput {Numpad3}
Sleep, 128
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad3}
Sleep, 188
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad7}
Sleep, 188
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad6}
Sleep, 128
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad3}
Sleep, 496
SendInput {Numpad2}
SendInput {Numpad7}
Sleep, 248
SendInput {Numpad3}
SendInput {F4}
Sleep, 128
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad3}
Sleep, 128
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad4}
Sleep, 188
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 188
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad6}
Sleep, 248
SendInput {Numpad4}
Sleep, 496
SendInput {Numpad1}
Sleep, 128
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad5}
SendInput {Numpad6}
Sleep, 248
SendInput {Numpad4}
Sleep, 248
SendInput {Numpad3}
Sleep, 188
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad5}
Sleep, 188
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad3}
SendInput {Numpad5}
Sleep, 128
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad1}
Sleep, 248
SendInput {Numpad5}
Sleep, 248
SendInput {Numpad4}
Sleep, 248
SendInput {Numpad4}
Sleep, 248
SendInput {Numpad5}
Sleep, 248
SendInput {Numpad4}
Sleep, 188
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad6}
SendInput {Numpad3}
Sleep, 188
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad6}
Sleep, 248
SendInput {Numpad6}
Sleep, 248
SendInput {Numpad6}
Sleep, 128
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 128
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad6}
Sleep, 248
SendInput {Numpad6}
Sleep, 128
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 188
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad7}
SendInput {Numpad3}
Sleep, 188
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad3}
Sleep, 128
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad3}
Sleep, 128
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad3}
Sleep, 128
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad2}
SendInput {Numpad3}
Sleep, 128
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad3}
Sleep, 128
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad3}
Sleep, 128
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad3}
Sleep, 128
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad4}
SendInput {Numpad1}
Sleep, 128
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad4}
Sleep, 248
SendInput {Numpad4}
Sleep, 248
SendInput {Numpad4}
Sleep, 248
SendInput {Numpad4}
Sleep, 128
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad5}
SendInput {Numpad4}
Sleep, 248
SendInput {Numpad4}
Sleep, 248
SendInput {Numpad3}
SendInput {Numpad4}
Sleep, 188
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad5}
SendInput {Numpad1}
Sleep, 188
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad3}
SendInput {Numpad1}
Sleep, 128
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad1}
Sleep, 248
SendInput {Numpad1}
Sleep, 248
SendInput {Numpad1}
Sleep, 248
SendInput {Numpad1}
Sleep, 248
SendInput {Numpad1}
Sleep, 248
SendInput {Numpad1}
Sleep, 188
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad6}
SendInput {Numpad3}
Sleep, 188
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad6}
Sleep, 248
SendInput {Numpad6}
Sleep, 248
SendInput {Numpad6}
Sleep, 128
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 128
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad6}
Sleep, 248
SendInput {Numpad6}
Sleep, 128
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 188
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad7}
SendInput {Numpad3}
Sleep, 188
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad3}
Sleep, 128
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad3}
Sleep, 128
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad3}
Sleep, 128
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad2}
SendInput {Numpad3}
Sleep, 248
SendInput {Numpad3}
Sleep, 128
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad3}
Sleep, 128
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad4}
SendInput {Numpad3}
Sleep, 188
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad6}
SendInput {Numpad1}
SendInput {Numpad4}
Sleep, 188
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad4}
Sleep, 248
SendInput {Numpad4}
Sleep, 248
SendInput {Numpad4}
Sleep, 248
SendInput {Numpad4}
Sleep, 128
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad5}
SendInput {Numpad4}
Sleep, 248
SendInput {Numpad4}
Sleep, 248
SendInput {Numpad3}
SendInput {Numpad4}
Sleep, 188
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad7}
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 248
SendInput {Numpad7}
SendInput {Numpad3}
SendInput {Numpad5}
Sleep, 188
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad5}
Sleep, 248
SendInput {Numpad5}
Sleep, 248
SendInput {Numpad5}
Sleep, 248
SendInput {Numpad5}
Sleep, 248
SendInput {Numpad5}
Sleep, 248
SendInput {Numpad5}
Sleep, 248
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 248
SendInput {Numpad1}
Sleep, 248
SendInput {Numpad1}
Sleep, 248
SendInput {Numpad1}
Sleep, 248
SendInput {Numpad1}
Sleep, 248
SendInput {Numpad1}
Sleep, 248
SendInput {Numpad1}
Sleep, 248
SendInput {Numpad1}
Sleep, 248
SendInput {Numpad1}
Sleep, 248
SendInput {Numpad1}
Sleep, 248
SendInput {Numpad1}
Sleep, 248
SendInput {Numpad1}
Sleep, 248
SendInput {Numpad1}
Sleep, 248
SendInput {Numpad1}
Sleep, 248
SendInput {Numpad1}
Sleep, 248
SendInput {Numpad1}
Sleep, 248
SendInput {Numpad1}
Sleep, 248
SendInput {Numpad1}
Sleep, 248
SendInput {Numpad1}
Sleep, 248
SendInput {Numpad1}
Sleep, 248
SendInput {Numpad1}
Sleep, 248
SendInput {Numpad1}
Sleep, 248
SendInput {Numpad1}
Sleep, 248
SendInput {Numpad1}
Sleep, 248
SendInput {Numpad1}
Sleep, 248
SendInput {Numpad1}
Sleep, 248
SendInput {Numpad1}
Sleep, 248
SendInput {Numpad1}
Sleep, 248
SendInput {Numpad1}
Sleep, 248
SendInput {Numpad1}
Sleep, 248
SendInput {Numpad1}
Sleep, 248
SendInput {Numpad1}
Sleep, 128
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad5}
SendInput {Numpad1}
Sleep, 128
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad1}
Sleep, 128
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad1}
Sleep, 128
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad1}
Sleep, 188
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad5}
SendInput {Numpad1}
Sleep, 188
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad1}
Sleep, 128
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad3}
SendInput {Numpad1}
Sleep, 248
SendInput {Numpad4}
SendInput {Numpad2}
Sleep, 128
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad2}
Sleep, 128
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad2}
Sleep, 128
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad2}
Sleep, 128
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad6}
SendInput {Numpad2}
Sleep, 128
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad2}
Sleep, 128
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad4}
SendInput {Numpad1}
Sleep, 248
SendInput {Numpad3}
SendInput {Numpad2}
Sleep, 248
SendInput {Numpad2}
SendInput {Numpad3}
Sleep, 248
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 128
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad6}
Sleep, 128
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad1}
SendInput {Numpad6}
Sleep, 128
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad6}
Sleep, 188
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad6}
Sleep, 188
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad6}
Sleep, 128
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 248
SendInput {Numpad4}
Sleep, 128
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad4}
Sleep, 128
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad4}
Sleep, 128
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad4}
Sleep, 128
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad3}
SendInput {Numpad4}
Sleep, 248
SendInput {Numpad4}
Sleep, 128
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad3}
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad3}
Sleep, 45
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad4}
Sleep, 45
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad4}
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad5}
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad5}
Sleep, 165
SendInput {Numpad5}
SendInput {Numpad1}
Sleep, 128
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad1}
Sleep, 128
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad1}
Sleep, 128
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad1}
Sleep, 188
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad5}
SendInput {Numpad1}
Sleep, 188
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad1}
Sleep, 128
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad3}
SendInput {Numpad1}
Sleep, 248
SendInput {Numpad4}
SendInput {Numpad2}
Sleep, 128
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad2}
Sleep, 128
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad2}
Sleep, 128
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad2}
Sleep, 128
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad6}
SendInput {Numpad2}
Sleep, 128
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad2}
Sleep, 128
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad4}
SendInput {Numpad1}
Sleep, 248
SendInput {Numpad3}
SendInput {Numpad2}
Sleep, 248
SendInput {Numpad2}
SendInput {Numpad3}
Sleep, 248
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 128
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad6}
Sleep, 128
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad1}
SendInput {Numpad6}
Sleep, 128
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad6}
Sleep, 188
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad6}
Sleep, 188
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad6}
Sleep, 128
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 248
SendInput {Numpad4}
Sleep, 128
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad4}
Sleep, 128
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad1}
SendInput {Numpad4}
Sleep, 128
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad4}
Sleep, 188
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad6}
SendInput {Numpad4}
Sleep, 188
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad4}
Sleep, 128
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad4}
SendInput {Numpad3}
Sleep, 248
SendInput {Numpad3}
SendInput {Numpad4}
Sleep, 248
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 248
SendInput {Numpad2}
SendInput {Numpad1}
Sleep, 128
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad1}
Sleep, 248
SendInput {Numpad1}
Sleep, 128
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad1}
Sleep, 248
SendInput {Numpad1}
Sleep, 128
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad1}
Sleep, 248
SendInput {Numpad1}
Sleep, 188
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad6}
SendInput {Numpad2}
Sleep, 188
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad2}
Sleep, 128
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad2}
Sleep, 128
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad2}
Sleep, 128
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad1}
SendInput {Numpad2}
Sleep, 248
SendInput {Numpad2}
Sleep, 128
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad1}
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad3}
Sleep, 45
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad2}
Sleep, 45
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad2}
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad3}
Sleep, 128
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad2}
SendInput {Numpad6}
Sleep, 128
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad6}
Sleep, 248
SendInput {Numpad6}
Sleep, 128
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad1}
SendInput {Numpad6}
Sleep, 248
SendInput {Numpad1}
SendInput {Numpad6}
Sleep, 128
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad6}
Sleep, 248
SendInput {Numpad6}
Sleep, 188
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad6}
SendInput {Numpad4}
Sleep, 188
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad4}
Sleep, 128
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad2}
SendInput {Numpad4}
Sleep, 128
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad4}
Sleep, 128
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad1}
SendInput {Numpad4}
Sleep, 248
SendInput {Numpad2}
SendInput {Numpad4}
Sleep, 248
SendInput {Numpad3}
Sleep, 248
SendInput {Numpad2}
SendInput {Numpad4}
Sleep, 248
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 248
SendInput {Numpad2}
SendInput {Numpad1}
Sleep, 128
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad1}
Sleep, 248
SendInput {Numpad1}
Sleep, 128
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad3}
SendInput {Numpad1}
Sleep, 248
SendInput {Numpad3}
SendInput {Numpad1}
Sleep, 128
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad1}
Sleep, 248
SendInput {Numpad1}
Sleep, 188
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad6}
SendInput {Numpad2}
Sleep, 188
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad2}
Sleep, 128
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad3}
SendInput {Numpad2}
Sleep, 128
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad2}
Sleep, 128
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad2}
Sleep, 248
SendInput {Numpad3}
SendInput {Numpad2}
Sleep, 128
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad1}
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad4}
Sleep, 45
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad2}
Sleep, 45
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad3}
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad3}
Sleep, 128
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 128
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad6}
Sleep, 128
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 248
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 248
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 248
SendInput {Numpad2}
SendInput {Numpad6}
Sleep, 248
SendInput {Numpad1}
SendInput {Numpad6}
Sleep, 248
SendInput {Numpad1}
SendInput {Numpad4}
Sleep, 128
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad4}
Sleep, 248
SendInput {Numpad4}
Sleep, 248
SendInput {Numpad4}
Sleep, 248
SendInput {Numpad4}
Sleep, 248
SendInput {Numpad6}
SendInput {Numpad4}
Sleep, 248
SendInput {Numpad4}
Sleep, 188
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad1}
SendInput {Numpad4}
Sleep, 248
SendInput {Numpad1}
SendInput {Numpad4}
Sleep, 248
SendInput {Numpad6}
SendInput {Numpad2}
Sleep, 188
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad2}
SendInput {Numpad6}
Sleep, 188
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad6}
SendInput {Numpad4}
SendInput {Numpad2}
Sleep, 188
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad2}
SendInput {Numpad6}
Sleep, 248
SendInput {Numpad2}
SendInput {Numpad6}
Sleep, 248
SendInput {Numpad2}
SendInput {Numpad6}
Sleep, 248
SendInput {Numpad2}
SendInput {Numpad6}
Sleep, 128
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad4}
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 436
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad7}
SendInput {Numpad4}
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 188
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 188
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad7}
SendInput {Numpad3}
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 188
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 188
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad7}
SendInput {Numpad3}
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 248
SendInput {Numpad7}
SendInput {Numpad4}
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 248
SendInput {Numpad7}
SendInput {Numpad3}
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 248
SendInput {Numpad7}
SendInput {Numpad3}
Sleep, 188
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad3}
SendInput {Numpad7}
Sleep, 248
SendInput {Numpad3}
SendInput {Numpad7}
Sleep, 248
SendInput {Numpad3}
SendInput {Numpad7}
Sleep, 188
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad7}
SendInput {Numpad2}
SendInput {Numpad3}
Sleep, 248
SendInput {Numpad7}
SendInput {Numpad3}
Sleep, 188
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad3}
SendInput {Numpad7}
Sleep, 128
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad4}
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 436
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad6}
SendInput {Numpad3}
Sleep, 188
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 188
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad6}
SendInput {Numpad2}
SendInput {Numpad3}
Sleep, 188
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 188
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad6}
SendInput {Numpad1}
SendInput {Numpad3}
Sleep, 188
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 248
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 128
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad2}
SendInput {Numpad4}
SendInput {F5}
Sleep, 128
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad4}
SendInput {F5}
Sleep, 248
SendInput {Numpad4}
SendInput {F5}
Sleep, 248
SendInput {Numpad4}
SendInput {F5}
Sleep, 248
SendInput {Numpad4}
SendInput {F5}
Sleep, 128
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad1}
SendInput {F2}
SendInput {Numpad4}
SendInput {F5}
Sleep, 188
SendInput {Numpad9}
Sleep, 60
SendInput {F5}
SendInput {Numpad2}
SendInput {Numpad4}
Sleep, 188
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad2}
SendInput {Numpad1}
SendInput {Numpad4}
Sleep, 188
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 188
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad1}
SendInput {Numpad4}
Sleep, 248
SendInput {Numpad1}
SendInput {Numpad4}
Sleep, 248
SendInput {Numpad1}
SendInput {Numpad4}
Sleep, 188
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad6}
SendInput {Numpad1}
SendInput {Numpad4}
Sleep, 248
SendInput {Numpad6}
SendInput {Numpad1}
SendInput {Numpad4}
Sleep, 188
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad1}
SendInput {Numpad4}
Sleep, 188
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad4}
SendInput {Numpad2}
SendInput {Numpad1}
Sleep, 248
SendInput {F5}
SendInput {Numpad4}
Sleep, 188
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad4}
SendInput {F5}
Sleep, 248
SendInput {Numpad4}
SendInput {F5}
Sleep, 248
SendInput {Numpad4}
SendInput {F5}
Sleep, 248
SendInput {Numpad4}
SendInput {F5}
Sleep, 248
SendInput {Numpad4}
SendInput {F5}
Sleep, 188
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad4}
SendInput {Numpad2}
SendInput {F5}
Sleep, 188
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad3}
SendInput {Numpad7}
Sleep, 376
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad3}
SendInput {Numpad7}
Sleep, 248
SendInput {Numpad3}
SendInput {Numpad7}
Sleep, 248
SendInput {Numpad3}
SendInput {Numpad7}
Sleep, 248
SendInput {Numpad3}
SendInput {Numpad7}
Sleep, 248
SendInput {Numpad3}
SendInput {Numpad7}
Sleep, 248
SendInput {Numpad3}
SendInput {Numpad7}
Sleep, 436
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad6}
SendInput {Numpad3}
Sleep, 188
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 248
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 248
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 188
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad6}
SendInput {Numpad3}
Sleep, 188
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 248
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 188
SendInput {Numpad0}
Sleep, 60
SendInput {F4}
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 248
SendInput {Numpad7}
SendInput {Numpad3}
Sleep, 188
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad3}
SendInput {Numpad7}
Sleep, 188
SendInput {Numpad0}
Sleep, 60
SendInput {F4}
SendInput {Numpad3}
SendInput {Numpad7}
Sleep, 188
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad3}
SendInput {Numpad7}
Sleep, 188
SendInput {Numpad0}
Sleep, 60
SendInput {F4}
SendInput {Numpad2}
SendInput {Numpad3}
SendInput {Numpad7}
Sleep, 248
SendInput {F4}
SendInput {Numpad3}
SendInput {Numpad7}
Sleep, 188
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad3}
SendInput {Numpad7}
Sleep, 188
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad6}
SendInput {Numpad4}
SendInput {Numpad3}
SendInput {Numpad7}
Sleep, 248
SendInput {Numpad6}
SendInput {Numpad1}
SendInput {Numpad4}
Sleep, 188
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad1}
SendInput {Numpad4}
Sleep, 248
SendInput {Numpad1}
SendInput {Numpad4}
Sleep, 248
SendInput {Numpad1}
SendInput {Numpad4}
Sleep, 248
SendInput {Numpad1}
SendInput {Numpad4}
Sleep, 128
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad5}
SendInput {Numpad1}
SendInput {Numpad4}
Sleep, 248
SendInput {Numpad4}
SendInput {Numpad1}
Sleep, 248
SendInput {Numpad3}
SendInput {Numpad1}
SendInput {Numpad4}
Sleep, 188
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad5}
SendInput {Numpad1}
Sleep, 248
SendInput {Numpad5}
SendInput {Numpad3}
SendInput {Numpad1}
Sleep, 188
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 248
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 248
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 248
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 248
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 248
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 188
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad6}
SendInput {Numpad3}
Sleep, 188
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 248
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 248
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 188
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad6}
SendInput {Numpad3}
Sleep, 188
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 248
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 188
SendInput {Numpad0}
Sleep, 60
SendInput {F4}
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 248
SendInput {Numpad7}
SendInput {Numpad3}
Sleep, 188
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad3}
SendInput {Numpad7}
Sleep, 188
SendInput {Numpad0}
Sleep, 60
SendInput {F4}
SendInput {Numpad3}
SendInput {Numpad7}
Sleep, 188
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad3}
SendInput {Numpad7}
Sleep, 188
SendInput {Numpad0}
Sleep, 60
SendInput {F4}
SendInput {Numpad2}
SendInput {Numpad3}
SendInput {Numpad7}
Sleep, 248
SendInput {F4}
SendInput {Numpad3}
SendInput {Numpad7}
Sleep, 188
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad3}
SendInput {Numpad7}
Sleep, 188
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad6}
SendInput {Numpad4}
SendInput {Numpad3}
SendInput {Numpad7}
Sleep, 248
SendInput {Numpad6}
SendInput {Numpad1}
SendInput {Numpad4}
Sleep, 188
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad1}
SendInput {Numpad4}
Sleep, 248
SendInput {Numpad1}
SendInput {Numpad4}
Sleep, 248
SendInput {Numpad1}
SendInput {Numpad4}
Sleep, 248
SendInput {Numpad1}
SendInput {Numpad4}
Sleep, 128
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad5}
SendInput {Numpad1}
SendInput {Numpad4}
Sleep, 248
SendInput {Numpad4}
SendInput {Numpad1}
Sleep, 248
SendInput {Numpad3}
SendInput {Numpad1}
SendInput {Numpad4}
Sleep, 188
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad5}
SendInput {Numpad1}
Sleep, 248
SendInput {Numpad5}
SendInput {Numpad3}
SendInput {Numpad1}
Sleep, 188
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 248
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 248
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 128
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad2}
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 128
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 248
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 188
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad6}
SendInput {Numpad3}
Sleep, 188
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 248
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 248
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 188
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad6}
SendInput {Numpad3}
Sleep, 188
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 248
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 188
SendInput {Numpad0}
Sleep, 60
SendInput {F4}
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 248
SendInput {Numpad7}
SendInput {Numpad3}
Sleep, 188
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad3}
SendInput {Numpad7}
Sleep, 188
SendInput {Numpad0}
Sleep, 60
SendInput {F4}
SendInput {Numpad3}
SendInput {Numpad7}
Sleep, 188
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad3}
SendInput {Numpad7}
Sleep, 188
SendInput {Numpad0}
Sleep, 60
SendInput {F4}
SendInput {Numpad2}
SendInput {Numpad3}
SendInput {Numpad7}
Sleep, 248
SendInput {F4}
SendInput {Numpad3}
SendInput {Numpad7}
Sleep, 188
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad3}
SendInput {Numpad7}
Sleep, 188
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad6}
SendInput {Numpad4}
SendInput {Numpad3}
SendInput {Numpad7}
Sleep, 248
SendInput {Numpad6}
SendInput {Numpad1}
SendInput {Numpad4}
Sleep, 188
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad1}
SendInput {Numpad4}
Sleep, 248
SendInput {Numpad1}
SendInput {Numpad4}
Sleep, 248
SendInput {Numpad1}
SendInput {Numpad4}
Sleep, 248
SendInput {Numpad1}
SendInput {Numpad4}
Sleep, 128
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad5}
SendInput {Numpad1}
SendInput {Numpad4}
Sleep, 248
SendInput {Numpad4}
SendInput {Numpad1}
Sleep, 248
SendInput {Numpad3}
SendInput {Numpad1}
SendInput {Numpad4}
Sleep, 188
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad5}
SendInput {Numpad1}
Sleep, 248
SendInput {Numpad5}
SendInput {Numpad3}
SendInput {Numpad1}
Sleep, 188
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 248
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 248
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 248
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 248
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 248
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 188
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad6}
SendInput {Numpad3}
Sleep, 188
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 248
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 248
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 188
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad6}
SendInput {Numpad3}
Sleep, 188
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 248
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 188
SendInput {Numpad0}
Sleep, 60
SendInput {F4}
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 248
SendInput {Numpad7}
SendInput {Numpad3}
Sleep, 188
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad3}
SendInput {Numpad7}
Sleep, 188
SendInput {Numpad0}
Sleep, 60
SendInput {F4}
SendInput {Numpad3}
SendInput {Numpad7}
Sleep, 188
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad3}
SendInput {Numpad7}
Sleep, 188
SendInput {Numpad0}
Sleep, 60
SendInput {F4}
SendInput {Numpad2}
SendInput {Numpad3}
SendInput {Numpad7}
Sleep, 248
SendInput {F4}
SendInput {Numpad3}
SendInput {Numpad7}
Sleep, 188
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad3}
SendInput {Numpad7}
Sleep, 188
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad6}
SendInput {Numpad4}
SendInput {Numpad3}
SendInput {Numpad7}
Sleep, 188
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad4}
SendInput {Numpad1}
Sleep, 128
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad1}
SendInput {Numpad4}
Sleep, 248
SendInput {Numpad1}
SendInput {Numpad4}
Sleep, 248
SendInput {Numpad1}
SendInput {Numpad4}
Sleep, 248
SendInput {Numpad1}
SendInput {Numpad4}
Sleep, 248
SendInput {Numpad1}
SendInput {Numpad4}
Sleep, 248
SendInput {Numpad1}
SendInput {Numpad4}
Sleep, 188
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad7}
SendInput {Numpad4}
SendInput {Numpad1}
Sleep, 248
SendInput {Numpad7}
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 188
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 248
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 248
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 248
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 248
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 248
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 248
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 128
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad5}
SendInput {Numpad1}
Sleep, 128
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad1}
Sleep, 128
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad1}
Sleep, 128
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad1}
Sleep, 188
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad5}
SendInput {Numpad1}
Sleep, 188
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad1}
Sleep, 128
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad3}
SendInput {Numpad1}
Sleep, 248
SendInput {Numpad4}
SendInput {Numpad2}
Sleep, 128
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad2}
Sleep, 128
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad2}
Sleep, 128
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad2}
Sleep, 128
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad6}
SendInput {Numpad2}
Sleep, 128
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad2}
Sleep, 128
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad4}
SendInput {Numpad1}
Sleep, 248
SendInput {Numpad3}
SendInput {Numpad2}
Sleep, 248
SendInput {Numpad2}
SendInput {Numpad3}
Sleep, 248
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 128
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad6}
Sleep, 128
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad1}
SendInput {Numpad6}
Sleep, 128
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad6}
Sleep, 188
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad6}
Sleep, 188
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad6}
Sleep, 128
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 248
SendInput {Numpad4}
Sleep, 128
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad4}
Sleep, 128
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad4}
Sleep, 128
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad4}
Sleep, 128
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad3}
SendInput {Numpad4}
Sleep, 248
SendInput {Numpad4}
Sleep, 128
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad3}
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad3}
Sleep, 45
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad4}
Sleep, 45
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad4}
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad5}
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad5}
Sleep, 165
SendInput {Numpad5}
SendInput {Numpad1}
Sleep, 128
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad1}
Sleep, 128
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad1}
Sleep, 128
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad1}
Sleep, 188
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad5}
SendInput {Numpad1}
Sleep, 188
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad1}
Sleep, 128
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad3}
SendInput {Numpad1}
Sleep, 248
SendInput {Numpad4}
SendInput {Numpad2}
Sleep, 128
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad2}
Sleep, 128
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad2}
Sleep, 128
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad2}
Sleep, 128
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad6}
SendInput {Numpad2}
Sleep, 128
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad2}
Sleep, 128
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad4}
SendInput {Numpad1}
Sleep, 248
SendInput {Numpad3}
SendInput {Numpad2}
Sleep, 248
SendInput {Numpad2}
SendInput {Numpad3}
Sleep, 248
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 128
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad6}
Sleep, 128
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad1}
SendInput {Numpad6}
Sleep, 128
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad6}
Sleep, 188
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad6}
Sleep, 188
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad6}
Sleep, 128
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 248
SendInput {Numpad4}
Sleep, 128
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad4}
Sleep, 128
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad4}
Sleep, 128
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad4}
Sleep, 128
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad3}
SendInput {Numpad4}
Sleep, 248
SendInput {Numpad4}
Sleep, 128
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad3}
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad3}
Sleep, 45
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad4}
Sleep, 45
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad4}
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad5}
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad5}
Sleep, 105
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad5}
SendInput {Numpad1}
Sleep, 188
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad5}
Sleep, 1000
