; title: Suicide Is Painless
; author: Johnny Mandel and Mike Altman
; instrument: Piano
; Converted by Serenade Music Converter

SendInput {Numpad0}
SendInput {Numpad1}
SendInput {Numpad3}
Sleep, 261
SendInput {Numpad5}
Sleep, 261
Sleep, 261
SendInput {Numpad1}
SendInput {Numpad3}
SendInput {Numpad7}
Sleep, 783
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad3}
Sleep, 261
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad6}
Sleep, 261
SendInput {Numpad1}
SendInput {Numpad3}
Sleep, 261
SendInput {Numpad6}
Sleep, 261
Sleep, 261
SendInput {Numpad1}
SendInput {Numpad3}
SendInput {Numpad7}
Sleep, 261
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad6}
Sleep, 522
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad5}
Sleep, 522
SendInput {Numpad6}
SendInput {Numpad1}
SendInput {Numpad4}
Sleep, 261
Sleep, 261
SendInput {Numpad3}
Sleep, 261
SendInput {Numpad6}
SendInput {Numpad1}
SendInput {Numpad4}
Sleep, 261
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad3}
Sleep, 522
SendInput {Numpad5}
SendInput {Numpad7}
SendInput {Numpad4}
Sleep, 261
Sleep, 261
SendInput {Numpad3}
Sleep, 522
SendInput {Numpad4}
SendInput {Numpad7}
SendInput {Numpad2}
Sleep, 261
Sleep, 261
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad2}
Sleep, 522
Sleep, 261
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad5}
SendInput {Numpad1}
SendInput {Numpad3}
Sleep, 261
Sleep, 261
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad5}
SendInput {Numpad1}
SendInput {Numpad3}
Sleep, 261
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad1}
Sleep, 261
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad2}
Sleep, 522
SendInput {Numpad6}
SendInput {Numpad1}
SendInput {Numpad3}
Sleep, 261
Sleep, 261
SendInput {Numpad2}
Sleep, 522
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 261
Sleep, 522
Sleep, 261
SendInput {Numpad3}
Sleep, 261
SendInput {Numpad4}
SendInput {Numpad6}
SendInput {Numpad2}
Sleep, 261
Sleep, 261
SendInput {Numpad1}
Sleep, 261
SendInput {Numpad4}
SendInput {Numpad6}
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 522
SendInput {Numpad4}
SendInput {Numpad1}
SendInput {Numpad2}
Sleep, 261
Sleep, 261
SendInput {Numpad1}
Sleep, 522
SendInput {Numpad9}
SendInput {Numpad4}
SendInput {Numpad7}
Sleep, 261
Sleep, 522
Sleep, 261
SendInput {Numpad0}
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad9}
SendInput {Numpad3}
SendInput {Numpad5}
SendInput {Numpad1}
Sleep, 261
Sleep, 261
SendInput {Numpad7}
Sleep, 261
SendInput {Numpad3}
SendInput {Numpad5}
SendInput {Numpad1}
Sleep, 261
SendInput {Numpad9}
SendInput {Numpad1}
Sleep, 261
SendInput {Numpad0}
SendInput {Numpad7}
Sleep, 522
SendInput {Numpad3}
SendInput {Numpad5}
SendInput {Numpad1}
Sleep, 261
Sleep, 261
SendInput {Numpad0}
SendInput {Numpad2}
Sleep, 522
SendInput {Numpad2}
SendInput {Numpad3}
Sleep, 261
Sleep, 261
SendInput {Numpad9}
SendInput {Numpad5}
Sleep, 261
SendInput {Numpad7}
Sleep, 261
SendInput {Numpad0}
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad9}
SendInput {Numpad5}
Sleep, 261
SendInput {Numpad7}
Sleep, 261
SendInput {Numpad0}
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad9}
SendInput {Numpad7}
Sleep, 261
SendInput {Numpad5}
SendInput {F1}
Sleep, 522
SendInput {Numpad5}
SendInput {F1}
Sleep, 522
SendInput {Numpad5}
SendInput {F1}
Sleep, 522
SendInput {Numpad0}
SendInput {Numpad5}
Sleep, 522
SendInput {Numpad1}
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 261
Sleep, 261
SendInput {Numpad5}
Sleep, 261
SendInput {Numpad1}
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 261
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad5}
Sleep, 522
SendInput {Numpad7}
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 261
Sleep, 261
SendInput {Numpad5}
Sleep, 783
Sleep, 261
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad5}
Sleep, 261
Sleep, 261
SendInput {Numpad1}
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 261
Sleep, 261
SendInput {Numpad5}
Sleep, 261
SendInput {Numpad1}
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 261
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad1}
Sleep, 261
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad5}
Sleep, 522
SendInput {Numpad1}
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 261
Sleep, 261
SendInput {Numpad5}
Sleep, 783
Sleep, 522
SendInput {Numpad5}
Sleep, 522
SendInput {Numpad6}
SendInput {Numpad1}
SendInput {Numpad3}
Sleep, 261
Sleep, 261
SendInput {Numpad5}
Sleep, 261
SendInput {Numpad1}
SendInput {Numpad5}
SendInput {Numpad6}
Sleep, 261
Sleep, 261
Sleep, 522
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 261
Sleep, 261
Sleep, 522
SendInput {Numpad7}
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 261
Sleep, 261
SendInput {Numpad5}
Sleep, 522
SendInput {Numpad1}
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 261
Sleep, 261
SendInput {Numpad9}
SendInput {Numpad6}
Sleep, 261
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 261
SendInput {Numpad9}
SendInput {Numpad7}
Sleep, 261
Sleep, 522
Sleep, 261
SendInput {Numpad6}
Sleep, 261
SendInput {Numpad0}
SendInput {Numpad1}
SendInput {Numpad3}
Sleep, 261
SendInput {Numpad9}
SendInput {Numpad6}
Sleep, 261
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 261
SendInput {Numpad9}
SendInput {Numpad3}
SendInput {Numpad7}
Sleep, 783
SendInput {Numpad0}
SendInput {Numpad5}
Sleep, 522
SendInput {Numpad6}
SendInput {Numpad1}
SendInput {Numpad4}
Sleep, 261
Sleep, 261
SendInput {Numpad3}
Sleep, 261
SendInput {Numpad6}
SendInput {Numpad1}
SendInput {Numpad4}
Sleep, 261
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad3}
Sleep, 522
SendInput {Numpad5}
SendInput {Numpad7}
SendInput {Numpad4}
Sleep, 261
Sleep, 261
SendInput {Numpad3}
Sleep, 522
SendInput {Numpad4}
SendInput {Numpad7}
SendInput {Numpad2}
Sleep, 261
Sleep, 261
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad2}
Sleep, 522
Sleep, 261
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad5}
SendInput {Numpad1}
SendInput {Numpad3}
Sleep, 261
Sleep, 261
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad5}
SendInput {Numpad1}
SendInput {Numpad3}
Sleep, 261
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad1}
Sleep, 261
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad2}
Sleep, 522
SendInput {Numpad6}
SendInput {Numpad1}
SendInput {Numpad3}
Sleep, 261
Sleep, 261
SendInput {Numpad2}
Sleep, 522
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 261
Sleep, 522
Sleep, 261
SendInput {Numpad3}
Sleep, 261
SendInput {Numpad4}
SendInput {Numpad6}
SendInput {Numpad2}
Sleep, 261
Sleep, 261
SendInput {Numpad1}
Sleep, 261
SendInput {Numpad4}
SendInput {Numpad6}
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 522
SendInput {Numpad4}
SendInput {Numpad1}
SendInput {Numpad2}
Sleep, 261
Sleep, 261
SendInput {Numpad1}
Sleep, 522
SendInput {Numpad9}
SendInput {Numpad4}
SendInput {Numpad7}
Sleep, 261
Sleep, 522
Sleep, 261
SendInput {Numpad0}
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad9}
SendInput {Numpad3}
SendInput {Numpad5}
SendInput {Numpad1}
Sleep, 261
Sleep, 261
SendInput {Numpad7}
Sleep, 261
SendInput {Numpad3}
SendInput {Numpad5}
SendInput {Numpad1}
Sleep, 261
SendInput {Numpad9}
SendInput {Numpad1}
Sleep, 261
SendInput {Numpad0}
SendInput {Numpad7}
Sleep, 522
SendInput {Numpad3}
SendInput {Numpad5}
SendInput {Numpad1}
Sleep, 261
Sleep, 261
SendInput {Numpad0}
SendInput {Numpad2}
Sleep, 522
SendInput {Numpad2}
SendInput {Numpad3}
Sleep, 261
Sleep, 261
SendInput {Numpad9}
SendInput {Numpad5}
Sleep, 261
SendInput {Numpad7}
Sleep, 261
SendInput {Numpad0}
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad9}
SendInput {Numpad5}
Sleep, 261
SendInput {Numpad7}
Sleep, 261
SendInput {Numpad0}
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad9}
SendInput {Numpad7}
Sleep, 261
SendInput {Numpad5}
SendInput {F1}
Sleep, 522
SendInput {Numpad5}
SendInput {F1}
Sleep, 522
SendInput {Numpad5}
SendInput {F1}
Sleep, 522
SendInput {Numpad0}
SendInput {Numpad5}
Sleep, 522
SendInput {Numpad1}
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 261
Sleep, 261
SendInput {Numpad5}
Sleep, 261
SendInput {Numpad1}
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 261
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad5}
Sleep, 522
SendInput {Numpad7}
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 261
Sleep, 261
SendInput {Numpad5}
Sleep, 783
Sleep, 261
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad2}
Sleep, 261
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad5}
Sleep, 261
Sleep, 261
SendInput {Numpad1}
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 261
Sleep, 261
SendInput {Numpad5}
Sleep, 261
SendInput {Numpad1}
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 261
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad1}
Sleep, 261
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad5}
Sleep, 522
SendInput {Numpad1}
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 261
Sleep, 261
SendInput {Numpad5}
Sleep, 783
Sleep, 522
SendInput {Numpad5}
Sleep, 522
SendInput {Numpad6}
SendInput {Numpad1}
SendInput {Numpad3}
Sleep, 261
Sleep, 261
SendInput {Numpad5}
Sleep, 261
SendInput {Numpad1}
SendInput {Numpad5}
SendInput {Numpad6}
Sleep, 261
Sleep, 261
Sleep, 522
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 261
Sleep, 261
Sleep, 522
SendInput {Numpad7}
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 261
Sleep, 261
SendInput {Numpad5}
Sleep, 522
SendInput {Numpad1}
SendInput {Numpad3}
Sleep, 261
Sleep, 261
SendInput {Numpad9}
SendInput {Numpad6}
Sleep, 261
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 261
SendInput {Numpad9}
SendInput {Numpad7}
Sleep, 261
Sleep, 522
Sleep, 261
SendInput {Numpad6}
Sleep, 261
SendInput {Numpad0}
SendInput {Numpad1}
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 261
SendInput {Numpad9}
SendInput {Numpad6}
Sleep, 261
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 261
SendInput {Numpad9}
SendInput {Numpad7}
Sleep, 261
Sleep, 522
Sleep, 261
SendInput {Numpad6}
Sleep, 261
SendInput {Numpad0}
SendInput {Numpad1}
SendInput {Numpad3}
Sleep, 261
SendInput {Numpad9}
SendInput {Numpad6}
Sleep, 261
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 261
SendInput {Numpad9}
SendInput {Numpad3}
SendInput {Numpad7}
Sleep, 783
SendInput {Numpad0}
SendInput {Numpad5}
Sleep, 522
SendInput {Numpad6}
SendInput {Numpad3}
Sleep, 522
SendInput {Numpad5}
Sleep, 522
SendInput {Numpad1}
SendInput {Numpad6}
Sleep, 522
Sleep, 522
SendInput {Numpad1}
Sleep, 68
SendInput {Numpad4}
Sleep, 70
SendInput {Numpad6}
Sleep, 384
Sleep, 522
SendInput {Numpad7}
SendInput {Numpad2}
SendInput {Numpad6}
Sleep, 522
SendInput {Numpad5}
Sleep, 522
SendInput {Numpad1}
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 261
SendInput {Numpad9}
SendInput {Numpad6}
Sleep, 261
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 261
SendInput {Numpad9}
SendInput {Numpad7}
Sleep, 261
SendInput {Numpad9}
SendInput {Numpad3}
Sleep, 522
Sleep, 261
SendInput {Numpad0}
SendInput {Numpad6}
Sleep, 261
SendInput {Numpad0}
SendInput {Numpad1}
SendInput {Numpad3}
Sleep, 261
SendInput {Numpad9}
SendInput {Numpad6}
Sleep, 261
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 261
SendInput {Numpad9}
SendInput {Numpad7}
Sleep, 261
SendInput {Numpad9}
SendInput {Numpad3}
Sleep, 522
Sleep, 261
SendInput {Numpad0}
SendInput {Numpad6}
Sleep, 261
SendInput {Numpad0}
SendInput {Numpad1}
SendInput {Numpad3}
Sleep, 261
SendInput {Numpad9}
SendInput {Numpad6}
Sleep, 261
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 261
SendInput {Numpad9}
SendInput {Numpad7}
Sleep, 261
SendInput {Numpad9}
SendInput {Numpad3}
Sleep, 522
SendInput {Numpad0}
SendInput {Numpad6}
Sleep, 522
SendInput {Numpad0}
SendInput {Numpad1}
SendInput {Numpad3}
