; title: The Avengers Theme
; author: Alan Silvestri
; instrument: Piano
; Converted by Serenade Music Converter

SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 750
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 125
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 125
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 500
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 125
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 125
SendInput {Numpad1}
SendInput {F4}
Sleep, 125
SendInput {Numpad1}
SendInput {F4}
Sleep, 125
SendInput {Numpad1}
SendInput {F4}
Sleep, 500
SendInput {Numpad1}
SendInput {F4}
Sleep, 125
SendInput {Numpad1}
SendInput {F4}
Sleep, 125
SendInput {Numpad1}
SendInput {Numpad6}
Sleep, 500
SendInput {Numpad1}
SendInput {Numpad6}
Sleep, 250
SendInput {Numpad1}
SendInput {Numpad6}
Sleep, 125
SendInput {Numpad1}
SendInput {Numpad6}
Sleep, 125
SendInput {Numpad1}
SendInput {F5}
Sleep, 125
SendInput {Numpad1}
SendInput {F5}
Sleep, 125
SendInput {Numpad1}
SendInput {F5}
Sleep, 500
SendInput {Numpad1}
SendInput {F5}
Sleep, 125
SendInput {Numpad1}
SendInput {F5}
Sleep, 125
SendInput {Numpad1}
SendInput {Numpad6}
Sleep, 500
SendInput {Numpad1}
SendInput {Numpad6}
Sleep, 250
SendInput {Numpad1}
SendInput {Numpad6}
Sleep, 125
SendInput {Numpad1}
SendInput {Numpad6}
Sleep, 125
SendInput {Numpad1}
SendInput {F4}
Sleep, 125
SendInput {Numpad1}
SendInput {F4}
Sleep, 125
SendInput {Numpad1}
SendInput {F4}
Sleep, 440
SendInput {Numpad9}
Sleep, 60
SendInput {F4}
SendInput {Numpad1}
Sleep, 125
SendInput {F4}
SendInput {Numpad1}
Sleep, 65
SendInput {Numpad0}
Sleep, 60
SendInput {F4}
SendInput {Numpad1}
SendInput {F2}
Sleep, 500
SendInput {Numpad4}
SendInput {Numpad1}
Sleep, 500
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 125
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 125
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 500
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 125
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 125
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 500
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 125
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 125
SendInput {Numpad1}
SendInput {F4}
Sleep, 125
SendInput {Numpad1}
SendInput {F4}
Sleep, 125
SendInput {Numpad1}
SendInput {F4}
Sleep, 500
SendInput {Numpad1}
SendInput {F4}
Sleep, 125
SendInput {Numpad1}
SendInput {F4}
Sleep, 125
SendInput {Numpad1}
SendInput {Numpad6}
Sleep, 500
SendInput {Numpad1}
SendInput {Numpad6}
Sleep, 250
SendInput {Numpad1}
SendInput {Numpad6}
Sleep, 125
SendInput {Numpad1}
SendInput {Numpad6}
Sleep, 125
SendInput {Numpad1}
SendInput {F5}
Sleep, 125
SendInput {Numpad1}
SendInput {F5}
Sleep, 125
SendInput {Numpad1}
SendInput {F5}
Sleep, 500
SendInput {Numpad1}
SendInput {F5}
Sleep, 125
SendInput {Numpad1}
SendInput {F5}
Sleep, 125
SendInput {Numpad1}
SendInput {Numpad6}
Sleep, 500
SendInput {Numpad1}
SendInput {Numpad6}
Sleep, 250
SendInput {Numpad1}
SendInput {Numpad6}
Sleep, 125
SendInput {Numpad1}
SendInput {Numpad6}
Sleep, 125
SendInput {Numpad1}
SendInput {F4}
Sleep, 125
SendInput {Numpad1}
SendInput {F4}
Sleep, 125
SendInput {Numpad1}
SendInput {F4}
Sleep, 500
SendInput {Numpad1}
SendInput {F4}
Sleep, 125
SendInput {Numpad1}
SendInput {F4}
Sleep, 125
SendInput {F4}
SendInput {Numpad1}
SendInput {F2}
Sleep, 500
SendInput {Numpad4}
SendInput {Numpad1}
SendInput {Numpad2}
Sleep, 500
SendInput {Numpad1}
Sleep, 750
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 125
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 125
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 500
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 125
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 125
SendInput {Numpad1}
SendInput {Numpad5}
SendInput {F4}
Sleep, 500
SendInput {Numpad4}
Sleep, 250
SendInput {Numpad1}
SendInput {F4}
Sleep, 125
SendInput {Numpad1}
SendInput {F2}
SendInput {F4}
Sleep, 125
SendInput {Numpad1}
SendInput {F2}
SendInput {Numpad6}
Sleep, 500
SendInput {Numpad1}
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 375
SendInput {Numpad5}
Sleep, 125
SendInput {Numpad1}
SendInput {Numpad5}
SendInput {F5}
Sleep, 500
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad1}
SendInput {F5}
Sleep, 125
SendInput {Numpad1}
SendInput {F5}
Sleep, 125
SendInput {Numpad1}
SendInput {Numpad6}
Sleep, 500
SendInput {Numpad1}
SendInput {Numpad6}
Sleep, 250
SendInput {Numpad1}
SendInput {Numpad6}
Sleep, 125
SendInput {Numpad1}
SendInput {Numpad6}
Sleep, 125
SendInput {Numpad1}
SendInput {Numpad5}
SendInput {F4}
Sleep, 500
SendInput {Numpad4}
Sleep, 250
SendInput {Numpad1}
Sleep, 125
SendInput {Numpad1}
SendInput {F2}
Sleep, 125
SendInput {F4}
SendInput {Numpad1}
SendInput {F2}
Sleep, 500
SendInput {Numpad4}
SendInput {Numpad1}
SendInput {Numpad2}
Sleep, 500
SendInput {Numpad1}
Sleep, 750
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 125
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 125
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 500
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 125
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 125
SendInput {Numpad1}
SendInput {Numpad5}
SendInput {F4}
Sleep, 500
SendInput {Numpad4}
Sleep, 250
SendInput {Numpad1}
SendInput {F4}
Sleep, 125
SendInput {Numpad1}
SendInput {F2}
SendInput {F4}
Sleep, 125
SendInput {Numpad1}
SendInput {F2}
SendInput {Numpad6}
Sleep, 500
SendInput {Numpad1}
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 375
SendInput {Numpad5}
Sleep, 125
SendInput {Numpad1}
SendInput {Numpad5}
SendInput {F5}
Sleep, 500
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad1}
SendInput {F5}
Sleep, 125
SendInput {Numpad1}
SendInput {F5}
Sleep, 125
SendInput {Numpad1}
SendInput {Numpad6}
Sleep, 500
SendInput {Numpad1}
SendInput {Numpad6}
Sleep, 250
SendInput {Numpad1}
SendInput {Numpad6}
Sleep, 125
SendInput {Numpad1}
SendInput {Numpad6}
Sleep, 125
SendInput {Numpad1}
SendInput {Numpad5}
SendInput {F4}
Sleep, 500
SendInput {Numpad4}
Sleep, 250
SendInput {Numpad1}
Sleep, 125
SendInput {Numpad1}
SendInput {F2}
Sleep, 125
SendInput {F4}
SendInput {Numpad1}
SendInput {F2}
Sleep, 500
SendInput {Numpad4}
SendInput {Numpad1}
SendInput {Numpad2}
Sleep, 500
SendInput {Numpad1}
Sleep, 750
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 125
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 125
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 500
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 125
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 125
SendInput {Numpad1}
SendInput {Numpad5}
SendInput {F4}
Sleep, 500
SendInput {Numpad4}
Sleep, 250
SendInput {Numpad1}
SendInput {F4}
Sleep, 125
SendInput {Numpad1}
SendInput {F2}
SendInput {F4}
Sleep, 125
SendInput {Numpad1}
SendInput {F2}
SendInput {Numpad6}
Sleep, 500
SendInput {Numpad1}
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 375
SendInput {Numpad5}
Sleep, 125
SendInput {Numpad1}
SendInput {Numpad5}
SendInput {F5}
Sleep, 500
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad1}
SendInput {F5}
Sleep, 125
SendInput {Numpad1}
SendInput {F5}
Sleep, 125
SendInput {Numpad1}
SendInput {Numpad6}
Sleep, 500
SendInput {Numpad1}
SendInput {Numpad6}
Sleep, 250
SendInput {Numpad1}
SendInput {Numpad6}
Sleep, 125
SendInput {Numpad1}
SendInput {Numpad6}
Sleep, 125
SendInput {Numpad1}
SendInput {Numpad5}
SendInput {F4}
Sleep, 500
SendInput {Numpad4}
Sleep, 250
SendInput {Numpad1}
Sleep, 125
SendInput {Numpad1}
SendInput {F2}
Sleep, 125
SendInput {F4}
SendInput {Numpad1}
SendInput {F2}
Sleep, 500
SendInput {Numpad4}
SendInput {Numpad1}
SendInput {Numpad2}
Sleep, 500
SendInput {Numpad1}
Sleep, 750
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 125
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 125
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 500
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 125
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 125
SendInput {Numpad1}
SendInput {Numpad5}
SendInput {F4}
Sleep, 500
SendInput {Numpad4}
Sleep, 250
SendInput {Numpad1}
SendInput {F4}
Sleep, 125
SendInput {Numpad1}
SendInput {F2}
SendInput {F4}
Sleep, 125
SendInput {Numpad1}
SendInput {F2}
SendInput {Numpad6}
Sleep, 500
SendInput {Numpad1}
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 375
SendInput {Numpad5}
Sleep, 125
SendInput {Numpad1}
SendInput {Numpad5}
SendInput {F5}
Sleep, 500
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad1}
SendInput {F5}
Sleep, 125
SendInput {Numpad1}
SendInput {F5}
Sleep, 125
SendInput {Numpad1}
SendInput {Numpad6}
Sleep, 500
SendInput {Numpad1}
SendInput {Numpad6}
Sleep, 250
SendInput {Numpad1}
SendInput {Numpad6}
Sleep, 125
SendInput {Numpad1}
SendInput {Numpad6}
Sleep, 125
SendInput {Numpad1}
SendInput {Numpad5}
SendInput {F4}
Sleep, 500
SendInput {Numpad4}
Sleep, 250
SendInput {Numpad1}
Sleep, 125
SendInput {Numpad1}
SendInput {F2}
Sleep, 125
SendInput {F4}
SendInput {Numpad1}
SendInput {F2}
Sleep, 500
SendInput {Numpad4}
SendInput {Numpad1}
SendInput {Numpad2}
Sleep, 440
SendInput {Numpad0}
Sleep, 60
SendInput {F2}
SendInput {Numpad5}
Sleep, 440
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad1}
Sleep, 440
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad1}
Sleep, 940
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad4}
SendInput {Numpad1}
SendInput {Numpad6}
Sleep, 1000
SendInput {Numpad4}
Sleep, 667
SendInput {Numpad1}
Sleep, 167
SendInput {Numpad5}
Sleep, 167
SendInput {F2}
Sleep, 333
SendInput {Numpad1}
Sleep, 607
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad1}
Sleep, 940
SendInput {Numpad9}
Sleep, 60
SendInput {F1}
SendInput {F4}
SendInput {Numpad4}
Sleep, 1000
SendInput {Numpad1}
SendInput {Numpad5}
SendInput {Numpad3}
Sleep, 940
SendInput {Numpad0}
Sleep, 60
SendInput {F4}
Sleep, 440
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad4}
Sleep, 440
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad4}
Sleep, 940
SendInput {Numpad9}
Sleep, 60
SendInput {F5}
SendInput {Numpad2}
SendInput {Numpad4}
Sleep, 940
SendInput {Numpad0}
Sleep, 60
SendInput {F5}
Sleep, 815
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad4}
Sleep, 65
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad5}
SendInput {Numpad2}
SendInput {Numpad1}
Sleep, 440
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad5}
Sleep, 440
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad5}
Sleep, 940
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad3}
SendInput {Numpad7}
SendInput {Numpad6}
Sleep, 500
SendInput {Numpad3}
Sleep, 500
SendInput {F4}
SendInput {Numpad7}
SendInput {Numpad3}
Sleep, 1000
SendInput {Numpad6}
SendInput {Numpad3}
Sleep, 690
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad1}
Sleep, 190
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad6}
Sleep, 250
SendInput {Numpad6}
Sleep, 190
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad1}
Sleep, 190
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad4}
SendInput {Numpad1}
Sleep, 500
SendInput {Numpad6}
Sleep, 500
SendInput {Numpad6}
Sleep, 690
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad3}
Sleep, 190
SendInput {Numpad9}
Sleep, 60
SendInput {F3}
SendInput {Numpad2}
Sleep, 690
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad1}
Sleep, 190
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad6}
Sleep, 250
SendInput {Numpad6}
Sleep, 250
SendInput {F3}
SendInput {Numpad2}
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad4}
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad6}
Sleep, 250
SendInput {Numpad6}
Sleep, 190
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad1}
Sleep, 190
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad5}
SendInput {Numpad2}
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad6}
Sleep, 250
SendInput {Numpad5}
SendInput {Numpad2}
SendInput {Numpad6}
Sleep, 190
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad5}
SendInput {Numpad1}
Sleep, 190
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad6}
SendInput {Numpad3}
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad6}
Sleep, 250
SendInput {Numpad6}
Sleep, 190
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad6}
Sleep, 250
SendInput {Numpad6}
Sleep, 250
SendInput {Numpad1}
Sleep, 190
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad4}
SendInput {Numpad1}
Sleep, 500
SendInput {Numpad6}
Sleep, 500
SendInput {Numpad6}
Sleep, 690
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad3}
Sleep, 130
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad2}
SendInput {F3}
SendInput {Numpad6}
Sleep, 690
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad1}
Sleep, 190
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad6}
Sleep, 250
SendInput {Numpad6}
Sleep, 190
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad2}
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad3}
SendInput {Numpad7}
SendInput {Numpad6}
Sleep, 190
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad7}
Sleep, 250
SendInput {Numpad7}
Sleep, 190
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad3}
SendInput {Numpad7}
Sleep, 250
SendInput {Numpad3}
SendInput {Numpad7}
SendInput {F4}
Sleep, 190
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad7}
Sleep, 250
SendInput {Numpad3}
SendInput {Numpad7}
Sleep, 190
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad3}
Sleep, 250
SendInput {Numpad4}
SendInput {Numpad1}
SendInput {Numpad6}
Sleep, 750
SendInput {Numpad5}
Sleep, 125
SendInput {Numpad6}
Sleep, 125
SendInput {Numpad5}
SendInput {Numpad2}
SendInput {Numpad7}
Sleep, 1000
SendInput {Numpad4}
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad4}
SendInput {Numpad1}
SendInput {Numpad6}
Sleep, 750
SendInput {Numpad5}
SendInput {Numpad2}
SendInput {Numpad6}
Sleep, 250
SendInput {Numpad5}
SendInput {Numpad2}
SendInput {Numpad7}
Sleep, 750
SendInput {Numpad6}
SendInput {Numpad3}
Sleep, 690
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad1}
Sleep, 190
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad6}
Sleep, 250
SendInput {Numpad6}
Sleep, 190
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad1}
Sleep, 190
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad4}
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad6}
Sleep, 250
SendInput {Numpad6}
Sleep, 500
SendInput {Numpad6}
Sleep, 690
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad3}
Sleep, 190
SendInput {Numpad9}
Sleep, 60
SendInput {F3}
SendInput {Numpad2}
Sleep, 690
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad1}
Sleep, 190
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad6}
Sleep, 250
SendInput {Numpad6}
Sleep, 190
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad1}
Sleep, 190
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad4}
SendInput {Numpad1}
Sleep, 1000
SendInput {Numpad5}
SendInput {Numpad2}
SendInput {Numpad7}
Sleep, 1000
SendInput {Numpad6}
SendInput {Numpad3}
Sleep, 690
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad1}
Sleep, 190
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad6}
Sleep, 250
SendInput {Numpad6}
Sleep, 190
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad1}
Sleep, 190
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad4}
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad6}
Sleep, 250
SendInput {Numpad6}
Sleep, 500
SendInput {Numpad6}
Sleep, 690
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad3}
Sleep, 130
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad2}
SendInput {F3}
SendInput {Numpad6}
Sleep, 880
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad2}
Sleep, 1000
SendInput {Numpad3}
SendInput {Numpad7}
SendInput {Numpad6}
Sleep, 1000
SendInput {F4}
Sleep, 380
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad9}
Sleep, 60
SendInput {F4}
Sleep, 440
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad6}
SendInput {Numpad3}
Sleep, 690
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad1}
Sleep, 190
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad6}
Sleep, 250
SendInput {Numpad6}
Sleep, 190
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad1}
Sleep, 190
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad4}
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad6}
Sleep, 250
SendInput {Numpad6}
Sleep, 500
SendInput {Numpad6}
Sleep, 690
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad3}
Sleep, 190
SendInput {Numpad9}
Sleep, 60
SendInput {F3}
SendInput {Numpad2}
Sleep, 690
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad1}
Sleep, 190
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad6}
Sleep, 250
SendInput {Numpad6}
Sleep, 190
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad1}
Sleep, 190
SendInput {Numpad9}
Sleep, 60
SendInput {Numpad4}
SendInput {Numpad1}
Sleep, 1000
SendInput {Numpad5}
SendInput {Numpad2}
SendInput {Numpad7}
Sleep, 1000
SendInput {Numpad4}
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad4}
SendInput {Numpad1}
SendInput {Numpad6}
Sleep, 750
SendInput {Numpad5}
SendInput {Numpad2}
SendInput {Numpad6}
Sleep, 250
SendInput {Numpad5}
SendInput {Numpad2}
SendInput {Numpad7}
Sleep, 750
SendInput {Numpad4}
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad4}
SendInput {Numpad1}
SendInput {Numpad6}
Sleep, 750
SendInput {Numpad5}
SendInput {Numpad2}
SendInput {Numpad6}
Sleep, 250
SendInput {Numpad5}
SendInput {Numpad2}
SendInput {Numpad7}
Sleep, 690
SendInput {Numpad0}
Sleep, 60
SendInput {Numpad6}
Sleep, 2000
SendInput {Numpad6}
Sleep, 61
SendInput {Numpad6}
Sleep, 62
SendInput {Numpad6}
Sleep, 61
SendInput {Numpad6}
Sleep, 62
SendInput {Numpad6}
Sleep, 61
SendInput {Numpad6}
Sleep, 62
SendInput {Numpad6}
Sleep, 61
SendInput {Numpad6}
Sleep, 62
SendInput {Numpad6}
Sleep, 61
SendInput {Numpad6}
Sleep, 62
SendInput {Numpad6}
Sleep, 61
SendInput {Numpad6}
Sleep, 62
SendInput {Numpad6}
Sleep, 61
SendInput {Numpad6}
Sleep, 62
SendInput {Numpad6}
Sleep, 61
SendInput {Numpad6}
Sleep, 62
SendInput {Numpad6}
Sleep, 61
SendInput {Numpad6}
Sleep, 62
SendInput {Numpad6}
Sleep, 61
SendInput {Numpad6}
Sleep, 62
SendInput {Numpad6}
Sleep, 61
SendInput {Numpad6}
Sleep, 62
SendInput {Numpad6}
Sleep, 61
SendInput {Numpad6}
Sleep, 62
SendInput {Numpad6}
Sleep, 62
SendInput {Numpad6}
Sleep, 61
SendInput {Numpad6}
Sleep, 62
SendInput {Numpad6}
Sleep, 61
SendInput {Numpad6}
Sleep, 62
SendInput {Numpad6}
Sleep, 61
SendInput {Numpad6}
Sleep, 62
SendInput {Numpad6}
Sleep, 78
SendInput {Numpad6}
Sleep, 1000
