; title: Thriller
; author: Michael Jackson
; instrument: Piano
; Converted by Serenade Music Converter

SendInput {Numpad2}
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 375
SendInput {Numpad4}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 1625
SendInput {Numpad4}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 500
SendInput {Numpad5}
SendInput {Numpad2}
SendInput {Numpad7}
Sleep, 500
SendInput {Numpad2}
SendInput {Numpad1}
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 875
SendInput {Numpad9}
SendInput {Numpad2}
Sleep, 125
SendInput {Numpad1}
SendInput {Numpad2}
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 250
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad4}
Sleep, 250
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad2}
Sleep, 875
SendInput {Numpad2}
Sleep, 125
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad4}
Sleep, 250
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad2}
Sleep, 875
SendInput {Numpad2}
Sleep, 125
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad4}
Sleep, 250
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad2}
Sleep, 875
SendInput {Numpad2}
Sleep, 125
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad4}
Sleep, 250
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad2}
Sleep, 250
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad6}
Sleep, 250
SendInput {Numpad4}
Sleep, 125
SendInput {Numpad2}
Sleep, 125
SendInput {Numpad1}
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad4}
Sleep, 250
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad2}
Sleep, 875
SendInput {Numpad2}
Sleep, 125
SendInput {Numpad1}
SendInput {Numpad2}
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 250
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad4}
Sleep, 250
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad2}
Sleep, 875
SendInput {Numpad2}
Sleep, 125
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad4}
Sleep, 250
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad2}
Sleep, 875
SendInput {Numpad2}
Sleep, 125
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad4}
Sleep, 250
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad0}
SendInput {F4}
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad5}
SendInput {Numpad1}
Sleep, 375
SendInput {Numpad9}
SendInput {Numpad2}
Sleep, 125
SendInput {Numpad1}
SendInput {Numpad5}
SendInput {Numpad7}
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad4}
Sleep, 250
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad3}
Sleep, 125
SendInput {Numpad9}
SendInput {Numpad2}
SendInput {Numpad7}
SendInput {Numpad4}
Sleep, 125
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad4}
Sleep, 250
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad2}
Sleep, 125
SendInput {Numpad1}
Sleep, 125
SendInput {Numpad6}
Sleep, 625
SendInput {Numpad2}
SendInput {Numpad6}
Sleep, 125
SendInput {Numpad1}
SendInput {Numpad6}
SendInput {Numpad2}
SendInput {Numpad4}
Sleep, 250
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad4}
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad5}
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad9}
SendInput {Numpad2}
SendInput {Numpad6}
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad4}
Sleep, 125
SendInput {Numpad2}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 125
SendInput {Numpad1}
Sleep, 125
SendInput {Numpad1}
Sleep, 125
SendInput {Numpad9}
SendInput {Numpad2}
SendInput {Numpad6}
Sleep, 250
SendInput {Numpad4}
Sleep, 250
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad2}
Sleep, 500
SendInput {Numpad0}
SendInput {Numpad6}
SendInput {Numpad1}
SendInput {Numpad4}
Sleep, 375
SendInput {Numpad9}
SendInput {Numpad2}
Sleep, 125
SendInput {Numpad1}
SendInput {Numpad5}
SendInput {Numpad7}
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad4}
Sleep, 250
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad3}
Sleep, 125
SendInput {Numpad9}
SendInput {Numpad2}
SendInput {Numpad7}
SendInput {Numpad4}
Sleep, 125
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad4}
Sleep, 250
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad2}
Sleep, 125
SendInput {Numpad1}
Sleep, 125
SendInput {Numpad6}
Sleep, 625
SendInput {Numpad2}
Sleep, 125
SendInput {Numpad1}
SendInput {Numpad6}
SendInput {Numpad2}
SendInput {Numpad4}
Sleep, 250
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad4}
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad5}
SendInput {Numpad1}
Sleep, 125
SendInput {Numpad6}
SendInput {Numpad2}
Sleep, 125
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad4}
Sleep, 125
SendInput {Numpad2}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 125
SendInput {Numpad1}
Sleep, 125
SendInput {Numpad1}
Sleep, 125
SendInput {Numpad9}
SendInput {Numpad2}
SendInput {Numpad6}
Sleep, 250
SendInput {Numpad4}
Sleep, 250
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad2}
SendInput {Numpad4}
SendInput {Numpad5}
SendInput {Numpad7}
Sleep, 250
SendInput {Numpad6}
Sleep, 125
SendInput {Numpad2}
SendInput {Numpad7}
SendInput {Numpad5}
Sleep, 125
SendInput {Numpad1}
Sleep, 125
SendInput {Numpad4}
Sleep, 125
SendInput {Numpad9}
SendInput {Numpad2}
SendInput {Numpad7}
Sleep, 250
SendInput {Numpad4}
Sleep, 250
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad2}
Sleep, 625
SendInput {Numpad0}
SendInput {Numpad5}
Sleep, 125
SendInput {Numpad5}
Sleep, 125
SendInput {Numpad2}
Sleep, 125
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 125
SendInput {Numpad4}
Sleep, 125
SendInput {Numpad2}
Sleep, 125
SendInput {Numpad4}
Sleep, 125
SendInput {Numpad4}
Sleep, 125
SendInput {Numpad3}
Sleep, 125
SendInput {Numpad5}
Sleep, 125
SendInput {Numpad7}
SendInput {Numpad3}
Sleep, 125
SendInput {Numpad2}
Sleep, 125
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad3}
Sleep, 250
SendInput {Numpad9}
SendInput {Numpad2}
SendInput {Numpad6}
SendInput {Numpad1}
SendInput {Numpad4}
Sleep, 125
SendInput {Numpad1}
SendInput {Numpad2}
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 125
SendInput {Numpad6}
SendInput {Numpad1}
SendInput {Numpad2}
Sleep, 125
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad4}
Sleep, 250
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad2}
SendInput {Numpad6}
SendInput {Numpad1}
SendInput {Numpad4}
Sleep, 875
SendInput {Numpad9}
SendInput {Numpad2}
Sleep, 125
SendInput {Numpad1}
SendInput {Numpad6}
SendInput {Numpad2}
SendInput {Numpad4}
Sleep, 250
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad4}
Sleep, 250
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad4}
Sleep, 250
SendInput {Numpad6}
Sleep, 125
SendInput {Numpad2}
SendInput {Numpad7}
SendInput {Numpad5}
Sleep, 125
SendInput {Numpad1}
SendInput {Numpad2}
SendInput {Numpad5}
SendInput {Numpad7}
Sleep, 125
SendInput {Numpad4}
Sleep, 125
SendInput {Numpad9}
SendInput {Numpad2}
SendInput {Numpad7}
Sleep, 250
SendInput {Numpad4}
Sleep, 250
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad2}
Sleep, 625
SendInput {Numpad0}
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad9}
SendInput {Numpad2}
Sleep, 125
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 125
SendInput {Numpad4}
Sleep, 125
SendInput {Numpad2}
Sleep, 125
SendInput {Numpad4}
Sleep, 125
SendInput {Numpad4}
Sleep, 125
SendInput {Numpad3}
Sleep, 125
SendInput {Numpad5}
Sleep, 125
SendInput {Numpad7}
SendInput {Numpad3}
Sleep, 125
SendInput {Numpad2}
Sleep, 125
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad3}
Sleep, 250
SendInput {Numpad2}
SendInput {Numpad6}
SendInput {F5}
SendInput {Numpad4}
Sleep, 125
SendInput {Numpad1}
SendInput {Numpad2}
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 250
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad4}
Sleep, 250
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad2}
SendInput {Numpad4}
Sleep, 250
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad2}
SendInput {Numpad4}
Sleep, 250
SendInput {Numpad6}
Sleep, 125
SendInput {Numpad2}
SendInput {Numpad4}
Sleep, 125
SendInput {Numpad1}
SendInput {Numpad6}
SendInput {Numpad3}
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad9}
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad4}
Sleep, 250
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad6}
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad9}
SendInput {Numpad6}
Sleep, 125
SendInput {Numpad2}
Sleep, 125
SendInput {Numpad1}
SendInput {Numpad2}
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 250
SendInput {Numpad9}
SendInput {Numpad2}
Sleep, 125
SendInput {Numpad4}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 125
SendInput {Numpad4}
Sleep, 250
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad2}
Sleep, 875
SendInput {Numpad2}
Sleep, 125
SendInput {Numpad1}
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 250
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad4}
SendInput {Numpad2}
SendInput {Numpad5}
SendInput {Numpad7}
Sleep, 250
SendInput {Numpad9}
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad2}
SendInput {Numpad1}
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 750
SendInput {Numpad6}
Sleep, 125
SendInput {Numpad2}
Sleep, 125
SendInput {Numpad1}
SendInput {Numpad7}
SendInput {Numpad2}
SendInput {Numpad4}
Sleep, 250
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad4}
SendInput {Numpad5}
Sleep, 125
SendInput {Numpad2}
Sleep, 125
SendInput {Numpad5}
Sleep, 125
SendInput {Numpad7}
SendInput {Numpad4}
Sleep, 125
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad9}
SendInput {Numpad7}
SendInput {Numpad4}
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad5}
Sleep, 125
SendInput {Numpad2}
SendInput {Numpad6}
Sleep, 125
SendInput {Numpad1}
SendInput {Numpad2}
SendInput {Numpad4}
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad4}
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad5}
SendInput {Numpad4}
Sleep, 125
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 125
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad6}
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad9}
SendInput {Numpad6}
Sleep, 125
SendInput {Numpad2}
Sleep, 125
SendInput {Numpad1}
SendInput {Numpad2}
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 250
SendInput {Numpad9}
SendInput {Numpad2}
Sleep, 125
SendInput {Numpad4}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 125
SendInput {Numpad4}
Sleep, 250
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad2}
Sleep, 875
SendInput {Numpad2}
Sleep, 125
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad4}
SendInput {Numpad2}
SendInput {Numpad5}
SendInput {Numpad7}
Sleep, 250
SendInput {Numpad9}
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad2}
SendInput {Numpad1}
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 750
SendInput {Numpad6}
Sleep, 125
SendInput {Numpad2}
Sleep, 125
SendInput {Numpad1}
SendInput {Numpad7}
SendInput {Numpad2}
SendInput {Numpad4}
Sleep, 250
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad4}
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad5}
SendInput {Numpad4}
Sleep, 125
SendInput {Numpad7}
SendInput {Numpad4}
Sleep, 125
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad4}
Sleep, 250
SendInput {Numpad5}
Sleep, 125
SendInput {Numpad2}
Sleep, 125
SendInput {F5}
SendInput {Numpad2}
SendInput {Numpad4}
SendInput {F4}
Sleep, 250
SendInput {Numpad4}
Sleep, 250
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad5}
SendInput {Numpad2}
SendInput {Numpad4}
SendInput {Numpad7}
Sleep, 250
SendInput {F4}
Sleep, 250
SendInput {Numpad4}
Sleep, 250
SendInput {Numpad1}
SendInput {Numpad2}
SendInput {Numpad4}
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 125
SendInput {Numpad2}
Sleep, 125
SendInput {Numpad1}
SendInput {Numpad2}
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 250
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad4}
Sleep, 125
SendInput {Numpad1}
Sleep, 125
SendInput {Numpad5}
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 250
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad2}
SendInput {Numpad4}
Sleep, 375
SendInput {Numpad9}
SendInput {Numpad2}
Sleep, 125
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad4}
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad5}
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad9}
SendInput {Numpad2}
Sleep, 500
SendInput {Numpad0}
SendInput {Numpad4}
Sleep, 375
SendInput {Numpad9}
SendInput {Numpad2}
Sleep, 125
SendInput {Numpad1}
SendInput {Numpad4}
SendInput {Numpad6}
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad4}
Sleep, 250
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad2}
Sleep, 875
SendInput {Numpad2}
Sleep, 125
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad4}
Sleep, 250
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad2}
Sleep, 875
SendInput {Numpad2}
Sleep, 125
SendInput {Numpad1}
SendInput {Numpad5}
SendInput {Numpad7}
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad4}
Sleep, 250
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad3}
Sleep, 125
SendInput {Numpad9}
SendInput {Numpad2}
SendInput {Numpad7}
SendInput {Numpad4}
Sleep, 125
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad4}
Sleep, 250
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad2}
Sleep, 125
SendInput {Numpad1}
Sleep, 125
SendInput {Numpad6}
Sleep, 625
SendInput {Numpad2}
SendInput {Numpad6}
Sleep, 125
SendInput {Numpad1}
SendInput {Numpad6}
SendInput {Numpad2}
SendInput {Numpad4}
Sleep, 250
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad4}
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad5}
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad9}
SendInput {Numpad2}
SendInput {Numpad6}
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad4}
Sleep, 125
SendInput {Numpad2}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 125
SendInput {Numpad1}
Sleep, 125
SendInput {Numpad1}
Sleep, 125
SendInput {Numpad9}
SendInput {Numpad2}
SendInput {Numpad6}
Sleep, 250
SendInput {Numpad4}
Sleep, 250
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad2}
Sleep, 500
SendInput {Numpad0}
SendInput {Numpad6}
SendInput {Numpad1}
SendInput {Numpad4}
Sleep, 375
SendInput {Numpad9}
SendInput {Numpad2}
Sleep, 125
SendInput {Numpad1}
SendInput {Numpad5}
SendInput {Numpad7}
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad4}
Sleep, 250
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad3}
Sleep, 125
SendInput {Numpad9}
SendInput {Numpad2}
SendInput {Numpad7}
SendInput {Numpad4}
Sleep, 125
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad4}
Sleep, 250
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad2}
Sleep, 125
SendInput {Numpad1}
Sleep, 125
SendInput {Numpad6}
Sleep, 625
SendInput {Numpad2}
Sleep, 125
SendInput {Numpad1}
SendInput {Numpad6}
SendInput {Numpad2}
SendInput {Numpad4}
Sleep, 250
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad4}
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad5}
SendInput {Numpad1}
Sleep, 125
SendInput {Numpad6}
SendInput {Numpad2}
Sleep, 125
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad4}
Sleep, 125
SendInput {Numpad2}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 125
SendInput {Numpad1}
Sleep, 125
SendInput {Numpad1}
Sleep, 125
SendInput {Numpad9}
SendInput {Numpad2}
SendInput {Numpad6}
Sleep, 250
SendInput {Numpad4}
Sleep, 250
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad2}
SendInput {Numpad4}
SendInput {Numpad5}
SendInput {Numpad7}
Sleep, 250
SendInput {Numpad6}
Sleep, 125
SendInput {Numpad2}
SendInput {Numpad7}
SendInput {Numpad5}
Sleep, 125
SendInput {Numpad1}
Sleep, 125
SendInput {Numpad4}
Sleep, 125
SendInput {Numpad9}
SendInput {Numpad2}
SendInput {Numpad7}
Sleep, 250
SendInput {Numpad4}
Sleep, 250
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad2}
Sleep, 625
SendInput {Numpad0}
SendInput {Numpad5}
Sleep, 125
SendInput {Numpad5}
Sleep, 125
SendInput {Numpad2}
Sleep, 125
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 125
SendInput {Numpad4}
Sleep, 125
SendInput {Numpad2}
Sleep, 125
SendInput {Numpad4}
Sleep, 125
SendInput {Numpad4}
Sleep, 125
SendInput {Numpad3}
Sleep, 125
SendInput {Numpad5}
Sleep, 125
SendInput {Numpad7}
SendInput {Numpad3}
Sleep, 125
SendInput {Numpad2}
Sleep, 125
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad3}
Sleep, 250
SendInput {Numpad9}
SendInput {Numpad2}
SendInput {Numpad6}
SendInput {Numpad1}
SendInput {Numpad4}
Sleep, 125
SendInput {Numpad1}
SendInput {Numpad2}
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 125
SendInput {Numpad6}
SendInput {Numpad1}
SendInput {Numpad2}
Sleep, 125
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad4}
Sleep, 250
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad2}
SendInput {Numpad6}
SendInput {Numpad1}
SendInput {Numpad4}
Sleep, 875
SendInput {Numpad9}
SendInput {Numpad2}
Sleep, 125
SendInput {Numpad1}
SendInput {Numpad6}
SendInput {Numpad2}
SendInput {Numpad4}
Sleep, 250
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad4}
Sleep, 250
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad4}
Sleep, 250
SendInput {Numpad6}
Sleep, 125
SendInput {Numpad2}
SendInput {Numpad7}
SendInput {Numpad5}
Sleep, 125
SendInput {Numpad1}
SendInput {Numpad2}
SendInput {Numpad5}
SendInput {Numpad7}
Sleep, 125
SendInput {Numpad4}
Sleep, 125
SendInput {Numpad9}
SendInput {Numpad2}
SendInput {Numpad7}
Sleep, 250
SendInput {Numpad4}
Sleep, 250
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad2}
Sleep, 625
SendInput {Numpad0}
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad9}
SendInput {Numpad2}
Sleep, 125
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 125
SendInput {Numpad4}
Sleep, 125
SendInput {Numpad2}
Sleep, 125
SendInput {Numpad4}
Sleep, 125
SendInput {Numpad4}
Sleep, 125
SendInput {Numpad3}
Sleep, 125
SendInput {Numpad5}
Sleep, 125
SendInput {Numpad7}
SendInput {Numpad3}
Sleep, 125
SendInput {Numpad2}
Sleep, 125
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad3}
Sleep, 250
SendInput {Numpad2}
SendInput {Numpad6}
SendInput {F5}
SendInput {Numpad4}
Sleep, 125
SendInput {Numpad1}
SendInput {Numpad2}
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 250
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad4}
Sleep, 250
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad2}
SendInput {Numpad4}
Sleep, 250
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad2}
SendInput {Numpad4}
Sleep, 250
SendInput {Numpad6}
Sleep, 125
SendInput {Numpad2}
SendInput {Numpad4}
Sleep, 125
SendInput {Numpad1}
SendInput {Numpad6}
SendInput {Numpad3}
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad9}
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad4}
Sleep, 250
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad6}
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad9}
SendInput {Numpad6}
Sleep, 125
SendInput {Numpad2}
Sleep, 125
SendInput {Numpad1}
SendInput {Numpad2}
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 250
SendInput {Numpad9}
SendInput {Numpad2}
Sleep, 125
SendInput {Numpad4}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 125
SendInput {Numpad4}
Sleep, 250
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad2}
Sleep, 875
SendInput {Numpad2}
Sleep, 125
SendInput {Numpad1}
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 250
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad4}
SendInput {Numpad2}
SendInput {Numpad5}
SendInput {Numpad7}
Sleep, 250
SendInput {Numpad9}
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad2}
SendInput {Numpad1}
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 750
SendInput {Numpad6}
Sleep, 125
SendInput {Numpad2}
Sleep, 125
SendInput {Numpad1}
SendInput {Numpad7}
SendInput {Numpad2}
SendInput {Numpad4}
Sleep, 250
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad4}
SendInput {Numpad5}
Sleep, 125
SendInput {Numpad2}
Sleep, 125
SendInput {Numpad5}
Sleep, 125
SendInput {Numpad7}
SendInput {Numpad4}
Sleep, 125
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad9}
SendInput {Numpad7}
SendInput {Numpad4}
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad5}
Sleep, 125
SendInput {Numpad2}
SendInput {Numpad6}
Sleep, 125
SendInput {Numpad1}
SendInput {Numpad2}
SendInput {Numpad4}
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad4}
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad5}
SendInput {Numpad4}
Sleep, 125
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 125
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad6}
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad9}
SendInput {Numpad6}
Sleep, 125
SendInput {Numpad2}
Sleep, 125
SendInput {Numpad1}
SendInput {Numpad2}
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 250
SendInput {Numpad9}
SendInput {Numpad2}
Sleep, 125
SendInput {Numpad4}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 125
SendInput {Numpad4}
Sleep, 250
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad2}
Sleep, 875
SendInput {Numpad2}
Sleep, 125
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad4}
SendInput {Numpad2}
SendInput {Numpad5}
SendInput {Numpad7}
Sleep, 250
SendInput {Numpad9}
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad2}
SendInput {Numpad1}
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 750
SendInput {Numpad6}
Sleep, 125
SendInput {Numpad2}
Sleep, 125
SendInput {Numpad1}
SendInput {Numpad7}
SendInput {Numpad2}
SendInput {Numpad4}
Sleep, 250
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad4}
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad5}
SendInput {Numpad4}
Sleep, 125
SendInput {Numpad7}
SendInput {Numpad4}
Sleep, 125
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad4}
Sleep, 250
SendInput {Numpad5}
Sleep, 125
SendInput {Numpad2}
Sleep, 125
SendInput {F5}
SendInput {Numpad2}
SendInput {Numpad4}
SendInput {F4}
Sleep, 250
SendInput {Numpad4}
Sleep, 250
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad5}
SendInput {Numpad2}
SendInput {Numpad4}
SendInput {Numpad7}
Sleep, 250
SendInput {F4}
Sleep, 250
SendInput {Numpad4}
Sleep, 250
SendInput {Numpad1}
SendInput {Numpad2}
SendInput {Numpad4}
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad9}
SendInput {Numpad2}
SendInput {Numpad4}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad9}
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad2}
Sleep, 125
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad1}
Sleep, 125
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad4}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad5}
SendInput {Numpad2}
SendInput {Numpad4}
SendInput {Numpad7}
Sleep, 875
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 375
SendInput {Numpad9}
SendInput {Numpad4}
SendInput {Numpad7}
Sleep, 125
SendInput {Numpad2}
Sleep, 125
SendInput {Numpad5}
SendInput {Numpad6}
Sleep, 375
SendInput {Numpad5}
Sleep, 375
SendInput {Numpad5}
SendInput {Numpad4}
Sleep, 125
SendInput {Numpad2}
Sleep, 125
SendInput {Numpad5}
SendInput {Numpad3}
Sleep, 375
SendInput {Numpad2}
Sleep, 125
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad3}
Sleep, 250
SendInput {Numpad5}
SendInput {Numpad7}
SendInput {Numpad2}
Sleep, 375
SendInput {Numpad4}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 375
SendInput {F5}
SendInput {Numpad2}
SendInput {Numpad3}
SendInput {Numpad4}
Sleep, 250
SendInput {Numpad9}
SendInput {F5}
SendInput {Numpad2}
SendInput {Numpad3}
Sleep, 750
SendInput {Numpad0}
SendInput {Numpad4}
Sleep, 125
SendInput {Numpad9}
SendInput {F5}
Sleep, 125
SendInput {F5}
SendInput {Numpad2}
Sleep, 750
SendInput {Numpad5}
Sleep, 125
SendInput {Numpad4}
Sleep, 125
SendInput {F5}
SendInput {Numpad2}
SendInput {Numpad4}
Sleep, 1000
SendInput {F5}
SendInput {Numpad2}
SendInput {Numpad4}
Sleep, 375
SendInput {Numpad0}
SendInput {Numpad1}
SendInput {Numpad3}
SendInput {Numpad5}
Sleep, 375
SendInput {Numpad2}
SendInput {Numpad4}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 625
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 375
SendInput {Numpad9}
SendInput {Numpad7}
Sleep, 125
SendInput {Numpad2}
Sleep, 125
SendInput {Numpad2}
SendInput {Numpad6}
Sleep, 250
SendInput {Numpad3}
Sleep, 125
SendInput {Numpad5}
Sleep, 125
SendInput {Numpad4}
Sleep, 250
SendInput {Numpad2}
SendInput {Numpad4}
Sleep, 250
SendInput {Numpad1}
SendInput {Numpad6}
SendInput {Numpad3}
SendInput {Numpad4}
Sleep, 375
SendInput {Numpad2}
Sleep, 125
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad3}
Sleep, 125
SendInput {Numpad1}
Sleep, 125
SendInput {Numpad1}
SendInput {Numpad4}
Sleep, 375
SendInput {Numpad5}
Sleep, 375
SendInput {Numpad2}
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 125
SendInput {Numpad1}
Sleep, 125
SendInput {Numpad7}
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad4}
Sleep, 125
SendInput {Numpad9}
SendInput {Numpad7}
SendInput {Numpad2}
Sleep, 500
SendInput {Numpad7}
Sleep, 125
SendInput {Numpad7}
Sleep, 500
SendInput {Numpad7}
SendInput {Numpad2}
Sleep, 375
SendInput {Numpad7}
Sleep, 125
SendInput {F5}
SendInput {Numpad2}
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 375
SendInput {Numpad5}
Sleep, 125
SendInput {F5}
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad2}
SendInput {Numpad6}
Sleep, 250
SendInput {Numpad0}
SendInput {F5}
SendInput {Numpad1}
Sleep, 375
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {F5}
Sleep, 125
SendInput {F5}
Sleep, 250
SendInput {F5}
SendInput {Numpad6}
Sleep, 250
SendInput {Numpad6}
SendInput {Numpad2}
SendInput {Numpad3}
Sleep, 500
SendInput {Numpad6}
Sleep, 125
SendInput {Numpad0}
SendInput {F5}
Sleep, 125
SendInput {Numpad6}
Sleep, 125
SendInput {Numpad3}
SendInput {Numpad5}
Sleep, 125
SendInput {Numpad6}
SendInput {Numpad2}
SendInput {Numpad3}
Sleep, 500
SendInput {Numpad9}
SendInput {Numpad6}
Sleep, 375
SendInput {Numpad6}
Sleep, 125
SendInput {Numpad6}
SendInput {F1}
SendInput {Numpad3}
Sleep, 500
SendInput {Numpad6}
Sleep, 500
SendInput {Numpad6}
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad4}
Sleep, 250
SendInput {Numpad2}
Sleep, 125
SendInput {Numpad1}
Sleep, 125
SendInput {Numpad1}
Sleep, 125
SendInput {Numpad2}
Sleep, 125
SendInput {Numpad1}
SendInput {Numpad5}
SendInput {Numpad7}
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad9}
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad4}
Sleep, 250
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad3}
Sleep, 125
SendInput {Numpad9}
SendInput {Numpad2}
SendInput {Numpad7}
SendInput {Numpad4}
Sleep, 125
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad4}
Sleep, 250
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad2}
Sleep, 125
SendInput {Numpad1}
Sleep, 125
SendInput {Numpad6}
Sleep, 625
SendInput {Numpad2}
SendInput {Numpad6}
Sleep, 125
SendInput {Numpad1}
SendInput {Numpad6}
SendInput {Numpad2}
SendInput {Numpad4}
Sleep, 250
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad4}
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad5}
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad9}
SendInput {Numpad2}
SendInput {Numpad6}
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad4}
Sleep, 125
SendInput {Numpad2}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 125
SendInput {Numpad1}
Sleep, 125
SendInput {Numpad1}
Sleep, 125
SendInput {Numpad9}
SendInput {Numpad2}
SendInput {Numpad6}
Sleep, 250
SendInput {Numpad4}
Sleep, 250
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad2}
Sleep, 500
SendInput {Numpad0}
SendInput {Numpad6}
SendInput {Numpad1}
SendInput {Numpad4}
Sleep, 375
SendInput {Numpad9}
SendInput {Numpad2}
Sleep, 125
SendInput {Numpad1}
SendInput {Numpad5}
SendInput {Numpad7}
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad4}
Sleep, 250
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad3}
Sleep, 125
SendInput {Numpad9}
SendInput {Numpad2}
SendInput {Numpad7}
SendInput {Numpad4}
Sleep, 125
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad4}
Sleep, 250
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad2}
Sleep, 125
SendInput {Numpad1}
Sleep, 125
SendInput {Numpad6}
Sleep, 625
SendInput {Numpad2}
Sleep, 125
SendInput {Numpad1}
SendInput {Numpad6}
SendInput {Numpad2}
SendInput {Numpad4}
Sleep, 250
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad4}
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad5}
SendInput {Numpad1}
Sleep, 125
SendInput {Numpad6}
SendInput {Numpad2}
Sleep, 125
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad4}
Sleep, 125
SendInput {Numpad2}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 125
SendInput {Numpad1}
Sleep, 125
SendInput {Numpad1}
Sleep, 125
SendInput {Numpad9}
SendInput {Numpad2}
SendInput {Numpad6}
Sleep, 250
SendInput {Numpad4}
Sleep, 250
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad2}
SendInput {Numpad4}
SendInput {Numpad5}
SendInput {Numpad7}
Sleep, 250
SendInput {Numpad6}
Sleep, 125
SendInput {Numpad2}
SendInput {Numpad7}
SendInput {Numpad5}
Sleep, 125
SendInput {Numpad1}
Sleep, 125
SendInput {Numpad4}
Sleep, 125
SendInput {Numpad9}
SendInput {Numpad2}
SendInput {Numpad7}
Sleep, 250
SendInput {Numpad4}
Sleep, 250
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad2}
Sleep, 625
SendInput {Numpad0}
SendInput {Numpad5}
Sleep, 125
SendInput {Numpad5}
Sleep, 125
SendInput {Numpad2}
Sleep, 125
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 125
SendInput {Numpad4}
Sleep, 125
SendInput {Numpad2}
Sleep, 125
SendInput {Numpad4}
Sleep, 125
SendInput {Numpad4}
Sleep, 125
SendInput {Numpad3}
Sleep, 125
SendInput {Numpad5}
Sleep, 125
SendInput {Numpad7}
SendInput {Numpad3}
Sleep, 125
SendInput {Numpad2}
Sleep, 125
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad3}
Sleep, 250
SendInput {Numpad9}
SendInput {Numpad2}
SendInput {Numpad6}
SendInput {Numpad1}
SendInput {Numpad4}
Sleep, 125
SendInput {Numpad1}
SendInput {Numpad2}
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 125
SendInput {Numpad6}
SendInput {Numpad1}
SendInput {Numpad2}
Sleep, 125
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad4}
Sleep, 250
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad2}
SendInput {Numpad6}
SendInput {Numpad1}
SendInput {Numpad4}
Sleep, 875
SendInput {Numpad9}
SendInput {Numpad2}
Sleep, 125
SendInput {Numpad1}
SendInput {Numpad6}
SendInput {Numpad2}
SendInput {Numpad4}
Sleep, 250
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad4}
Sleep, 250
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad4}
Sleep, 250
SendInput {Numpad6}
Sleep, 125
SendInput {Numpad2}
SendInput {Numpad7}
SendInput {Numpad5}
Sleep, 125
SendInput {Numpad1}
SendInput {Numpad2}
SendInput {Numpad5}
SendInput {Numpad7}
Sleep, 125
SendInput {Numpad4}
Sleep, 125
SendInput {Numpad9}
SendInput {Numpad2}
SendInput {Numpad7}
Sleep, 250
SendInput {Numpad4}
Sleep, 250
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad2}
Sleep, 625
SendInput {Numpad0}
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad9}
SendInput {Numpad2}
Sleep, 125
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 125
SendInput {Numpad4}
Sleep, 125
SendInput {Numpad2}
Sleep, 125
SendInput {Numpad4}
Sleep, 125
SendInput {Numpad4}
Sleep, 125
SendInput {Numpad3}
Sleep, 125
SendInput {Numpad5}
Sleep, 125
SendInput {Numpad7}
SendInput {Numpad3}
Sleep, 125
SendInput {Numpad2}
Sleep, 125
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad3}
Sleep, 250
SendInput {Numpad2}
SendInput {Numpad6}
SendInput {F5}
SendInput {Numpad4}
Sleep, 125
SendInput {Numpad1}
SendInput {Numpad2}
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 250
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad4}
Sleep, 250
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad2}
SendInput {Numpad4}
Sleep, 250
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad2}
SendInput {Numpad4}
Sleep, 250
SendInput {Numpad6}
Sleep, 125
SendInput {Numpad2}
SendInput {Numpad4}
Sleep, 125
SendInput {Numpad1}
SendInput {Numpad6}
SendInput {Numpad3}
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad9}
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad4}
Sleep, 250
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad6}
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad9}
SendInput {Numpad6}
Sleep, 125
SendInput {Numpad2}
Sleep, 125
SendInput {Numpad1}
SendInput {Numpad2}
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 250
SendInput {Numpad9}
SendInput {Numpad2}
Sleep, 125
SendInput {Numpad4}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 125
SendInput {Numpad4}
Sleep, 250
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad2}
Sleep, 875
SendInput {Numpad2}
Sleep, 125
SendInput {Numpad1}
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 250
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad4}
SendInput {Numpad2}
SendInput {Numpad5}
SendInput {Numpad7}
Sleep, 250
SendInput {Numpad9}
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad2}
SendInput {Numpad1}
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 750
SendInput {Numpad6}
Sleep, 125
SendInput {Numpad2}
Sleep, 125
SendInput {Numpad1}
SendInput {Numpad7}
SendInput {Numpad2}
SendInput {Numpad4}
Sleep, 250
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad4}
SendInput {Numpad5}
Sleep, 125
SendInput {Numpad2}
Sleep, 125
SendInput {Numpad5}
Sleep, 125
SendInput {Numpad7}
SendInput {Numpad4}
Sleep, 125
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad9}
SendInput {Numpad7}
SendInput {Numpad4}
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad5}
Sleep, 125
SendInput {Numpad2}
SendInput {Numpad6}
Sleep, 125
SendInput {Numpad1}
SendInput {Numpad2}
SendInput {Numpad4}
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad4}
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad5}
SendInput {Numpad4}
Sleep, 125
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 125
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad6}
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad9}
SendInput {Numpad6}
Sleep, 125
SendInput {Numpad2}
Sleep, 125
SendInput {Numpad1}
SendInput {Numpad2}
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 250
SendInput {Numpad9}
SendInput {Numpad2}
Sleep, 125
SendInput {Numpad4}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 125
SendInput {Numpad4}
Sleep, 250
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad2}
Sleep, 875
SendInput {Numpad2}
Sleep, 125
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad4}
SendInput {Numpad2}
SendInput {Numpad5}
SendInput {Numpad7}
Sleep, 250
SendInput {Numpad9}
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad2}
SendInput {Numpad1}
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 750
SendInput {Numpad6}
Sleep, 125
SendInput {Numpad2}
Sleep, 125
SendInput {Numpad1}
SendInput {Numpad7}
SendInput {Numpad2}
SendInput {Numpad4}
Sleep, 250
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad4}
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad5}
SendInput {Numpad4}
Sleep, 125
SendInput {Numpad7}
SendInput {Numpad4}
Sleep, 125
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad4}
Sleep, 250
SendInput {Numpad5}
Sleep, 125
SendInput {Numpad2}
Sleep, 125
SendInput {Numpad2}
SendInput {Numpad4}
SendInput {F4}
SendInput {F5}
Sleep, 250
SendInput {Numpad4}
Sleep, 250
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad5}
SendInput {Numpad2}
SendInput {Numpad4}
SendInput {Numpad7}
Sleep, 250
SendInput {F4}
Sleep, 250
SendInput {Numpad4}
Sleep, 250
SendInput {Numpad1}
SendInput {Numpad2}
SendInput {Numpad4}
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad9}
SendInput {F4}
Sleep, 250
SendInput {Numpad3}
SendInput {Numpad2}
SendInput {F4}
SendInput {Numpad7}
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad9}
SendInput {Numpad7}
Sleep, 250
SendInput {F2}
SendInput {F1}
SendInput {F4}
SendInput {F5}
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad4}
Sleep, 250
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad9}
SendInput {Numpad1}
SendInput {Numpad4}
SendInput {Numpad5}
SendInput {F5}
Sleep, 750
SendInput {Numpad1}
Sleep, 500
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad6}
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad9}
SendInput {Numpad6}
Sleep, 125
SendInput {Numpad2}
Sleep, 125
SendInput {Numpad1}
SendInput {Numpad2}
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 250
SendInput {Numpad9}
SendInput {Numpad2}
Sleep, 125
SendInput {Numpad4}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 125
SendInput {Numpad4}
Sleep, 250
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad2}
Sleep, 875
SendInput {Numpad2}
Sleep, 125
SendInput {Numpad1}
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 250
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad4}
SendInput {Numpad2}
SendInput {Numpad5}
SendInput {Numpad7}
Sleep, 250
SendInput {Numpad9}
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad2}
SendInput {Numpad1}
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 750
SendInput {Numpad6}
Sleep, 125
SendInput {Numpad2}
Sleep, 125
SendInput {Numpad1}
SendInput {Numpad7}
SendInput {Numpad2}
SendInput {Numpad4}
Sleep, 250
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad4}
SendInput {Numpad5}
Sleep, 125
SendInput {Numpad2}
Sleep, 125
SendInput {Numpad5}
Sleep, 125
SendInput {Numpad7}
SendInput {Numpad4}
Sleep, 125
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad9}
SendInput {Numpad7}
SendInput {Numpad4}
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad5}
Sleep, 125
SendInput {Numpad2}
SendInput {Numpad6}
Sleep, 125
SendInput {Numpad1}
SendInput {Numpad2}
SendInput {Numpad4}
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad4}
Sleep, 250
SendInput {Numpad5}
SendInput {Numpad2}
Sleep, 125
SendInput {Numpad2}
SendInput {Numpad6}
Sleep, 125
SendInput {Numpad2}
Sleep, 500
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad4}
Sleep, 125
SendInput {Numpad2}
Sleep, 125
SendInput {Numpad1}
SendInput {Numpad2}
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 250
SendInput {Numpad9}
SendInput {Numpad2}
Sleep, 125
SendInput {Numpad4}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 125
SendInput {Numpad4}
Sleep, 250
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad2}
Sleep, 875
SendInput {Numpad2}
Sleep, 125
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad4}
SendInput {Numpad2}
SendInput {Numpad5}
SendInput {Numpad7}
Sleep, 250
SendInput {Numpad9}
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad2}
SendInput {Numpad1}
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 750
SendInput {Numpad6}
Sleep, 125
SendInput {Numpad2}
Sleep, 125
SendInput {Numpad1}
SendInput {Numpad7}
SendInput {Numpad2}
SendInput {Numpad4}
Sleep, 250
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad4}
SendInput {Numpad5}
Sleep, 250
SendInput {Numpad5}
SendInput {Numpad4}
Sleep, 125
SendInput {Numpad7}
SendInput {Numpad4}
Sleep, 125
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad4}
Sleep, 250
SendInput {Numpad5}
Sleep, 125
SendInput {Numpad2}
Sleep, 125
SendInput {F5}
SendInput {Numpad2}
SendInput {Numpad4}
SendInput {F4}
Sleep, 250
SendInput {Numpad4}
Sleep, 250
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad5}
SendInput {Numpad2}
SendInput {Numpad4}
SendInput {Numpad7}
Sleep, 250
SendInput {F4}
Sleep, 250
SendInput {Numpad4}
Sleep, 250
SendInput {Numpad1}
SendInput {Numpad2}
SendInput {Numpad4}
SendInput {Numpad5}
Sleep, 375
SendInput {Numpad9}
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad0}
SendInput {Numpad2}
Sleep, 125
SendInput {Numpad9}
SendInput {Numpad2}
SendInput {Numpad6}
Sleep, 125
SendInput {Numpad5}
Sleep, 125
SendInput {Numpad6}
Sleep, 250
SendInput {Numpad6}
Sleep, 125
SendInput {Numpad5}
Sleep, 125
SendInput {Numpad6}
Sleep, 250
SendInput {Numpad6}
Sleep, 125
SendInput {Numpad5}
Sleep, 125
SendInput {Numpad6}
Sleep, 125
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad2}
Sleep, 125
SendInput {Numpad2}
SendInput {Numpad6}
Sleep, 125
SendInput {Numpad5}
Sleep, 125
SendInput {Numpad6}
Sleep, 250
SendInput {Numpad6}
Sleep, 125
SendInput {Numpad5}
Sleep, 125
SendInput {Numpad6}
Sleep, 250
SendInput {Numpad6}
Sleep, 125
SendInput {Numpad5}
Sleep, 125
SendInput {Numpad6}
Sleep, 125
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad2}
Sleep, 125
SendInput {Numpad2}
SendInput {Numpad6}
Sleep, 125
SendInput {Numpad5}
Sleep, 125
SendInput {Numpad6}
Sleep, 250
SendInput {Numpad6}
Sleep, 125
SendInput {Numpad5}
Sleep, 125
SendInput {Numpad6}
Sleep, 250
SendInput {Numpad6}
Sleep, 125
SendInput {Numpad5}
Sleep, 125
SendInput {Numpad6}
Sleep, 125
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad2}
Sleep, 250
SendInput {Numpad2}
Sleep, 125
SendInput {Numpad2}
SendInput {Numpad6}
Sleep, 125
SendInput {Numpad5}
Sleep, 125
SendInput {Numpad6}
Sleep, 250
SendInput {Numpad6}
Sleep, 125
SendInput {Numpad5}
Sleep, 125
SendInput {Numpad6}
Sleep, 250
SendInput {Numpad6}
Sleep, 125
SendInput {Numpad5}
Sleep, 125
SendInput {Numpad6}
Sleep, 125
SendInput {Numpad1}
Sleep, 250
SendInput {Numpad2}
Sleep, 125
SendInput {Numpad3}
Sleep, 125
SendInput {Numpad2}
Sleep, 125
SendInput {Numpad2}
Sleep, 1625
SendInput {Numpad2}
Sleep, 125
SendInput {Numpad4}
SendInput {F5}
SendInput {Numpad2}
Sleep, 125
SendInput {Numpad2}
Sleep, 125
SendInput {Numpad2}
Sleep, 1625
SendInput {Numpad2}
Sleep, 125
SendInput {Numpad3}
SendInput {Numpad5}
SendInput {Numpad1}
Sleep, 125
SendInput {Numpad2}
Sleep, 125
SendInput {Numpad2}
Sleep, 1625
SendInput {Numpad2}
Sleep, 125
SendInput {Numpad2}
SendInput {Numpad5}
SendInput {Numpad7}
Sleep, 125
SendInput {Numpad2}
Sleep, 125
SendInput {Numpad2}
Sleep, 1750
SendInput {Numpad0}
SendInput {Numpad3}
Sleep, 125
SendInput {Numpad2}
Sleep, 125
SendInput {Numpad2}
Sleep, 1625
SendInput {Numpad2}
Sleep, 125
SendInput {Numpad4}
SendInput {F5}
SendInput {Numpad2}
Sleep, 125
SendInput {Numpad2}
Sleep, 125
SendInput {Numpad2}
Sleep, 1625
SendInput {Numpad2}
Sleep, 125
SendInput {Numpad3}
SendInput {Numpad5}
SendInput {Numpad1}
Sleep, 125
SendInput {Numpad2}
Sleep, 125
SendInput {Numpad2}
Sleep, 1625
SendInput {Numpad2}
Sleep, 125
SendInput {Numpad2}
SendInput {Numpad5}
SendInput {Numpad7}
Sleep, 125
SendInput {Numpad2}
Sleep, 125
SendInput {Numpad2}
