# title: Wonderwall
# author: Oasis
# instrument: Harp
; Converted by Serenade Music Converter

SendInput {Numpad3}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 75
SendInput {Numpad6}
Sleep, 675
SendInput {Numpad6}
Sleep, 75
SendInput {Numpad3}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 675
SendInput {Numpad9}
SendInput {Numpad1}
Sleep, 188
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 563
SendInput {Numpad1}
SendInput {Numpad3}
SendInput {Numpad5}
Sleep, 750
SendInput {Numpad5}
Sleep, 188
SendInput {Numpad2}
SendInput {Numpad5}
SendInput {Numpad1}
Sleep, 563
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad5}
SendInput {Numpad1}
Sleep, 75
SendInput {Numpad5}
Sleep, 675
SendInput {Numpad6}
Sleep, 188
SendInput {Numpad1}
SendInput {Numpad6}
Sleep, 563
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 75
SendInput {Numpad6}
Sleep, 300
SendInput {Numpad6}
Sleep, 375
SendInput {Numpad6}
Sleep, 75
SendInput {Numpad3}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 675
SendInput {Numpad3}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 75
SendInput {Numpad6}
Sleep, 675
SendInput {Numpad1}
Sleep, 188
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 563
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad1}
SendInput {Numpad3}
SendInput {Numpad5}
Sleep, 750
SendInput {Numpad5}
Sleep, 188
SendInput {Numpad2}
SendInput {Numpad5}
SendInput {Numpad1}
Sleep, 563
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad5}
SendInput {Numpad1}
Sleep, 75
SendInput {Numpad5}
Sleep, 675
SendInput {Numpad6}
Sleep, 188
SendInput {Numpad1}
SendInput {Numpad6}
Sleep, 563
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 75
SendInput {Numpad6}
Sleep, 300
SendInput {Numpad6}
Sleep, 375
SendInput {Numpad6}
Sleep, 75
SendInput {Numpad3}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 675
SendInput {Numpad3}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 75
SendInput {Numpad6}
Sleep, 675
SendInput {Numpad1}
Sleep, 188
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 563
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad1}
SendInput {Numpad3}
SendInput {Numpad5}
Sleep, 750
SendInput {Numpad5}
Sleep, 188
SendInput {Numpad2}
SendInput {Numpad5}
SendInput {Numpad1}
Sleep, 563
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad5}
SendInput {Numpad1}
Sleep, 75
SendInput {Numpad5}
Sleep, 675
SendInput {Numpad6}
Sleep, 188
SendInput {Numpad1}
SendInput {Numpad6}
Sleep, 563
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 75
SendInput {Numpad6}
Sleep, 300
SendInput {Numpad6}
Sleep, 375
SendInput {Numpad6}
Sleep, 75
SendInput {Numpad3}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 675
SendInput {Numpad3}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 75
SendInput {Numpad6}
Sleep, 675
SendInput {Numpad1}
Sleep, 188
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 563
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad1}
SendInput {Numpad3}
SendInput {Numpad5}
Sleep, 750
SendInput {Numpad5}
Sleep, 188
SendInput {Numpad2}
SendInput {Numpad5}
SendInput {Numpad1}
Sleep, 563
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad5}
SendInput {Numpad1}
Sleep, 75
SendInput {Numpad5}
Sleep, 675
SendInput {Numpad6}
Sleep, 188
SendInput {Numpad1}
SendInput {Numpad6}
Sleep, 563
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 75
SendInput {Numpad6}
Sleep, 300
SendInput {Numpad6}
Sleep, 375
SendInput {Numpad6}
Sleep, 415
SendInput {Numpad3}
Sleep, 335
SendInput {Numpad9}
SendInput {Numpad2}
SendInput {Numpad6}
Sleep, 75
SendInput {Numpad6}
Sleep, 488
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 188
SendInput {Numpad1}
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 188
SendInput {Numpad1}
Sleep, 188
SendInput {Numpad2}
Sleep, 188
SendInput {Numpad1}
Sleep, 188
SendInput {Numpad1}
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 415
SendInput {Numpad2}
Sleep, 148
SendInput {Numpad1}
Sleep, 188
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 188
SendInput {Numpad1}
Sleep, 188
SendInput {Numpad2}
Sleep, 188
SendInput {Numpad1}
Sleep, 188
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 75
SendInput {Numpad5}
Sleep, 340
SendInput {Numpad3}
Sleep, 148
SendInput {Numpad3}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 188
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad6}
Sleep, 188
SendInput {Numpad6}
Sleep, 563
SendInput {Numpad6}
Sleep, 750
SendInput {Numpad6}
Sleep, 415
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad3}
Sleep, 335
SendInput {Numpad9}
SendInput {Numpad2}
SendInput {Numpad6}
Sleep, 75
SendInput {Numpad6}
Sleep, 488
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 188
SendInput {Numpad1}
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 188
SendInput {Numpad1}
Sleep, 188
SendInput {Numpad2}
Sleep, 188
SendInput {Numpad1}
Sleep, 188
SendInput {Numpad1}
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 415
SendInput {Numpad2}
Sleep, 148
SendInput {Numpad1}
Sleep, 188
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 188
SendInput {Numpad1}
Sleep, 188
SendInput {Numpad2}
Sleep, 188
SendInput {Numpad1}
Sleep, 188
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 75
SendInput {Numpad5}
Sleep, 340
SendInput {Numpad3}
Sleep, 148
SendInput {Numpad3}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 188
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad6}
Sleep, 188
SendInput {Numpad6}
Sleep, 563
SendInput {Numpad6}
Sleep, 750
SendInput {Numpad6}
Sleep, 75
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 113
SendInput {Numpad5}
Sleep, 188
SendInput {Numpad3}
Sleep, 188
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 40
SendInput {Numpad6}
Sleep, 523
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad5}
Sleep, 188
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 40
SendInput {Numpad1}
Sleep, 523
SendInput {Numpad5}
Sleep, 188
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 188
SendInput {Numpad1}
Sleep, 188
SendInput {Numpad1}
Sleep, 563
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 563
SendInput {Numpad2}
Sleep, 188
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 188
SendInput {Numpad3}
Sleep, 375
SendInput {Numpad9}
SendInput {Numpad3}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 188
SendInput {Numpad6}
Sleep, 188
SendInput {Numpad6}
Sleep, 188
SendInput {Numpad5}
Sleep, 188
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 75
SendInput {Numpad6}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 188
SendInput {Numpad1}
Sleep, 188
SendInput {Numpad3}
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 375
SendInput {Numpad9}
SendInput {Numpad6}
Sleep, 375
SendInput {Numpad9}
SendInput {Numpad1}
SendInput {Numpad3}
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 750
SendInput {Numpad5}
Sleep, 75
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 153
SendInput {Numpad5}
Sleep, 523
SendInput {Numpad5}
Sleep, 75
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 75
SendInput {Numpad5}
Sleep, 300
SendInput {Numpad6}
Sleep, 75
SendInput {Numpad3}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad6}
Sleep, 375
SendInput {Numpad6}
Sleep, 75
SendInput {Numpad3}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 300
SendInput {Numpad3}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 75
SendInput {Numpad6}
Sleep, 675
SendInput {Numpad0}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 188
SendInput {Numpad6}
Sleep, 563
SendInput {Numpad3}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 75
SendInput {Numpad6}
Sleep, 300
SendInput {Numpad6}
Sleep, 75
SendInput {Numpad3}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 300
SendInput {Numpad9}
SendInput {Numpad6}
Sleep, 415
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad3}
Sleep, 335
SendInput {Numpad9}
SendInput {Numpad2}
SendInput {Numpad6}
Sleep, 75
SendInput {Numpad6}
Sleep, 488
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 188
SendInput {Numpad1}
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 188
SendInput {Numpad1}
Sleep, 188
SendInput {Numpad2}
Sleep, 188
SendInput {Numpad1}
Sleep, 188
SendInput {Numpad1}
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 415
SendInput {Numpad2}
Sleep, 148
SendInput {Numpad1}
Sleep, 188
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 188
SendInput {Numpad1}
Sleep, 188
SendInput {Numpad2}
Sleep, 188
SendInput {Numpad1}
Sleep, 188
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 75
SendInput {Numpad5}
Sleep, 340
SendInput {Numpad3}
Sleep, 148
SendInput {Numpad9}
SendInput {Numpad3}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 188
SendInput {Numpad2}
Sleep, 563
SendInput {Numpad1}
Sleep, 188
SendInput {Numpad2}
Sleep, 375
SendInput {Numpad1}
Sleep, 375
SendInput {Numpad9}
SendInput {Numpad6}
Sleep, 415
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad3}
Sleep, 335
SendInput {Numpad9}
SendInput {Numpad2}
SendInput {Numpad6}
Sleep, 75
SendInput {Numpad6}
Sleep, 488
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 188
SendInput {Numpad1}
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 188
SendInput {Numpad1}
Sleep, 188
SendInput {Numpad2}
Sleep, 188
SendInput {Numpad1}
Sleep, 188
SendInput {Numpad1}
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 415
SendInput {Numpad2}
Sleep, 148
SendInput {Numpad1}
Sleep, 188
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 188
SendInput {Numpad1}
Sleep, 188
SendInput {Numpad2}
Sleep, 188
SendInput {Numpad1}
Sleep, 188
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 75
SendInput {Numpad5}
Sleep, 340
SendInput {Numpad3}
Sleep, 148
SendInput {Numpad9}
SendInput {Numpad3}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 188
SendInput {Numpad2}
Sleep, 563
SendInput {Numpad1}
Sleep, 188
SendInput {Numpad2}
Sleep, 375
SendInput {Numpad1}
Sleep, 375
SendInput {Numpad9}
SendInput {Numpad6}
Sleep, 75
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 113
SendInput {Numpad5}
Sleep, 188
SendInput {Numpad3}
Sleep, 188
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 40
SendInput {Numpad6}
Sleep, 523
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad5}
Sleep, 188
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 40
SendInput {Numpad1}
Sleep, 523
SendInput {Numpad5}
Sleep, 188
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 188
SendInput {Numpad1}
Sleep, 188
SendInput {Numpad1}
Sleep, 563
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 563
SendInput {Numpad2}
Sleep, 188
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 188
SendInput {Numpad3}
Sleep, 375
SendInput {Numpad9}
SendInput {Numpad3}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 188
SendInput {Numpad2}
Sleep, 563
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 188
SendInput {Numpad2}
SendInput {Numpad6}
Sleep, 375
SendInput {Numpad1}
Sleep, 188
SendInput {Numpad1}
Sleep, 188
SendInput {Numpad6}
Sleep, 375
SendInput {Numpad6}
Sleep, 375
SendInput {Numpad1}
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 75
SendInput {Numpad6}
Sleep, 675
SendInput {Numpad1}
Sleep, 188
SendInput {Numpad3}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 563
SendInput {Numpad9}
SendInput {Numpad1}
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 750
SendInput {Numpad5}
Sleep, 75
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 675
SendInput {Numpad0}
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 75
SendInput {Numpad5}
Sleep, 675
SendInput {Numpad2}
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 75
SendInput {Numpad2}
Sleep, 488
SendInput {Numpad1}
Sleep, 188
SendInput {Numpad2}
Sleep, 375
SendInput {Numpad1}
Sleep, 188
SendInput {Numpad4}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 188
SendInput {Numpad4}
Sleep, 415
SendInput {Numpad0}
SendInput {Numpad2}
Sleep, 148
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 188
SendInput {Numpad4}
Sleep, 375
SendInput {Numpad9}
SendInput {Numpad7}
Sleep, 188
SendInput {Numpad5}
SendInput {Numpad1}
Sleep, 188
SendInput {Numpad5}
Sleep, 415
SendInput {Numpad0}
SendInput {Numpad2}
Sleep, 148
SendInput {Numpad6}
Sleep, 188
SendInput {Numpad5}
Sleep, 375
SendInput {Numpad9}
SendInput {Numpad7}
Sleep, 188
SendInput {Numpad3}
SendInput {Numpad1}
Sleep, 188
SendInput {Numpad6}
Sleep, 375
SendInput {Numpad6}
Sleep, 375
SendInput {Numpad9}
SendInput {Numpad6}
Sleep, 750
SendInput {Numpad0}
SendInput {Numpad3}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 750
SendInput {Numpad9}
SendInput {Numpad1}
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 375
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 188
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 188
SendInput {Numpad4}
Sleep, 415
SendInput {Numpad2}
Sleep, 148
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 188
SendInput {Numpad4}
Sleep, 375
SendInput {Numpad9}
SendInput {Numpad7}
Sleep, 188
SendInput {Numpad5}
SendInput {Numpad1}
Sleep, 188
SendInput {Numpad5}
Sleep, 415
SendInput {Numpad0}
SendInput {Numpad2}
Sleep, 148
SendInput {Numpad6}
Sleep, 188
SendInput {Numpad5}
Sleep, 375
SendInput {Numpad9}
SendInput {Numpad7}
Sleep, 188
SendInput {Numpad3}
SendInput {Numpad1}
Sleep, 188
SendInput {Numpad6}
Sleep, 375
SendInput {Numpad6}
Sleep, 375
SendInput {Numpad9}
SendInput {Numpad6}
Sleep, 750
SendInput {Numpad0}
SendInput {Numpad3}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 750
SendInput {Numpad9}
SendInput {Numpad1}
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 750
SendInput {Numpad0}
SendInput {Numpad4}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 375
SendInput {Numpad0}
SendInput {Numpad2}
Sleep, 188
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 188
SendInput {Numpad4}
Sleep, 375
SendInput {Numpad9}
SendInput {Numpad7}
Sleep, 188
SendInput {Numpad5}
SendInput {Numpad1}
Sleep, 188
SendInput {Numpad5}
Sleep, 188
SendInput {Numpad5}
Sleep, 415
SendInput {Numpad0}
SendInput {Numpad2}
Sleep, 148
SendInput {Numpad6}
Sleep, 188
SendInput {Numpad5}
Sleep, 563
SendInput {Numpad1}
Sleep, 188
SendInput {Numpad3}
SendInput {Numpad5}
Sleep, 563
SendInput {Numpad3}
Sleep, 188
SendInput {Numpad2}
Sleep, 40
SendInput {Numpad7}
Sleep, 375
SendInput {Numpad3}
Sleep, 148
SendInput {Numpad3}
SendInput {Numpad1}
Sleep, 188
SendInput {Numpad6}
Sleep, 188
SendInput {Numpad1}
Sleep, 188
SendInput {Numpad1}
Sleep, 188
SendInput {Numpad1}
Sleep, 40
SendInput {Numpad2}
Sleep, 148
SendInput {Numpad3}
Sleep, 375
SendInput {Numpad9}
SendInput {Numpad2}
SendInput {Numpad6}
Sleep, 188
SendInput {Numpad2}
Sleep, 188
SendInput {Numpad1}
Sleep, 188
SendInput {Numpad6}
Sleep, 375
SendInput {Numpad9}
SendInput {Numpad2}
Sleep, 750
SendInput {Numpad0}
SendInput {Numpad2}
Sleep, 563
SendInput {Numpad2}
Sleep, 188
SendInput {Numpad2}
Sleep, 750
SendInput {Numpad9}
SendInput {Numpad1}
Sleep, 188
SendInput {Numpad2}
Sleep, 375
SendInput {Numpad1}
Sleep, 188
SendInput {Numpad2}
Sleep, 375
SendInput {Numpad1}
Sleep, 188
SendInput {Numpad2}
Sleep, 1313
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad2}
Sleep, 188
SendInput {Numpad3}
Sleep, 40
SendInput {Numpad2}
Sleep, 335
SendInput {Numpad3}
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 563
SendInput {Numpad1}
Sleep, 188
SendInput {Numpad4}
Sleep, 750
SendInput {Numpad6}
Sleep, 188
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 75
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 488
SendInput {Numpad1}
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 75
SendInput {Numpad6}
Sleep, 675
SendInput {Numpad1}
Sleep, 750
SendInput {Numpad9}
SendInput {Numpad1}
SendInput {Numpad3}
Sleep, 375
SendInput {Numpad6}
Sleep, 188
SendInput {Numpad3}
SendInput {Numpad1}
Sleep, 188
SendInput {Numpad6}
Sleep, 188
SendInput {Numpad6}
Sleep, 188
SendInput {Numpad1}
Sleep, 188
SendInput {Numpad6}
Sleep, 188
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 75
SendInput {Numpad6}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 375
SendInput {Numpad3}
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 563
SendInput {Numpad1}
Sleep, 188
SendInput {Numpad4}
Sleep, 750
SendInput {Numpad6}
Sleep, 188
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 75
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 488
SendInput {Numpad1}
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 75
SendInput {Numpad6}
Sleep, 675
SendInput {Numpad1}
Sleep, 750
SendInput {Numpad9}
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 375
SendInput {Numpad0}
SendInput {Numpad3}
Sleep, 375
SendInput {Numpad1}
SendInput {Numpad4}
Sleep, 375
SendInput {Numpad9}
SendInput {Numpad5}
Sleep, 40
SendInput {Numpad6}
Sleep, 710
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 375
SendInput {Numpad9}
SendInput {Numpad4}
Sleep, 750
SendInput {Numpad4}
Sleep, 75
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 675
SendInput {Numpad6}
Sleep, 188
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 75
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 488
SendInput {Numpad1}
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 75
SendInput {Numpad6}
Sleep, 675
SendInput {Numpad1}
Sleep, 750
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 40
SendInput {Numpad3}
Sleep, 335
SendInput {Numpad3}
Sleep, 375
SendInput {Numpad1}
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 375
SendInput {Numpad6}
Sleep, 40
SendInput {Numpad3}
Sleep, 710
SendInput {Numpad3}
Sleep, 40
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 335
SendInput {Numpad4}
Sleep, 228
SendInput {Numpad2}
Sleep, 148
SendInput {Numpad1}
Sleep, 415
SendInput {Numpad9}
SendInput {Numpad4}
Sleep, 710
SendInput {Numpad6}
Sleep, 188
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 75
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 488
SendInput {Numpad1}
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 75
SendInput {Numpad6}
Sleep, 675
SendInput {Numpad0}
SendInput {Numpad1}
SendInput {Numpad3}
SendInput {Numpad5}
Sleep, 750
SendInput {Numpad1}
Sleep, 188
SendInput {Numpad1}
Sleep, 563
SendInput {Numpad1}
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 750
SendInput {Numpad6}
Sleep, 415
SendInput {Numpad0}
SendInput {Numpad3}
Sleep, 335
SendInput {Numpad9}
SendInput {Numpad2}
SendInput {Numpad6}
Sleep, 75
SendInput {Numpad6}
Sleep, 488
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 188
SendInput {Numpad1}
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 188
SendInput {Numpad1}
Sleep, 188
SendInput {Numpad2}
Sleep, 188
SendInput {Numpad1}
Sleep, 188
SendInput {Numpad1}
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 415
SendInput {Numpad2}
Sleep, 148
SendInput {Numpad1}
Sleep, 188
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 188
SendInput {Numpad1}
Sleep, 188
SendInput {Numpad2}
Sleep, 188
SendInput {Numpad1}
Sleep, 188
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 75
SendInput {Numpad5}
Sleep, 340
SendInput {Numpad3}
Sleep, 148
SendInput {Numpad9}
SendInput {Numpad3}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 188
SendInput {Numpad2}
Sleep, 563
SendInput {Numpad1}
Sleep, 188
SendInput {Numpad2}
Sleep, 375
SendInput {Numpad1}
Sleep, 375
SendInput {Numpad9}
SendInput {Numpad6}
Sleep, 415
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad3}
Sleep, 335
SendInput {Numpad9}
SendInput {Numpad2}
SendInput {Numpad6}
Sleep, 75
SendInput {Numpad6}
Sleep, 488
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 188
SendInput {Numpad1}
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 188
SendInput {Numpad1}
Sleep, 188
SendInput {Numpad2}
Sleep, 188
SendInput {Numpad1}
Sleep, 188
SendInput {Numpad1}
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 415
SendInput {Numpad2}
Sleep, 148
SendInput {Numpad1}
Sleep, 188
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 188
SendInput {Numpad1}
Sleep, 188
SendInput {Numpad2}
Sleep, 188
SendInput {Numpad1}
Sleep, 188
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 75
SendInput {Numpad5}
Sleep, 340
SendInput {Numpad3}
Sleep, 148
SendInput {Numpad9}
SendInput {Numpad3}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 188
SendInput {Numpad2}
Sleep, 563
SendInput {Numpad1}
Sleep, 188
SendInput {Numpad2}
Sleep, 375
SendInput {Numpad1}
Sleep, 375
SendInput {Numpad9}
SendInput {Numpad6}
Sleep, 75
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 113
SendInput {Numpad5}
Sleep, 188
SendInput {Numpad3}
Sleep, 188
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 40
SendInput {Numpad6}
Sleep, 523
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad5}
Sleep, 188
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 40
SendInput {Numpad1}
Sleep, 523
SendInput {Numpad5}
Sleep, 188
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 188
SendInput {Numpad1}
Sleep, 188
SendInput {Numpad1}
Sleep, 563
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 563
SendInput {Numpad2}
Sleep, 188
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 188
SendInput {Numpad3}
Sleep, 375
SendInput {Numpad9}
SendInput {Numpad3}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 188
SendInput {Numpad2}
Sleep, 563
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 188
SendInput {Numpad2}
SendInput {Numpad6}
Sleep, 375
SendInput {Numpad1}
Sleep, 188
SendInput {Numpad1}
Sleep, 188
SendInput {Numpad6}
Sleep, 375
SendInput {Numpad6}
Sleep, 375
SendInput {Numpad1}
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 75
SendInput {Numpad6}
Sleep, 675
SendInput {Numpad1}
Sleep, 188
SendInput {Numpad3}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 563
SendInput {Numpad9}
SendInput {Numpad1}
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 750
SendInput {Numpad5}
Sleep, 75
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 675
SendInput {Numpad0}
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 75
SendInput {Numpad5}
Sleep, 675
SendInput {Numpad2}
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 75
SendInput {Numpad2}
Sleep, 488
SendInput {Numpad1}
Sleep, 188
SendInput {Numpad2}
Sleep, 375
SendInput {Numpad1}
Sleep, 188
SendInput {Numpad4}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 188
SendInput {Numpad4}
Sleep, 415
SendInput {Numpad0}
SendInput {Numpad2}
Sleep, 148
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 188
SendInput {Numpad4}
Sleep, 375
SendInput {Numpad9}
SendInput {Numpad7}
Sleep, 188
SendInput {Numpad5}
SendInput {Numpad1}
Sleep, 188
SendInput {Numpad5}
Sleep, 415
SendInput {Numpad0}
SendInput {Numpad2}
Sleep, 148
SendInput {Numpad6}
Sleep, 188
SendInput {Numpad5}
Sleep, 375
SendInput {Numpad9}
SendInput {Numpad7}
Sleep, 188
SendInput {Numpad3}
SendInput {Numpad1}
Sleep, 188
SendInput {Numpad6}
Sleep, 375
SendInput {Numpad6}
Sleep, 375
SendInput {Numpad9}
SendInput {Numpad6}
Sleep, 750
SendInput {Numpad0}
SendInput {Numpad3}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 750
SendInput {Numpad9}
SendInput {Numpad1}
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 375
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 188
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 188
SendInput {Numpad4}
Sleep, 415
SendInput {Numpad2}
Sleep, 148
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 188
SendInput {Numpad4}
Sleep, 375
SendInput {Numpad9}
SendInput {Numpad7}
Sleep, 188
SendInput {Numpad5}
SendInput {Numpad1}
Sleep, 188
SendInput {Numpad5}
Sleep, 415
SendInput {Numpad0}
SendInput {Numpad2}
Sleep, 148
SendInput {Numpad6}
Sleep, 188
SendInput {Numpad5}
Sleep, 375
SendInput {Numpad9}
SendInput {Numpad7}
Sleep, 188
SendInput {Numpad3}
SendInput {Numpad1}
Sleep, 188
SendInput {Numpad6}
Sleep, 375
SendInput {Numpad6}
Sleep, 375
SendInput {Numpad9}
SendInput {Numpad6}
Sleep, 750
SendInput {Numpad0}
SendInput {Numpad3}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 750
SendInput {Numpad9}
SendInput {Numpad1}
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 750
SendInput {Numpad0}
SendInput {Numpad4}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 375
SendInput {Numpad0}
SendInput {Numpad2}
Sleep, 188
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 188
SendInput {Numpad4}
Sleep, 375
SendInput {Numpad9}
SendInput {Numpad7}
Sleep, 188
SendInput {Numpad5}
SendInput {Numpad1}
Sleep, 188
SendInput {Numpad5}
Sleep, 188
SendInput {Numpad5}
Sleep, 415
SendInput {Numpad0}
SendInput {Numpad2}
Sleep, 148
SendInput {Numpad6}
Sleep, 188
SendInput {Numpad5}
Sleep, 563
SendInput {Numpad1}
Sleep, 188
SendInput {Numpad3}
SendInput {Numpad5}
Sleep, 563
SendInput {Numpad3}
Sleep, 188
SendInput {Numpad2}
Sleep, 40
SendInput {Numpad7}
Sleep, 375
SendInput {Numpad3}
Sleep, 148
SendInput {Numpad3}
SendInput {Numpad1}
Sleep, 188
SendInput {Numpad6}
Sleep, 188
SendInput {Numpad1}
Sleep, 188
SendInput {Numpad1}
Sleep, 188
SendInput {Numpad1}
Sleep, 40
SendInput {Numpad2}
Sleep, 148
SendInput {Numpad3}
Sleep, 375
SendInput {Numpad9}
SendInput {Numpad2}
SendInput {Numpad6}
Sleep, 188
SendInput {Numpad2}
Sleep, 188
SendInput {Numpad1}
Sleep, 188
SendInput {Numpad6}
Sleep, 375
SendInput {Numpad9}
SendInput {Numpad2}
Sleep, 750
SendInput {Numpad0}
SendInput {Numpad2}
Sleep, 563
SendInput {Numpad2}
Sleep, 188
SendInput {Numpad2}
Sleep, 750
SendInput {Numpad9}
SendInput {Numpad1}
Sleep, 188
SendInput {Numpad2}
Sleep, 375
SendInput {Numpad1}
Sleep, 188
SendInput {Numpad2}
Sleep, 375
SendInput {Numpad1}
Sleep, 188
SendInput {Numpad2}
Sleep, 1313
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad2}
Sleep, 188
SendInput {Numpad3}
Sleep, 40
SendInput {Numpad2}
Sleep, 335
SendInput {Numpad3}
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 563
SendInput {Numpad1}
Sleep, 188
SendInput {Numpad4}
Sleep, 750
SendInput {Numpad6}
Sleep, 188
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 75
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 488
SendInput {Numpad1}
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 75
SendInput {Numpad6}
Sleep, 675
SendInput {Numpad1}
Sleep, 750
SendInput {Numpad9}
SendInput {Numpad1}
SendInput {Numpad3}
Sleep, 375
SendInput {Numpad6}
Sleep, 188
SendInput {Numpad3}
SendInput {Numpad1}
Sleep, 188
SendInput {Numpad6}
Sleep, 188
SendInput {Numpad6}
Sleep, 188
SendInput {Numpad1}
Sleep, 188
SendInput {Numpad6}
Sleep, 188
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 75
SendInput {Numpad6}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 375
SendInput {Numpad3}
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 563
SendInput {Numpad1}
Sleep, 188
SendInput {Numpad4}
Sleep, 750
SendInput {Numpad6}
Sleep, 188
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 75
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 488
SendInput {Numpad1}
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 75
SendInput {Numpad6}
Sleep, 675
SendInput {Numpad1}
Sleep, 750
SendInput {Numpad9}
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 375
SendInput {Numpad0}
SendInput {Numpad3}
Sleep, 375
SendInput {Numpad1}
SendInput {Numpad4}
Sleep, 375
SendInput {Numpad9}
SendInput {Numpad5}
Sleep, 40
SendInput {Numpad6}
Sleep, 710
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 375
SendInput {Numpad9}
SendInput {Numpad4}
Sleep, 750
SendInput {Numpad4}
Sleep, 75
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 675
SendInput {Numpad6}
Sleep, 188
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 75
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 488
SendInput {Numpad1}
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 75
SendInput {Numpad6}
Sleep, 675
SendInput {Numpad1}
Sleep, 750
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 40
SendInput {Numpad3}
Sleep, 335
SendInput {Numpad3}
Sleep, 375
SendInput {Numpad1}
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 375
SendInput {Numpad6}
Sleep, 40
SendInput {Numpad3}
Sleep, 710
SendInput {Numpad3}
Sleep, 40
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 335
SendInput {Numpad4}
Sleep, 228
SendInput {Numpad2}
Sleep, 148
SendInput {Numpad1}
Sleep, 415
SendInput {Numpad9}
SendInput {Numpad4}
Sleep, 710
SendInput {Numpad6}
Sleep, 188
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 75
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 488
SendInput {Numpad1}
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 75
SendInput {Numpad6}
Sleep, 675
SendInput {Numpad0}
SendInput {Numpad1}
SendInput {Numpad3}
SendInput {Numpad5}
Sleep, 750
SendInput {Numpad9}
SendInput {Numpad1}
SendInput {Numpad3}
SendInput {Numpad5}
Sleep, 750
SendInput {Numpad6}
Sleep, 188
SendInput {Numpad3}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 188
SendInput {Numpad6}
Sleep, 375
SendInput {Numpad0}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 188
SendInput {Numpad2}
Sleep, 188
SendInput {Numpad3}
Sleep, 375
SendInput {Numpad9}
SendInput {Numpad3}
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 563
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 188
SendInput {Numpad4}
Sleep, 750
SendInput {Numpad6}
Sleep, 188
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 75
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 488
SendInput {Numpad1}
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 75
SendInput {Numpad6}
Sleep, 675
SendInput {Numpad1}
Sleep, 750
SendInput {Numpad9}
SendInput {Numpad1}
SendInput {Numpad3}
Sleep, 375
SendInput {Numpad6}
Sleep, 188
SendInput {Numpad3}
SendInput {Numpad1}
Sleep, 188
SendInput {Numpad6}
Sleep, 188
SendInput {Numpad6}
Sleep, 188
SendInput {Numpad1}
Sleep, 188
SendInput {Numpad6}
Sleep, 188
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 75
SendInput {Numpad6}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 375
SendInput {Numpad3}
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 563
SendInput {Numpad1}
Sleep, 188
SendInput {Numpad4}
Sleep, 750
SendInput {Numpad6}
Sleep, 188
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 75
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 488
SendInput {Numpad1}
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 75
SendInput {Numpad6}
Sleep, 675
SendInput {Numpad1}
Sleep, 750
SendInput {Numpad9}
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 375
SendInput {Numpad0}
SendInput {Numpad3}
Sleep, 375
SendInput {Numpad1}
SendInput {Numpad4}
Sleep, 375
SendInput {Numpad9}
SendInput {Numpad5}
Sleep, 40
SendInput {Numpad6}
Sleep, 710
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 375
SendInput {Numpad9}
SendInput {Numpad4}
Sleep, 750
SendInput {Numpad4}
Sleep, 75
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 675
SendInput {Numpad6}
Sleep, 188
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 75
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 488
SendInput {Numpad1}
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 75
SendInput {Numpad6}
Sleep, 675
SendInput {Numpad1}
Sleep, 750
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 40
SendInput {Numpad3}
Sleep, 335
SendInput {Numpad3}
Sleep, 375
SendInput {Numpad1}
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 375
SendInput {Numpad6}
Sleep, 40
SendInput {Numpad3}
Sleep, 710
SendInput {Numpad3}
Sleep, 40
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 335
SendInput {Numpad4}
Sleep, 228
SendInput {Numpad2}
Sleep, 148
SendInput {Numpad1}
Sleep, 415
SendInput {Numpad9}
SendInput {Numpad4}
Sleep, 710
SendInput {Numpad6}
Sleep, 188
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 75
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 488
SendInput {Numpad1}
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 75
SendInput {Numpad6}
Sleep, 675
SendInput {Numpad0}
SendInput {Numpad1}
SendInput {Numpad3}
SendInput {Numpad5}
Sleep, 750
SendInput {Numpad9}
SendInput {Numpad1}
SendInput {Numpad3}
SendInput {Numpad5}
Sleep, 750
SendInput {Numpad6}
Sleep, 188
SendInput {Numpad3}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 188
SendInput {Numpad6}
Sleep, 375
SendInput {Numpad0}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 188
SendInput {Numpad2}
Sleep, 188
SendInput {Numpad3}
Sleep, 375
SendInput {Numpad9}
SendInput {Numpad3}
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 563
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 188
SendInput {Numpad4}
Sleep, 750
SendInput {Numpad6}
Sleep, 188
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 75
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 488
SendInput {Numpad1}
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 75
SendInput {Numpad6}
Sleep, 675
SendInput {Numpad1}
Sleep, 750
SendInput {Numpad9}
SendInput {Numpad1}
SendInput {Numpad3}
Sleep, 375
SendInput {Numpad6}
Sleep, 188
SendInput {Numpad3}
SendInput {Numpad1}
Sleep, 188
SendInput {Numpad6}
Sleep, 188
SendInput {Numpad6}
Sleep, 188
SendInput {Numpad1}
Sleep, 188
SendInput {Numpad6}
Sleep, 188
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 75
SendInput {Numpad6}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 375
SendInput {Numpad3}
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 563
SendInput {Numpad1}
Sleep, 188
SendInput {Numpad4}
Sleep, 750
SendInput {Numpad6}
Sleep, 188
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 75
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 488
SendInput {Numpad1}
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 75
SendInput {Numpad6}
Sleep, 675
SendInput {Numpad1}
Sleep, 750
SendInput {Numpad9}
SendInput {Numpad1}
SendInput {Numpad3}
Sleep, 375
SendInput {Numpad6}
Sleep, 188
SendInput {Numpad3}
SendInput {Numpad1}
Sleep, 188
SendInput {Numpad6}
Sleep, 188
SendInput {Numpad6}
Sleep, 188
SendInput {Numpad1}
Sleep, 188
SendInput {Numpad6}
Sleep, 188
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 75
SendInput {Numpad6}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 375
SendInput {Numpad3}
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 563
SendInput {Numpad1}
Sleep, 188
SendInput {Numpad4}
Sleep, 750
SendInput {Numpad6}
Sleep, 188
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 75
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 488
SendInput {Numpad1}
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 75
SendInput {Numpad6}
Sleep, 675
SendInput {Numpad1}
Sleep, 750
SendInput {Numpad9}
SendInput {Numpad1}
SendInput {Numpad3}
Sleep, 375
SendInput {Numpad6}
Sleep, 188
SendInput {Numpad3}
SendInput {Numpad1}
Sleep, 188
SendInput {Numpad6}
Sleep, 188
SendInput {Numpad6}
Sleep, 188
SendInput {Numpad1}
Sleep, 188
SendInput {Numpad6}
Sleep, 188
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 75
SendInput {Numpad6}
Sleep, 300
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 375
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad3}
SendInput {Numpad4}
Sleep, 375
SendInput {Numpad0}
SendInput {Numpad4}
Sleep, 375
SendInput {Numpad4}
SendInput {Numpad1}
Sleep, 375
SendInput {Numpad1}
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 375
SendInput {Numpad9}
SendInput {Numpad6}
Sleep, 188
SendInput {Numpad6}
Sleep, 563
SendInput {Numpad6}
Sleep, 375
SendInput {Numpad0}
SendInput {Numpad4}
Sleep, 375
SendInput {Numpad9}
SendInput {Numpad1}
SendInput {Numpad3}
Sleep, 375
SendInput {Numpad0}
SendInput {Numpad4}
Sleep, 375
SendInput {Numpad1}
Sleep, 375
SendInput {Numpad9}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 75
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 1800
SendInput {Numpad3}
SendInput {Numpad4}
Sleep, 375
SendInput {Numpad0}
SendInput {Numpad4}
Sleep, 375
SendInput {Numpad4}
SendInput {Numpad1}
Sleep, 375
SendInput {Numpad1}
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 375
SendInput {Numpad9}
SendInput {Numpad6}
Sleep, 188
SendInput {Numpad6}
Sleep, 563
SendInput {Numpad6}
Sleep, 375
SendInput {Numpad0}
SendInput {Numpad4}
Sleep, 375
SendInput {Numpad9}
SendInput {Numpad1}
SendInput {Numpad3}
Sleep, 375
SendInput {Numpad0}
SendInput {Numpad4}
Sleep, 375
SendInput {Numpad1}
Sleep, 375
SendInput {Numpad9}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 75
SendInput {Numpad3}
SendInput {Numpad6}
