; title: Zombie
; author: The Cranberries
; instrument: Piano
; Converted by Serenade Desktop

SendInput {Numpad9}
SendInput {Numpad6}
SendInput {Numpad1}
SendInput {Numpad3}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad3}
Sleep, 366
SendInput {Numpad6}
Sleep, 366
SendInput {Numpad3}
Sleep, 366
SendInput {Numpad7}
Sleep, 366
SendInput {Numpad3}
Sleep, 366
SendInput {Numpad6}
Sleep, 366
SendInput {Numpad3}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad4}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 366
SendInput {Numpad4}
Sleep, 366
SendInput {Numpad1}
Sleep, 366
SendInput {Numpad5}
Sleep, 366
SendInput {Numpad1}
Sleep, 366
SendInput {Numpad4}
Sleep, 366
SendInput {Numpad1}
Sleep, 366
SendInput {Numpad1}
SendInput {Numpad5}
SendInput {Numpad3}
Sleep, 366
SendInput {Numpad5}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad1}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad5}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad2}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad5}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad1}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad5}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad5}
SendInput {Numpad7}
SendInput {Numpad2}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad5}
Sleep, 366
SendInput {Numpad7}
Sleep, 366
SendInput {Numpad5}
Sleep, 366
SendInput {Numpad7}
Sleep, 64
SendInput {Numpad1}
Sleep, 302
SendInput {Numpad7}
Sleep, 366
SendInput {Numpad6}
Sleep, 366
SendInput {Numpad5}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad6}
SendInput {Numpad1}
SendInput {Numpad3}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad3}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad1}
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 366
SendInput {Numpad5}
SendInput {Numpad3}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad7}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad3}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad6}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad6}
SendInput {Numpad1}
SendInput {Numpad5}
SendInput {Numpad3}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad4}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad4}
SendInput {Numpad1}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad4}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad3}
SendInput {Numpad1}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad5}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad2}
SendInput {Numpad1}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad4}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad5}
SendInput {Numpad1}
SendInput {Numpad4}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad1}
SendInput {Numpad5}
SendInput {Numpad3}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad3}
SendInput {Numpad5}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad2}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad5}
SendInput {Numpad7}
SendInput {Numpad2}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad5}
Sleep, 366
SendInput {Numpad7}
Sleep, 366
SendInput {Numpad5}
Sleep, 366
SendInput {Numpad7}
Sleep, 64
SendInput {Numpad1}
Sleep, 302
SendInput {Numpad7}
Sleep, 366
SendInput {Numpad6}
Sleep, 366
SendInput {Numpad5}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad6}
SendInput {Numpad1}
SendInput {Numpad3}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad6}
SendInput {Numpad3}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad1}
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 366
SendInput {Numpad5}
SendInput {Numpad3}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad7}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad3}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad6}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad6}
SendInput {Numpad1}
SendInput {Numpad5}
SendInput {Numpad3}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad4}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad4}
SendInput {Numpad1}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad4}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad3}
SendInput {Numpad1}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad5}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad2}
SendInput {Numpad1}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad4}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad5}
SendInput {Numpad1}
SendInput {Numpad4}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad1}
SendInput {Numpad5}
SendInput {Numpad3}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad3}
SendInput {Numpad5}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad2}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad5}
SendInput {Numpad7}
SendInput {Numpad2}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad5}
Sleep, 366
SendInput {Numpad7}
Sleep, 366
SendInput {Numpad5}
Sleep, 366
SendInput {Numpad7}
Sleep, 64
SendInput {Numpad9}
SendInput {Numpad1}
Sleep, 302
SendInput {Numpad7}
Sleep, 366
SendInput {Numpad7}
Sleep, 366
SendInput {Numpad6}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad6}
SendInput {Numpad1}
SendInput {Numpad3}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad6}
SendInput {Numpad3}
Sleep, 366
SendInput {Numpad7}
SendInput {Numpad1}
Sleep, 366
SendInput {Numpad6}
SendInput {Numpad3}
Sleep, 366
Sleep, 366
SendInput {Numpad6}
SendInput {Numpad3}
Sleep, 366
SendInput {Numpad7}
SendInput {Numpad1}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad1}
SendInput {Numpad3}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad4}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 366
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 366
SendInput {Numpad7}
SendInput {Numpad6}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad1}
Sleep, 366
Sleep, 366
SendInput {Numpad1}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad7}
SendInput {Numpad6}
Sleep, 366
SendInput {Numpad5}
SendInput {Numpad1}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad1}
SendInput {Numpad5}
SendInput {Numpad3}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad7}
SendInput {Numpad3}
Sleep, 366
SendInput {Numpad5}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 366
SendInput {Numpad1}
SendInput {Numpad3}
Sleep, 366
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad7}
SendInput {Numpad5}
SendInput {Numpad2}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad5}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad2}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad5}
Sleep, 366
SendInput {Numpad7}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad1}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad7}
Sleep, 366
SendInput {Numpad6}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad6}
SendInput {Numpad1}
SendInput {Numpad3}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad6}
SendInput {Numpad3}
Sleep, 366
SendInput {Numpad7}
SendInput {Numpad1}
Sleep, 366
SendInput {Numpad6}
SendInput {Numpad3}
Sleep, 366
Sleep, 366
SendInput {Numpad6}
SendInput {Numpad3}
Sleep, 366
SendInput {Numpad7}
SendInput {Numpad1}
Sleep, 366
SendInput {Numpad6}
SendInput {Numpad3}
Sleep, 366
SendInput {Numpad4}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 366
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 366
SendInput {Numpad7}
SendInput {Numpad6}
Sleep, 366
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 366
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad1}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad7}
SendInput {Numpad6}
Sleep, 366
SendInput {Numpad5}
SendInput {Numpad1}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad1}
SendInput {Numpad5}
SendInput {Numpad3}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad7}
SendInput {Numpad3}
Sleep, 366
SendInput {Numpad5}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 366
SendInput {Numpad1}
SendInput {Numpad3}
Sleep, 366
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad7}
SendInput {Numpad5}
SendInput {Numpad2}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad5}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad7}
SendInput {Numpad2}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad5}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad7}
SendInput {Numpad1}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad7}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad7}
SendInput {Numpad6}
Sleep, 366
SendInput {Numpad7}
SendInput {Numpad5}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad1}
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad3}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad1}
Sleep, 366
SendInput {Numpad6}
SendInput {Numpad3}
Sleep, 366
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad3}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad7}
SendInput {Numpad1}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad2}
SendInput {Numpad3}
Sleep, 366
SendInput {Numpad1}
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 183
SendInput {Numpad2}
Sleep, 183
SendInput {Numpad1}
SendInput {Numpad6}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 366
Sleep, 366
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 366
SendInput {Numpad7}
SendInput {Numpad6}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad5}
SendInput {Numpad1}
SendInput {Numpad3}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad1}
SendInput {Numpad5}
SendInput {Numpad3}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad6}
SendInput {Numpad5}
Sleep, 366
SendInput {Numpad7}
SendInput {Numpad3}
Sleep, 366
SendInput {Numpad5}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad6}
SendInput {Numpad5}
Sleep, 366
SendInput {Numpad7}
SendInput {Numpad3}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad7}
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad5}
SendInput {Numpad7}
SendInput {Numpad2}
Sleep, 366
SendInput {Numpad7}
SendInput {Numpad5}
Sleep, 366
SendInput {Numpad2}
Sleep, 366
SendInput {Numpad7}
SendInput {Numpad5}
Sleep, 366
SendInput {Numpad1}
Sleep, 366
SendInput {Numpad7}
Sleep, 366
SendInput {Numpad7}
SendInput {Numpad6}
Sleep, 366
SendInput {Numpad7}
SendInput {Numpad5}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad1}
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad3}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad1}
Sleep, 366
SendInput {Numpad6}
SendInput {Numpad3}
Sleep, 366
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad3}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad7}
SendInput {Numpad1}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad2}
SendInput {Numpad3}
Sleep, 366
SendInput {Numpad1}
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 183
SendInput {Numpad2}
Sleep, 183
SendInput {Numpad1}
SendInput {Numpad6}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 366
Sleep, 366
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 366
SendInput {Numpad7}
SendInput {Numpad6}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad5}
SendInput {Numpad1}
SendInput {Numpad3}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad1}
SendInput {Numpad5}
SendInput {Numpad3}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad6}
SendInput {Numpad5}
Sleep, 366
SendInput {Numpad7}
SendInput {Numpad3}
Sleep, 366
SendInput {Numpad5}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad6}
SendInput {Numpad5}
Sleep, 366
SendInput {Numpad7}
SendInput {Numpad3}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad7}
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad5}
SendInput {Numpad7}
SendInput {Numpad2}
Sleep, 366
SendInput {Numpad7}
SendInput {Numpad5}
Sleep, 366
SendInput {Numpad2}
Sleep, 366
SendInput {Numpad7}
SendInput {Numpad5}
Sleep, 366
SendInput {Numpad1}
Sleep, 366
SendInput {Numpad7}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad6}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad1}
SendInput {Numpad3}
SendInput {Numpad6}
SendInput {Numpad5}
Sleep, 366
SendInput {Numpad6}
SendInput {Numpad1}
SendInput {Numpad3}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad3}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad1}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad7}
SendInput {Numpad3}
Sleep, 366
Sleep, 366
SendInput {Numpad3}
Sleep, 366
SendInput {Numpad3}
SendInput {Numpad1}
Sleep, 366
SendInput {Numpad6}
SendInput {Numpad1}
SendInput {Numpad4}
SendInput {Numpad3}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad4}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 366
SendInput {Numpad6}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad7}
SendInput {Numpad1}
Sleep, 366
Sleep, 366
SendInput {Numpad4}
SendInput {Numpad1}
Sleep, 366
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 366
SendInput {Numpad5}
SendInput {Numpad1}
SendInput {Numpad3}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad1}
SendInput {Numpad5}
SendInput {Numpad3}
Sleep, 366
SendInput {Numpad5}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad3}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad7}
SendInput {Numpad5}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad3}
SendInput {Numpad5}
Sleep, 366
SendInput {Numpad3}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad5}
SendInput {Numpad7}
SendInput {Numpad2}
Sleep, 366
SendInput {Numpad5}
SendInput {Numpad7}
SendInput {Numpad2}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad5}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad2}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad7}
SendInput {Numpad5}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad2}
SendInput {Numpad7}
Sleep, 366
SendInput {Numpad2}
SendInput {Numpad6}
Sleep, 366
SendInput {Numpad3}
SendInput {Numpad5}
Sleep, 366
SendInput {Numpad6}
SendInput {Numpad1}
SendInput {Numpad3}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad3}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad1}
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 366
SendInput {Numpad5}
SendInput {Numpad3}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad7}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad3}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad6}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad6}
SendInput {Numpad1}
SendInput {Numpad5}
SendInput {Numpad3}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad4}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad4}
SendInput {Numpad1}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad4}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad3}
SendInput {Numpad1}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad5}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad2}
SendInput {Numpad1}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad4}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad5}
SendInput {Numpad1}
SendInput {Numpad4}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad1}
SendInput {Numpad5}
SendInput {Numpad3}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad3}
SendInput {Numpad5}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad2}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad5}
SendInput {Numpad7}
SendInput {Numpad2}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad5}
Sleep, 366
SendInput {Numpad7}
Sleep, 366
SendInput {Numpad5}
Sleep, 366
SendInput {Numpad7}
Sleep, 64
SendInput {Numpad1}
Sleep, 302
SendInput {Numpad7}
Sleep, 366
SendInput {Numpad6}
Sleep, 366
SendInput {Numpad5}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad6}
SendInput {Numpad1}
SendInput {Numpad3}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad6}
SendInput {Numpad3}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad1}
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 366
SendInput {Numpad5}
SendInput {Numpad3}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad7}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad3}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad6}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad6}
SendInput {Numpad1}
SendInput {Numpad5}
SendInput {Numpad3}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad4}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad4}
SendInput {Numpad1}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad4}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad3}
SendInput {Numpad1}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad5}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad2}
SendInput {Numpad1}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad4}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad5}
SendInput {Numpad1}
SendInput {Numpad4}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad1}
SendInput {Numpad5}
SendInput {Numpad3}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad3}
SendInput {Numpad5}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad2}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad5}
SendInput {Numpad7}
SendInput {Numpad2}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad5}
Sleep, 366
SendInput {Numpad7}
Sleep, 366
SendInput {Numpad5}
Sleep, 366
SendInput {Numpad7}
Sleep, 64
SendInput {Numpad9}
SendInput {Numpad1}
Sleep, 302
SendInput {Numpad7}
Sleep, 366
SendInput {Numpad7}
Sleep, 366
SendInput {Numpad6}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad6}
SendInput {Numpad1}
SendInput {Numpad3}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad6}
SendInput {Numpad3}
Sleep, 366
SendInput {Numpad7}
SendInput {Numpad1}
Sleep, 366
SendInput {Numpad6}
SendInput {Numpad3}
Sleep, 366
Sleep, 366
SendInput {Numpad6}
SendInput {Numpad3}
Sleep, 366
SendInput {Numpad7}
SendInput {Numpad1}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad1}
SendInput {Numpad3}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad4}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 366
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 366
SendInput {Numpad7}
SendInput {Numpad6}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad1}
Sleep, 366
Sleep, 366
SendInput {Numpad1}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad7}
SendInput {Numpad6}
Sleep, 366
SendInput {Numpad5}
SendInput {Numpad1}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad1}
SendInput {Numpad5}
SendInput {Numpad3}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad7}
SendInput {Numpad3}
Sleep, 366
SendInput {Numpad5}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 366
SendInput {Numpad1}
SendInput {Numpad3}
Sleep, 366
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad7}
SendInput {Numpad5}
SendInput {Numpad2}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad5}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad2}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad5}
Sleep, 366
SendInput {Numpad7}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad1}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad7}
Sleep, 366
SendInput {Numpad6}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad6}
SendInput {Numpad1}
SendInput {Numpad3}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad6}
SendInput {Numpad3}
Sleep, 366
SendInput {Numpad7}
SendInput {Numpad1}
Sleep, 366
SendInput {Numpad6}
SendInput {Numpad3}
Sleep, 366
Sleep, 366
SendInput {Numpad6}
SendInput {Numpad3}
Sleep, 366
SendInput {Numpad7}
SendInput {Numpad1}
Sleep, 366
SendInput {Numpad6}
SendInput {Numpad3}
Sleep, 366
SendInput {Numpad4}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 366
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 366
SendInput {Numpad7}
SendInput {Numpad6}
Sleep, 366
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 366
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad1}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad7}
SendInput {Numpad6}
Sleep, 366
SendInput {Numpad5}
SendInput {Numpad1}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad1}
SendInput {Numpad5}
SendInput {Numpad3}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad7}
SendInput {Numpad3}
Sleep, 366
SendInput {Numpad5}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 366
SendInput {Numpad1}
SendInput {Numpad3}
Sleep, 366
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad7}
SendInput {Numpad5}
SendInput {Numpad2}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad5}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad7}
SendInput {Numpad2}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad5}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad7}
SendInput {Numpad1}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad7}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad7}
SendInput {Numpad6}
Sleep, 366
SendInput {Numpad7}
SendInput {Numpad5}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad1}
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad3}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad1}
Sleep, 366
SendInput {Numpad6}
SendInput {Numpad3}
Sleep, 366
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad3}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad7}
SendInput {Numpad1}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad2}
SendInput {Numpad3}
Sleep, 366
SendInput {Numpad1}
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 183
SendInput {Numpad2}
Sleep, 183
SendInput {Numpad1}
SendInput {Numpad6}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 366
Sleep, 366
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 366
SendInput {Numpad7}
SendInput {Numpad6}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad5}
SendInput {Numpad1}
SendInput {Numpad3}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad1}
SendInput {Numpad5}
SendInput {Numpad3}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad6}
SendInput {Numpad5}
Sleep, 366
SendInput {Numpad7}
SendInput {Numpad3}
Sleep, 366
SendInput {Numpad5}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad6}
SendInput {Numpad5}
Sleep, 366
SendInput {Numpad7}
SendInput {Numpad3}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad7}
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad5}
SendInput {Numpad7}
SendInput {Numpad2}
Sleep, 366
SendInput {Numpad7}
SendInput {Numpad5}
Sleep, 366
SendInput {Numpad2}
Sleep, 366
SendInput {Numpad7}
SendInput {Numpad5}
Sleep, 366
SendInput {Numpad1}
Sleep, 366
SendInput {Numpad7}
Sleep, 366
SendInput {Numpad7}
SendInput {Numpad6}
Sleep, 366
SendInput {Numpad7}
SendInput {Numpad5}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad1}
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad3}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad1}
Sleep, 366
SendInput {Numpad6}
SendInput {Numpad3}
Sleep, 366
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad3}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad7}
SendInput {Numpad1}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad2}
SendInput {Numpad3}
Sleep, 366
SendInput {Numpad1}
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 183
SendInput {Numpad2}
Sleep, 183
SendInput {Numpad1}
SendInput {Numpad6}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 366
Sleep, 366
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 366
SendInput {Numpad7}
SendInput {Numpad6}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad5}
SendInput {Numpad1}
SendInput {Numpad3}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad1}
SendInput {Numpad5}
SendInput {Numpad3}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad6}
SendInput {Numpad5}
Sleep, 366
SendInput {Numpad7}
SendInput {Numpad3}
Sleep, 366
SendInput {Numpad5}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad6}
SendInput {Numpad5}
Sleep, 366
SendInput {Numpad7}
SendInput {Numpad3}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad7}
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad5}
SendInput {Numpad7}
SendInput {Numpad2}
Sleep, 366
SendInput {Numpad7}
SendInput {Numpad5}
Sleep, 366
SendInput {Numpad2}
Sleep, 366
SendInput {Numpad7}
SendInput {Numpad5}
Sleep, 366
SendInput {Numpad1}
Sleep, 366
SendInput {Numpad7}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad6}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad1}
SendInput {Numpad3}
SendInput {Numpad6}
SendInput {Numpad5}
Sleep, 366
SendInput {Numpad6}
SendInput {Numpad1}
SendInput {Numpad3}
Sleep, 366
SendInput {Numpad6}
SendInput {Numpad3}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad6}
SendInput {Numpad3}
Sleep, 366
Sleep, 366
SendInput {Numpad6}
SendInput {Numpad3}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad1}
SendInput {Numpad4}
SendInput {Numpad6}
SendInput {Numpad3}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad4}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad6}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 366
Sleep, 366
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 366
SendInput {Numpad7}
SendInput {Numpad6}
Sleep, 366
SendInput {Numpad1}
SendInput {Numpad3}
SendInput {Numpad5}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad1}
SendInput {Numpad5}
SendInput {Numpad3}
Sleep, 366
SendInput {Numpad5}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad3}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad5}
Sleep, 366
SendInput {Numpad1}
Sleep, 366
SendInput {Numpad5}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad3}
Sleep, 183
SendInput {Numpad2}
Sleep, 183
SendInput {Numpad3}
SendInput {Numpad5}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad5}
SendInput {Numpad7}
SendInput {Numpad2}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad5}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad2}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad5}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad1}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad7}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad5}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad6}
SendInput {Numpad1}
SendInput {Numpad3}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad3}
Sleep, 366
SendInput {Numpad6}
Sleep, 366
SendInput {Numpad3}
Sleep, 366
SendInput {Numpad7}
Sleep, 366
SendInput {Numpad3}
Sleep, 366
SendInput {Numpad6}
Sleep, 366
SendInput {Numpad3}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad4}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 366
SendInput {Numpad4}
Sleep, 366
SendInput {Numpad1}
Sleep, 366
SendInput {Numpad4}
Sleep, 64
SendInput {Numpad5}
Sleep, 302
SendInput {Numpad4}
Sleep, 366
SendInput {Numpad3}
Sleep, 366
SendInput {Numpad1}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad6}
SendInput {Numpad1}
SendInput {Numpad3}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad3}
Sleep, 366
SendInput {Numpad6}
Sleep, 366
SendInput {Numpad3}
Sleep, 366
SendInput {Numpad7}
Sleep, 366
SendInput {Numpad3}
Sleep, 366
SendInput {Numpad6}
Sleep, 366
SendInput {Numpad3}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad4}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 366
SendInput {Numpad4}
Sleep, 366
SendInput {Numpad1}
Sleep, 366
SendInput {Numpad4}
Sleep, 64
SendInput {Numpad5}
Sleep, 302
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad3}
SendInput {Numpad4}
Sleep, 366
SendInput {Numpad3}
Sleep, 366
SendInput {Numpad3}
SendInput {Numpad1}
Sleep, 366
SendInput {Numpad3}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 366
SendInput {Numpad4}
SendInput {Numpad3}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad2}
SendInput {Numpad3}
Sleep, 366
SendInput {Numpad3}
Sleep, 366
SendInput {Numpad3}
Sleep, 366
SendInput {Numpad3}
SendInput {Numpad1}
Sleep, 366
SendInput {Numpad3}
Sleep, 366
SendInput {Numpad3}
SendInput {Numpad4}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 366
SendInput {Numpad4}
SendInput {Numpad1}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad6}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad2}
SendInput {Numpad1}
Sleep, 366
SendInput {Numpad3}
Sleep, 366
SendInput {Numpad3}
SendInput {Numpad1}
Sleep, 366
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 366
SendInput {Numpad3}
SendInput {Numpad1}
Sleep, 366
SendInput {Numpad3}
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 366
SendInput {Numpad4}
SendInput {Numpad5}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad3}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 366
SendInput {Numpad3}
SendInput {Numpad1}
Sleep, 366
SendInput {Numpad3}
SendInput {Numpad5}
Sleep, 366
SendInput {Numpad3}
Sleep, 366
SendInput {Numpad3}
SendInput {Numpad5}
Sleep, 366
SendInput {Numpad3}
SendInput {Numpad5}
SendInput {Numpad7}
SendInput {Numpad2}
Sleep, 366
SendInput {Numpad4}
SendInput {Numpad5}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad2}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 366
SendInput {Numpad3}
SendInput {Numpad1}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad7}
Sleep, 366
SendInput {Numpad7}
SendInput {Numpad6}
Sleep, 366
SendInput {Numpad7}
SendInput {Numpad5}
Sleep, 366
SendInput {Numpad7}
SendInput {Numpad6}
SendInput {Numpad1}
SendInput {Numpad3}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad1}
SendInput {Numpad3}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 366
SendInput {Numpad6}
SendInput {Numpad3}
Sleep, 366
SendInput {Numpad7}
Sleep, 366
SendInput {Numpad7}
SendInput {Numpad3}
Sleep, 366
SendInput {Numpad7}
SendInput {Numpad1}
Sleep, 366
SendInput {Numpad7}
SendInput {Numpad3}
Sleep, 366
SendInput {Numpad7}
SendInput {Numpad4}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad1}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad6}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 366
SendInput {Numpad7}
Sleep, 366
SendInput {Numpad7}
SendInput {Numpad1}
Sleep, 366
SendInput {Numpad7}
SendInput {Numpad6}
Sleep, 366
SendInput {Numpad7}
SendInput {Numpad1}
Sleep, 366
SendInput {Numpad7}
SendInput {Numpad1}
SendInput {Numpad5}
SendInput {Numpad3}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad3}
Sleep, 366
SendInput {Numpad6}
SendInput {Numpad5}
Sleep, 366
SendInput {Numpad7}
SendInput {Numpad1}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad5}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad3}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad5}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad7}
SendInput {Numpad5}
SendInput {Numpad2}
Sleep, 366
SendInput {Numpad6}
SendInput {Numpad5}
Sleep, 366
SendInput {Numpad2}
Sleep, 366
SendInput {Numpad6}
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 366
SendInput {Numpad6}
SendInput {Numpad2}
SendInput {Numpad1}
Sleep, 366
SendInput {Numpad7}
SendInput {Numpad3}
Sleep, 366
SendInput {Numpad7}
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 366
SendInput {Numpad2}
SendInput {Numpad5}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 366
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 366
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 366
SendInput {Numpad2}
SendInput {Numpad5}
SendInput {Numpad3}
Sleep, 366
SendInput {Numpad2}
SendInput {Numpad5}
SendInput {Numpad1}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad7}
SendInput {Numpad3}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad2}
SendInput {Numpad5}
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 366
SendInput {Numpad3}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad6}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad3}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 366
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 366
SendInput {Numpad2}
SendInput {Numpad5}
SendInput {Numpad1}
Sleep, 366
SendInput {Numpad2}
SendInput {Numpad5}
SendInput {Numpad6}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad7}
SendInput {Numpad3}
SendInput {Numpad1}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad2}
SendInput {Numpad5}
SendInput {Numpad1}
SendInput {Numpad3}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad7}
SendInput {Numpad3}
SendInput {Numpad5}
Sleep, 366
SendInput {Numpad3}
Sleep, 366
SendInput {Numpad6}
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 366
SendInput {Numpad7}
SendInput {Numpad3}
SendInput {Numpad1}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad5}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad3}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad5}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad7}
SendInput {Numpad3}
SendInput {Numpad5}
SendInput {Numpad2}
Sleep, 366
SendInput {Numpad6}
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 366
SendInput {Numpad2}
Sleep, 366
SendInput {Numpad6}
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 366
SendInput {Numpad6}
SendInput {Numpad2}
SendInput {Numpad1}
Sleep, 366
SendInput {Numpad7}
SendInput {Numpad3}
Sleep, 366
SendInput {Numpad7}
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 366
SendInput {Numpad2}
SendInput {Numpad5}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 366
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 366
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 366
SendInput {Numpad2}
SendInput {Numpad5}
SendInput {Numpad3}
Sleep, 366
SendInput {Numpad2}
SendInput {Numpad5}
SendInput {Numpad1}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad7}
SendInput {Numpad3}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad2}
SendInput {Numpad5}
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 366
SendInput {Numpad3}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad6}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad3}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 366
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 366
SendInput {Numpad2}
SendInput {Numpad5}
SendInput {Numpad1}
Sleep, 366
SendInput {Numpad2}
SendInput {Numpad5}
SendInput {Numpad6}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad7}
SendInput {Numpad3}
SendInput {Numpad1}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad2}
SendInput {Numpad5}
SendInput {Numpad1}
SendInput {Numpad3}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad7}
SendInput {Numpad3}
SendInput {Numpad5}
Sleep, 366
SendInput {Numpad3}
Sleep, 366
SendInput {Numpad6}
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 366
SendInput {Numpad7}
SendInput {Numpad3}
SendInput {Numpad1}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad5}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad3}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad5}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad7}
SendInput {Numpad3}
SendInput {Numpad5}
SendInput {Numpad2}
Sleep, 366
SendInput {Numpad6}
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 366
SendInput {Numpad2}
Sleep, 366
SendInput {Numpad6}
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 366
SendInput {Numpad6}
SendInput {Numpad2}
SendInput {Numpad1}
Sleep, 366
SendInput {Numpad7}
SendInput {Numpad3}
Sleep, 366
SendInput {Numpad7}
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad2}
SendInput {Numpad5}
Sleep, 366
SendInput {Numpad6}
SendInput {Numpad1}
SendInput {Numpad3}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad3}
Sleep, 366
SendInput {Numpad6}
Sleep, 366
SendInput {Numpad3}
Sleep, 366
SendInput {Numpad7}
Sleep, 366
SendInput {Numpad3}
Sleep, 366
SendInput {Numpad6}
Sleep, 366
SendInput {Numpad3}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad4}
SendInput {Numpad6}
SendInput {Numpad1}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 366
SendInput {Numpad4}
Sleep, 366
SendInput {Numpad1}
Sleep, 366
SendInput {Numpad5}
Sleep, 366
SendInput {Numpad1}
Sleep, 366
SendInput {Numpad4}
Sleep, 366
SendInput {Numpad1}
Sleep, 366
SendInput {Numpad1}
SendInput {Numpad5}
SendInput {Numpad3}
Sleep, 366
SendInput {Numpad5}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad1}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad5}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad2}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad5}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad1}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad5}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad5}
SendInput {Numpad7}
SendInput {Numpad2}
Sleep, 366
SendInput {Numpad0}
SendInput {Numpad5}
Sleep, 366
SendInput {Numpad7}
Sleep, 366
SendInput {Numpad5}
Sleep, 366
SendInput {Numpad7}
Sleep, 64
SendInput {Numpad1}
Sleep, 302
SendInput {Numpad7}
Sleep, 366
SendInput {Numpad6}
Sleep, 366
SendInput {Numpad5}
Sleep, 366
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad6}
SendInput {Numpad1}
SendInput {Numpad3}
Sleep, 1000
