; title: Imagine
; author: John Lennon
; instrument: Piano
; Converted by Serenade midi2ahk

SendInput {Numpad5}
SendInput {Numpad3}
Sleep, 429
SendInput {Numpad1}
Sleep, 429
SendInput {Numpad5}
SendInput {Numpad3}
Sleep, 429
SendInput {Numpad1}
Sleep, 429
SendInput {Numpad5}
SendInput {Numpad3}
Sleep, 429
SendInput {Numpad1}
Sleep, 429
SendInput {Numpad7}
SendInput {Numpad5}
Sleep, 429
SendInput {Numpad1}
Sleep, 429
SendInput {Numpad6}
SendInput {Numpad4}
Sleep, 429
SendInput {Numpad1}
Sleep, 429
SendInput {Numpad6}
SendInput {Numpad4}
Sleep, 429
SendInput {Numpad1}
Sleep, 429
SendInput {Numpad6}
SendInput {Numpad4}
Sleep, 429
SendInput {Numpad1}
Sleep, 429
SendInput {Numpad6}
Sleep, 214
SendInput {F5}
Sleep, 214
SendInput {Numpad7}
Sleep, 429
SendInput {Numpad5}
SendInput {Numpad3}
Sleep, 429
SendInput {Numpad1}
Sleep, 429
SendInput {Numpad5}
SendInput {Numpad3}
Sleep, 429
SendInput {Numpad1}
Sleep, 429
SendInput {Numpad5}
SendInput {Numpad3}
Sleep, 429
SendInput {Numpad1}
Sleep, 429
SendInput {Numpad7}
SendInput {Numpad5}
Sleep, 429
SendInput {Numpad1}
Sleep, 429
SendInput {Numpad6}
SendInput {Numpad4}
Sleep, 429
SendInput {Numpad1}
Sleep, 429
SendInput {Numpad6}
SendInput {Numpad4}
Sleep, 429
SendInput {Numpad1}
Sleep, 429
SendInput {Numpad6}
SendInput {Numpad4}
Sleep, 429
SendInput {Numpad1}
Sleep, 429
SendInput {Numpad6}
Sleep, 214
SendInput {F5}
Sleep, 214
SendInput {Numpad7}
Sleep, 429
SendInput {Numpad5}
SendInput {Numpad3}
Sleep, 429
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 429
SendInput {Numpad5}
SendInput {Numpad3}
Sleep, 429
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 429
SendInput {Numpad5}
SendInput {Numpad3}
Sleep, 429
SendInput {Numpad1}
Sleep, 429
SendInput {Numpad7}
SendInput {Numpad5}
Sleep, 429
SendInput {Numpad1}
Sleep, 429
SendInput {Numpad6}
SendInput {Numpad4}
SendInput {Numpad7}
Sleep, 429
SendInput {Numpad1}
Sleep, 429
SendInput {Numpad6}
SendInput {Numpad4}
Sleep, 429
SendInput {Numpad1}
Sleep, 429
SendInput {Numpad6}
SendInput {Numpad4}
Sleep, 429
SendInput {Numpad1}
Sleep, 429
SendInput {Numpad6}
Sleep, 214
SendInput {F5}
Sleep, 214
SendInput {Numpad7}
Sleep, 429
SendInput {Numpad5}
SendInput {Numpad3}
Sleep, 429
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 429
SendInput {Numpad5}
SendInput {Numpad3}
Sleep, 429
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 429
SendInput {Numpad5}
SendInput {Numpad3}
Sleep, 429
SendInput {Numpad1}
Sleep, 429
SendInput {Numpad7}
SendInput {Numpad5}
Sleep, 429
SendInput {Numpad1}
Sleep, 429
SendInput {Numpad6}
SendInput {Numpad4}
SendInput {Numpad7}
Sleep, 429
SendInput {Numpad1}
Sleep, 429
SendInput {Numpad6}
SendInput {Numpad4}
Sleep, 429
SendInput {Numpad1}
Sleep, 429
SendInput {Numpad6}
SendInput {Numpad4}
Sleep, 429
SendInput {Numpad1}
Sleep, 429
SendInput {Numpad6}
Sleep, 214
SendInput {F5}
Sleep, 214
SendInput {Numpad7}
Sleep, 429
SendInput {Numpad5}
SendInput {Numpad3}
Sleep, 429
SendInput {Numpad1}
Sleep, 429
SendInput {Numpad5}
SendInput {Numpad3}
Sleep, 429
SendInput {Numpad1}
Sleep, 429
SendInput {Numpad5}
SendInput {Numpad3}
Sleep, 429
SendInput {Numpad1}
Sleep, 429
SendInput {Numpad7}
SendInput {Numpad5}
Sleep, 429
SendInput {Numpad1}
Sleep, 429
SendInput {Numpad6}
SendInput {Numpad4}
SendInput {Numpad7}
Sleep, 429
SendInput {Numpad1}
Sleep, 429
SendInput {Numpad6}
SendInput {Numpad4}
Sleep, 429
SendInput {Numpad1}
Sleep, 429
SendInput {Numpad6}
SendInput {Numpad4}
Sleep, 429
SendInput {Numpad1}
Sleep, 429
SendInput {Numpad6}
Sleep, 214
SendInput {F5}
Sleep, 214
SendInput {Numpad7}
Sleep, 429
SendInput {Numpad5}
SendInput {Numpad3}
Sleep, 429
SendInput {Numpad1}
Sleep, 429
SendInput {Numpad5}
SendInput {Numpad3}
Sleep, 429
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 429
SendInput {Numpad5}
SendInput {Numpad3}
Sleep, 429
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 429
SendInput {Numpad7}
SendInput {Numpad5}
Sleep, 429
SendInput {Numpad1}
SendInput {Numpad7}
Sleep, 429
SendInput {Numpad6}
SendInput {Numpad4}
Sleep, 429
SendInput {Numpad1}
Sleep, 429
SendInput {Numpad6}
SendInput {Numpad4}
Sleep, 429
SendInput {Numpad1}
Sleep, 429
SendInput {Numpad6}
SendInput {Numpad4}
Sleep, 429
SendInput {Numpad1}
Sleep, 429
SendInput {Numpad6}
SendInput {Numpad4}
Sleep, 429
SendInput {Numpad1}
Sleep, 429
SendInput {Numpad0}
SendInput {Numpad4}
Sleep, 429
SendInput {Numpad9}
SendInput {Numpad1}
SendInput {Numpad6}
Sleep, 429
SendInput {Numpad9}
SendInput {Numpad4}
SendInput {Numpad1}
SendInput {Numpad6}
Sleep, 429
SendInput {Numpad0}
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 429
SendInput {Numpad3}
SendInput {Numpad1}
Sleep, 429
SendInput {Numpad6}
Sleep, 429
SendInput {Numpad9}
SendInput {Numpad3}
SendInput {Numpad1}
Sleep, 429
SendInput {Numpad0}
SendInput {Numpad3}
Sleep, 429
SendInput {Numpad2}
SendInput {Numpad3}
Sleep, 429
SendInput {Numpad6}
Sleep, 429
SendInput {Numpad9}
SendInput {Numpad4}
SendInput {Numpad2}
Sleep, 429
SendInput {Numpad0}
SendInput {Numpad2}
Sleep, 429
SendInput {Numpad1}
Sleep, 429
SendInput {Numpad2}
Sleep, 429
SendInput {Numpad9}
SendInput {Numpad4}
SendInput {Numpad2}
SendInput {Numpad6}
Sleep, 429
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 429
SendInput {Numpad0}
SendInput {Numpad7}
Sleep, 429
SendInput {Numpad9}
SendInput {Numpad2}
Sleep, 429
SendInput {Numpad5}
SendInput {Numpad7}
Sleep, 857
SendInput {Numpad0}
SendInput {Numpad7}
Sleep, 429
SendInput {Numpad9}
SendInput {Numpad2}
Sleep, 429
SendInput {Numpad9}
SendInput {Numpad5}
SendInput {Numpad2}
SendInput {Numpad1}
Sleep, 857
SendInput {Numpad4}
SendInput {Numpad2}
Sleep, 1714
SendInput {Numpad3}
Sleep, 429
SendInput {Numpad5}
Sleep, 643
SendInput {Numpad3}
Sleep, 214
SendInput {Numpad2}
Sleep, 214
SendInput {Numpad1}
Sleep, 214
SendInput {Numpad0}
SendInput {Numpad5}
SendInput {Numpad3}
Sleep, 429
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 429
SendInput {Numpad5}
SendInput {Numpad3}
Sleep, 429
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 429
SendInput {Numpad5}
SendInput {Numpad3}
Sleep, 429
SendInput {Numpad1}
Sleep, 429
SendInput {Numpad7}
SendInput {Numpad5}
Sleep, 429
SendInput {Numpad1}
Sleep, 429
SendInput {Numpad6}
SendInput {Numpad4}
SendInput {Numpad7}
Sleep, 429
SendInput {Numpad1}
Sleep, 429
SendInput {Numpad6}
SendInput {Numpad4}
Sleep, 429
SendInput {Numpad1}
Sleep, 429
SendInput {Numpad6}
SendInput {Numpad4}
Sleep, 429
SendInput {Numpad1}
Sleep, 429
SendInput {Numpad6}
Sleep, 214
SendInput {F5}
Sleep, 214
SendInput {Numpad7}
Sleep, 429
SendInput {Numpad5}
SendInput {Numpad3}
Sleep, 429
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 429
SendInput {Numpad5}
SendInput {Numpad3}
Sleep, 429
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 429
SendInput {Numpad5}
SendInput {Numpad3}
Sleep, 429
SendInput {Numpad1}
Sleep, 429
SendInput {Numpad7}
SendInput {Numpad5}
Sleep, 429
SendInput {Numpad1}
Sleep, 429
SendInput {Numpad6}
SendInput {Numpad4}
SendInput {Numpad7}
Sleep, 429
SendInput {Numpad1}
Sleep, 429
SendInput {Numpad6}
SendInput {Numpad4}
Sleep, 429
SendInput {Numpad1}
Sleep, 429
SendInput {Numpad6}
SendInput {Numpad4}
Sleep, 429
SendInput {Numpad1}
Sleep, 429
SendInput {Numpad6}
Sleep, 214
SendInput {F5}
Sleep, 214
SendInput {Numpad7}
Sleep, 429
SendInput {Numpad5}
SendInput {Numpad3}
Sleep, 429
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 429
SendInput {Numpad5}
SendInput {Numpad3}
Sleep, 429
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 429
SendInput {Numpad5}
SendInput {Numpad3}
Sleep, 429
SendInput {Numpad1}
Sleep, 429
SendInput {Numpad7}
SendInput {Numpad5}
Sleep, 429
SendInput {Numpad1}
Sleep, 429
SendInput {Numpad6}
SendInput {Numpad4}
SendInput {Numpad7}
Sleep, 429
SendInput {Numpad1}
Sleep, 429
SendInput {Numpad6}
SendInput {Numpad4}
Sleep, 429
SendInput {Numpad1}
Sleep, 429
SendInput {Numpad6}
SendInput {Numpad4}
Sleep, 429
SendInput {Numpad1}
Sleep, 429
SendInput {Numpad6}
Sleep, 214
SendInput {F5}
Sleep, 214
SendInput {Numpad7}
Sleep, 429
SendInput {Numpad5}
SendInput {Numpad3}
Sleep, 429
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 429
SendInput {Numpad5}
SendInput {Numpad3}
Sleep, 429
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 429
SendInput {Numpad5}
SendInput {Numpad3}
Sleep, 429
SendInput {Numpad1}
Sleep, 429
SendInput {Numpad7}
SendInput {Numpad5}
Sleep, 429
SendInput {Numpad1}
Sleep, 429
SendInput {Numpad6}
SendInput {Numpad4}
SendInput {Numpad7}
Sleep, 429
SendInput {Numpad1}
Sleep, 429
SendInput {Numpad6}
SendInput {Numpad4}
Sleep, 429
SendInput {Numpad1}
Sleep, 429
SendInput {Numpad6}
SendInput {Numpad4}
Sleep, 429
SendInput {Numpad1}
Sleep, 429
SendInput {Numpad6}
SendInput {Numpad4}
Sleep, 429
SendInput {Numpad1}
Sleep, 429
SendInput {Numpad0}
SendInput {Numpad4}
Sleep, 429
SendInput {Numpad9}
SendInput {Numpad1}
SendInput {Numpad6}
Sleep, 429
SendInput {Numpad9}
SendInput {Numpad4}
SendInput {Numpad1}
SendInput {Numpad6}
Sleep, 429
SendInput {Numpad0}
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 429
SendInput {Numpad3}
SendInput {Numpad1}
Sleep, 429
SendInput {Numpad6}
Sleep, 429
SendInput {Numpad9}
SendInput {Numpad3}
SendInput {Numpad1}
Sleep, 429
SendInput {Numpad0}
SendInput {Numpad3}
Sleep, 429
SendInput {Numpad2}
SendInput {Numpad3}
Sleep, 429
SendInput {Numpad6}
Sleep, 429
SendInput {Numpad9}
SendInput {Numpad4}
SendInput {Numpad2}
Sleep, 429
SendInput {Numpad0}
SendInput {Numpad2}
Sleep, 429
SendInput {Numpad1}
Sleep, 429
SendInput {Numpad2}
Sleep, 429
SendInput {Numpad9}
SendInput {Numpad4}
SendInput {Numpad2}
SendInput {Numpad6}
Sleep, 429
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 429
SendInput {Numpad0}
SendInput {Numpad7}
Sleep, 429
SendInput {Numpad9}
SendInput {Numpad2}
Sleep, 429
SendInput {Numpad5}
SendInput {Numpad7}
Sleep, 857
SendInput {Numpad0}
SendInput {Numpad7}
Sleep, 429
SendInput {Numpad9}
SendInput {Numpad2}
Sleep, 429
SendInput {Numpad9}
SendInput {Numpad5}
SendInput {Numpad2}
SendInput {Numpad1}
Sleep, 857
SendInput {Numpad4}
SendInput {Numpad2}
Sleep, 1714
SendInput {Numpad3}
Sleep, 429
SendInput {Numpad5}
Sleep, 643
SendInput {Numpad3}
Sleep, 214
SendInput {Numpad2}
Sleep, 214
SendInput {Numpad1}
Sleep, 214
SendInput {Numpad4}
Sleep, 429
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 429
SendInput {Numpad1}
SendInput {Numpad6}
SendInput {Numpad4}
Sleep, 429
SendInput {Numpad0}
SendInput {Numpad4}
SendInput {Numpad1}
Sleep, 429
SendInput {Numpad5}
SendInput {Numpad7}
Sleep, 429
SendInput {Numpad7}
Sleep, 429
SendInput {Numpad9}
SendInput {Numpad7}
SendInput {Numpad5}
SendInput {Numpad2}
SendInput {Numpad6}
Sleep, 429
SendInput {Numpad0}
SendInput {Numpad5}
SendInput {Numpad7}
Sleep, 429
SendInput {Numpad9}
SendInput {Numpad1}
Sleep, 429
SendInput {Numpad3}
SendInput {Numpad1}
Sleep, 429
SendInput {Numpad9}
SendInput {Numpad3}
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 429
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 429
SendInput {Numpad0}
SendInput {Numpad7}
Sleep, 429
SendInput {Numpad9}
SendInput {Numpad3}
Sleep, 429
SendInput {Numpad9}
SendInput {Numpad3}
SendInput {Numpad2}
SendInput {F4}
Sleep, 429
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad3}
Sleep, 429
SendInput {Numpad4}
Sleep, 429
SendInput {Numpad9}
SendInput {Numpad1}
Sleep, 429
SendInput {Numpad1}
SendInput {Numpad6}
SendInput {Numpad4}
Sleep, 429
SendInput {Numpad0}
SendInput {Numpad4}
SendInput {Numpad1}
Sleep, 429
SendInput {Numpad5}
SendInput {Numpad7}
Sleep, 429
SendInput {Numpad7}
Sleep, 429
SendInput {Numpad9}
SendInput {Numpad7}
SendInput {Numpad5}
SendInput {Numpad2}
SendInput {Numpad6}
Sleep, 429
SendInput {Numpad0}
SendInput {Numpad5}
SendInput {Numpad6}
Sleep, 429
SendInput {Numpad9}
SendInput {Numpad1}
SendInput {Numpad3}
Sleep, 429
SendInput {Numpad3}
Sleep, 429
SendInput {Numpad9}
SendInput {Numpad3}
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 429
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 429
SendInput {Numpad0}
SendInput {Numpad7}
Sleep, 429
SendInput {Numpad9}
SendInput {Numpad3}
Sleep, 429
SendInput {Numpad9}
SendInput {Numpad3}
SendInput {Numpad2}
SendInput {F4}
Sleep, 429
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad3}
Sleep, 429
SendInput {Numpad4}
Sleep, 429
SendInput {Numpad9}
SendInput {Numpad1}
SendInput {Numpad6}
Sleep, 429
SendInput {Numpad1}
SendInput {Numpad6}
SendInput {Numpad4}
Sleep, 429
SendInput {Numpad0}
SendInput {Numpad4}
SendInput {Numpad1}
Sleep, 429
SendInput {Numpad5}
SendInput {Numpad7}
Sleep, 429
SendInput {Numpad7}
Sleep, 429
SendInput {Numpad9}
SendInput {Numpad7}
SendInput {Numpad5}
SendInput {Numpad2}
SendInput {Numpad6}
Sleep, 429
SendInput {Numpad0}
SendInput {Numpad5}
SendInput {Numpad7}
Sleep, 429
SendInput {Numpad9}
SendInput {Numpad1}
Sleep, 429
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 429
SendInput {Numpad9}
SendInput {Numpad3}
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 429
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 429
SendInput {Numpad0}
SendInput {Numpad7}
Sleep, 429
SendInput {Numpad9}
SendInput {Numpad3}
Sleep, 429
SendInput {Numpad9}
SendInput {Numpad3}
SendInput {Numpad2}
SendInput {F4}
Sleep, 429
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad3}
Sleep, 429
SendInput {Numpad4}
Sleep, 429
SendInput {Numpad9}
SendInput {Numpad1}
Sleep, 429
SendInput {Numpad9}
SendInput {Numpad1}
SendInput {Numpad6}
SendInput {Numpad4}
Sleep, 429
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad4}
SendInput {Numpad1}
Sleep, 429
SendInput {Numpad5}
SendInput {Numpad2}
Sleep, 429
SendInput {Numpad7}
Sleep, 429
SendInput {Numpad9}
SendInput {Numpad7}
SendInput {Numpad5}
SendInput {Numpad2}
SendInput {Numpad1}
Sleep, 429
SendInput {Numpad0}
SendInput {Numpad5}
SendInput {Numpad2}
Sleep, 429
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad3}
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 429
SendInput {Numpad1}
Sleep, 429
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad5}
SendInput {Numpad1}
Sleep, 429
SendInput {Numpad9}
SendInput {Numpad5}
Sleep, 429
SendInput {Numpad0}
SendInput {Numpad6}
Sleep, 429
SendInput {Numpad9}
SendInput {Numpad5}
Sleep, 429
SendInput {Numpad0}
SendInput {Numpad7}
Sleep, 429
SendInput {Numpad9}
SendInput {Numpad5}
Sleep, 429
SendInput {Numpad5}
SendInput {Numpad3}
Sleep, 429
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 429
SendInput {Numpad5}
SendInput {Numpad3}
Sleep, 429
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 429
SendInput {Numpad5}
SendInput {Numpad3}
Sleep, 429
SendInput {Numpad1}
Sleep, 429
SendInput {Numpad7}
SendInput {Numpad5}
Sleep, 429
SendInput {Numpad1}
Sleep, 429
SendInput {Numpad6}
SendInput {Numpad4}
SendInput {Numpad7}
Sleep, 429
SendInput {Numpad1}
Sleep, 429
SendInput {Numpad6}
SendInput {Numpad4}
Sleep, 429
SendInput {Numpad1}
Sleep, 429
SendInput {Numpad6}
SendInput {Numpad4}
Sleep, 429
SendInput {Numpad1}
Sleep, 429
SendInput {Numpad6}
Sleep, 214
SendInput {F5}
Sleep, 214
SendInput {Numpad7}
Sleep, 429
SendInput {Numpad5}
SendInput {Numpad3}
Sleep, 429
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 429
SendInput {Numpad5}
SendInput {Numpad3}
Sleep, 429
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 429
SendInput {Numpad5}
SendInput {Numpad3}
Sleep, 429
SendInput {Numpad1}
Sleep, 429
SendInput {Numpad7}
SendInput {Numpad5}
Sleep, 429
SendInput {Numpad1}
Sleep, 429
SendInput {Numpad6}
SendInput {Numpad4}
SendInput {Numpad7}
Sleep, 429
SendInput {Numpad1}
Sleep, 429
SendInput {Numpad6}
SendInput {Numpad4}
Sleep, 429
SendInput {Numpad1}
Sleep, 429
SendInput {Numpad6}
SendInput {Numpad4}
Sleep, 429
SendInput {Numpad1}
Sleep, 429
SendInput {Numpad6}
Sleep, 214
SendInput {F5}
Sleep, 214
SendInput {Numpad7}
Sleep, 429
SendInput {Numpad5}
SendInput {Numpad3}
Sleep, 429
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 429
SendInput {Numpad5}
SendInput {Numpad3}
Sleep, 429
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 429
SendInput {Numpad5}
SendInput {Numpad3}
Sleep, 429
SendInput {Numpad1}
Sleep, 429
SendInput {Numpad7}
SendInput {Numpad5}
Sleep, 429
SendInput {Numpad1}
Sleep, 429
SendInput {Numpad6}
SendInput {Numpad4}
SendInput {Numpad7}
Sleep, 429
SendInput {Numpad1}
Sleep, 429
SendInput {Numpad6}
SendInput {Numpad4}
Sleep, 429
SendInput {Numpad1}
Sleep, 429
SendInput {Numpad6}
SendInput {Numpad4}
Sleep, 429
SendInput {Numpad1}
Sleep, 429
SendInput {Numpad6}
Sleep, 214
SendInput {F5}
Sleep, 214
SendInput {Numpad7}
Sleep, 429
SendInput {Numpad5}
SendInput {Numpad3}
Sleep, 429
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 429
SendInput {Numpad5}
SendInput {Numpad3}
Sleep, 429
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 429
SendInput {Numpad5}
SendInput {Numpad3}
Sleep, 429
SendInput {Numpad1}
Sleep, 429
SendInput {Numpad7}
SendInput {Numpad5}
Sleep, 429
SendInput {Numpad1}
Sleep, 429
SendInput {Numpad6}
SendInput {Numpad4}
SendInput {Numpad7}
Sleep, 429
SendInput {Numpad1}
Sleep, 429
SendInput {Numpad6}
SendInput {Numpad4}
Sleep, 429
SendInput {Numpad1}
Sleep, 429
SendInput {Numpad6}
SendInput {Numpad4}
Sleep, 429
SendInput {Numpad1}
Sleep, 429
SendInput {Numpad6}
SendInput {Numpad4}
Sleep, 429
SendInput {Numpad1}
Sleep, 429
SendInput {Numpad0}
SendInput {Numpad4}
Sleep, 429
SendInput {Numpad9}
SendInput {Numpad1}
SendInput {Numpad6}
Sleep, 429
SendInput {Numpad9}
SendInput {Numpad4}
SendInput {Numpad1}
SendInput {Numpad6}
Sleep, 429
SendInput {Numpad0}
SendInput {Numpad4}
SendInput {Numpad6}
Sleep, 429
SendInput {Numpad3}
SendInput {Numpad1}
Sleep, 429
SendInput {Numpad6}
Sleep, 429
SendInput {Numpad9}
SendInput {Numpad3}
SendInput {Numpad1}
Sleep, 429
SendInput {Numpad0}
SendInput {Numpad3}
Sleep, 429
SendInput {Numpad2}
SendInput {Numpad3}
Sleep, 429
SendInput {Numpad6}
Sleep, 429
SendInput {Numpad9}
SendInput {Numpad4}
SendInput {Numpad2}
Sleep, 429
SendInput {Numpad0}
SendInput {Numpad2}
Sleep, 429
SendInput {Numpad1}
Sleep, 429
SendInput {Numpad2}
Sleep, 429
SendInput {Numpad9}
SendInput {Numpad4}
SendInput {Numpad2}
SendInput {Numpad6}
Sleep, 429
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 429
SendInput {Numpad0}
SendInput {Numpad7}
Sleep, 429
SendInput {Numpad9}
SendInput {Numpad2}
Sleep, 429
SendInput {Numpad5}
SendInput {Numpad7}
Sleep, 857
SendInput {Numpad0}
SendInput {Numpad7}
Sleep, 429
SendInput {Numpad9}
SendInput {Numpad2}
Sleep, 429
SendInput {Numpad9}
SendInput {Numpad5}
SendInput {Numpad2}
SendInput {Numpad1}
Sleep, 857
SendInput {Numpad4}
SendInput {Numpad2}
Sleep, 1714
SendInput {Numpad3}
Sleep, 429
SendInput {Numpad5}
Sleep, 643
SendInput {Numpad3}
Sleep, 214
SendInput {Numpad2}
Sleep, 214
SendInput {Numpad1}
Sleep, 214
SendInput {Numpad4}
Sleep, 429
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 429
SendInput {Numpad1}
SendInput {Numpad6}
SendInput {Numpad4}
Sleep, 429
SendInput {Numpad0}
SendInput {Numpad4}
SendInput {Numpad1}
Sleep, 429
SendInput {Numpad5}
SendInput {Numpad7}
Sleep, 429
SendInput {Numpad7}
Sleep, 429
SendInput {Numpad9}
SendInput {Numpad7}
SendInput {Numpad5}
SendInput {Numpad2}
SendInput {Numpad6}
Sleep, 429
SendInput {Numpad0}
SendInput {Numpad5}
SendInput {Numpad7}
Sleep, 429
SendInput {Numpad9}
SendInput {Numpad1}
Sleep, 429
SendInput {Numpad3}
SendInput {Numpad1}
Sleep, 429
SendInput {Numpad9}
SendInput {Numpad3}
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 429
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 429
SendInput {Numpad0}
SendInput {Numpad7}
Sleep, 429
SendInput {Numpad9}
SendInput {Numpad3}
Sleep, 429
SendInput {Numpad9}
SendInput {Numpad3}
SendInput {Numpad2}
SendInput {F4}
Sleep, 429
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad3}
Sleep, 429
SendInput {Numpad4}
Sleep, 429
SendInput {Numpad9}
SendInput {Numpad1}
Sleep, 429
SendInput {Numpad1}
SendInput {Numpad6}
SendInput {Numpad4}
Sleep, 429
SendInput {Numpad0}
SendInput {Numpad4}
SendInput {Numpad1}
Sleep, 429
SendInput {Numpad5}
SendInput {Numpad7}
Sleep, 429
SendInput {Numpad7}
Sleep, 429
SendInput {Numpad9}
SendInput {Numpad7}
SendInput {Numpad5}
SendInput {Numpad2}
SendInput {Numpad6}
Sleep, 429
SendInput {Numpad0}
SendInput {Numpad5}
SendInput {Numpad6}
Sleep, 429
SendInput {Numpad9}
SendInput {Numpad1}
SendInput {Numpad3}
Sleep, 429
SendInput {Numpad3}
Sleep, 429
SendInput {Numpad9}
SendInput {Numpad3}
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 429
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 429
SendInput {Numpad0}
SendInput {Numpad7}
Sleep, 429
SendInput {Numpad9}
SendInput {Numpad3}
Sleep, 429
SendInput {Numpad9}
SendInput {Numpad3}
SendInput {Numpad2}
SendInput {F4}
Sleep, 429
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad3}
Sleep, 429
SendInput {Numpad4}
Sleep, 429
SendInput {Numpad9}
SendInput {Numpad1}
SendInput {Numpad6}
Sleep, 429
SendInput {Numpad1}
SendInput {Numpad6}
SendInput {Numpad4}
Sleep, 429
SendInput {Numpad0}
SendInput {Numpad4}
SendInput {Numpad1}
Sleep, 429
SendInput {Numpad5}
SendInput {Numpad7}
Sleep, 429
SendInput {Numpad7}
Sleep, 429
SendInput {Numpad9}
SendInput {Numpad7}
SendInput {Numpad5}
SendInput {Numpad2}
SendInput {Numpad6}
Sleep, 429
SendInput {Numpad0}
SendInput {Numpad5}
SendInput {Numpad7}
Sleep, 429
SendInput {Numpad9}
SendInput {Numpad1}
Sleep, 429
SendInput {Numpad3}
SendInput {Numpad6}
Sleep, 429
SendInput {Numpad9}
SendInput {Numpad3}
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 429
SendInput {Numpad0}
SendInput {Numpad1}
Sleep, 429
SendInput {Numpad0}
SendInput {Numpad7}
Sleep, 429
SendInput {Numpad9}
SendInput {Numpad3}
Sleep, 429
SendInput {Numpad9}
SendInput {Numpad3}
SendInput {Numpad2}
SendInput {F4}
Sleep, 429
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad3}
Sleep, 429
SendInput {Numpad4}
Sleep, 429
SendInput {Numpad9}
SendInput {Numpad1}
Sleep, 429
SendInput {Numpad9}
SendInput {Numpad1}
SendInput {Numpad6}
SendInput {Numpad4}
Sleep, 429
SendInput {Numpad0}
SendInput {Numpad0}
SendInput {Numpad4}
SendInput {Numpad1}
Sleep, 429
SendInput {Numpad5}
SendInput {Numpad2}
Sleep, 429
SendInput {Numpad7}
Sleep, 429
SendInput {Numpad9}
SendInput {Numpad7}
SendInput {Numpad5}
SendInput {Numpad2}
SendInput {Numpad1}
Sleep, 429
SendInput {Numpad0}
SendInput {Numpad5}
SendInput {Numpad2}
Sleep, 429
SendInput {Numpad9}
SendInput {Numpad9}
SendInput {Numpad3}
SendInput {Numpad1}
SendInput {Numpad5}
Sleep, 429
SendInput {Numpad1}
Sleep, 429
SendInput {Numpad1}
